### ISSUE TITLE
Missing and unloaded files should cause warnings or exceptions

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#100]
When invoking SWI-Prolog with the recommended syntax (see manpage) for loading files, i.e.:

    swipl file1 file2 ...

then SWI-Prolog should give a clear warning if the given files are **not** loaded for any reason.

For example, currently, with `*.chr` files (which even appear in the SWI distribution):

    swipl primes.chr

does **not** load the specified file (although it exists), but fails to give any indication about this.

Similarly, when mistyping the extension of a file and using for example:

    swipl anyfile.plg

SWI should give a warning or throw an exception because the file could not be loaded.

**Comment by JanWielemaker** [comment]
No.  Anything that is not *.pl starts the application  arguments.  That avoids the need for `--` to separate command line arguments.
