### ISSUE TITLE
Base64 encoding discrepancy

### ISSUE THREAD

**Issue by totpet** [SWI-Prolog/swipl-devel#1000]
There is an error in the handling of non-ASCII atoms when trying the encode them to base64:

```prolog
?- T1 = 'ő', base64(T1, X), base64(T2, X).
T1 = ő,
X = 'UQ==',
T2 = 'Q'.
```

The correct encoded value should be this:

```bash
$ echo -n 'ő' | base64
xZE=
$ echo -n 'ő' | base64 | base64 -d | hexdump -C
00000000  c5 91                                             |..|
00000002
```

I tested it in SWI 7.6.4 and 8.5.10

**Comment by JanWielemaker** [comment]
This is not evident.   Base64 encoding encodes _bytes_.  When applying this to text we need an _encoding_.   In the good old days that was often silently assumed to be ASCII or ISO-Latin-1.   The ő character is the Unicode code point 337, which doesn't fit in a byte anyway.  So, we must apply some multibyte encoding.   Many standards these days use UTF-8 for that.  That works:

```
?- atom_codes('ő', Codes),
   phrase(utf8_codes(Codes), UTF8),
   phrase(base64(UTF8), Encoded),
   atom_codes(EncAtom, Encoded).
Codes = [337],
UTF8 = [197, 145],
Encoded = [120, 90, 69, 61],
EncAtom = 'xZE='.
```

Not sure what to do with this.   Adding a remark to the docs.   Possibly adding a test, but even that is ambiguous as it is unclear how text that uses the range 128-255 must be handled.   It may use UTF-8, but doesn't need to.

**Comment by totpet** [comment]
Thank you, I understand. A solution I can think of is simply not accepting atoms (like [Python does with strings vs bytes](https://docs.python.org/3/library/base64.html#base64.b64encode)). Or having a mandatory encoding argument. But both of these would be breaking changes.

**Comment by JanWielemaker** [comment]
Adding an encoding option is probably the way to go.   This is already the case for some of the secure hash predicates.

**Comment by kamahen** [comment]
> Base64 encoding encodes bytes. When applying this to text we need an encoding.

This was a huge source of bugs in Python2 and one of the biggest changes from Python2 to Python3. In Python3, you'll get an error if you use something like `base64`:
```python
>>> text='Mary had a little lamb'
>>> base64.b64encode(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/lib/python3.12/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
>>> base64.b64encode(text.encode('utf8'))
b'TWFyeSBoYWQgYSBsaXR0bGUgbGFtYg=='
```
One solution is to define base64/2 to only work on a list of chars or codes and throw an error for an atom or string (which will break existing code). Or, as @jan suggested, add an encoding option to base64/2. (There's already a base64_encoded/2, with no documentation). A big warning should be added to the documentation also. ;)

**Comment by JanWielemaker** [comment]
Perhaps we need an atom_bytes(?Atom, ?Bytes, +Encoding) (and similar string_bytes/3)?   That would be simple to implement because we have all we need in the C primitives and provides a direct route for such problems.

**Comment by kamahen** [comment]
In addition to atom_bytes(?Atom, ?Bytes, +Encoding), it might make sense to also have codes_bytes/3 and chars_bytes/3. (And string_bytes/3 ?)

**Comment by JanWielemaker** [comment]
I surely do not want that many predicates for something that should not have a lot of use.   SWI-Prolog's design is to hide all these encoding problems from the user.   There are some places where this doesn't work, such as for base64 encoding that is defined for bytes.   Note that the memory files library can already do these transformations.   The disadvantage would be that the base64 library becomes dependent on an extension library.   There is also quite a bit more indirection.   Possibly string_bytes/2 is the best if we want one, taking (as all similar predicates), arbitrary text input.   For bytes-to-X that means using a string as intermediate.   Strings are by far the cheapest of the text representations though.

**Comment by kamahen** [comment]
I see you've already added `string_bytes(?String, ?Bytes, +Encoding)` ... and it would seem that codes_bytes/3 etc aren't needed because existing conversions between codes and chars via strings is efficient enough. It might be worth mentioning this in the documentation.

PS: there's a typo on the documentation page: "are supporte." missing a final "d".

**Comment by JanWielemaker** [comment]
Thanks.  Added a remark and fixed the typo.
