### ISSUE TITLE
Top-level $Variable cache not updating on Vars and Attvars

### ISSUE THREAD

**Issue by logicmoo** [SWI-Prolog/swipl-devel#101]
Thank you for Top-level $Variable cache

But EGDDP = Every good deed deserves punishment

````
[debug] 51 ?- X=1.
X = 1.

[debug] 52 ?- X=2.
X = 2.

[debug] 53 ?- writeq($X).
2
true.

[debug] 54 ?-  ?- m1:put_atts(X,+a(x1,y1)),m1:put_atts(X,+b(x1,y1)),m1:put_atts(X,-a(_,_)),m2:put_atts(X,+b(x2,y2)).
put_attr(V, m1, [b(x1, y1)]),
put_attr(V, m2, [b(x2, y2)]).

[debug] 55 ?- writeq($X).
2
true.

[debug] 56 ?- put_attr(X, a, 1).
put_attr(X, a, b).

[debug] 57 ?- writeq($X).
2
true.

````
^
Not updating

````
[debug] 58 ?- X = v(_).
X = v(_G258084).

[debug] 59 ?- writeq($X).
v(_G258117)
true.

````
^
Ok it is just vars

````

[debug] 62 ?- put_attr(VV, a, 1).
put_attr(VV, a, 1).

[debug] 63 ?- writeq($VV).
ERROR: variable `'VV'' does not exist
````
^
Also not creating when Var/Attvar 
I understand the in reasoning why it's this way and not wanting to save vars .  Maybe we should only save if its an attvar?

Why I decided it was worth reporting though was this: 

````
[debug] 66 ?- X = v(X).
X = v(X).

[debug] 67 ?- writeq($X).
^CUnknown option (h for help)
abort
% Execution Aborted
[debug] 68 ?-
````
Good, we showed cyclic terms can be difficult!

I can submit a patch it in a couple days. but there are a few distinct things I'd expect to patch:

Not updating issue - should be fixed

Not saving vars issue - should not be fixed... (After all nothing is in it anyways)
````
[debug] 93 ?-  \+ (XX=1).
true.

[debug] 94 ?- writeq($XX).
ERROR: variable `'XX'' does not exist
````
Oops I am wrong, that should be fixed.  (to help in teaching)

Not saving attvars issue - should be fixed.  (makes writing walkthru docs easier)

Teaching students cyclic terms can create problems -  should or should not be fixed?
I think it should, though we lose the chance of showing off SWI's resilience with abort I get tired of hearing "Only this or that prolog can handle cyclic terms"

**Comment by logicmoo** [comment]
Wait that was supposed to be: "No good deed goes unpunished."    I am an american liberal, so, to have quoted the other, I would have had to switch parties first.

**Comment by logicmoo** [comment]
````
[debug] 78 ?- X=x(X),writteq(X).
Correct to: "writeq(X)"? yes
@(S_1,[S_1=x(S_1)])
X = x(X).

[debug] 79 ?- X=x(X),writeq(X).
@(S_1,[S_1=x(S_1)])
X = x(X).

[debug] 80 ?- print_toplevel_variables.
$X =        @(S_1,[S_1=x(S_1)])
$M =        user
$Y =        1
false.

[debug] 81 ?- writeq($X).
ERROR: Out of local stack
   Exception: (5) [$expand] expand_goal(writeq(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(...))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))),_G261360,_G261361,_G261362) ?
````

Just letting us know it's the goal_expansion code that broken.. not some printing code.

**Comment by JanWielemaker** [comment]
I'm not against adding variables with attributes to the bindings.  Please make a pull request.  The non-termination is due to the functional-notation expansion.  Tat can, of course, be fixed.  Does require some rather tricky code though.

**Comment by logicmoo** [comment]
````
?- put_attr(X,a,b).
put_attr(X, a, b).

?- get_attr($X,a,W).
W = b.
````

**Comment by logicmoo** [comment]
Closing this issue since it now has been converted to a pull request.
