### ISSUE TITLE
Encoding errors with running "env -i PATH=/usr/bin ctest"

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1013]
`src/Tests/core/test_string.pl` gives "Illegal multibyte Sequence" errors 
- this can be fixed by adding `:- encoding(utf8).`

`src/Tests/files/test_glob.pl`gives errors such as
```
file_directory_name/2: Cannot represent due to `encoding' (Cannot represent char U0498 using current locale encoding)
```
I was able to get the `test_glob.pl` to work with `LANG=en_US.UTF-8` -- setting `LC_CTYPE` and `LC_ALL` didn't work.

**Comment by JanWielemaker** [comment]
Thanks.  Added the encoding directive for the string tests.   Dynamically disable the file system checks if the default encoding cannot represent these characters.   Locale names and availability are not standardized, which makes them hard to use cross-platform.
