### ISSUE TITLE
issue with qsave'd programs

### ISSUE THREAD

**Issue by josd** [SWI-Prolog/swipl-devel#1017]
Since yesterday many of the EYE reasoner tests are failing.

So we always (since years) make an `eye.pvm` quick load file but that seems to be somehow not working as before.
After several hours of trying to narrow down the issue I found that some calls didn't work as expected e.g. line https://github.com/josd/eye/blob/c1fc08fa41c734214dd48198eb720ddafed85352/eye.pl#L10184 fails unexpectedly and also line https://github.com/josd/eye/blob/c1fc08fa41c734214dd48198eb720ddafed85352/eye.pl#L9877 is (sometimes?) failing.

It all works fine when we use eye as `swipl -g main eype.pl`

**Comment by JanWielemaker** [comment]
Both depend on new functionality in the C core.   This not functioning in a saved state and working fine on the toplevel indicates the saved state is somehow picking up an old version of libswipl.so.   Maybe a setting for SWI_HOME_DIR or LD_LIBRARY_PATH?

If that doesn't help, please describe how to reproduce this.

**Comment by josd** [comment]
There is no setting for `SWI_HOME_DIR` nor `LD_LIBRARY_PATH`.
Deleting the `build` dir and then building again didn't help.
Only (finally) `sudo rm -fr /lib/swi-prolog` and then building again helped, 'oef' :-)

**Comment by JanWielemaker** [comment]
Picking up the executable and libswipl.so is an OS task.   On Linux I typically use ldd or in extreme cases strace to figure out what files are opened.   Anyway, it seems it was a version mixup.  Closing.
