### ISSUE TITLE
Rational to float conversion isn't monotonic

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#1022]
Given two rational numbers `L` and `H` such that `L < H`, conversion to float numbers `FL` and `FH` respectively should result in `FL < FH` but that isn't always the case. An example:
```
?- L = 584094523496279505433936574847581143766216585231r194698174498759837706356112910407296779993255941, FL is float(L), 
H = 194698174498759837706356112910407296779993255941r64899391499586611287930076989528974497703888215, FH is float(H),
L<H, FL>FH.

L = 584094523496279505433936574847581143766216585231r194698174498759837706356112910407296779993255941,
FL = 3.0000000000000004,
H = 194698174498759837706356112910407296779993255941r64899391499586611287930076989528974497703888215,
FH = 3.0.
```
The C function in `pl-gmp.c` responsible for low level conversion appears to be `mpz_fdiv` ("copied from ECLiPSe  7.0_53"). Not really sure what this function does in detail and why the GMP function `mpq_get_d` isn't used as it appears to specifically implement the required functionality.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/rounding-error-in-2/5795/9

**Comment by ridgeworks** [comment]
Unreproducible in 8.5.18 ; believed to be fixed with latest round of changes to `mpz_fdiv()`.
