### ISSUE TITLE
(wasm shell) sleep/1 example hangs indefinitely

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [SWI-Prolog/swipl-devel#1023]
Maybe this is an issue of `flush_output/1`. But I don't
get this example working:
```
test :- write('Hello '), flush_output,
   sleep(1),
   write('World!'), nl.
```
It hangs here:

![image](https://user-images.githubusercontent.com/95891213/185783365-96fad3d9-7e9a-42d9-90b6-34c20fc9301f.png)

**Comment by Jean-Luc-Picard-2021** [comment]
A related but different bug here:
https://github.com/ciao-lang/ciao/issues/66

**Comment by JanWielemaker** [comment]
Thanks.   Was broken after rewrite of the high level Prolog query interface using iterators :cry: 
Updated dev.swi-prolog.org/wasm.   Flush works correctly.  See rebinding of standard streams in shell.html.
