### ISSUE TITLE
minor issue ... absolute_file_name/3 does not see Python Microsoft Store app in Windows 10

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#1030]
Well this is a minor issue, because a professional developer would not install python from Microsoft Store, I think, but I'll still report this here and now. 
process_create/3 depends on absolute_file_name/3 ( with access(read) option) so process_create/3 fails 

```
?- exists_file('c:/users/someuser/appdata/local/microsoft/windowsapps/pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0/python.exe').
true.

?- absolute_file_name('c:/users/someuser/appdata/local/microsoft/windowsapps/pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0/python.exe',Abs,[access(read)]).
ERROR: source_sink `'c:/users/someuser/appdata/local/microsoft/windowsapps/pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0/python.exe'' does not exist
?- version.
Welcome to SWI-Prolog (threaded, 64 bits, version 8.5.15)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

true.
```

**Comment by JanWielemaker** [comment]
Are you claiming the file has no read access?   In that case `access(exist)` might work?    In that case, did something change in Windows?   AFAIK Windows doesn't support files that can be executed but not read, no?

**Comment by xpxaxsxi** [comment]
That is  a [reparse point](https://docs.microsoft.com/en-us/windows/win32/fileio/reparse-points-and-file-operations). Today I have first time ever read about them, weird. 

Sometimes file IO behaves differently when using reparse points says Microsoft. Here is  more [specs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/e57148b1-300b-4d1e-8f67-091de2de815e)

Now according to what I have read today CreateProcess() should be able open them.

**Comment by JanWielemaker** [comment]
Thanks!   Learned something I rather preferred not to have learned :smile:  Pushed SWI-Prolog/packages-clib@da9ccfc462b307eb9ca97eb544ed99c262a92fcc to address this, basically retrying the search with `exist` if `read` fails.   As I understand it, reparse points can do just about anything, so it gets really hard to see what happens :cry: 

Please let me know if you see something better or close this if you agree this is as good as it gets.

**Comment by xpxaxsxi** [comment]
Ok thanks
