### ISSUE TITLE
make fails for SWI-Prolog

### ISSUE THREAD

**Issue by navdeepkjohal** [SWI-Prolog/swipl-devel#1043]
Hello I am building SWi-Prolog on a UBuntu Machine and when I run make I get the following error. Could you please help

/home/na*/swipl-devel/packages/clib/uuid.c: In function ‘pl_uuid’:
/home/na*/swipl-devel/packages/clib/uuid.c:71:23: error: ‘UUID_MAKE_V1’ undeclared (first use in this function)
 { unsigned int mode = UUID_MAKE_V1;
                       ^~~~~~~~~~~~
/home/na*/swipl-devel/packages/clib/uuid.c:71:23: note: each undeclared identifier is reported only once for each function it appears in
/home/na*/swipl-devel/packages/clib/uuid.c:77:3: error: unknown type name ‘uuid_rc_t’; did you mean ‘uuid_t’?
   uuid_rc_t urc;
   ^~~~~~~~~
   uuid_t
/home/na*/swipl-devel/packages/clib/uuid.c:99:19: error: ‘UUID_MAKE_MC’ undeclared (first use in this function); did you mean ‘UUID_MAKE_V1’?
    case 2: mode = UUID_MAKE_MC; break;
                   ^~~~~~~~~~~~
                   UUID_MAKE_V1
/home/na*/swipl-devel/packages/clib/uuid.c:100:19: error: ‘UUID_MAKE_V3’ undeclared (first use in this function); did you mean ‘UUID_MAKE_V1’?
    case 3: mode = UUID_MAKE_V3; break;
                   ^~~~~~~~~~~~
                   UUID_MAKE_V1
/home/na*/swipl-devel/packages/clib/uuid.c:101:19: error: ‘UUID_MAKE_V4’ undeclared (first use in this function); did you mean ‘UUID_MAKE_V3’?
    case 4: mode = UUID_MAKE_V4; break;
                   ^~~~~~~~~~~~
                   UUID_MAKE_V3
/home/na*/swipl-devel/packages/clib/uuid.c:102:19: error: ‘UUID_MAKE_V5’ undeclared (first use in this function); did you mean ‘UUID_MAKE_V4’?
    case 5: mode = UUID_MAKE_V5; break;
                   ^~~~~~~~~~~~
                   UUID_MAKE_V4
/home/na*/swipl-devel/packages/clib/uuid.c:140:7: warning: implicit declaration of function ‘uuid_create’; did you mean ‘uuid_clear’? [-Wimplicit-function-declaration]
       uuid_create(&uuid);
       ^~~~~~~~~~~
       uuid_clear
/home/na*/swipl-devel/packages/clib/uuid.c:141:17: warning: implicit declaration of function ‘uuid_make’; did you mean ‘uuid_type’? [-Wimplicit-function-declaration]
       if ( (urc=uuid_make(uuid, mode)) != UUID_RC_OK )
                 ^~~~~~~~~
                 uuid_type
/home/na*/swipl-devel/packages/clib/uuid.c:141:43: error: ‘UUID_RC_OK’ undeclared (first use in this function); did you mean ‘UUID_MAKE_V5’?
       if ( (urc=uuid_make(uuid, mode)) != UUID_RC_OK )
                                           ^~~~~~~~~~
                                           UUID_MAKE_V5
/home/na*/swipl-devel/packages/clib/uuid.c:142:40: warning: implicit declaration of function ‘uuid_error’; did you mean ‘PL_dlerror’? [-Wimplicit-function-declaration]
  return PL_warning("UUID: make: %s\n", uuid_error(urc));
                                        ^~~~~~~~~~
                                        PL_dlerror
/home/na*/swipl-devel/packages/clib/uuid.c:153:7: warning: implicit declaration of function ‘uuid_load’; did you mean ‘uuid_copy’? [-Wimplicit-function-declaration]
       uuid_load(uuid_ns, ns);
       ^~~~~~~~~
       uuid_copy
/home/na*/swipl-devel/packages/clib/uuid.c:156:7: warning: implicit declaration of function ‘uuid_destroy’; did you mean ‘uuid_type’? [-Wimplicit-function-declaration]
       uuid_destroy(uuid_ns);
       ^~~~~~~~~~~~
       uuid_type
/home/na*/swipl-devel/packages/clib/uuid.c:165:14: error: ‘UUID_LEN_STR’ undeclared (first use in this function); did you mean ‘UUID_RC_OK’?
   { char buf[UUID_LEN_STR+1];
              ^~~~~~~~~~~~
              UUID_RC_OK
/home/na*/swipl-devel/packages/clib/uuid.c:169:15: warning: implicit declaration of function ‘uuid_export’; did you mean ‘uuid_type’? [-Wimplicit-function-declaration]
     if ( (urc=uuid_export(uuid, UUID_FMT_STR, &ptr, &datalen)) != UUID_RC_OK )
               ^~~~~~~~~~~
               uuid_type
/home/na*/swipl-devel/packages/clib/uuid.c:169:33: error: ‘UUID_FMT_STR’ undeclared (first use in this function); did you mean ‘UUID_LEN_STR’?
     if ( (urc=uuid_export(uuid, UUID_FMT_STR, &ptr, &datalen)) != UUID_RC_OK )
                                 ^~~~~~~~~~~~
                                 UUID_LEN_STR
/home/na*/swipl-devel/packages/clib/uuid.c:165:10: warning: unused variable ‘buf’ [-Wunused-variable]
   { char buf[UUID_LEN_STR+1];
          ^~~
/home/na*/swipl-devel/packages/clib/uuid.c:173:14: error: ‘UUID_LEN_SIV’ undeclared (first use in this function); did you mean ‘UUID_LEN_STR’?
   { char buf[UUID_LEN_SIV+1];
              ^~~~~~~~~~~~
              UUID_LEN_STR
/home/na*/swipl-devel/packages/clib/uuid.c:178:33: error: ‘UUID_FMT_SIV’ undeclared (first use in this function); did you mean ‘UUID_FMT_STR’?
     if ( (urc=uuid_export(uuid, UUID_FMT_SIV, &ptr, &datalen)) != UUID_RC_OK )
                                 ^~~~~~~~~~~~
                                 UUID_FMT_STR
/home/na*/swipl-devel/packages/clib/uuid.c:173:10: warning: unused variable ‘buf’ [-Wunused-variable]
   { char buf[UUID_LEN_SIV+1];
          ^~~
packages/clib/CMakeFiles/plugin_uuid.dir/build.make:75: recipe for target 'packages/clib/CMakeFiles/plugin_uuid.dir/uuid.c.o' failed
make[2]: *** [packages/clib/CMakeFiles/plugin_uuid.dir/uuid.c.o] Error 1
CMakeFiles/Makefile2:4580: recipe for target 'packages/clib/CMakeFiles/plugin_uuid.dir/all' failed
make[1]: *** [packages/clib/CMakeFiles/plugin_uuid.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JanWielemaker** [comment]
Looks like you have some uuid library laying around in your system that is not compatible with the ossp-uuid library.   Make sure `libossp-uuid-dev` is installed and there is nothing in e.g. /usr/local that takes priority.

**Comment by navdeepkjohal** [comment]
Hello, Thank you for replying to me. libossp-uuid-dev is already installed in my system. I uninstalled uuid-dev by sudo apt-get remove uuid-dev just to see if that is interfering with the installation. Now I am getting the following error. 

/home/na*/swipl-devel/packages/clib/uuid.c:41:10: fatal error: uuid.h: No such file or directory
 #include <uuid.h>
          ^~~~~~~~
compilation terminated.
packages/clib/CMakeFiles/plugin_uuid.dir/build.make:75: recipe for target 'packages/clib/CMakeFiles/plugin_uuid.dir/uuid.c.o' failed
make[2]: *** [packages/clib/CMakeFiles/plugin_uuid.dir/uuid.c.o] Error 1
CMakeFiles/Makefile2:4580: recipe for target 'packages/clib/CMakeFiles/plugin_uuid.dir/all' failed
make[1]: *** [packages/clib/CMakeFiles/plugin_uuid.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

Could you please tell what else could interfere with the libossp-uuid-dev ? Any help would be appreciated. 

Thanks

**Comment by JanWielemaker** [comment]
The fact that removing uuid-dev causes these problems suggest an interaction.   Note that after making these changes you should re-run `cmake` to make it find the new locations and you must make sure it doesn't use its cache.   Possibly this suffices:

    cmake -U '*UUID*' .

But when unsure what you are doing, remove CMakeCache.txt and re-run cmake.    You make also look in `CMakeCache.txt` to see where it things the UUID library and headers are and whether that matches ossp-uuid.

**Comment by navdeepkjohal** [comment]
Hello,

removing CMakeCache.txt and re-run cmake has worked for me. the make command ran without error this time. 

Thank you so much for you kind help !
