### ISSUE TITLE
PL_scan_options() doesn't respect flag OPT_ALL

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1058]
I started to make PR to fix this (add `flags` field to `struct dictopt_ctx`), but wasn't sure how to do a PL_domain_error() call in `dict_option()`, which returns -1 for error (it's used by `PL_for_dict()`.

**Comment by kamahen** [comment]
I have a test case for this in packages/cpp (not yet in a PR).

**Comment by JanWielemaker** [comment]
> but wasn't sure how to do a PL_domain_error() call in `dict_option()`

I'd expect `return PL_domain_error(...), -1` to work.

**Comment by JanWielemaker** [comment]
Closing.   Supported in current version.
