### ISSUE TITLE
Negation breaks solving?

### ISSUE THREAD

**Issue by inferrna** [SWI-Prolog/swipl-devel#1064]
Hi. I'd tried to solve a real world problem which is very meaning to me: https://logiclike.com/2.0/cabinet/exercise/1/1/1/problem/79475

So I wrote this code:
```prolog
is_good(Item) :-
    not(round(Item)),
    green(Item).

round(melon).
round(umbrella).
round(ball).

green(melon).
green(bow).
```
Trying to solve this, I got:
```prolog
is_good(bow).
true
is_good(melon).
false
is_good(X).
false
```
So, there is one solution, but we have to check it manually.
But when I changed code to this (no negation):
```prolog
is_good(Item) :-
    round(Item),
    green(Item).

round(melon).
round(umbrella).
round(ball).

green(melon).
green(bow).
```
All seems fine:
```prolog
is_good(bow).
false
is_good(melon).
true
is_good(X).
X = melon
```

I'm very new in Prolog, hope right way to solve this problem is more obvious than chosen by me.

**Comment by JanWielemaker** [comment]
Please discuss these things in the forum or Stackoverflow.    This is a place for bugs, etc, not for discussing how to use Prolog.
