### ISSUE TITLE
pack_install appears to not propogate enviroment variables.

### ISSUE THREAD

**Issue by blueforesticarus** [SWI-Prolog/swipl-devel#1070]
When using pack_install, environment variables like PKG_CONFIG_PATH appear not to propagated to invoked build processes.

**Comment by JanWielemaker** [comment]
For now added `PKG_CONFIG_PATH` to the passed variables.   I'm not sure whether propagating everything is a good idea.  Might be ...

**Comment by blueforesticarus** [comment]
Not propagating everything is extremely abnormal. And confusing. 
The user has a multitude of ways to *prevent* env vars from being passed, but if pack_install decides not to propagate something there is basically no way to work around it.

**Comment by JanWielemaker** [comment]
Agree.   Pushed.   Pushed a change.    Most of the normal build-related environment is redefined anyway, so what is left are things such as PKG_CONFIG_PATH, etc.

**Comment by blueforesticarus** [comment]
> normal build-related environment is redefined anyway

I think this needs clearer documentation on what exactly gets clobbered. You may even consider printing a warning when those  env vars have pre-existing values.

**Comment by JanWielemaker** [comment]
See build_environment/2 in library/build/tools.pl

**Comment by blueforesticarus** [comment]
I find it confusing that 
1. https://www.swi-prolog.org/pldoc/doc_for?object=build_tools%3Abuild_environment/2
2. https://www.swi-prolog.org/pldoc/doc/_SWI_/library/build/tools.pl
3. https://www.swi-prolog.org/pldoc/man?section=prologpack
don't link to each other at all.

Specifically I remember seeing (1) and then never being able to find it again :/
