### ISSUE TITLE
unhandled exception writing a string in xpce text editor

### ISSUE THREAD

**Issue by bobtie** [SWI-Prolog/swipl-devel#1077]
using the graphical xpce editor to edit a file, when I start writing a string, after having typed in the first " character an exception "Unhandled exception: append_args/3: Unknown procedure" appears in a dialog.

prolog version: SWI-Prolog version 8.4.2 for x86_64-linux
installation: sudo apt install swi-prolog-full
OS: ubuntu 22.04 on a virtual machine

**Comment by JanWielemaker** [comment]
Doesn't reproduce in 9.0.0, so I assume it is fixed.    Please upgrade and if the problem persists reopen with a detailed description on your interaction with the debugger/editor.
