### ISSUE TITLE
working_directory(CWD, CWD) returns path to target of a symlink, not the link itself

### ISSUE THREAD

**Issue by anionic** [SWI-Prolog/swipl-devel#1082]
In SWI-Prolog 8.1.32, but not in 8.0.3, built under CentOS 7, where the working directory is a soft link to somewhere, `working_directory(CWD, CWD)` returns the path to the **target**, where it formerly returned the path to the link itself.

**Comment by JanWielemaker** [comment]
Are you sure something changed?   Both are really old versions  ...    working_directory/2 returns the canonical working directory.    On Unix platforms SWI-Prolog maintains a table of canonical directories.   If it needs to return a canonical directory it first does a dev/ino lookup there.  So, if it ever decided CWD or one of the parent directories had some specific path, it sticks to this.    That code is already very old.

**Comment by anionic** [comment]
Sorry, totally false alarm; had me convinced for a while but it was entirely my fault :-/
