### ISSUE TITLE
http_post/4 gives out  stream  that is not utf8, http_open/3 gives out octet stream, in Windows 10

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#1085]
I am not sure about if this is a symptom for some bug in Swi-Prolog or in some https server sending out JSON code, but I'll try to explain why I think is weird. 

http_post/4 gives out data that has some encoding problems, like name "Aki Kaurismäki" in JSON responses gets written as "Aki KaurismÃ¤ki". I have not found any option to fix this.
Tried debugging it using the output(X) option, X gives out an stream pair, and it's readable part is reported with stream_property/2 as encoding(wchar_t), isn't this weird??

When I change my code to use http_open/3, I have now access to the stream. The encoding is reported as octet (weird??). But now I am able to fix the encoding/decoding issues somewhere, I can set_stream/2 the stream to utf8 and everything is fixed

This did not happen when I set up a local server with Swi-Prolog, but I did not use the JSON libraries, my local server  just sent back plain text. 
I have been playing with OpenAI site's API, but this is not the first site where http_open/3 needs it's stream fixed.

I have rarely used the http_open/3 (in Windows 10) and I think I have always had to fix the stream encoding ...  I am not sure.  This is not a new behaviour, this has been around for years. 
I have not really used the http_post/4, this probaply was first time ever. 
Could be that I have some request headers left out or used badly.

**Comment by JanWielemaker** [comment]
Its hard to say without code to reproduce.   The wchar_t hints you get the wrong stream somehow.    Sockets starts with octet encoding and may switch to something else depending on the Content-type header.    As this seems to happen with public services, why don't you make the exact call available?

**Comment by xpxaxsxi** [comment]
I have not  used a proper module...  I also made some Windows 10 configuration changes, but it seems
that this was a module issue.

These modules create the streams with octet/wchar_t. 
Now http_post/4   Reply argument is an atom.
```
:- use_module(library(http/json)).  %wrong module, no effect if I comment out this
:- use_module(library(http/http_client)).
```

Now the http_post/4 Reply is straight away a json term without encoding problems! Great!
```
:- use_module(library(http/http_json)).  %this is the proper one
:- use_module(library(http/http_client)).
```

Now that http_post/4 is working I am happy with that. 
Earlier quick fix using http_get/3 still needs a manual change by set_stream/2 to utf8,

**Comment by JanWielemaker** [comment]
Without `library(http/http_json)` the HTTP client libraries do not know how to deal with `application/json` and thus simply return the text.   If there is no explicit encoding in the HTTP reply it assumes binary encoding.   That is how it works intentionally.  

AFAIK this should also apply to http_get/3 as it uses the same logic to process the reply.   Only http_open/3 is different; it just returns a stream and leaves all the post processing to the user.

**Comment by xpxaxsxi** [comment]
Sorry I meant http_open/3 when I earlier wrote about http_get/3
