### ISSUE TITLE
`max(1,nan)` broken in 9.1.2

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#1095]
In 9.1.2 (but not 9.1.1), arithmetic function max erroneously returns `nan` when only one argument is `nan`. Example:
```
?- X is max(1,nan).
X = 1.5NaN.
```
However:
```
?- X is max(nan,1).
X = 1.

?- X is max(1.0,nan).
X = 1.0.

?- X is min(1,nan).
X = 1.
```
Reproducible on current SWISH (9.1.2). 

Suspect it has something to do with:https://github.com/SWI-Prolog/swipl-devel/commit/3e8df9b1b02eb523e9f31710b086d33cc9444680

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 73d55e15f29e481d6a407aa6e900974edcdd2750.  Also added tests.   The simplification to simply revert the arguments for the case when the second argument is a float got us `-CMP_NOTEQ`, which is not correct.
