### ISSUE TITLE
ctrl-C in read causes exit from REPL

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1097]
If I interrupt a read with ctrl-C, the various debug options either do nothing (e.g., "continue") or raise "abort" or "exit". Both of the latter exit from the top-level. I'm pretty sure this is a somewhat new behavior, but haven't tried to track down when it started.
```
$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 9.1.2-17-gcd86f975e-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- foo
|    ^C
Action (h for help) ? abort
$
```

**Comment by kamahen** [comment]
I rebuilt with the latest commit - https://github.com/SWI-Prolog/swipl-devel/commit/0a145e44bd89e5743e45b0e8828f5d1b98c29620 - and got the same result (except for the version # of course).

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/cant-terminate-input-routine-or-infinite-loops-without-corrupting-prolog-session/6850/2
