### ISSUE TITLE
Fails to build on systems without libgmp

### ISSUE THREAD

**Issue by sei-mwd** [SWI-Prolog/swipl-devel#1113]
The change a8a4ba95999f6d8858d7e2088261ff2484fd500c causes build failures on systems without `O_GMP` defined.  This is due to the `get_rational` macro being defined twice in `pl-gmp.h`, once on line 46 and once on line 157.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with e23dc5668113f76cff92fd4a51eb5f562e91a527.   Note that this asks for both ``-DUSE_GMP=OFF -DUSE_LIBBF=OFF``.   I don't know whether there is much sense to keep supporting that.    Would have to evaluate the performance and size impact.

**Comment by JanWielemaker** [comment]
Just made the test on the benchmark suite, which does a lot of small number arithmetic.   There is no measurable performance impact between no bignum at all, gmp bignum or libbf bignum.   Sizes are 1.65Mb (no bignum), 1.70Mb (GMP bignum, so you also get libgmp.so) and 1.82Mb for LibBF based bignums.   Seems there is not much reason to maintain the no bignum version.
