### ISSUE TITLE
Error in doc on page https://www.swi-prolog.org/pldoc/man?section=threadsync

### ISSUE THREAD

**Issue by briggs-w** [SWI-Prolog/swipl-devel#1116]
There is an error in the example program.  The line

                   ( retractall(address(Id, _)),

should be

                   ( retractall(address_db(Id, _)),

since what's being asserted/retracted is the address_db/2 fact(s), not the address/2 relation. Changing this gives the desired/expected behavior.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed (will be on the online docs with the next release).
