### ISSUE TITLE
Missing string_insert fonction ?

### ISSUE THREAD

**Issue by n-ai-up8-edu** [SWI-Prolog/swipl-devel#1121]
Dear All,
Insertion inside a string is very usefull.
As I haven't found a function to perform an insertion in a string, I propose to add the following function in swipl.
The following insert Val at the position At in Str to make NewStr :
/////////////////////
string_insert(Str,Val,At,NewStr):-
  string_length(Str,Size),sub_string(Str,0,At,_,Str1),
  N is Size-At, sub_string(Str,At,N,_,Str2),
  string_concat(Str1,Val,Str3),string_concat(Str3,Str2,NewStr).
/////////////////////
Or did I missed a function somewhere ?

**Comment by kamahen** [comment]
This appears to do what you want:
```prolog
string_insert(Str, Val, At, NewStr) :-
    sub_string(Str, 0, At, A1, S1),
    sub_string(Str, At, A1, _, S2),
    atomic_list_concat([S1,Val,S2], NewStr).
```

**Comment by JanWielemaker** [comment]
> ```prolog
> atomic_list_concat([S1,Val,S2], NewStr).
> ```

atomics_to_string([S1,Val,S2], NewStr). if you want a string as result.    May be useful for your application.   In general Prolog systems do not natively support this AFAIK, so I assume the demand is low.   Surely I never needed it :smile:

**Comment by kamahen** [comment]
The documentation has examples spread between sub_atom/5 and sub_string/5 ... I will combine them and add the "insert" example. (I think I have a few other examples of using sub_string/5, which I can also add)

**Comment by n-ai-up8-edu** [comment]
Tx for the answer. I did not thought using atomic_list_concat.
