### ISSUE TITLE
PL_atom_to_encoding() in wrong header file?

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1133]
`PL_atom_to_encoding()` and `PL_encoding_to_atom()` in `SWI-Stream.h` are inside `#ifdef _SWI_PROLOG_H`, which means that `SWI-Prolog.h` is required to be included before `SWI-Stream.h`.

However, `foreign.doc` says in the documentation for `\cfunction{int}{write}{IOSTREAM *s, atom_t a, int flags}`:
```
The \arg{flags} are a bitwise
\emph{or} of zero or more of the \const{PL_WRT_*} flags defined in
\file{SWI-Prolog.h}. This prototype is available if the
\file{SWI-Stream.h} is included \emph{before}
\file{SWI-Prolog.h}.
```
One of these is wrong.
(There's also one code example in `foreign.doc` that has `SWI-Stream.h` included before `SWI-Prolog.h`.

Ideally, the order of includes shouldn't matter.

**Comment by kamahen** [comment]
Whatever decision is made for this, there are also a few functions in pl-wic.c that will need to be treated similarly for issue https://github.com/SWI-Prolog/swipl-devel/issues/1120, such as
`PL_qlf_putStringW(const pl_wchar_t *s, size_t len, IOSTREAM *fd);`
because of `pl_wchar_t`.

**Comment by JanWielemaker** [comment]
Making the order irrelevant is probably best.     I guess that may involve a helper to get the common definitions in place?

**Comment by kamahen** [comment]
Should I create SWI-Prolog2.h, which is included by both SWI-Prolog.h and SWI-Streams.h and contains (for now) just `atom_t`?

**Comment by JanWielemaker** [comment]
If that is all that is needed, just duplicate the definition and add some macro such that they are not defined twice.   That seems easier to manage than adding a file that must be handled by installers, etc.  Something like can simply appear in both files.

```
#ifndef PL_COMMON_TYPES_DEFINED
#define PL_COMMON_TYPES_DEFINED
typedef ...
...
#endif
```

**Comment by kamahen** [comment]
Please assign this to me and I'll fix it as part of the "Make some functions in pl-wic.c public" work (PR https://github.com/SWI-Prolog/swipl-devel/pull/1134 and follow-ons)

**Comment by JanWielemaker** [comment]
Thanks.

**Comment by JanWielemaker** [comment]
Closing as fixed.
