### ISSUE TITLE
PL_PRUNED not called for C++ foreign predicate

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1150]
When a non-deterministic foreign predicate is pruned (by a cut), PL_PRUNED isn't called, so there's no chance to clean up the context.
This only happens with foreign predicates written in C++; the similar predicate written in C does get called with PL_PRUNED. Possibly relevant: for the C code, the PL_register_foreign() option is PL_FA_NONDETERMINISTIC; for C++, it's PL_FA_NONDETERMINISTIC|PL_FA_VARARGS.

(Test code is in test_cpp.cpp and test_cpp.pl)

@JanWielemaker where is PL_PRUNED set for calling a foreign predicate? - I ran grep over the source but didn't find it and `pl-wan.c is` not easy to read.

**Comment by JanWielemaker** [comment]
The cleanup is called from discardForeignFrame().  It still uses the old FRG_CUTTED, but this is the same as PL_PRUNED.   Should work fine with VARARGS as that is also used for almost all internal foreign predicates.

**Comment by kamahen** [comment]
It's a bit difficult to trace this, even with a DEBUG build. It appears that the problem is in discardForeignFrame() [`pl-wam.c:603] - `true(def,P_VARARG)` seems to return FALSE even though this is a C++ foreign function that should be vararg. When I traced through the code with gdb, it seemed to skip over both the "then" and the "else" of the test. The net result was that the foreign function simply wasn't called. (This might be a compiler bug? I'm using g++ (GCC) 12.2.1 20220822)

Here is code to reproduce - call with `range(1,10,X)` and do a top-level cut:
```cpp
PREDICATE_NONDET(range_cpp, 3)
{ auto t_low = A1, t_high = A2, t_result = A3;
  PlForeignContextPtr<RangeCtxt> ctxt(handle);

  switch( PL_foreign_control(handle) )
  { case PL_FIRST_CALL:
      ctxt.set(new RangeCtxt(t_low.as_long(), t_high.as_long()));
      break;
    case PL_REDO:
      break;
    case PL_PRUNED:
      return true;
    default:
      assert(0);
      return false;
  }

  if ( ctxt->i >= ctxt->high ||
       !t_result.unify_integer(ctxt->i) )
    return false;

  ctxt->i += 1;
  if ( ctxt->i >= ctxt->high )
  { return true; // Last result: succeed without a choice point
  }

  ctxt.keep();
  PL_retry_address(ctxt.get()); // Succeed with a choice point
}
```

This probably needs the latest version of `SWI-cpp2.h`, which is here:
https://github.com/kamahen/packages-cpp/tree/exceptions  (https://github.com/kamahen/packages-cpp branch `exceptions`)
(The code for `range_cpp/3` is in `test_cpp.cpp` of that branch)

**Comment by kamahen** [comment]
I downgraded to gcc 12.2.0, which is an official release, and got the same behavior. I also tried 10.2.1 and it was the same -- neither the "then" nor the "else" appeared to be executed. I confirmed that the foreign predicate wasn't being called, using debug print statements.

There is a slight possibility that I'm freeing the "handle" to the non-deterministic predicate when doing PL_retry_address ... is there a way to check for this? (I'm 99.9% sure that I'm not freeing it - but C++ destructors can sometimes do weird things)

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/cpp2-exceptions/6040/68

**Comment by JanWielemaker** [comment]
Tried to compile, but it doesn't have `RangeCtxt`.  Guess it is on some header and I may need some more flags, but Google does not give quick answers.   Please use complete code ....

**Comment by JanWielemaker** [comment]
Thanks.   It calls the implementation fine.   Just, the passed `t0` term handle is `0` (zero), which is not appreciated by

    return pl_ ## name ## __ ## arity(PlTermv(arity, PlTerm_term_t(t0)), c);

In the PL_PRUNED branch, __only__ the context contains valid information; the arguments are not available.    Closing this here as this is not a core issue but an packages/cpp issue.

**Comment by kamahen** [comment]
I don't think that that's the cause -- PlTerm_term_t() isn't supposed to check the validity of the term_t; and if it did, it would throw an exception (from the verify() method) and I didn't see that when I was tracing using gdb. But the gdb trace didn't even seem to call the foreign function (or its C++ wrapper) -- I don't understand what I saw because the gdb "step" seemed to skip over both the "then" and the "else" parts of the conditional. (You might need my latest version of SWI-cpp2.h to look at this -- it's in https://github.com/kamahen/packages-cpp/tree/exceptions).

I am unable to work on this because we've lost power again (from the recent storms). When I'm able, I'll try tracing the execution again - it's possible that I did something stupid when using gdb, which is why I didn't see the call to the foreign function. [I was using a debug build, so the compiler shouldn't have done any optimization]

**Comment by JanWielemaker** [comment]
It is :smile:     Possibly you messed up something with gdb.  Add to SWI-cpp2.h:

```
	_pl_ ## name ## __ ## arity(term_t t0, int a, control_t c) \
	{ (void)a; \
Sdprintf("Calling with t0=%zd; control = %p\n", (size_t)t0, c); \
```

Next:

```
swipl-ld -g -o ndet -shared ndet.cpp
swipl
?- use_foreign_library(ndet).
?- range_cpp(0, 4, X).
Calling with t0=182; control = 0x7ffe284089f8
X = 0 ;
Calling with t0=182; control = 0x7ffe284089f8
X = 1 .

Calling with t0=0; control = 0x7ffe28408170
?- 
```
You see?   When I finish the iteration the toplevel cuts the query and we see `Calling with t0=0; control = 0x7ffe28408170`

Hope power is restored soon.

**Comment by kamahen** [comment]
It seems that the DEBUG option isn't turned on for the C++ compilation. For example, it seems that `O_DEBUG` wasn't set. This could account for why I had trouble stepping with gdb - there's probably quite a bit inline optimizing.

BTW, it does seem that a `PlFail` is being thrown, which shouldn't happen with a call to `PlTerm_term_t`, so it's good that we caught this now.

I think I've got the debug flag working by adding this to `BuildType.cmake` (is the `CACHE_STRING` line correct?):
```
  set(CMAKE_CXX_FLAGS_DEBUG "-DO_DEBUG -DO_DEBUG_ATOMGC -O0 -gdwarf-2 -g3"
      CACHE STRING "CFLAGS for a Debug build" FORCE)
```

**Comment by kamahen** [comment]
I've figured it out, even though gdb was not very cooperative.
Briefly, Pltermv() checked the validity of its arguments, so I just let it assume its arguments are valid.
I also fixed a number of places where `PlFail` was being thrown instead of `PlException`.
And I'll make a PR to set the debug flags for C++.
