### ISSUE TITLE
time/1 and run_tests give wrong times, inferences when run in multiple threads

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1151]
Here is what happens when I run my tests with `jobs(1)`:
```
$ time swipl -g 'time(run_tests)' -t halt  ~/src/nerdle/test_nerdle.pl 
[127/127] nerdle10:9 ........................................ passed (0.024 sec)
% All 127 tests passed in 67.769 seconds (67.750 cpu)
% 695,642,884 inferences, 67.757 CPU in 67.776 seconds (100% CPU, 10266803 Lips)

real	1m9.434s
user	1m9.325s
sys	0m0.102s
```
And when I add `:- set_test_options([jobs(11)]).` on a 4-core machine:
```
$ time swipl -g 'time(run_tests)' -t halt  ~/src/nerdle/test_nerdle.pl 
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――











―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
% All 127 tests passed in 24.373 seconds (0.005 cpu)
% 41,772 inferences, 0.023 CPU in 24.391 seconds (0% CPU, 1803568 Lips)

real	0m25.889s
user	1m34.192s
sys	0m0.094s
```

**Comment by JanWielemaker** [comment]
time/1 doesn't count time in threads it creates.    This could be done, but is not trivial as threads and their creator are basically unrelated.   So, T can start T1 and die while T1 remains running, T1 may be detached or joined by some arbitrary Tx.    A partial solution is probably to add a stat field for time in child threads and add to that if a thread is joined by the same thread that created it.    Jan Burse suggested something along these lines.    

"The same thread that created it" is not so easy though, as we cannot use the integer thread id (might be reused) and we cannot use the thread handle as that is a blob subject to GC and we do not want to prevent GC.    We'd need something like a sequence count for created threads?

**Comment by kamahen** [comment]
Working as I expect with 93c3f9c29eda9a27a203842d193cfaceb64935e7

```
$ time swipl -g 'time(run_tests)' -t halt  ~/src/nerdle/test_nerdle.pl 
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――












―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
% All 131 tests passed in 20.974 seconds (0.004 cpu)
% 716,279,726 inferences, 88.878 CPU in 20.992 seconds (423% CPU, 8059166 Lips)

real	0m22.437s
user	1m30.195s
sys	0m0.142s
```
