### ISSUE TITLE
Non coherent tags

### ISSUE THREAD

**Issue by moueza** [SWI-Prolog/swipl-devel#1152]
Hi 
in https://www.swi-prolog.org/build/PPA.html > Stable versions

sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  swi-prolog-core swi-prolog-core-packages swi-prolog-doc
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  swi-prolog-nox
Suggested packages:
  prolog-el
The following packages will be upgraded:
  swi-prolog-nox
1 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
4 not fully installed or removed.
Need to get 0 B/4 352 kB of archives.
After this operation, 21,9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 731155 files and directories currently installed.)
Preparing to unpack .../swi-prolog-nox_9.0.4-3-g333f86c3d-kineticppa2_amd64.deb 
...
Unpacking swi-prolog-nox (9.0.4-3-g333f86c3d-kineticppa2) over (8.4.2+dfsg-2ubun
tu1) ...
dpkg: error processing archive /var/cache/apt/archives/swi-prolog-nox_9.0.4-3-g3
33f86c3d-kineticppa2_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/cmake/swipl/SWIPLConfig.cmake', which is also in 
package swi-prolog-core 8.4.2

... indicates that 8.4.2 and 9.0.4 are stable versions : but these ones are not in main tag views https://github.com/SWI-Prolog/swipl-devel/tags?after=V8.5.9

**Comment by JanWielemaker** [comment]
The stable versions are maintained in SWI-Prolog/swipl.git.   That is where you also find these tags.    It may have been better to have one repo and use two branches.   Effectively this is more or less the same though.    swipl.git merges from swipl-devel.git for a major new version and cherry-picks from there for patch levels.
