### ISSUE TITLE
SERVER ERROR 

### ISSUE THREAD

**Issue by Nelson6203** [SWI-Prolog/swipl-devel#1154]
Today while i was to go continue with my project, I got this error message when I tried to open my project (web version)
Server error
{ "code":500, "message":"redis:redis_write_msg/2: stream `(0x557cf8f9ec00,0x557cf870ec00)' does not exist" }

Is there any way to recover the project?

**Comment by JanWielemaker** [comment]
The server is back online.   Thanks for reporting.
