### ISSUE TITLE
ERROR: Duplicate key

### ISSUE THREAD

**Issue by z5h** [SWI-Prolog/swipl-devel#1156]
I'm using Dicts in findall.

When I do a `State.put([k1=v1,k2=v2])` I get the error.
When I do `State.put(k1,v1).put(k2,v2)` the error does not occur.

I'm being careful to always use keys in order.
I haven't yet been able to reproduce this in isolation.

**Comment by kamahen** [comment]
How are you using `State.put` in findall/3?
This might help you understand what's going on. As you can see, the `.` operator is expanded at compile time.
```
p1(State) :- State.put([k1=v1,k2=v2]) .

p2(State) :- State.put(k1,v1).put(k2,v2).
```
```
?- listing(p1).
p1(State) :-
    '.'(State, put([k1=v1, k2=v2]), A),
    call(A).


?- listing(p2).
p2(State) :-
    '.'(State, put(k1, v1), A),
    '.'(A, put(k2, v2), B),
    call(B).
```

**Comment by JanWielemaker** [comment]
Closing as there is no follow up.    For questions, please use https://swi-prolog.discourse.group/
