### ISSUE TITLE
Wrong arity for some predicates in navigation index

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#116]
On the SWI Web site, the handy navigation index on the left hand side displays a wrong arity for some predicates.

Example: `rdf_register_predicate/2` appears twice on [this page](http://www.swi-prolog.org/pldoc/man?section=semweb-prefixes).

Intended behavior: the second occurrence should be ternary.

**Comment by JanWielemaker** [comment]
Dealing with multiple predicates in one description has been improved a lot.  This was one of the issues.  Closing.
