### ISSUE TITLE
Prolog flag answer_write_options is ignored

### ISSUE THREAD

**Issue by duesentrieb17** [SWI-Prolog/swipl-devel#1164]
Hi Jan,

as I understand it, an empty option list for write_term/2 should result in the options defined by the Prolog flag answer_write_options being used:
_answer_write_options(term, changeable)  
This argument is given as option-list to [write_term/2](https://www.swi-prolog.org/pldoc/man?predicate=write_term/2) for printing results of queries._
```
?- current_prolog_flag(answer_write_options,O).
O = [quoted(true), portray(true), max_depth(10), spacing(next_argument)].

?- write_term(t(1,2),[]).
t(1,2) <-- the space is missing
true.
```

Or is the flag answer_write_options completely ignored by now?
Which would be a pity, because then you can't adjust the outputs globally.

Regards
Holger

**Comment by JanWielemaker** [comment]
This flag is used by the toplevel to print answers.    It has no effect on write_term/2,3.   It is the toplevel that gets a term and uses write_term/3 using the options from this flag.   We don't want write_term/2,3 to depend on some flag.    If the docs suggests this, please show where and I'll correct it.

It is of course easy enough to add your own write variant that uses some flag to define the defaults.

**Comment by duesentrieb17** [comment]
Thanks for the clarification!
However, it would be good if the documentation for the answer_write_options flag would be improved accordingly:
https://www.swi-prolog.org/pldoc/doc_for?object=current_prolog_flag/2

Implementing our own special variants is of course no problem.

But my problem is that there are a lot of calls to format/2 in our code.
And there is a difference in the output of terms between v5.9.7 and the current version v9.

v5.9.7:
```
1 ?- format('~w',t(a,b)).
t(a, b) <- with blank
```

v9.0.4:
```
?- format('~w',t(a,b)).
t(a,b) <- without blank
```

And unfortunately, the blanks in our security-related output files are also significant.
So I was looking for a way to make it easier for me to port our SW to the current version.
