### ISSUE TITLE
Permission error: modify static_procedure while asserting/retracting/abolishing dynamic predicates

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/swipl-devel#1168]
Bug found running Logtalk `benchmarks` example while testing SWI-Prolog 9.1.8. With repeated asserting/retracting/abolishing dynamic predicates (as performed when running the example), SWI-Prolog aborts with errors like:

```text
$ swilgt -q
?- {benchmarks(loader)}.
...
?- benchmarks::run(100000).
...
!     Permission error: modify static_procedure '$xpto#0._super'/5
!       in goal: create_object(xpto,[],[],[])
!       with execution context:
!         entity:            benchmarks
!         sender:            user
!         this:              benchmarks
!         self:              benchmarks
!         meta-call context: []
!         coinduction stack: []
!     
```

But the reported predicate is dynamic, not static. This bug doesn't occur when the number of repetitions is smaller. You may need to increase the number (or be able to decrease it) depending on hardware performance.

**Comment by JanWielemaker** [comment]
Thanks.  Reproduces (needed to increase the number of repetitions; 1 000 000 did the trick).    I'll see what gdb thinks about this.
