### ISSUE TITLE
Operator definition in a module seems to need a definition in parent module to be fully defined

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#1175]
Could be that I am not understanding something from [Operators](https://www.swi-prolog.org/pldoc/man?section=operators).  I have a version 9.1.6 in Windows 10
```
1 ?- module(tmp1).
Warning: tmp1 is not a current module (created)
true.

tmp1: 2 ?- op(501,xfy,<-).
true.

tmp1: 3 ?- A=a<-b-c. % I expected to have "A= a<-b-c." printed out
A = <-(a, b-c). 

tmp1: 4 ?- module(user).
true.

5 ?-  op(501,xfy,<-).
true.

6 ?- module(tmp1).
true.

tmp1: 7 ?- A=a<-b-c.
A = a<-b-c.

tmp1: 8 ?-

```

Interestingly this works with [write_term/2](https://www.swi-prolog.org/pldoc/doc_for?object=write_term/2)
```
1 ?- module(tmp1).
Warning: tmp1 is not a current module (created)
true.

tmp1: 2 ?-  op(501,xfy,<-).
true.

tmp1: 3 ?- A=a<-b-c,write_term(A,[module(tmp1)]).
a<-b-c
A = <-(a, b-c).

tmp1: 4 ?- A=a<-b-c,write_term(A,[module(user)]).
<-(a,b-c)
A = <-(a, b-c).
```

**Comment by JanWielemaker** [comment]
As documented in write_term/2, writing by default uses the operators from module `user`, regardless of the calling context.   That decision was mostly to reduce the impact of introducing
module-local operators.   One could argue that this should be different if the toplevel module is changed.    That might also lead to more confusion as it would cause the toplevel answer writing and explicit writes to behave differently.

Unfortunately there is no agreement in the Prolog world on how operators and modules interact.

Please use the Discourse forum for this type of questions and only use this for obvious bugs.
