### ISSUE TITLE
Add issue forms/templates

### ISSUE THREAD

**Issue by Panquesito7** [SWI-Prolog/swipl-devel#1177]
### Description

By adding issue templates/forms, it'll be easier for the maintainers and users to create and manage issues.
You can have checkboxes, required fields, dropdowns, and so much more.

More information: https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

**Comment by JanWielemaker** [comment]
Thanks for the suggestion.   As far as I'm concerned most of the issues are fairly clear or would not have become much clearer by using a form.    Yes, occasionally a version, OS, etc. is missing.   But then, often it does not matter and we also have cases where really more detail is required, such as how it has been built with which compiler, etc.     The ideal bug report has a program to replicate the issue, but this is not always possible.    All in all, the system has too many build and usage options to cover these in a form and we have to rely on thinking users.    Many do well.

**Comment by Panquesito7** [comment]
Yes, good point. We could have a section for additional information.
But do it as you wish. Thank you. 🙂

**Comment by kamahen** [comment]
My 2 cents is that experienced developers will write useful bug reports even without a form; if we start getting less experienced people reporting bugs, we might need a more structured form. (SWI-Prolog is also remarkably stable, so most of the bugs seem to be in corner cases where people are pushing the limits, and not the kinds of things that beginners are likely to run into.)
