### ISSUE TITLE
Add funding button

### ISSUE THREAD

**Issue by Panquesito7** [SWI-Prolog/swipl-devel#1178]
### Description

The organization has GitHub Sponsors/funding support, which is displaying a button in the organization.

However, a button can be added to the repository as well by adding a `FUNDING.yml` file (more information [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)).
This can help by promoting the sponsorship on the repository as well.

What do you think about this? Thanks. 🙂

**Comment by JanWielemaker** [comment]
Thanks for the tip.   I'll surely look into that :smile:

**Comment by JanWielemaker** [comment]
Added :smile:
