### ISSUE TITLE
`qsave_program` fatal error saving bundled module `clpBNR`

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#1184]
SWIP 9.1.11, MacOS 10.14.g (Mojave)

Running from the command line (qt console vanishes on abort):
```
$ /Applications/SWI-Prolog9.1.11.app/Contents/MacOS/swipl 
Welcome to SWI-Prolog (threaded, 64 bits, version 9.1.11)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?-  use_module(library(clpBNR)).
% *** clpBNR v0.11.1 ***.
%   Arithmetic global flags set to prefer rationals and IEEE continuation values.
true.

?- qsave_program(test_qsave).
% Disabled autoloading (loaded 53 files)
% Disabled autoloading (loaded 2 files)
% Disabled autoloading (loaded 0 files)
[FATAL ERROR: at Thu Jul  6 12:44:12 2023
	No support for VM argtype 9 (arg 0 of a_mpq)]
Abort trap: 6
$ 
```

**Comment by kamahen** [comment]
I did a fresh `pack_install(clpBNR)` and it worked for me. (version version 9.1.11-1-g1ae98e16e-DIRTY - but the changes from 9.1.11 are trivial)

**Comment by ridgeworks** [comment]
I believe you're on Unix. From the message, I think this has something to do with rational arithmetic support. For the past few releases the Mac versions (since 9.1.0?) have been using LibBF rather than GMP. My suspicion is the root cause is somewhere in this area.

Thanks for confirming correct operation on Unix/GMP (?).

**Comment by kamahen** [comment]
From looking at the code for saveWICClause() (in pl-wic.c), which seems to be emitting the error message, there are few cases that are ifdef-ed out for a non-GMP executable. In particular, `CA1_MPQ` seems to correspond to the `9` in your error message.

**Comment by ridgeworks** [comment]
Don't really understand the details but this would suggest that maybe occurrences of `O_GMP` in `pl-wic.c` should be replaced by `O_BIGNUM`.

**Comment by ridgeworks** [comment]
If the theory is correct, I'm pretty sure  @JanWielemaker will know what to do - he did all the necessary changes to support LibBF as an option.

**Comment by JanWielemaker** [comment]
I pushed 6160c27ecde9cce918c87cc08711cec75c18f1e6, which deals with the saving part.    That was easy and ensures bignums/rationals from the LibBF version can be read by the GMP version.

The other side, reading into the LibBF version when restoring a state is harder.   It seems this code can use some merging or at least inspiration from the `IMPORT/EXPORT` code in pl-gmp.c, which deals with bignums in PL_record_external().     A quick scan suggests this format is identical or nearly identical.

The representation of bignums in compiled code is different for the two libraries.   This implies we may need to update the size of the loaded clause and relative jump instructions.    That all has some support as that is also required to load states from the 32-bit VM onto the 64-bit one and the other way around.

It requires more work for which I do not have time now (and next week I'm at the ICLP in London).

**Comment by ridgeworks** [comment]
>    It requires more work for which I do not have time now (and next week I'm at the ICLP in London).
No need for quick resolution on my part, now that I understand the problem.
