### ISSUE TITLE
format('~W', [X, [numbervars(true)]]) ignores "numbervars"

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1186]
The first two printed lines should be the same, but aren't. Note that `quoted(true)` is obeyed; only `numbervars(true)` is ignored..
```prolog
?- Goal=foo(X,a,'b c',Y,X), 
    format('~W~n', [Goal, [numbervars(true),quoted(true)]]), 
    print_term(Goal, [numbervars(true),quoted(true)]), nl.
foo(_22584,a,'b c',_22590,_22584)
foo(A,a,'b c',_,A)
Goal = foo(X, a, 'b c', Y, X).
```

**Comment by JanWielemaker** [comment]
print_term/2 does the numbervars/4 for you.   It must as it is all written in Prolog, so it is not unlikely a GC will happen during its execution which would modify the `_NNN`  names.

format/3 relies on write_term/3, which the standard says it just handles the `'$VAR'(N)` terms, not that it produces them.   So, I fear this is more or less what it should be.

**Comment by kamahen** [comment]
That was one of my more impressive "I thought I was writing one thing but actually wrote another thing" mistakes. :)
Anyway, the solution is to use `~@` with `print_term/2` or similar:
```prolog
?- Goal=foo(X,a,'b c',Y,X), format('PRINT: ~@~n', [print_term(Goal,[output(current_output),indent_arguments(false),right_margin(0)])]).
PRINT: foo(A,a,'b c',_,A)
Goal = foo(X, a, 'b c', Y, X).
```

**Comment by JanWielemaker** [comment]
Or use this.   That is quite a bit faster and easier if you do not need to stuff from print_term/2 to be smart with large terms.

    \+ \+ ( numbervars(Term, 1, _, [singletons(true)]), format(...) ).

**Comment by kamahen** [comment]
I tried a few other things ... `write_canonical/1` (format `~k`) doesn't behave the way the documentation says, probably because `numbervars/4` with `singleton` doesn't seem to do anything (the outputs with `B` should have `_` if singletons are detected):
```prolog
?- Goal=foo(A,_,'a b', A), 
   numbervars(Goal, 0, _, [singleton(true)]), 
   format('FORMAT: ~q ~k~n', [Goal,Goal]), 
   write('CANONICAL: '), write_canonical(Goal), nl, 
   write('WRITE_TERM: '), write_term(Goal, [ignore_ops, quoted, quote_non_ascii, brace_terms(false), numbervars]), nl.
FORMAT: foo(A,B,'a b',A) foo('$VAR'(0),'$VAR'(1),'a b','$VAR'(0))
CANONICAL: foo('$VAR'(0),'$VAR'(1),'a b','$VAR'(0))
WRITE_TERM: foo(A,B,'a b',A)
Goal = foo(A, B, 'a b', A),
A = A.
```

BTW, `writeq/1` should have an extra line saying that its output can't be read back in if the term contains something of the form `$VAR(N)`. I'll make a "minor doc fix" PR.

**Comment by kamahen** [comment]
It seems that `numbervars` with `singleton` doesn't behave as documented (and possibly `write_canonical` also doesn't behave as documented, but I suspect `numbervars` is the cause) - in the following the `B`s ought to be `_`:
```prolog
?- Goal=foo(A,_,'a b', A), 
   numbervars(Goal, 0, _, [singleton(true)]), format('FORMAT: ~q ~k~n', [Goal,Goal]), 
   write('CANONICAL: '), write_canonical(Goal), nl, 
   write('WRITE_TERM: '), write_term(Goal, [ignore_ops, quoted, quote_non_ascii, brace_terms(false), numbervars]), nl.
FORMAT: foo(A,B,'a b',A) foo('$VAR'(0),'$VAR'(1),'a b','$VAR'(0))
CANONICAL: foo('$VAR'(0),'$VAR'(1),'a b','$VAR'(0))
WRITE_TERM: foo(A,B,'a b',A)
Goal = foo(A, B, 'a b', A),
A = A.
```

**Comment by JanWielemaker** [comment]
write_canonical/1,2 does analyze the variables:    Note that as a result you cannot do e.g.
`?- write('foo('), write_canonical(X), write(','), write_canonical(Y), write(')').` as this may lead to incorrect variable sharing.    You could not so so reliably anyway (there can be a GC between the two, changing
the `_NNN` numbers).   The big advantage is that output is more readable and reproduces exactly, so you can do text comparison on produced files.

```
1 ?- Goal=foo(A,_,'a b', A), write_canonical(Goal).
foo(A,_,'a b',A)
Goal = foo(A, _, 'a b', A).
```

> BTW, `writeq/1` should have an extra line saying that its output can't be read back in if the term contains something of the form `$VAR(N)`

Why not?   It will write '$VAR'(N) as it is _quoted_.

> ```prolog
> [singleton(true)])
> ```

Must be `singletons` (with an __s__)
