### ISSUE TITLE
sandbox:format_calls/3 gnerates exception on non-list argument

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#1205]
SWIP 9.1.18, MacOS 10.14.6

According to the documentation for format/2:

> _Arguments_ provides the arguments required by the format specification. If only one argument is required and this single argument is not a list, the argument need not be put in a list. Otherwise the arguments are put in a list.

However calls to sandbox:format_calls/3 with a non-list single argument generate an exception:
```
?- sandbox:format_calls("~w",42,Calls).
ERROR: length/2: Type error: `list' expected, found `42' (an integer)
Could not print message for exception:
	error(format_error("~w",[any],42),context(prolog_stack([frame(11,call(system:throw/1),throw(error(format_error("~w",...,42),_168))),frame(9,clause(<clause>(0x6000012cd5f0),3),toplevel_call(user:sandbox:(...)))]),_124))

?- sandbox:format_calls("~w",[42],Calls).
Calls = [].
```

**Comment by ridgeworks** [comment]
This still doesn't work quite right. Given:
```
clpBNR:debug_clpBNR_(FString,Args) :- debug(clpBNR,FString,Args).
```
the result:
```
?- safe_goal(clpBNR:debug_clpBNR_('Add ~p',{C})).
ERROR: format(""): too many arguments (found 1, need 0)
```
The problem seems to arise because sandbox tries to eventually tries to prove:
```
sandbox:safe_meta_call(prolog_debug:debug(clpBNR, _44344, _44346), clpBNR, _74146)
```
Note the loss of the original argument values. But without the arguments:
```
?- safe_goal(debug(clpBNR,_,_)).
ERROR: format(""): too many arguments (found 1, need 0)

?- safe_goal(debug(clpBNR,'Add ~p',{C})).  %%%% but this works fine
true.
```
This is caused by:
```
?- format_types(Format,Types).
Format = "",
Types = [].
```
in `sandbox:format_calls/3`. Since the `Types` list and the `Args` list are now different lengths, `format_callables/3` fails and generates the exception.

This appears to be caused by the recent addition of type checking to `format_calls/3` - previously if `Args` was a var it got unified with the empty list (so same length as `Types` list); now it's wrapped in a list so the new `Args` has length 1.

**Comment by JanWielemaker** [comment]
I see.   That is not good.   Pushed a fix that makes format_types/2 raise an instantiation error.   The sandbox first tries whether the goal is safe regardless of the arguments.   If that raises an instantiation fault it backtracks and passes (increasingly more) of the instantiation until it either passes or runs out of time.

**Comment by ridgeworks** [comment]
Just confirming that this fixes the sandbox related issue for me; thanks.
