### ISSUE TITLE
call_with_time_limit doesn't work with initialization

### ISSUE THREAD

**Issue by deRemo** [SWI-Prolog/swipl-devel#1207]
How to reproduce:

-  call_with_time_limit/2 works within the `swipl` interpreter:
```console
? - catch(call_with_time_limit(1, sleep(3)), time_limit_exceeded, (writeln("catched!"), halt)), writeln("not catched :(("), halt.

catched!
```

- let's wrap the very same query in an initialization predicate, using `sleep.pl` file
```sh
#!/usr/bin/swipl

:- initialization catch(call_with_time_limit(1, sleep(3)), time_limit_exceeded, (writeln("catched!"), halt)), writeln("not catched :(("), halt.
```
- Make the file runnable with `chmod +x sleep.pl`
- Run:
```console
$> ./sleep.pl
not catched :((
```

**Comment by JanWielemaker** [comment]
call_with_time_limit/3 is based on interrupts and initialization/1 is guarded against interrupt such that it cannot be aborted and result in partially initialized modules.

initialization/1 is poorly designed to run applications.  Use initialization/2 using the `main` 2nd argument for that.
