### ISSUE TITLE
dcg_basics:digits//1 unnecessarily commits too early and has incorrect determinism declaration

### ISSUE THREAD

**Issue by GeoffChurch** [SWI-Prolog/swipl-devel#1208]
Here is the [current impl](https://www.swi-prolog.org/pldoc/doc/_SWI_/library/dcg/basics.pl?show=src#digits/3):
```prolog
%!  digits(?Chars)// is det.
%!  digit(?Char)// is det.
%!  integer(?Integer)// is det.
%
%   Number processing. The predicate  digits//1   matches a possibly
%   empty set of digits,  digit//1  processes   a  single  digit and
%   integer processes an  optional  sign   followed  by  a non-empty
%   sequence of digits into an integer.

digits([H|T]) -->
    digit(H),
    !,
    digits(T).
digits([]) -->
    [].

digit(C) -->
    [C],
    { code_type(C, digit)
    }.
```

The cut leads to this sort of behavior:
```prolog
?- use_module(library(dcg/basics)).
true.

?- phrase(digits([A,B,C]), [X,Y,Z]).
A = B, B = C, C = X, X = Y, Y = Z, Z = 48.
```

Also, the determinism would ideally be `nondet` for the most general query (once the impl is changed).

**Comment by JanWielemaker** [comment]
It is meant for _parsing_.    Non-determinism mostly leads to a lot of unneeded backtracking on the thing it is intended to do.

**Comment by GeoffChurch** [comment]
Got it, although shouldn't it be marked `semidet` in that case? Unless we break the DCG abstraction, in which case we can specify the following two `det` modes conditioned on a `list(digit)` type:
```prolog
%!  digits(-Chars:list(digit), +S0:list(digit), -S:list(digit)) is det.
%!  digits(+Chars:list(digit), -S0:list(digit), -S:list(digit)) is det.
```

Also, could the two clauses of `digits` be swapped, since they're indexed anyway? This would improve termination when `Chars` is partial. Maybe there is a good reason to keep them as-is?

**Comment by JanWielemaker** [comment]
You can't swap because you want to match eagerly for eating integers.   digits//2 is det, but digit//1 should probably be marked semidet, though it depends on the mode (+,-,-)  is det, (-,+,-) is semidet.    Possibly digit and digits should be marked `digits(-Digits)//`.  The other mode makes little sense.  The documentation could be better :cry:

**Comment by GeoffChurch** [comment]
Ah maximal munch! That makes sense. Thank you for the response.
