### ISSUE TITLE
Documentation for `rdf_register_prefix/[2,3]` appears twice

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#121]
Documentation for `rdf_register_prefix/[2,3]` appears twice: http://www.swi-prolog.org/pldoc/doc_for?object=rdf_register_prefix/2

**Comment by fnogatz** [comment]
This applies to other predicates too. 

```
digits(?Chars)// is det
Sourcedigit(?Char)// is det
Sourceinteger(?Integer)// is det
```
is displayed three times in [`dcg/basics`](http://www.swi-prolog.org/pldoc/doc/swi/library/dcg/basics.pl).

**Comment by JanWielemaker** [comment]
@wouterbeek Appeared twice in manual ...  @fnogatz this has been reported before.  I do not know the
real cause.  It happens sometimes and sometimes not.  Not-locked indexing or something similar seems likely, but all code I checked is fine ...  Anyway, this unrelated.
