### ISSUE TITLE
pack buildenv.sh incorrectly sets `LD`

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1214]
`LD='usr/bin/cc` in `buildenv.sh` is wrong for two reasons:
* it should be the same as `CC='gcc'`
* `LD` isn't a value that's used by `gmake` (see https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html)

The value of `LD` causes problems with `libtool.m4`, which uses that value and defaults to `ld`.

(There should also be a `CXX='g++'`, I think)

It is possible that other build tools (`cmake`, etc.) use the value of `LD`, so it's not clear to me that removing `LD` is the correct thing to do.
For now, I've put a `unset LD` in the Makefile for pack(hdt).

**Comment by kamahen** [comment]
The problem might be different -- I had diagnosed it by running
```bash
source buildenv.sh  # after removing `LD=/usr/bin/cc` and its export
make
make test
```
which was what I thought `pack_install(.)` does. However, adding `unset LD`s to the Makefile didn't fix things. I'll investigate further.

The symptoms: 
`hdt-cpp` creates some executables that are envoked using a `libtool`-created script that sets the `LD_LIBRARY_PATH`; and when I used a `buildenv.sh` that sets `LD`, there were references in the executables to `../.libs/libhdt.so` and `../../libcds/.libs/libcds.so` instead of just `libhdt.so` and `libcds.so` -- these references might have been put there by the `libtool` scripts, which modify the executable. I'm not familiar with `libtool`, so this will take a bit of work.

**Comment by JanWielemaker** [comment]
> which was what I thought `pack_install(.)` does

It doesn't use the `buildenv.sh` script itself.   It just writes it to simplify running the build process by hand with the same environment.

Note that most of the variables have been renamed to avoid conflicts when there is a term `pack_version(2)` in `pack.pl`.   See `library/build/tools.pl`.

**Comment by kamahen** [comment]
But `LD` (or `SWIPL_LD`) shouldn't be `/usr/bin/cc` -- it should be the same as what `CC` is set to (e.g.., `gcc`).

Anyway, I found a separate problem in `hdt/Makefile` -- it was setting the Makefile `LD` variable. Even so, `LD` is wrong for gmake.

Question: do other build tools, such as cmake, use `LD`? Or should it simply be removed? (I think it should be removed because it confuses `libtool`)

**Comment by JanWielemaker** [comment]
> Or should it simply be removed?

I'm reluctant to change this.   It will probably break packs.   I don't know how it gets to `cc`, as the implementation says

```
def_environment(VAR, Value, Options) :-
    env_name(ld, VAR, Options),
    (   getenv('LD', Value)
    ->  true
    ;   current_prolog_flag(c_cc, Value)
    ).
```

Could it be that LD is in your environment all along?    If neither CC or LD are defined they are both set to `current_prolog_flag(c_cc, Value)`.    And yes, there is basically no support for similar variables for C++.    That should probably be added.

The `c_cc` flag comes from CMake, which by default uses `cc` (which on many systems is `gcc`).  If I look at the `clang` build on Linux, it correctly says `/bin/clang-15`.

**Comment by kamahen** [comment]
However, `def_environment/3` for `cc` does a call to `default_c_compiler/1` before trying `current_prolog_flag(c_cc,Value)`. Perhaps this is wrong?

Anyway, my question was about `LD`, not `CC` -- `libtool` seems to expect `ld` or its equivalent rather than `cc` or its equivalent. (And we should probably add `CXX` as well)

BTW, switching to `pack_version(2)` fixed things for `hdt-cpp`. Thank-you for pointing that out.

**Comment by JanWielemaker** [comment]
> Perhaps this is wrong?

Seems so.   Pushed 25e03b6d7678fcf6599b6dcb9e7de9788aa7f652 to improve on that.    Problem with libtool interaction probably remains.   Shouldn't be a big issue.   Few packs build external libraries as part of their process, libtool isn't that popular and with version 2 of the pack files we can avoid such conflicts.
