### ISSUE TITLE
warning on SWI-Prolog.h

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swipl-devel#1216]
When compiling a pack using a foreign library I get this warning
'''
Warning: In file included from ./swi_lbfgs.c:2:
Warning: /usr/local/lib/swipl/include/SWI-Prolog.h:215:35: warning: this function declaration is not a prototype [-Wstrict-prototypes]
'''

**Comment by JanWielemaker** [comment]
This seems to be an issue that has no clean solution in C.   Strict C does not allow to cast `void*` to/from function pointers.  If prototypes are not enforced, the current way of defining works.    The only alternatives are to use a union or define a single complete type and force the user to cast to this type.    Of course, if you know something better, I'm all ears.

**Comment by friguzzi** [comment]
I have no better solution, I removed `-Wstrict-prototypes` from the options in the pack
