### ISSUE TITLE
multiple pyhton interpreters

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swipl-devel#1217]
In the installation process, there is no way to indicate which python interpreter to use, in case there is more than one installed in the system, for example in Mac there can be a OS one, a brew one and conda one

**Comment by JanWielemaker** [comment]
Yes, that is pretty confusing.    Our CMake configuration uses `find_package(Python, ...)` and only explicitly listens to `-DCPYTHON_VERSION=<version>`.   There is a whole lot of settings defined by [FindPython.cmake](https://cmake.org/cmake/help/latest/module/FindPython.html)   Probably I should add a link to that?

**Comment by friguzzi** [comment]
Thanks, I think a link to FindPyhton.cmake would help

**Comment by friguzzi** [comment]
I think it could also be useful a janus predicate for indicating dynamically which python interpreter to use, if that's possible

**Comment by JanWielemaker** [comment]
> if that's possible

I'm afraid not.   It could work for multiple Python installations that have the same version (including minor version), but even there it would be system dependent.

**Comment by friguzzi** [comment]
Running cmake as follows
```
cmake -DDCPYTHON_VERSION=3.11 -G Ninja ..
```
I get
```
CMake Warning:
  Manually-specified variables were not used by the project:

    DCPYTHON_VERSION
```
Picking up the correct version of Pyhton is  a nightmare ....

**Comment by friguzzi** [comment]
Thanks, it now works. Maybe it is worth adding the CPYTHON_VERION option to CMAKE.md for quick reference
