### ISSUE TITLE
Dict access with `.` is lifted out of `findall`

### ISSUE THREAD

**Issue by BarrensZeppelin** [SWI-Prolog/swipl-devel#1219]
Consider the following (nonsensical) Prolog snippet:

```prolog
bar :-
    findall((member(X, L), Dict.X == V), Elements).

baz :-
    findall((member(X, L), get_dict(X, Dict, Y), Y == V), Elements).
```

To my understanding these predicates should behave in the same way.
However, when we inspect the code for the predicates with `listing/1`, we get:

```
?- listing(bar/0).
bar :-
    '.'(Dict, X, A),
    findall((member(X, L), A==V), Elements).

true.

?- listing(baz/0).
baz :-
    findall((member(X, L), get_dict(X, Dict, Y), Y==V),
            Elements).

true.
```

Notice that for `bar` the dict access is lifted out of the `findall` goal.
This dramatically changes the semantics of the program, as `X` becomes bound before the call to `member(X, L)`!

Is this intentional?

```
$ swipl --version
SWI-Prolog version 9.1.21 for x86_64-linux
```

**Comment by jan-swi-prolog-01** [comment]
Because you use findall/2, which does not exist and thus the argument is not a goal.   If we use

```
bar :-
    findall(X, (member(X, L), Dict.X == V), Elements).
```

it works fine.   I typically argue against this though as it only works if all meta predicate declarations are correct.   It is really easy to get wrong as we cannot figure out reliably what is code and what is data.   So, 

    G = (member(X, L), Dict.X == V), findall(X, G, Elements)

goes wrong.

**Comment by BarrensZeppelin** [comment]
Right, my bad. While simplifying the example I made some errors.
I originally encountered the problem with `aggregate_all/3`:

```prolog
bar :-
    aggregate_all(count, (member(X, L), Dict.X == V), Count).
```

```
?- listing(bar/0).
bar :-
    '.'(Dict, X, A),
    aggregate_all(count,
                  ( member(X, L),
                    A==V
                  ),
                  Count).

true.
```

Sorry, but I don't understand what you argue against. What would you propose to do instead?

**Comment by jan-swi-prolog-01** [comment]
Should work for aggregate_all/3 as well, but you must make sure the library is loaded explicitly to get the meta-predicate declaration.

> What would you propose to do instead?

Write a predicate that does the trickery things with functions and pass that to your aggregation predicate.

**Comment by BarrensZeppelin** [comment]
Right. So far I've blissfully ignored meta-predicates.
I guess the autoload of `aggregate_all/3` will load the meta-predicate, but it happens too late?

**Comment by jan-swi-prolog-01** [comment]
> but it happens too late?

Yes.   That is one of the issues with auto loading that still needs to be resolved :cry:
