### ISSUE TITLE
qsave_program with stand_alone=true ignores -g or goal(…) option

### ISSUE THREAD

**Issue by soli** [SWI-Prolog/swipl-devel#1228]
Running 9.2.0 from homebrew on an intel Mac I get the following behavior:

I run the example from https://www.swi-prolog.org/pldoc/man?section=cmdlinecomp :
```prolog
% swipl
<banner>

?- [load].
?- qsave_program(myprog,
                 [ goal(main),
                   stand_alone(true)
                 ]).
?- halt.
```

With `load.pl` as follows:
```prolog
main :- writeln('Hello').
```

Running the generated stand-alone saved-state `myprog` shows the banner but no "Hello".

NB: same program runs fine (printing "Hello") when using 9.1.10 from Nix packages (Darwin) on the same machine

**Comment by JanWielemaker** [comment]
Thanks.   Note that without stand-alone, all works as expected.

**Comment by soli** [comment]
Yes, I had noted, sorry for not pointing that out, and thanks for the quick fix!
