### ISSUE TITLE
swipl-win.exe Help>Check installation gives out two problems 

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#1237]
I am running 64bit 9.3.0
```
% Loading library(socket) ...................... FAILEDExported procedure socket:tcp_connect/2 is not defined
Warning: [Thread pce] 
Warning: [Thread pce] See http://www.swi-prolog.org/build/issues/socket.html
```

I dont have Python installed, Check installation gives a stack trace for janus. I was expecting 'FAILED'
```
% Loading library(janus) ....................... FAILEDc:/program files/swipl/library/janus.pl:98: Initialization goal raised exception:
Warning: [Thread pce] Could not find executable file "'python3.dll'" in %PATH%
Warning: [Thread pce] In:
Warning: [Thread pce]   [53] throw(error(existence_error(source_sink,...),_8032))
Warning: [Thread pce]   [48] janus:add_python_dll_dir at c:/program files/swipl/library/janus.pl:95
```
And this continues for about 20 lines these warnings

**Comment by JanWielemaker** [comment]
Doesn't reproduce.   Did you confirm to remove the old installation?     Otherwise, try Discourse.   Possibly other people can confirm or not.

**Comment by xpxaxsxi** [comment]
About the problem 1 of 2: 
the socket warning: I had been tweaking things in the installation directory under "c:/program files/swipl" and uninstalling old version did not succeed. Cleaned up manually the system and no more warnings from socket-library. 

While cleaning up the registry I found that 64-bit Windows version is again being  installed unproperly as a 32-bit application, it was fixed in https://github.com/SWI-Prolog/swipl-devel/commit/05402119726828b579a2994ddda6859033e66096

About the problem 2 of 2:
Sorry I should have reported the 2nd problem about janus as a separate issue. 
I still get the other one in checking janus: I think the "Help>Check Installation" throws a uncaught exception and is giving stack trace associated to the  warning that says "Could not find executable file "'python3.dll'" in %PATH%"

**Comment by JanWielemaker** [comment]
> While cleaning up the registry I found that 64-bit Windows version is again being installed unproperly to registry as a 32-bit application, it was fixed in [0540211](https://github.com/SWI-Prolog/swipl-devel/commit/05402119726828b579a2994ddda6859033e66096)

It also needed the NSIS template patch in cmake ...    Applied, so next release should be ok again

> "Could not find executable file "'python3.dll'" in %PATH%"

You need to install Python separately and such that this dll is in `%PATH%`.     Did you do so?

**Comment by xpxaxsxi** [comment]
I mean that when Python is not installed the Help>Check installation>janus should give a informative warning, I think it now outputs 20 lines of stack trace and Check does not continue. I will someday try out the janus.

**Comment by xpxaxsxi** [comment]
>>While cleaning up the registry I found that 64-bit Windows version is again being installed unproperly to >>registry as a 32-bit application, it was fixed in [0540211](https://github.com/SWI-Prolog/swipl-devel/commit/>>05402119726828b579a2994ddda6859033e66096)

>It also needed the NSIS template patch in cmake ... Applied, so next release should be ok again

Daily builds are failing, the last daily build is Sun Feb 11 04:34:28 2024. 

No hurry, I am just informing.

**Comment by xpxaxsxi** [comment]
I built the 64-bit windows version myself with docker-swipl-build-mingw (commit dc9c7) just half a hour ago.It built ok and  and executable installs properly.

**Comment by JanWielemaker** [comment]
Good.   Is the nightly still wrong?    These are properly build again.    They were pushed to the old server that is now offline.    That has been fixed.    They use this version of the docker image as far as I can tell.

**Comment by xpxaxsxi** [comment]
Nightlies install without problems now.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/exported-procedure-socket-tcp-connect-2-is-not-defined/7546/3
