### ISSUE TITLE
Misc Documentation Issues

### ISSUE THREAD

**Issue by itegebo** [SWI-Prolog/swipl-devel#124]
http://www.swi-prolog.org/
Tutorials drop-down,

Beginners -> "Modules" (external site is down)
Intermediate -> "PlDoc" 404

Then in the reference manual,

http://www.swi-prolog.org/pldoc/man?section=flags#flag:editor

following the link to "section 4.5" goes to documentation on "listing" rather than for "details on selecting the editor used."

**Comment by wouterbeek** [comment]
The buggy link in the manual is also fixed now.  Closing...
