### ISSUE TITLE
Add support for `process` module in WASM build

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/swipl-devel#1260]
In order to support the [`log:shell`](https://github.com/eyereasoner/eye/commit/d8679628056788e3d2934e3deeebc6bffc4c63c0) eye built-in in the [eye-js](https://github.com/eyereasoner/eye-js?tab=readme-ov-file) WASM build; the `process` module needs to be made available in the WASM environment.

I have had a go at seeing if adding `process` to https://github.com/SWI-Prolog/swipl-devel/blob/456ad55a3acc77326317c41af339e1e705c62298/cmake/PackageSelection.cmake#L119 would be all that is needed; but doing so resulted in flakey `ctest` errors which can be observed in https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/8600021543/job/23564129152?pr=572 - but seemed to succeed after a re-run.

Any support in understanding and resolving these errors would be greatly appreciated @JanWielemaker @josd

**EDIT** 
   - I Managed to make pre-release for swipl-wasm which should have process (https://github.com/SWI-Prolog/npm-swipl-wasm/compare/v3.7.5...v3.8.0-alpha.1)
   - I Subsequently opened up https://github.com/eyereasoner/eye-js/pull/1007 to test this; but that PR is still producing an empty output for -quiet --nope ./calc.n3 and no prompt is logged to the console either (https://github.com/eyereasoner/eye-js/actions/runs/8602152070/job/23571076169?pr=1007)

I'm at a loss as to where I should proceed from here.

~I also tested to see what would happen if one removed that `ctest` line from the docker build and attempted to use the  build artefact anyway (https://github.com/SWI-Prolog/npm-swipl-wasm/pull/573), however, it appears that the `process` module is not made available as I am not getting any output on commands making use of `log:shell` [image](https://github.com/SWI-Prolog/swipl-devel/assets/63333554/205f777f-297b-46d1-a763-aa8d3b26f203)~

**Comment by jeswr** [comment]
**Update** The problem is that my attempted addition of the `process` library did not work. With `swipl-wasm@v3.8.0-alpha.1` I still get the error

```
source_sink `library(process)' does not exist
{
  error: true,
  message: "source_sink `library(process)' does not exist"
}
```

When running

```ts
import SWIPL from "swipl-wasm";

async function main() {
  const swipl = await SWIPL({ arguments: ["-q"] });
  console.log(swipl.prolog.query("use_module(library(process)).").once());
}

main();
```

**Comment by JanWielemaker** [comment]
library(process) is part of the `clib` package, so the `CMakeLists.txt` there needs to be extended to include the process plugin.    That said, do we really want that?   It only makes sense in the node environment (I guess) and why do you need processes to do logging?    Prolog should be able to deal with that itself, no?
