### ISSUE TITLE
Handling I/O in `WASM` build / using the `read_lines_to_codes` predicate

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/swipl-devel#1261]
Related to #1260 

In eye the `log:ask` and `log:shell` features are being built in order to support the behavior of requesting additional user input when running the prolog program (elaborated on below). 

The `log:ask` predicate is an alternative to `log:shell` that does not make use of the `process` module. `log:ask` is implemented [in this commit](https://github.com/eyereasoner/eye/commit/c6b77b1e791f115cf043b8e5d0df51b95f1e45f1) using the `read_lines_to_codes` predicate. When trying to execute the example given below using `swipl-wasm` (I've tried with both the bundled and node builds), I get the following error:

```
calc 1+1
** ERROR ** eam ** error(io_error(read,user_input),context(read_util:read_line_to_codes/2,I/O error))
```

The advice given [here](https://github.com/emscripten-core/emscripten/issues/14887) by Emscripten is that you need to build with `-s NODERAWFS` in order to support `stdin` calls in C; but this is already enabled for the node build of `swipl-wasm`.

So I'm now at a loss for how to get the `read_line_to_codes` predicate working. Any advice/thoughts on how to achieve this would be greatly appreciated.

---

EYE v10.2.3 has an experimental log:ask built-in that basically writes the subject string and reads into the object string e.g.
```
$ cat calc_ask.n3
@prefix log: <http://www.w3.org/2000/10/swap/log#>.
@prefix : <#>.

{
    "calc 1+1" log:ask ?Y.
} log:query {
    :result :is ?Y.
}.
```
```
$ eye --quiet --nope calc_ask.n3
calc 1+1
|: 2
@prefix : <file:///home/jdroo/temp/calc_ask.n3#>.

:result :is "2".
```
you have to type `2` and `ENTER` at the `|:` prompt

**Comment by JanWielemaker** [comment]
I don't know.   It might be better to discuss these things on Discourse as there are more people watching there.    For the browser, the trick is to yield, just as is done for Prolog's toplevel read.  See boot/toplevel.pl.    For node, I don't know.  read/1 works fine in `node src/swipl` in the build environment, but how to use that with the bundle?

**Comment by jeswr** [comment]
Thanks for the pointers - this is now working in https://github.com/eyereasoner/eye/commit/56c0ef6582286b99ecb5e50f7ac2593251e56e84
