### ISSUE TITLE
WASM: Return value of `.call` is inconsistent and missing bindings.

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/swipl-devel#1264]
In particular:

```js
// Returns { done: true, value: 23 }
swipl.prolog.call("X = atom", { async: true });
// Returns true
swipl.prolog.call("X = atom");
```

In both cases I would expect:
1. An object to be returned
2. The bindings to be present for the `value`, not the number 23

**Comment by JanWielemaker** [comment]
Prolog.call() is documented to return a boolean.  To get bindings, you need the Query() interface.   The options argument is not documented.   It is a bit long ago, but I think `call` as is should be renamed to an internal method and a new `call` should call this without options.    Call using `async` returns the identifier for a Prolog term vector at the C level.    Nothing a user wants to know about.

Prolog.call() is mainly there to do things for which you'd normally use a directive, e.g., set a flag, write a message, etc.

If you want the async I/O in eye, use Prolog.foreach() if I recall correctly.

**Comment by jeswr** [comment]
I'm a little confused about how to get `forEach` working when using the `await` predicate.

When I'm trying to run 

```js
const res = swipl.prolog
        .forEach("await('inputV', Input)", (mod, prolog) => {
          console.log('hello', mod, prolog);
        })
console.log('res', await res);
```

It just has the following promise rejection without the callback being called.

```bash
Error: the object {
  "done": false
  "resume": [Function]
  "value": [null]
  "yield": "inputV"
} was thrown, throw an Error :)
```
