### ISSUE TITLE
SWIPL not compiling on Fedora 40

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#1269]
So I have just upgraded to Fedora 40 and tried to compile SWI Prolog 9.3.5 from github sources, but I encountered a failure:

~~~
Function: zipOpenNewFileInZip4_64
Line: 1230
error: assignment to ‘const z_crc_t *’
       {aka ‘const long unsigned int *’}
       from incompatible pointer type ‘const uint32_t *’
       {aka ‘const unsigned int *’} 
       [-Wincompatible-pointer-types]

 1230 |         zi->ci.pcrc_32_tab = get_crc_table();
      |                            ^
~~~

After some analysis, we find:

**Left-Hand-Side**

The file `src/minizip/zip.c` contains this code:

```
#    ifndef NOCRYPT
    zi->ci.crypt_header_size = 0;
    if ((err==Z_OK) && (password != NULL))
    {
        unsigned char bufHead[RAND_HEAD_LEN];
        unsigned int sizeHead;
        zi->ci.encrypt = 1;
        zi->ci.pcrc_32_tab = get_crc_table();         // <---------- line 1230 gives compilation problems
        /*init_keys(password,zi->ci.keys,zi->ci.pcrc_32_tab);*/

        sizeHead=crypthead(password,bufHead,RAND_HEAD_LEN,zi->ci.keys,zi->ci.pcrc_32_tab,crcForCrypting);
        zi->ci.crypt_header_size = sizeHead;

        if (ZWRITE64(zi->z_filefunc,zi->filestream,bufHead,sizeHead) != sizeHead)
                err = ZIP_ERRNO;
    }
#    endif
```

The same file, a bit further up, defines type `z_crc_t` as `unisgned long` (the `Z_U4` makes me think it wants at least 4 byte for that):

```
#ifndef NOCRYPT
#ifndef z_crc_t
#ifdef Z_U4
typedef Z_U4 z_crc_t;
#else
typedef unsigned long z_crc_t; // <----------- line 48
#endif
#endif
#endif
```

And variable `ci` on line 1230 is a `curfile64_info` (also defined in `zip.c`) and it contains 

```
const z_crc_t* pcrc_32_tab
```

So indeed on the Left-Hand-Side of line 1230 we have a pointer to `unsigned long`.

**Right-Hand-Side**

`get_crc_table()`  is declared in `zlib.h` (in `/usr/include`) as

~~~
Z_EXTERN const uint32_t * Z_EXPORT get_crc_table    (void);
~~~

The above includes `stdint.h`,  which includes `bits/stdint-uintn.h` which contains:

~~~
typedef __uint32_t uint32_t;
~~~

and `__uint32_t` is declared in `/usr/include/bits/types.h` as 

~~~
typedef unsigned int __uint32_t;
~~~

So that's where the `unsigned int` on the Right-Hand-Side of line 1230 comes from.

**What changed?**

`/usr/include/zlib.h` belongs to package `zlib-ng-compat-devel-2.1.6-2.fc40.x86_64`

This seems to be compatibility layer to a replacement library for (previously, on Fedora 39) `zlib-1.2.13-4.fc39`, now replaced by https://github.com/zlib-ng/zlib-ng: _zlib replacement with optimizations for "next generation" systems._

**Quickfix**

A solution that leads to successful compilation and testing is to change `src/minizip/zip.c` of SWIPL at line 48 to:

```
typedef uint32_t z_crc_t;
```

but is that right?

**Comment by JanWielemaker** [comment]
Thanks for the extensive analysis.   It seems that the official zlib sources define get_crc_table() to return `z_crc_t*`.   At least, that is true for 1.3.1, which is the latest official source.    zlib.h and zconf.h do not define `z_crc_t` though, which makes the whole thing a bit dodgy as the binary does contain some interpretation of this type.    Possibly fedora choose to use a properly defined type for this reason.  There is some info at https://bugzilla.redhat.com/show_bug.cgi?id=1424609.

Pushing a patch that will detect whether zlib.h defines z_crc_t and if so omit the definition in zip.c/unzip.c.    That is the safest route I can think of.
