### ISSUE TITLE
Broken URL reference to FAQ/ToplevelMode.txt

### ISSUE THREAD

**Issue by brebs-gh** [SWI-Prolog/swipl-devel#1278]
In swi-prolog on Linux:
Welcome to SWI-Prolog (threaded, 64 bits, version 9.2.4)

If a user mistakenly copy-pastes the prompt:

```prolog
?- ?-member(X, [1,2]).
ERROR: Unknown procedure: (?-)/1
ERROR:   ?- is the Prolog prompt
ERROR:   See FAQ at https://www.swi-prolog.org/FAQ/ToplevelMode.txt
```

But https://www.swi-prolog.org/FAQ/ToplevelMode.txt just shows:

```
Not Found

The requested URL /FAQ/ToplevelMode.txt was not found on this server
[SWI-Prolog](http://www.swi-prolog.org/) httpd at bc2254db600d
```

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.    Unfortunately it is the link that must be changed after some modernization of the website
