### ISSUE TITLE
Unicode in thread window missing

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#130]
Release: SWI-Prolog 7.3.18 for Windows XP/Vista/7/8 64-bit edition
Expected Behaviour: Since unicode is shown in main window, 
unicode should be also shown in thread window, opened with 
the menu item "run | new thread".
Current Behaviour: Unicode is not shown in thread window.
Priority: Low

![main_window](https://cloud.githubusercontent.com/assets/5411487/13556955/5207276e-e3e6-11e5-81e7-6469e0abc265.gif)
![thread_window](https://cloud.githubusercontent.com/assets/5411487/13556956/568b6930-e3e6-11e5-9f0b-ff3587482d53.gif)

**Comment by JanWielemaker** [comment]
Tested using `?- format('\u0404~n', [])`, this seems to work fine.  I do 
see however that the thread window uses the default initial font.
We could consider this a feature as well :-)  Try setting the font
for the thread console to the same as the main one.

	Cheers --- Jan

**Comment by jburse** [comment]
I wrote "Priority: Low", also I am afraid, that I would prefer an 
out of the box solution, I am not very good with changing settings. 

Also I don't understand why it doesn't work on my 2K screen,
its the same fonts, isn't it? I see a settings hell coming to me...

**Comment by JanWielemaker** [comment]
On 03/07/2016 12:57 PM, j4n bur53 wrote:
> I wrote "Priority: Low", also I am afraid, that I would prefer an
> out of the box solution, I am not very good with changing settings.

There is a menu Settings/Font... I don't know much about Windows font
logic. Point is that not all fonts define all Unicode characters and
thus you need to select one that supports the things you need. Missing
characters are shown as a (small) black blob. That is what you see.

> Also I don't understand why it doesn't work on my 2K screen,
> its the same fonts, isn't it? I see a settings hell coming to me...

As opposed to what?  The initial font can depend on the Windows
version and preferences.

If you know a better way to select a default font, please have a look
at src/win32/console.

	Cheers --- Jan

**Comment by jburse** [comment]
Using the fonts menu item works. 
For example "Consolas" gives the desired result.
Have to use the fonts menu item separately on the main window and on the thread window.
So have to use the fonts menu item two times.
And somehow the setting survives leaving the interpreter and starting it again.

**Comment by wouterbeek** [comment]
Hi @jburse,

Why can the font not be stored in `.swiplrc`?

  1. Selecting a font in the options menu would be stored as a setting in `.swiplrc`.
  2. Whenever a (thread) window starts it takes its front setting from `.swiplrc`.

**Comment by jburse** [comment]
Actually the issue is already close, see my last post.
Do I have to do something more? 
I don't know how this ticket system works.

I guess:
"fonts menu item" (in my last post) = "font in the options menu" (in your post) ?
