### ISSUE TITLE
error messages upon opening the prolog editor

### ISSUE THREAD

**Issue by MatthiasFreiburghaus** [SWI-Prolog/swipl-devel#1302]
Operating System: Windows 10
Swi-Prolog Version: 9.2.6-1x64

Behaviour: When opening the built in editor, either with a new or existing file, the following error messages appear:

ERROR: c:/program files/swipl/xpce/prolog/lib/emacs/language_mode.pl:40:
ERROR:    Exported procedure socket:tcp_connect/2 is not defined
ERROR: c:/program files/swipl/xpce/prolog/lib/emacs/language_mode.pl:40:
ERROR:    Exported procedure socket:tcp_host_to_address/2 is not defined

**Comment by JanWielemaker** [comment]
You probably upgraded by installing the new version over the old one?   Normally this is fine, but a recent upgrade moved a lot of files around.   First delete the old installation and reinstall
