### ISSUE TITLE
Unicode in main window high resolution displays missing

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#131]
Release: SWI-Prolog 7.3.18 for Windows XP/Vista/7/8 64-bit edition
Expected Behaviour: Since unicode is shown in main window on low
resolution displays, unicode should be also shown in main window on
high resolution displays.
Current Behaviour: Unicode is not shown in main window on
high resolution displays.
Priority: Low

![main_window](https://cloud.githubusercontent.com/assets/5411487/13556985/18696eb2-e3e7-11e5-9787-7b3b017a4ec8.gif)
![main_window_2k](https://cloud.githubusercontent.com/assets/5411487/13556986/1ce42da6-e3e7-11e5-8caa-86bc518fbea6.gif)

**Comment by jburse** [comment]
On Windows:

Using the fonts menu item works.
For example "Consolas" gives the desired result.

**Comment by jburse** [comment]
Hi wouterbeek, should I reopen the issue for some reason?

**Comment by wouterbeek** [comment]
Only if the issue persist for you or for some other user.
