### ISSUE TITLE
where to add unit tests for prolog functions?

### ISSUE THREAD

**Issue by younes-io** [SWI-Prolog/swipl-devel#1316]
I'd like to initiate a PR to add unit tests for certain functions located in the `library/` directory. However, I'm unsure about the appropriate location for these tests. Could someone help with this?

**Comment by JanWielemaker** [comment]
Tests for the libraries are in src/Tests/library/test_*.pl.    For non-trivial predicates, additions are always welcome!

**Comment by younes-io** [comment]
Thank you @JanWielemaker for sharing this!
