### ISSUE TITLE
library(error): unclear definition of between(L, U)

### ISSUE THREAD

**Issue by edechter** [SWI-Prolog/swipl-devel#132]
Documentation specifies that `between(L, U)` is the type of `number` between L and U. But:

``` 
 ?- bash-3.2$ swipl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.16-7-g69f2501)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- is_of_type(between(1, 3), 2).
true.

?- is_of_type(between(1, 3), 2.2).
false.

?- is_of_type(number, 2.2).
true.
```

**Comment by eazar001** [comment]
I think the definition is more according to:
```
is_of_type(positive_integer, 2.2)
false.
```

**Comment by eazar001** [comment]
or actually, just ... just plain `integer` is more accurate.

**Comment by edechter** [comment]
Yes, and I think that's as it should be, given between/3. But if that's the intention the documentation should be updated to reflect that.

**Comment by wouterbeek** [comment]
Hi @edechter,

I believe this was recently updated.  Can you check [whether this now looks fine to you?](http://eu.swi-prolog.org/pldoc/doc_for?object=error%3Amust_be/2)

`between(IntL,IntU)`: `Integer [IntL..IntU]`
`between(FloatL,FloatU)`: Number [FloatL..FloatU]`

**Comment by edechter** [comment]
Yes, it looks fine to me now.
