### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by dsletten** [SWI-Prolog/swipl-devel#1323]
Section 4.27.2.2 [Rational number examples](https://www.swi-prolog.org/pldoc/man?section=rational) states that prefer_rationals is true by default. However, [section 2.12](https://www.swi-prolog.org/pldoc/man?section=flags#flag:prefer_rationals) reports that the default is false.

**Comment by JanWielemaker** [comment]
Thanks for spotting.   Removed the claim.  As the long term aim is still to change the default, no claim is more robust :smile:
