### ISSUE TITLE
Behaviour of subseq/3

### ISSUE THREAD

**Issue by jp-diegidio** [SWI-Prolog/swipl-devel#1328]
About `subseq/3`: https://www.swi-prolog.org/pldoc/doc_for?object=subseq/3

The docs, modulo invocation modes, say: `subseq(List, SubList, Complement)`,

but that generates `SubList` from elements of `List` in order right-to-left.

Unless it is a bug, maybe it should be: `subseq(List, Complement, SubList)`?

Consider these examples for comparison:

```prolog
?- forall((length(A, 2), subseq([1,2,3,4], A, B)), format('~w-~w~n', [A,B])).
[3,4]-[1,2]
[2,4]-[1,3]
[2,3]-[1,4]
[1,4]-[2,3]
[1,3]-[2,4]
[1,2]-[3,4]
true.

?- forall((length(A, 2), subseq([1,2,3,4], B, A)), format('~w-~w~n', [A,B])).
[1,2]-[3,4]
[1,3]-[2,4]
[1,4]-[2,3]
[2,3]-[1,4]
[2,4]-[1,3]
[3,4]-[1,2]
true.

?- forall(subseq(L, [1,2], [3,4]), format('~w~n', [L])).
[3,4,1,2]
[3,1,4,2]
[3,1,2,4]
[1,3,4,2]
[1,3,2,4]
[1,2,3,4]
true.

?- forall(subseq(L, [3,4], [1,2]), format('~w~n', [L])).
[1,2,3,4]
[1,3,2,4]
[1,3,4,2]
[3,1,2,4]
[3,1,4,2]
[3,4,1,2]
true.
```

**Comment by JanWielemaker** [comment]
> Unless it is a bug, maybe it should be: `subseq(List, Complement, SubList)`?

I don't know.    It does not make any claim on the order.    The argument naming as well as the order in which things are generated seems compatible with SICStus.    It came to the lists library via the SICStus emulation libraries.   Given both sublist and complement unbound, it creates sublist (2nd arg) with increasing length, which seems reasonable.   Considering compatibility I see little reason to change anything.

**Comment by jp-diegidio** [comment]
I see, makes sense, but maybe the docs page could be strengthened: renaming the parameters and/or with an example or a note as to the actual behaviour: it does not generate solutions in the natural order, indeed a naive use requires a `reverse` afterwards in most cases.

**Comment by jp-diegidio** [comment]
In fact, looking e.g. at `sub_atom/5`, where `SubAtom` is the last argument, I think the problem here does boil down to simply the parameter names (order) in `subseq/3`: `SubList` should be the last one.

**Comment by JanWielemaker** [comment]
There are several ways you can use this, some producing "natural" order and some not.   I.e., sublists are generated with growing length, but sublists of a particular length are generated right-to-left.   Both arguments have more or less the same status.   I have my doubt about being more explicit in the docs.    The SICStus docs are also not explicit.    Formally, I guess this implies you cannot rely on the order.

**Comment by jp-diegidio** [comment]
> Formally, I guess this implies you cannot rely on the order.

Which, IMO, is a "category error" as well as unworkable: I cannot sort lists after every call to a predicate because SWI-Prolog, a specific Prolog implementation, does not define behaviour exactly, I'll rather have to document my code with a SWI-Prolog version.

Anyway, my 2c and thanks for the answer.

**Comment by kamahen** [comment]
In general, I don't rely on the order of results; similarly, when I use SQL, I add an "ORDERED BY" to ensure things are in the order I want. (I usually prefer setof/3 to bagof/3)

**Comment by jp-diegidio** [comment]
This is not SQL: think implementing a search algorithm, do you re-sort a list-based stack or queue after every append?

I'll reiterate for the last time, just to be clear: (IMO) this is just a minor (to fix) though important issue with the name of the parameters in the docs declaration.

**Comment by jp-diegidio** [comment]
And thank you so much for promptly closing this, excellent work as usual.

**Comment by jp-diegidio** [comment]
Meanwhile Mr. GNU Prolog is working for Microsoft and that is simply abandoned.  Which is the only reason I am back to SWI and the swine.  What a fucking corporate driven nazi-retarded shithole...  You do deserve your own extinction.  <Plonk>

**Comment by jp-diegidio** [comment]
Are you all working for Microsoft (or Monsanto, I forget which is which)?

**Comment by JanWielemaker** [comment]
You can easily find that I'm working for SWI-Prolog Solutions b.v.   And no, I'm not going to share anything about its customers here.
