### ISSUE TITLE
Discussions feature

### ISSUE THREAD

**Issue by younes-io** [SWI-Prolog/swipl-devel#1332]
Hello,

I occasionally have questions about SWI-Prolog and would find it helpful if the Discussions feature was enabled for this repository. Would it be possible to enable this GitHub feature?

Thank you for considering this request.

**Comment by JanWielemaker** [comment]
Discussions happen at the Discourse forum at https://swi-prolog.discourse.group/  The Github features should be limited to clear bugs.  More places do discuss makes things harder to follow and Discourse functions well.

**Comment by younes-io** [comment]
Ah, I wasn't aware of the discourse.
Thanks
