### ISSUE TITLE
0.000 CPU in display by time/1 built-in

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [SWI-Prolog/swipl-devel#1334]
I could produce just now with SWI-Prolog 9.3.14,
tested on Windows 11 Pro, 22631.4460:
```
?-  time(test).
% 7,001,002 inferences, 1.234 CPU in 1.243 seconds (99% CPU, 5671698 Lips)
true.

?- time(test).
% 7,001,001 inferences, 0.000 CPU in 1.257 seconds (0% CPU, Infinite Lips)
true.

?- time(test).
% 7,001,001 inferences, 1.203 CPU in 1.246 seconds (97% CPU, 5819014 Lips)
true.

?- time(test).
% 7,001,001 inferences, 0.000 CPU in 1.249 seconds (0% CPU, Infinite Lips)
true.
```
The test case was:
```
:- dynamic(foo/2).

test :-
   retractall(foo(_,_)),
   warehouse(1000000, 1, 18884).

warehouse(0, _, _) :- !.
warehouse(N, X, Y) :-
   assertz(foo(Y, bar)),
   (retract(foo(X, bar)) -> true; true),
   zx81(X, Z), zx81(Y, T),
   M is N-1,
   warehouse(M, Z, T).

zx81(X, Y) :- Y is (X*75+74) mod 65537.
```

**Comment by JanWielemaker** [comment]
Works fine for me.   What OS?   Possibly in a VM?   Looks more like an OS issue than a SWI-Prolog issue.   SWI-Prolog just queries the relevant OS call.

**Comment by Jean-Luc-Picard-2021** [comment]
Edition	Windows 11 Pro
Build	22631.4460

**Comment by Jean-Luc-Picard-2021** [comment]
Maybe this can be ignored. Could be an artefact
that some GC thread is doing a lot of work, so that
the main thread time measurement falls below

the time granulatrity of the time measurement used.
Could be a bug of the Ryzen CPU. Similar problems are
found elsewhere that thread CPU is not available:

**Title: JVMPI GetCurrentThreadCpuTime() always returns zero time when using NSJ 1.3**
https://support.hpe.com/hpesc/public/docDisplay?docId=ns102.0.28374788.4363595en_us&docLocale=en_US

**Comment by JanWielemaker** [comment]
There is no portable way to get thread CPU time.   What is implemented works most of the time on quite a wide range of systems using various OS specific techniques .    This should most probably be considered an OS issue if it does not work as advertised.
