### ISSUE TITLE
lazy_list_location/2 fails when called with newly opened file

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#135]
1. Generate a test file with 
ping -D google.com > pinglog

2. consult the code below and query analyze_pings(pinglog). 

3. EXPECTED: this program has a bug, it fails to account for the file starting with 
PING google.com (216.58.193.110) 56(84) bytes of data.
and thus falls into the last clause of pings//0 . I expected it to report the location in the file
so I could print an error message.  (It also doesn't eat the newline, another bug). 
OBSERVED: lazy_list_location throws 
debug]  ?- analyze_pings('pinglog').
ERROR: stream_position/3: Domain error: `stream_position' expected, found `-'

this is because PrevPos is '-' at this point, and it's expecting a stream position.

:- use_module(library(dcg/basics)).

:- dynamic sample_gc/2.

analyze_pings(FileName) :-
	phrase_from_file(pings, FileName).

pings --> blanks.
pings --> ping,
	blanks,
	pings.
pings -->
	lazy_list_location(file(Name, Line, LinePos, _CharNo)),
	string_without(`\n`, Line),
	{
	    format('**** ~w~nerror in ~w on line ~w at column ~w~n',
		  [Line, Name, Line, LinePos ])
        }.

ping -->
	"[",
	float(Time),
	"] ",
	integer(Bytes),
	" from ",
	uri(URI),
	" (",
	ip_address(IP),
	"): icmp_seq=",
	integer(ICMP_SEQ),
	" ttl=",
	integer(TTL),
	" time=",
	float(PING_TIME),
	" ms",
	blanks_to_nl,
	{
	    format('~w,~w,\"~w\",~w,~w,~w,~w',
		   [Time, Bytes, URI, IP, ICMP_SEQ, TTL, PING_TIME])
	}.

uri(URI) -->
	string_without(` `, URI).

ip_address(`127.0.0.1`) -->
	"localhost".
ip_address(IP) -->
	integer(Seg0),
	".",
	integer(Seg1),
	".",
	integer(Seg2),
	".",
	integer(Seg3),
	{
	    format(codes(IP), '~w.~w.~w.~w', [Seg0,Seg1,Seg2,Seg3])
	}.

... --> []|[_], ... .

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 17480a20c6bff8b803df2bd71423003c370509f6
