### ISSUE TITLE
swi-prolog.org download page seems to be broken

### ISSUE THREAD

**Issue by honnix** [SWI-Prolog/swipl-devel#137]
http://www.swi-prolog.org/download/devel is not displayed properly and http://eu.swi-prolog.org/wiki_edit?location=/download/ChangeLog doesn't work.

**Comment by JanWielemaker** [comment]
The display is a duplicate on what Anne reported on failed diaplay of images.

**Comment by honnix** [comment]
Sorry I should actually have reported it here https://github.com/SWI-Prolog/plweb in this case. Right?

**Comment by JanWielemaker** [comment]
Probably.  It is a PlDoc issue.  Just testing the patch.  Closing this one.
