### ISSUE TITLE
toplevel_print_options should also affect residual constraints

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#139]
Currently, `toplevel_print_options` seems to have no impact on residual constraints:

<pre>
?- use_module(library(clpb)).
true.

?- set_prolog_flag(clpb_residuals, graphviz).
true.

?- sat(card([2],[X,Y,Z])).
sat(X*Y#X*Y*Z#X*Z#Y*Z),
dot(digraph([node(4, [label=X]), node(2, [label=Y]), node(0, [label=Z]), node(3, [label=Y]), node(1, [... = ...]), edge([...]),  (... -> ...)|...])).

?- <b>set_prolog_flag(toplevel_print_options, [quoted(true), portray(true)]).</b>
true.

?- sat(card([2],[X,Y,Z])).
sat(X*Y#X*Y*Z#X*Z#Y*Z),
<b>dot(digraph([node(4, [label=X]), node(2, [label=Y]), node(0, [label=Z]), node(3, [label=Y]), node(1, [... = ...]), edge([...]),  (... -> ...)|...])).</b>
</pre>

Note that the depth of the shown terms is still limited.

**Comment by JanWielemaker** [comment]
The simple reason is that `toplevel_print_options` has been replaced by the flag `answer_write_options` quite a few versions back ...  That still won't affect SWISH though, but it
should affect the normal toplevel.  See result//2 in boot/messages.pl
