### ISSUE TITLE
read_stream_to_codes/2 fails in a qsaved program

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#141]
`read_stream_to_codes/2` fails in a qsaved program created by `qsave_program/1`.  Reconsulting the module `readutil`, with `[library(readutil)]` _NOT_ with `use_module(readutil)`, after restoring the qsaved program does works.

Reproduce:
1. Install a SWI-Prolog Pack with `pack_install(<SOME-PACK>)`.
2. Run the following shell script to create a qsaved state:
   
   ```
   #! /bin/sh
   SWIPL=/usr/local/bin/swipl
   
   PACLIB=${HOME}/lib/swipl/pack/pac/prolog
   SCRIPT=${PACLIB}/pac.pl
   TARGET=${HOME}/saved-state
   
   ${SWIPL} -s ${SCRIPT} \
            -g "qsave_program('${TARGET}'),halt" \
            -t 'halt(1)'
   ```
3. Execute the saved state with `$ ~/saved-state` and call:
   
   ```
   ?- open("/path/to/textfile", read, F), read_stream_to_codes(F, X).
   false.
   ?- [library(readutil)].
   ?- open("/path/to/textfile", read, F), read_stream_to_codes(F, X).
   F = <stream>(0x7f8959f486c0),
   X = [35, 35, 35, 32, 46, 98, 97, 115, 104|…].
   ```

_This bug was reported by Kuniaki Mukai on the SWI-Prolog mailing list._

**Comment by JanWielemaker** [comment]
This is because the code contains this as a first directive.

```{prolog}
:- initialization(prolog, restore).
```

As this initialization never returns, none of the other initialization directives are executed, including those that load foreign code.
