### ISSUE TITLE
Possible error in pl-atom.c:947-949

### ISSUE THREAD

**Issue by borisvassilev** [SWI-Prolog/swipl-devel#143]
If you take a look [here](https://github.com/SWI-Prolog/swipl-devel/blob/e2e5da45ba28a965cee1f0c4b088646038afdf0a/src/pl-atom.c#L947-L949) you will notice that there is a semicolon right after the `if` condition, followed by a `{  ... }` block that will always get evaluated. Without understanding the code, it seems like a benign error.

This was reported by gcc 6.1.1 during normal compilation.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.  Is indeed benign, but can cause some additional memory usage.
