### ISSUE TITLE
Module names in lambda expressions 

### ISSUE THREAD

**Issue by edechter** [SWI-Prolog/swipl-devel#145]
When using library(yall), expressions qualified with module names result in syntax errors unless wrapped in parentheses:

``` prolog
?- Xs = [1, 2], maplist([X]>>lists:member(X, Xs), [1,2]).
ERROR: Undefined procedure: apply: (:)/3
```

However: 

```
?- Xs = [1, 2], maplist([X]>>(lists:member(X, Xs)), [1,2]).
Xs = [1, 2] 
```

Can the :/2 operator precedence be changed to fix this?

**Comment by JanWielemaker** [comment]
Both are standard (>>) or de-facto standard operators.  Messing with them seems a bad idea.

**Comment by wouterbeek** [comment]
I've ran into this problem myself.  I've added the requirement to use parentheses in this case to the documentation.
