### ISSUE TITLE
Interval Glitch in CLP(FD)

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#146]
I have already posted some weeks ago in the SWI-Prolog Google 
Group, that I think the interval calculation has a glitch. I see this glitch 
again in this example:

The following query gives a greatest lower bound for Y as 20:

```
 ?- 3*X+2*Y #> 100, X in 10..20.
 X in 10..20,
101#=<3*X+2*Y,
 Y in 20..sup.
```

But this bound is too large by one unit. Even the CLP(FD) system itself
knows this somehow. SInce when I do the following, I get the correct
greatest lower bound as 21 for Y:

```
 ?- 3*X+2*Y #> 100, X in 10..20, Y in 0..100.
 X in 10..20,
101#=<3*X+2*Y,
 Y in 21..100.
```

Unfortunately I did not yet have time to look at the SWI-Prolog CLP(FD)
source and pin point the error. So I leave it here as a bug. 

Sorry for being so picky, but since I work side by side with other CLP(FD) 
systems (SICStus, Jekejeke, etc..), this comes up again and again.

**Comment by triska** [comment]
A **mistake** in the solver means that it is either too general or too specific in that it either shows an answer that violates the posted constraints or fails to show an answer that satisfies them. None if those is the case here.

Improved propagation strength is one of the features I am working on in [**CLP(Z)**](https://github.com/triska/clpz).

If you supply a patch for this in SWI-Prolog, I will review it! `remove_dist_upper/2` and related predicates seem good candidates to look into in this&nbsp;case.

**Comment by jburse** [comment]
I think its a bug if intervals for any constraint C are defined as greatest lower bound and least upper bound. If we would say that they are just lower bounds and upper bounds then there wouldn't be a problem. The crucial words are greatest and least.

SICStus Prolog can do it correctly:
![sicstus_ok](https://cloud.githubusercontent.com/assets/5411487/15447504/a0324f56-1f44-11e6-9086-aed92e15995a.gif)

**Comment by triska** [comment]
The CLP(FD) documentation makes no guarantees regarding consistency of arithmetic predicates. SICStus may do it differently in this concrete case, but also does not *and cannot* guarantee any kind of consistency in general. Example:

    ?- A #= X mod 2, A #\= X mod 2.

You fill find it hard to find an integer `A` that satisfies these constraints. Yet the query doesn't fail in SICStus but succeeds with:

    X in inf..sup,
    A in 0..1.

Note that determining consistency of arithmetic predicates is **undecidable** in general, and you will therefore necessarily always have such cases.

**Comment by jburse** [comment]
I am not talking about "consistency" in general. Just the usual "interval consistency" of an elementary constraint. The example you give are two elementary constraints together. But the definition of "interval consistency" reads:

 "**A constraint c** is interval consistent if for every variable in the constraint c each of its two domain bounds participates in a solution to c."

It doesn't say a goal G should be interval consistent. It talks about a single constraint in the repertoir of the constraint solver. I guess it also doesn't mean that we want interval consistency for global constraints, only for elementary (local) constraints.

**Comment by jburse** [comment]
Comparing to ECLiPSe Prolog can be helpful, since ECLiPSe Prolog also
allows infinite domains (cool!):

Result by ECLiPSe Prolog for lowerbound of Y is 21:
```
[eclipse 2]: 3*X+2*Y #> 100, X::10..20.
X = X{10 .. 20}
Y = Y{21 .. 1.0Inf}
Delayed goals:
        2 * Y{21 .. 1.0Inf} + 3 * X{10 .. 20} #> 100
Yes (0.00s cpu)
```

Result by SWI-Prolog for lowerbound of Y is 21:
```
?- 3*X+2*Y #> 100, X in 10..20.
X in 10..20,
101#=<3*X+2*Y,
Y in 20..sup.
```
