### ISSUE TITLE
Should debug/1 use a set out outputs?

### ISSUE THREAD

**Issue by edechter** [SWI-Prolog/swipl-devel#147]
Currently, in library(debug)

```prolog
:- debug(a).
:- debug(a).
```

and 

```prolog
:- debug(a > tmp).
:- debug(a > tmp).
```

do not behave in similar ways. The former prints each debug message to user_error once, but the latter prints each one to file tmp twice. Among other things, this means that reconsulting modules using the former as directives results in multiple messages sent to output streams. 

Should the list of outputs [here](https://github.com/SWI-Prolog/swipl-devel/blob/master/library/debug.pl#L147-L155) be a set?

**Comment by JanWielemaker** [comment]
Pushed a `fix' (not true it should be called a bug).
