### ISSUE TITLE
Superflous Choice Point either in Indexing or when/2

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#148]
Since SWI-Prolog has automatic multi-argument indexing I 
am not expecting a choice point here:

```
flip(V, W) :- var(V), var(W), !, when((nonvar(V);nonvar(W)), flip(V, W)).
flip(red, black).
flip(black, red).
flip(node(X,Y), node(Z,T)) :- flip(X,Z), flip(Y,T).
```

when I run the following query:

```
?- flip(X,Y), Y=node(black,red).
X = node(red, black),
Y = node(black, red) ;
false.
```

But it does insert a choice point somewhere, which is seen in the
top-level when the interpreter waits for a semicolon.

Bye

P.S.: Here is a run with Jekejeke Prolog 1.1.3 using library(term/suspend):

```
?- flip(X,Y), Y=node(black,red).
X = node(red,black),
Y = node(black,red)
```

**Comment by JanWielemaker** [comment]
The recursive call has mode (-,+).  SWI-Prolog only creates secondary indexes if there are enough
clauses.

**Comment by jburse** [comment]
What are the exact criteria? What do you mean by secondary indexes? 
How is the first call judged with two variables, that are anyway freezed?

**Comment by JanWielemaker** [comment]
They are unspecified and will remain so.   The only guarantee is that first argument indexing on atoms, small integers and functors is deterministic.  That is the classical Prolog promise.  Other ndexes are created when the system considers the time/space tradeof interesting.  They are mostly hashes and thus do not guarantee there is not a choice point anyway due to a hash collision.

**Comment by jburse** [comment]
Thats strange, I was expecting a goal p(V1,..,Vn) where V1..Vn are 
doesn't generate an index in the first place.

But maybe its a hash problem, but hash collision shouldn't affect
the index itself. It only usually affects the hash table, and indicates
that the hash table needs additional equals() to find its entry.

Or do you use the hash as the key itself? You could also use
the atomic as the key. Usually hash table look works as follows:

    int hash = key.hashCode();
    int idx = hash & (table.length -1);
    Now walk through the list behind table[idx] with equals()

Hash collision makes the list at table[idx] larger, but doesn't make the index
less specific. You should nevertheless find your list entry. Which might then
point to a clause set.

Bye

**Comment by JanWielemaker** [comment]
It might actually do that.  I'd have to check the source.   I'll leave that as an exercise though :)
But, back to the original, when the flip(X,node(black,red)) wakes up, it calls flip(X, black) and
that is not indexed as there is no index for the second argument.

Whether or not that is a good idea, I don't know.   Building indexes costs time and space.  So
does running not indexed code.  Ideally you'd make the tradeof.   That would make an interesting project: figure out during stack shifts or GC that certain predicates keep many choicepoints around and next time be greedier trying to get rid of them.   That should be possible.  I once considered whether it was possible to sort out during shift/GC which choicepoints were in fact meaningless and destroy them.  As you don't know the arguments when the predicate was entered that will be hard though.

**Comment by jburse** [comment]
When it wakes up, it will call flip(X, node(black,red)). Since I am freezing/whening at the
beginning of the predicate.

If it would have not created an index for the initial call flip(X,Y), where all arguments are
variable, there wouldn't be any index around. (unconfirmed whether this happens)

And if there wouldn't be any index around, it could create a primary index with
mode (-,+). And then avoid choice points.

But if criteria for secondary index are too restrictive, you cannot use the same predicate
with different modes. Speaking for flip/2 you cannot do both with the advantage of indexes in the same application:

```
?- flip(X,Y), Y=node(black,red).
X = node(red,black),
Y = node(black,red)

?- flip(X,Y), X = node(red,black).
X = node(red,black),
Y = node(black,red)
```

**Comment by jburse** [comment]
Concerning your Shift/GC idea I cannot relate, since in Java i.e. 
Jekejeke Prolog I don't have access to the GC. 

But I guess you could also locally collect the call frequency without refering 
to Shift/GC and chose index criteria based on this additional parameter. 

This gives some adaptive algorithm similar to the JVM that uses
such critera since HotSpot to native compile methods.

**Comment by JanWielemaker** [comment]
> When it wakes up, it will call flip(X, node(black,red)). Since I am freezing/whening at the
> beginning of the predicate.

Yip.  That matches the last clause, calling flip(X, Z), where X is unbound and Z is black.  QED.

**Comment by jburse** [comment]
Yes we know that it will not generate a choice point there. But then next it will call flip(_G, black) (not flip(X, black)). But it wont go into the second clause with the fact. 

It will go in the first clause and check the var/1 guards. Except if you have var/1 indexing, like YAP (or Jekejeke recently), then it might skip this clause already during indexing.

After the first clause it will go into the second clause, and if it has not started the search with an (-, X) index, it will not know that there are no other choice points.

Do you have an index dump command?

**Comment by jburse** [comment]
Here is the tactic of Jekejeke:
- When calling flip(X,Y) alone, no index is generated. Usually p(V1,..,Vn) doesn't generate an index when V1,..,Vn are variables.
- When Y=node(black,red) is done the call is redone, an index is generated, an index on arg=1 is generated.
- The index has key=<key>, guard and nonguard entries. The guard entries are for those clauses where arg=1 has a var/1 constraint.
- As a result the clause set for key=black is only of length=1. But that doesn't matter here, even if it were of length=2, since the fact is the last clause, the result would be deterministic. The guard entries separation only gives speed here not less choice points.

![flip_dump](https://cloud.githubusercontent.com/assets/5411487/16057637/478b0858-327b-11e6-99d9-f162eb2b21b3.gif)

**Comment by jburse** [comment]
Ok I found a description of your strategy here:
http://www.swi-prolog.org/pldoc/man?section=jitindex

BTW: The distinction into key=value, guard and nonguard has a further advantage. As you correctly write normally clauses with a variable argument need to be put in all bouquets:

"Clauses that have a variable at an otherwise indexable argument must be linked into all hash buckets. Currently, predicates that have more than 10% such clauses for a specific argument are not considered for indexing on that argument."

But this is not the case for a clause with a var/1 guard. You don't need to put such a clause in all bouquets, since the var/1 condition is anyway not fullfiled if you choose any of those bouquets, since you choose any of those bouquets when you have an argument=value and you find a bouquet with key=value. The value is always nonvar/1 and never var/1.

**Comment by JanWielemaker** [comment]
Dealing with variables specially when  it appears as first and/or last clause does make sense.  Well, if there is a concrete project that needs this I'm afraid.  That is how SWI development works most of the time.  

P.s.  `predicate_property/2` tells you which indexes have been created.

**Comment by jburse** [comment]
Ok, I have to check predicate_property/2. BTW: The var/1 indexing has a lot of application. Here is a typical ISO predicate and its internal implementation:

```
atom_concat(Str1, Str2, Str) :-
   var(Str1),
   var(Str2), !,
   /* some code */
atom_concat(Str1, Str2, Str) :-
   var(Str2), !,
   /* some code */
atom_concat(Str1, Str2, Str) :-
   var(Str1), !,
   /* some code */
atom_concat(Str1, Str2, Str) :-
    /* some code */
```

The dispatch is practically already done in the index. The var/1 indexing helps when a predicate with different mode is implemented. Here is the index for the atom_concat/3 example after calling atom_concat/3 with all possible modes.

```
-------- atom_concat/3 ---------
length=4
arg=0, map=0
  nonguard, length=2
    arg=1, map=0
      nonguard, length=1  /* directly to here, when both arguments are bound */
      guard, length=1
    arg=2, map=0
      nonguard, length=2
  guard, length=2
arg=1, map=0
  nonguard, length=2
    arg=2, map=0
      nonguard, length=2
  guard, length=2
arg=2, map=0
  nonguard, length=4
```

In the above index there is a direct route to the clause when the first two arguments are bound. This is seen during trace, the unify port only hits one time:

```
?- visible(all), leash(all).
Yes 
?- trace.
Yes 
?- atom_concat(abc, def, X).
    0 Call atom_concat(abc, def, X) ? 
    1 Unify atom_concat(abc, def, X) ? 
[...]
Yes ;
    0 Redo atom_concat(abc, def, abcdef) ? 
[...]
No
```
