### ISSUE TITLE
./src/configure: No such file or directory

### ISSUE THREAD

**Issue by olsky** [SWI-Prolog/swipl-devel#151]
Am I missing something?

- Downloaded 7.3.23 (tried from GIT releases and from Swi-prolog.org)
- unzip/tar
- renamed template, edited
- run and get this:

swipl-7.3.23-linux > ./configure --enable-shared --enable-static --with-world COFLAGS="-O2 -g3"
./configure: line 77: ./src/configure: No such file or directory

the configure file is missing in the src folder, but it was in some versions there :-/

PS: checked in 7.3.19 is was there

**Comment by JanWielemaker** [comment]
The tarball you download from github only contain the git part of the sources.  All generated stuff is not in there.  You need to run ./prepare to pull that in.  You either need the tarball from www.swi-prolog.org,
which does contain the generated files or (better), `git clone' the sources from git and run ./prepare.  You must run that after any update you get through `git pull`.
