### ISSUE TITLE
Documentation fails to build with "tex('SWI-Prolog-7.3.24.tex') does not exist"

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#153]
With the pull request I have filed (to include `ltx2htm` in the packages), I am able to get quite with building the documentation, but still get an error at the end.

Please note that `SWI-Prolog-7.3.24.tex` **does** exist in `swipl-devel/man`!

I am using Debian 8.1.

The output of `make html` is:

<pre>
swipl-devel/man$ make html
../src/swipl.sh select.pl PDF main.doc > SWI-Prolog-7.3.24.doc
./doc2tex SWI-Prolog-7.3.24.doc > SWI-Prolog-7.3.24.tex
./doc2tex intro.doc > intro.tex
./doc2tex overview.doc > overview.tex
./doc2tex builtin.doc > builtin.tex
./doc2tex module.doc > module.tex
./doc2tex foreign.doc > foreign.tex
./doc2tex runtime.doc > runtime.tex
./doc2tex hack.doc > hack.tex
./doc2tex summary.doc > summary.tex
./doc2tex xpce.doc > xpce.tex
./doc2tex glossary.doc > glossary.tex
./doc2tex ide.doc > ide.tex
./doc2tex license.doc > license.tex
./doc2tex threads.doc > threads.tex
./doc2tex engines.doc > engines.tex
./doc2tex lib/library.doc > lib/library.tex
./doc2tex lib/readutil.doc > lib/readutil.tex
./doc2tex lib/wwwbrowser.doc > lib/wwwbrowser.tex
./doc2tex lib/registry.doc > lib/registry.tex
swipl -q -f libtotex.pl -g libtotex -- 'library(check)'
swipl -q -f libtotex.pl -g libtotex -- 'library(url)'
swipl -q -f libtotex.pl -g libtotex -- 'library(debug)'
swipl -q -f libtotex.pl -g libtotex -- 'library(lists)'
./doc2tex lib/clpqr.doc > lib/clpqr.tex
./doc2tex lib/gensym.doc > lib/gensym.tex
./doc2tex lib/nbset.doc > lib/nbset.tex
./doc2tex lib/libsummary.doc > lib/libsummary.tex
swipl -q -f libtotex.pl -g libtotex -- --section 'library(prolog_pack)'
./doc2tex lib/assoc.doc > lib/assoc.tex
./doc2tex lib/prologxref.doc > lib/prologxref.tex
./doc2tex lib/ugraphs.doc > lib/ugraphs.tex
swipl -q -f libtotex.pl -g libtotex -- 'library(ordsets)'
./doc2tex lib/broadcast.doc > lib/broadcast.tex
./doc2tex lib/record.doc > lib/record.tex
swipl -q -f libtotex.pl -g libtotex -- 'library(clpfd)'
swipl -q -f libtotex.pl -g libtotex -- 'library(pairs)'
swipl -q -f libtotex.pl -g libtotex -- 'library(option)'
swipl -q -f libtotex.pl -g libtotex -- 'library(apply)'
swipl -q -f libtotex.pl -g libtotex -- 'library(aggregate)'
swipl -q -f libtotex.pl -g libtotex -- 'library(thread_pool)'
./doc2tex lib/pio.doc > lib/pio.tex
swipl -q -f libtotex.pl -g libtotex -- --subsection 'library(pure_input)'
swipl -q -f libtotex.pl -g libtotex -- 'library(charsio)'
swipl -q -f libtotex.pl -g libtotex -- --subsection 'library(shlib)'
swipl -q -f libtotex.pl -g libtotex -- 'library(csv)'
swipl -q -f libtotex.pl -g libtotex -- 'library(optparse)'
swipl -q -f libtotex.pl -g libtotex -- 'library(clpb)'
./doc2tex lib/predicateoptions.doc > lib/predicateoptions.tex
swipl -q -f libtotex.pl -g libtotex -- --lib=predicate_options lib/predopts.txt
swipl -q -f libtotex.pl -g libtotex -- 'library(random)'
swipl -q -f libtotex.pl -g libtotex -- 'library(varnumbers)'
swipl -q -f libtotex.pl -g libtotex -- 'library(quasi_quotations)'
swipl -q -f libtotex.pl -g libtotex -- 'library(solution_sequences)'
swipl -q -f libtotex.pl -g libtotex -- 'library(iostream)'
swipl -q -f libtotex.pl -g libtotex -- 'library(persistency)'
swipl -q -f libtotex.pl -g libtotex -- 'library(yall)'
swipl -q -f libtotex.pl -g libtotex -- 'library(error)'
./doc2tex lib/tabling.doc > lib/tabling.tex
swipl -q -f libtotex.pl -g libtotex -- --lib=tabling lib/tablinglib.md
Warning: Unknown message: pldoc(no_predicates_from(current_table/1))
swipl -q -f libtotex.pl -g libtotex -- 'library(simplex)'
./doc2tex profile.doc > profile.tex
./doc2tex attvar.doc > attvar.tex
./doc2tex chr.doc > chr.tex
./doc2tex xref.doc > xref.tex
./doc2tex bit64.doc > bit64.tex
./doc2tex dialect.doc > dialect.tex
./doc2tex extensions.doc > extensions.tex
rm -f Manual/*.html Manual/*.gif
env TEXINPUTS=lib:$TEXINPUTS latex2html SWI-Prolog-7.3.24
Welcome to LaTeX2HTML version 0.98

Loaded LaTeX commands from "/usr/local/lib/latex2html/latex.cmd"
<b>ERROR: Prolog initialisation failed:
ERROR: source_sink `tex('SWI-Prolog-7.3.24.tex')' does not exist
Makefile:88: recipe for target 'html' failed
make: *** [html] Error 1</b>
</pre>

**Comment by triska** [comment]
Addendum 1: `make pdf` produces a PDF as expected.

**Comment by JanWielemaker** [comment]
Might be because `TEXINPUTS` is undefined before running this?  Seems my `.bashrc` defines it as `/home/jan/tex/macros::`.  The `::' makes it look in the current directory (I think).  Try using `TEXINPUTS=lib::`.  If that helps we should fix the `Makefile.in`

**Comment by triska** [comment]
Yes, the following worked:

    export TEXINPUTS=lib::

Thank you!

**Comment by JanWielemaker** [comment]
Updated.  Thanks.
