### ISSUE TITLE
libtotex pulls in unrelated predicates when processing markdown

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#154]
Please consider [**clpfdlib.md**](https://github.com/SWI-Prolog/swipl-devel/blob/master/man/lib/clpfdlib.md): It contains an entry for `[[element/3]]`.

In the resulting HTML file (`clpfd.html`), there appear **two** entries for `element/3`: One is from an unrelated library about&nbsp;HTML.

Is there a way to restrict the predicate description to the `element/3` constraint from `library(clpfd)`?

**Comment by JanWielemaker** [comment]
The related pltotex.pl in packages/semweb passes a module option to the PlDoc translator.   I have added the option --module=Module option to libtotex.pl.  I don't know whether that works.  That surely is the right direction though.

**Comment by triska** [comment]
Thank you, that fixed it!
