### ISSUE TITLE
Possibility of system deadlock when using queues and threads

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#156]
There is a new predicate balance/3 which is similar to concurrent/3. It also
spawns a number of threads and then solves a problem via queues.

I was playing around with 4 threads on a dual core machine. The I tried 8
threads on a quad core machine, and got a hang. Went back to the dual core
machine and do get also a hang with 8 threads.

Logically this should not happend with preemptive threads. Here is the
full test code. The predicate suite/0 is the sequential test and the predicate
psuite/0 is the parallel test:
https://gist.github.com/jburse/66da6e1109869878ce41331278ec2552

Here is an example run, where I get this hang:
![swi_deadlock](https://cloud.githubusercontent.com/assets/5411487/16902235/60b8cd4a-4c59-11e6-8383-f077f79561b6.gif)

On the quad core there was a quite impressive speedup for 2, 3 and 4 
threads. But using 5 or more threads shows the above behaviour.

**Comment by jburse** [comment]
I was experimenting with a new variant of the balance/3 predicate. In the new version I have made a new version of the predicate sys_take_all/3 which is supposed to take elements from a queue.

I now get not only a hang but also a termination dialog:
![abort_predicate](https://cloud.githubusercontent.com/assets/5411487/17458374/b9996856-5c0e-11e6-8092-48664c94c449.gif)

The change in the predicate sys_take_all/3 was replacing an Erlang style queue receiver by a repeat/0 based queue receiver. The predicate is now as simple as:

sys_take_all(T, Q, N) :-
   between(1, N, _),
   sys_take_all2(T, Q).

sys_take_all2(T, Q) :-
   repeat,
   pipe_take(Q, A),
   (A = the(S) -> S = T;
    A = ball(E) -> sys_raise(E);
    !, fail).

I have updated the test suite on gist. You find it again on gist. The test suite has been enlarged by more test cases. There are now the test cases many, many2, many4, first, first2 and first4. 

A test case XXX2 or XXX4 indicates using 2 or 4 threads. The firstX test cases use a once/1 around the balance/3, so I am now testing tear down of the threads more thoroughly.

This gist link is again:
https://gist.github.com/jburse/66da6e1109869878ce41331278ec2552

**Comment by jburse** [comment]
For easier access I have moved the test suite for the module "distributed" from Gist to GitHub. The new link is as follows. See the Issues and Contributing section how to use the repository.
https://github.com/jburse/jekejeke-samples/tree/master/jekrun/benchdist

**Comment by JanWielemaker** [comment]
There is no psuite/0 in the github version.   Is this just `suite/0`?  If I run that many times it should hang at some point?

**Comment by jburse** [comment]
Either suite/0 or suite2/0 might hang very sporadically. 
Last tests I did was on Windows 10, it happens very rarely now.

**Comment by JanWielemaker** [comment]
It is now already running `?- forall(repeat, suite).` for over an hour on an Intel i7-3770 machine running Ubuntu.  No leaking, no hanging.   Does that justify the suspicion that the bug does not exist on Linux?

**Comment by jburse** [comment]
On Windows 10, if a crash happens, I have no other option than 
abort the application. If it hang sometimes ^C and a works. But I 
usually then also abort the application and restart it. I didn't test 
on Linux and MacOS so far.
It could be an OS bug. But then they did a work around for it
in Java, since it doesn't happen in the JVM to me so far. Next
time it happens I could send it the dump.

**Comment by jburse** [comment]
Yes I see that the stats show some GC from time to time for the 
SWI-Prolog system. But I am not sure whether the problems needs
a lot of GC. I guess there is no need for an atom GC, right? If big
nums happen they don't need atom GC right?

What I have doubt about is the destruction of the queue. So far
 I didn't do something. There is two times a pipe_new/2 which 
redirects to message_queue_create/2. But the compatibility code 
has no message_queue_destroy/1 yet.

**Comment by JanWielemaker** [comment]
Bignums are allocated on the stacks and thus may cause normal heap GC, but not atom-GC.
Queues however are presented by symbols (in recent versions) and are subject to atom-GC.  This does not apply for queues that have an _alias_; _only_ for _anonymous_ queues.   So, if you create anonymous queues you can simple leave them around and GC will take care of them.

**Comment by JanWielemaker** [comment]
> It could be an OS bug. But then they did a work around for it
> in Java, since it doesn't happen in the JVM to me so far. Next
> time it happens I could send you the dump.

I'm not claiming it is an OS bug.  The implementations for queues is quite different between Windows and POSIX systems.   This also leads to quite different timing:

  - Linux

```
user:dummy	in 1	(0 gc) ms
user:many	in 3116	(0 gc) ms
user:many2	in 1758	(0 gc) ms
user:many4	in 1122	(0 gc) ms
user:many8	in 981	(0 gc) ms
user:first	in 2980	(0 gc) ms
user:first2	in 5445	(0 gc) ms
user:first4	in 4300	(0 gc) ms
user:first8	in 4028	(0 gc) ms
Total	in 23730	(0 gc) ms
```

  - Windows (using Wine on the same hardware)

```
user:dummy      in 0    (0 gc) ms
user:many       in 2983 (0 gc) ms
user:many2      in 2927 (0 gc) ms
user:many4      in 1779 (0 gc) ms
user:many8      in 1770 (0 gc) ms
user:first      in 2904 (0 gc) ms
user:first2     in 2403 (0 gc) ms
user:first4     in 1398 (0 gc) ms
user:first8     in 1474 (0 gc) ms
Total   in 17638        (0 gc) ms
```

That said, it runs fine under Wine for quite a while already ...

**Comment by jburse** [comment]
If you look at manyX, then Windows is better. 
If you look at firstX then Linux is better.

The test case firstX is tricky, it can have more random
timings. Whereas the the test case manyX does something
along your concurrent/3, the test case firstX does something
along your first_solution/3.

Why do I have only one meta-predicate balance/3? Well 
in the test case firstX I use a once/1 around the balance/3 
predicate. This leads to many issues of fast thread tear down
and fairness of the queues.

That Linux is so bad for firstX is not good news!

Bye

**Comment by jburse** [comment]
If you look at manyX, then Windows is better.
If you look at firstX then Linux is better.

The test case firstX is tricky, it can have more random
timings. Whereas the the test case manyX does something
along your concurrent/3, the test case firstX does something
along your first_solution/3. See also:

High level thread primitives
http://www.swi-prolog.org/pldoc/doc/swi/library/thread.pl

Why do I have only one meta-predicate balance/3? Well
in the test case firstX I use a once/1 around the balance/3
predicate. This leads to many issues of fast thread tear down
and fairness of the queues.

That Linux is so bad for firstX is not good news! Could
be an issue with theard down or an issue with fairness,
or both. Mostlikely theard tear down problem. Something
with thread_signal/2 or thread_join/1.

**Comment by jburse** [comment]
In Jekejeke Prolog both thread_send_message/2 and 
thread_get_message/2 respond to thread_signal/2. Maybe
your Windows implementation also responds but your
Linux implementation doesn't.

But then I still wonder why it terminates nevertheless. I am
not sure it works if only one of the two message predicates
is interruptible and the other is not. Since the work threads
use both predicates and tear down should always be possible.

Maybe we nevertheless need a message_queue_destroy/1
since the threads would then get existence error, right? 
Also the waiting threads. I have an idea how message queue
destroy could be incorporated:

In the module "swiclean.p" introduce a predicate:
- sys_clean_queue/2: Safe queue creation, installs
      a message_queue_destroy/1 hook.
Then use this predicate in the module "swidistributed.p".

As soon as I have time I will do this change and upload it.
I will also do some timing measures. Lets whether it will
break something, and if not whether it will improve the
timings for firstX.

**Comment by JanWielemaker** [comment]
> In Jekejeke Prolog both thread_send_message/2 and
> thread_get_message/2 respond to thread_signal/2. Maybe
> your Windows implementation also responds but your
> Linux implementation doesn't.

That might explain the timing.  The Linux version responds slowly on thread_signal/2,  polling every 250ms, while the Windows version does the proper thing here.  Destroying a queue while threads are waiting on it is supported.  The problem is of course that this works immediately if the thread is waiting on the queue, but not if it is doing something else.

The Wine version eventually hanged itself, although it took about an hour.  I now need to figure out how to attach a debugger and get a stack trace.

**Comment by jburse** [comment]
I have pushed a new version of the compatibility library to 
jekejeke-samples. I am not anymore using Jeff Roses trick
with nondet. Instead I am directly using setup_call_cleanup/3.

With setup_call_cleanup/3 I am able to attain the desired
order of memory_queue_destroy/1 and thread_signal/2. First
regression testing showed that suite/0 and suite2/0 work fine 
on Windows machine.

Wondering what the result on a Linux machine will 
be. I think a 250ms polling cannot explain the difference 
in 4-5 secs between Windows and Linux for firstX.

**Comment by JanWielemaker** [comment]
On 08/22/2016 11:38 PM, j4n bur53 wrote:
> I have pushed a new version of the compatibility library to
> jekejeke-samples. I am not anymore using Jeff Roses trick
> with nondet. Instead I am directly using setup_call_cleanup/3.
>
> With setup_call_cleanup/3 I am able to attain the desired
> order of memory_queue_destroy/1 and thread_signal/2. First
> regression testing showed that suite/0 and suite2/0 work fine
> on Windows machine.

What does that mean in terms of ordering? Are we dealing with a race if
thread_signal is sent to a thread waiting in Q while Q is being
destroyed? What is different in the timing?  If we have a hypothesis
we can create a test case testing this particular feature, which makes
the bug quicker to reproduce and easier to fix.

> Wondering what the result on a Linux machine will
> be. I think a 250ms polling cannot explain the difference
> in 4-5 secs between Windows and Linux for firstX.

The performance of the new version is not significantly different from
the previous version. In itself it is rather remarkable that the Windows
version wins with a big margin; it is almost always slower as soon as
threads, processes or I/O is involved. Poor support for thread_signal
while waiting for a queue is one of the few exceptions.  If fairness
of queues is involved it is claimed that POSIX condition variables are
`fair' and the used emulation on Windows is not.  Of course, possibly
an unfair policy works out better in this case.

	Cheers --- Jan

**Comment by jburse** [comment]
I have to rollback the new version I recently pushed. The ordering is 
still not right thread_join is done before message_queue_destroy.

But thread_join might block indefinitely when we do not destroy
the message queues first. Since threads might be waiting for queues.

But abandoning jeff roses trick and doing something with setup_call_cleanup
doesn't help here. setup_call_cleanup stacks the cleanup handlers.

Take for example:

p(G)  :- 
     setup_call_cleanup(writeln(p_in), q(G), writeln(p_out)).
q(G)  :- 
     setup_call_cleanup(writeln(q_in), G, writeln(q_out)).

If I call p(true) I get:

p_in
q_in
q_out
p_out

But if p is the message setup and q is the thread setup
I need the following order of execution:

p_in
q_in
p_out
q_out

I don't have a solution yet. I guess I give up for the moment.
Maybe interruptible queues would be the easier solution.

I might come up with a solution for SWI-Prolog in a few weeks.

**Comment by jburse** [comment]
There are also some doubts that using message_queue_destroy/1
as a way to notify slaves in a setting where there are recursive
actions. The balance/3 predicate has two arguments;

?- balance(generator(X), test(X,Y), N).

What if balance is more intelligent does a less local load
balancing and a more global load balancing as in a fork join
framework. And if test/2 uses a balance/3 itself.

test(_,_) :- 
    ...., balance(_, _, _), ...

With the message_queue_destroy/1 approach we will not
be able to tear down test/2. Since the balance/3 in test/2
has created new queues, and we don't know about these 
queues and there might be some waiting.

**Comment by jburse** [comment]
I have uploaded a new concurrent test case. The SWI-Prolog code is here:

Balanced execution of pool extraction.
https://github.com/jburse/jekejeke-samples/blob/master/jekrun/benchdist/tests/swipool.p

This test case challenges a couple of Prolog features. Namely concurrent access to
dynamic predicates. Contrary to static predicates, dynamic predicates should be
allow in write modus from different threads. This requires some locking.

Further what is challenged is concurrent retract despice the logical update view
approach of Prolog. I don't know whether SWI-Prolog breaks the logical update view
in favor of the post condition of retract/1 that the clause wasn't removed twice.

We had to adapt our retract/1 predicate, and it is now a mixture of logical update
and clause reference erase which fails, if clause is already removed. Together with
the additional locking, the pool fetch could be a bottle neck.

SWI-Prolog performs well! 

But unfortunately we had a hang again:
https://github.com/jburse/jekejeke-samples/blob/master/jekrun/benchdist/galery/ideapad_swi3.gif

**Comment by jburse** [comment]
BTW: Here is a verification that both Prolog systems do the same:

SWI-Prolog between/3 vs retract/1
![verify_swi](https://cloud.githubusercontent.com/assets/5411487/18048481/9801978c-6de2-11e6-8431-25000ff5a7fc.gif)

Jekejeke Prolog between/3 vs retract/1
![verify_jekejeke](https://cloud.githubusercontent.com/assets/5411487/18048489/ac127336-6de2-11e6-929a-b0f1c27964e9.gif)
