### ISSUE TITLE
Feature Request: Interruptible Internal Condition Variables

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#161]
Derived from the experience with:
https://github.com/jburse/jekejeke-samples/tree/master/jekrun/benchdist/compat

And the problems here:
https://github.com/SWI-Prolog/swipl-devel/issues/156

**Request Specification:**

I request a new predicate as follows:

% thread_abort(+Thread, +Message)
thread_abort(T, M) :-
     /\* interrupt the target thread T if it is waiting for a condition variable */
     catch(thread_signal(T,
          throw(error(M, _))), _, true).

/\* Existing internal condition variables that should be interruptible by
   the new predicate thread_abort/2:
- non-empty in thread_message_get/2
- non-full in thread_message_send/2
  What else */

Possibly the request can come with new API calls that expose
these internal condition variables so that the application
programmer can use them for other queuing or synchronization
primitives.

**Request Rational:**

There are the following inherent problems with the current
SWI-Prolog thread and queue predicates.
- It seems that a message_queue_destroy/1 is needed for a complete
  tear down of slave threads from within a master thread. Most likely
  the message_queue_destroy/1 call must be issued before a
  thread_join/2. Coding such a sequence is non-trivial, the
  setup_call_cleanup/3 doesn't help. See the bug entry.
- Even if we manage to install such a destroy/join sequence for a
  particular master thread, there are doubts that this is a sustainable
  technique. As soon as the master thread needs an additional queue
  code has to be probably rewritten in a non-trivial way. We cannot
  provide a stacking sys_clean_queue/2 because of the particular
  required sequencing.
- Also there are doubts that message_queue_destroy/1 is an appropriate
  way to notify threads to not use a queue anymore. It could be the
  case that the master thread wants to use an existing queue, and
  the slave shoud only stop using the queue but we don't want to
  destroy the queue. Examples could be GUI queues, alarm queues
  etc.. etc..

Bye

**Comment by jburse** [comment]
Maybe the current delay problems can be mittigated by 
changing the non-Windows **dispatch_cond_wait** routine:

Instead:

```
    switch( rc )
    { case ETIMEDOUT:
        if ( is_signalled(LD) )
           return EINTR;
        if ( api_timeout == deadline )
           return ETIMEDOUT;
        return 0;
      default:
        return rc;

```

Try the following:

```
    switch( rc )
    { case ETIMEDOUT:
        if ( is_signalled(LD) )
          return EINTR;
        if ( api_timeout == deadline )
          return ETIMEDOUT;
        return 0;
      case 0:
        if ( is_signalled(LD) )
          return EINTR;
        return 0;
      default:
        return rc;
```

**Comment by JanWielemaker** [comment]
Doesn't help on Linux (added anyway as it might on some platforms).

**Comment by jburse** [comment]
One work around would be to use more than pthread_kill to issue 
a signal from one thread to another, although I didn't check your source.

In Jekejeke Prolog I am already using a more complex machinery on
on top of the Java based interrupt(), I do my own masking and stuff like that.

So adding a layer could be benefitial, the idea I had for the layer
is as follows: Each thread knows which condition variable it is waiting for.

There will be maximum one condition variable or non a thread is
waiting for. A signal will also kick this condition variable if any.

No need for 250ms.

I am currently sifting through the java CCP files, but the thing of
their monitors is very complicated, they have bias locks, inflate structures etc..

So I didn't find the trick yet that Java is using. But I know that when
taking a thread dump one sees whether a thread is inside a condition variable.

So they must have this info per thread.

**Comment by JanWielemaker** [comment]
That layer is already present.  The needed trick is indeed to publish the CV it is waiting for, but we need to be careful about a raise condition where the signaling thread finds the CV, but before it can signal it the CV is
already destroyed.  So, we need a little layer with some atomic operations to avoid that race.   Another approach might be to have exactly one CV for each thread and signal that.  That might be a better option.  Both require some redesign, which is not on my priority queue.

**Comment by jburse** [comment]
Any solution that involves modifying the balance/3 predicate itself
must still preserve the following requirement:
- If the balance/3 predicate is interrupted no zombie threads are left
- If the balance/3 predicate receives a cut no zombie threads are left
- if the balance/3 predicate receives an exception from the continuation no zombie threads are left

I have a solution against zombies both for SWI-Prolog and for Jekejeke Prolog. In
SWI-Prolog the solution is the predicate sys_clean_thread/2 in the compatibility
module swiclean.p. In Jekejeke Prolog the predicate comes from a new 
module "clean".

The solution is based on Jeff Roses trick, i.e. the nondet predicate:

```
sys_clean_thread(G) :-
   setup_call_cleanup(
       sys_thread_init(G, T),
       nondet,
       sys_thread_fini(T)).
```

I am assuming a setup_call_cleanup/3 implementation that
executes both the setup and cleanup part without receiving
interrupts, i.e. it masks them out and delays them.

This is important since sys_thread_fini/1 executes two goals:

sys_thread_fini(T) :-
   catch(thread_signal(T,
      throw(error(system_error(user_close), _))), _, true),
   thread_join(T, _).

If an interrupt would be received here in the unify port, we would
have signal and join. If an interrupt is received her between signal
and join, well we might have only a signaled the thread, which is
less severe.

In Jekejeke Prolog the cleanup part of setup_call_cleanup/3 is 
executed with interrupts masked out, so I guess I cannot create
zombies in Jekejeke Prolog. Currently I don't know for 100% whether
this also works similarly in SWI-Prolog.

Compared to thread.pl, the predicate balance/3 really makes 
considerations that no zombies are created. But I still have no solution
for the new problem wth the delay, that also takes care of not
creating zombies.

Bye
