### ISSUE TITLE
erase/1 doesn't check and modify the reference state as an atomic operation

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#162]
A common artificial intelligence technique is to use a blackboard for
communication between agents. The blackboard would be just a dynamic
database where facts are asserted and retracted.

I want to do something simpler. Namely I want to use a blackboard to
define a set of work items via assert, and then use retract to pick work items.
The retract predicate should have the following post condition:
1) If retract gives an element, it wasn't retracted by another thread
2) if retract doesn't give an element, it was retracted by another thread,
3) Or the retract was issued when the facts and rules for the predicate were 
    already reduced, and it is going along 1) and 2) with a smaller logical view 

By the logical view update, the build-in predicate retract/1, when issued
from multiple threads all return the same snapshot of facts and rules, or
maybe a redued snapshot. This snapshot is returned via the built-in retract/1 
to the multiple client threads, independent of the individual retract state of the clauses.

Since the retract state is not reflected for the individual threads, this makes 
it impossible to use the built in retract/1 as a means to distribute work 
over multiple threads. The threads will do duplicate work. We therefore
deviced the following "clean" version of retract:

```
sys_clean_retract(V) :- var(V),
   throw(error(instantiation_error, _)).
sys_clean_retract((H :- B)) :- !,
   clause(H, B, R), erase(R).
sys_clean_retract(H) :-
   clause(H, true, R), erase(R).
```

Unfortunately this clean version doesn't work. It either crashes or the post
conditions 1) and 2) are not satisified. It seems that the erase/1 predicate cannot
check and modify the delete state of the clause reference in an atomic way. 
This is a pitty, since a failing erase/1 for an already deleted clause reference is
exactly what would be needed.

I don't need a blocking queue, only an enumeration which gives me non-deleted
clause references. The above sys_clean_retract/1 does this, even if there is a race
condition as experimentation with Jekejeke Prolog shows. In the upcoming release
of Jekejeke Prolog retract/1 is exactly implemented as above.

Could erase/1 be fixed, so that it is a non-crashing atomic operation?

**Comment by jburse** [comment]
The test case is here:
https://github.com/jburse/jekejeke-samples/blob/master/jekrun/benchdist/tests/swipool.p

Invoking horde/2 the parallel work distributor directly we should aways see the
sum 984997, this should be the same sum executed non-parallel and parallel.

SWI-Prolog sum error and 
![swi_failure](https://cloud.githubusercontent.com/assets/5411487/18056919/3aee2548-6e0e-11e6-9972-757c5156af8e.gif)

Jekejeke Prolog no sum error and no crash:
![jekejeke_ok](https://cloud.githubusercontent.com/assets/5411487/18056935/44869284-6e0e-11e6-953f-b579dc024313.gif)

**Comment by JanWielemaker** [comment]
Pushed a modification for single success of retract/1 and erase/1 on concurrent access.  I think it makes sense, although the principal work distribution mechanism is a message queue.    Without an operation that waits for new facts on a dynamic predicate using predicates for this purpose is rather dubious IMO.

**Comment by jburse** [comment]
I saw your changes. You can even speed up a little bit the implementation, I also did the same today with my own implementation. Before I had:

```
        synchronized (this) {
            if ((clause.flags & Clause.MASK_CLAUSE_ASSE) == 0)
                return false;
```
 
Now I have the following double check:

```
        if ((clause.flags & Clause.MASK_CLAUSE_ASSE) == 0)
            return false;
        synchronized (this) {
            if ((clause.flags & Clause.MASK_CLAUSE_ASSE) == 0)
                return false;
```

You could do the same. Since it might take some time to enter the locked region, and then check the flag. There is no harm to check the flag before only some speed gain. I think I saw today some speed gain if I am using 8 or so threads. 8 threads will delete much more and a single thread can then much faster go to the next non-deleted clause.

In your C code this would approximately look as follows. We have before:

```
LOCKDEF(def);
  if ( true(clause, CL_ERASED) )
  { UNLOCKDEF(def);
    return FALSE;
  }
```

And the slightly optimized code, then looks as follows:

```
if ( true(clause, CL_ERASED) )
    return FALSE;
LOCKDEF(def);
  if ( true(clause, CL_ERASED) )
  { UNLOCKDEF(def);
    return FALSE;
  }
```

I saw this double checking elsewhere in your code. And I am also using it elsewhere in my code, but I forgot about this. Currently I have two more optimizations in my code, both for erase_ref/1 and also recordz_ref/1 and recorda_ref/1, the later two don't exist as such in SWI-Prolog:
- I don't use a lock for static predicates (this is tricky)
- I don't use a lock for thread local predicates (this is obvious)

Bye

**Comment by JanWielemaker** [comment]
I doubt it is worth the trouble in this case.   I sometimes do double checking if the likely case is that the pre-check succeeds and the test is time critical.  I'm not that sure in this case and I don't really believe in the use case anyway.

Current SWI-Prolog releases have no locks for predicates execution, being it static, dynamic or thread local.   Most modification predicates do lock.  I think that is fine.

**Comment by jburse** [comment]
Strange that it is possible to do execution without lock, even in presence of
modification, but still need locks for modification (I don't mean the flag, the rest)?! 

Anyway I don't understand this kind of datastructures yet (Java has similar 
libs and they use some atomic pointer ops to implement them).

if the new release is out will do some testing, hope the crash goes away!

**Comment by jburse** [comment]
There might be also an issue with record references. 
Don't know whether your clause ref fix also touched them.

Will only know for sure tomorrow, nightly build is 
at 04:00 o'clock I guess, wont stay awake so long.

Here is a sample run in SWI-Prolog, have already 
pushed the stuff to jekejeke-samples:
![swi_recorded_erase_nok](https://cloud.githubusercontent.com/assets/5411487/18069245/06e2dcfc-6e46-11e6-8f27-7bf14949296c.gif)

**Comment by jburse** [comment]
BTW: Here is the impact of double checking:
(Warning **Hoax**, my CPU(s) is/are sometimes in good mood
and produces better results. Maybe some hash codes
are differently generated and then there are less collisions)

![cpu_playing_tricks](https://cloud.githubusercontent.com/assets/5411487/18069388/11c82194-6e47-11e6-9f43-5b8696f0982d.gif)

**Comment by jburse** [comment]
Since there are hangs and crashes, I guess the code of SWI-Prolog has
to be watched with more scrunity. A possible source of multi-threading
errors are some innocent looking macros. Take for example the following
two macros found in pl-incl.h:

#define set(s, a)		((s)->flags |= (a))
#define clear(s, a)		((s)->flags &= ~(a))

Unfortunately such operations are not atomic in multi-threaded environment, 
and there is no guarantee that they do what they are probably supposed to
do. The problem is that under the hood the CPU has to load and then save
an object field.

The CPU also does this when it has a single instruction for the update. So
there can be errorneous interleaving, for example set() can be spurious:

     Thread 1:                               Thread 2:
     LOAD field                             LOAD field
     OR mask1                              OR mask2
     STORE field                            STORE field

The above concurrent execution has the following possible outcomes
field' = field OR mask1 OR mask2 (intended), field' = field OR mask1
(not intended), field' = field OR mask2 (not intended).

I had the same problem in Jekejeke Prolog, using an integer for bits.
One solution is to update such integer bit fields only when a lock is
present. But this often gets unnoticed, that one hasn't a lock.

(I could actually prevent that it gets unnoticed by making the field
private, and provide Java methods that always lock.) I skimmed the 
code, and found many instances with missing locks, was only looking 
for clause relevant flag modifications:

pl-proc.c:
Line: 1253:   set(cl, CL_ERASED), could be spurious 
Line: 1305:   set(clause, CL_ERASED); looks ok
Line: 1472:   set(cl, CL_ERASED); could be spurious

But for the clause this need not be a problem. Since there seems
to be no other mask than CL_ERASED that is used to update. 
Except maybe DBREF_ERASED_CLAUSE. I don't know enough.

Maybe other entities and other flags could be critical. Just saying!

**Comment by JanWielemaker** [comment]
I know that.  I also know it is not unlikely there are errors in this region.  They are not really on my shortlist though.  I would be interested in conditionally instrumenting the source to check for assumptions about locking.  Something like ASSERT_LOCKED(L_PREDICATE).   Defining the macro isn't that hard.  Getting it inserted everywhere to establish comprehensive checking of locking consistency is.

There has been a lot of redesign that has led to both too much locking and quite likely inconsistent locking at some places.

**Comment by jburse** [comment]
Yeah, programming a MT interpreter and 
then running MT tests feels a little bit like:
https://www.youtube.com/watch?v=MXcLybhbChQ

**Comment by jburse** [comment]
After a long daw of thinking, I came to an interesting conclusion. 
Instead of seeking a lock free data structure to access dynamic 
predicates. There is an other possibility.

The other possibility consists of using a read-write lock instead
of a mutex. When a dynamic predicate is accessed a read lock
is acquired. When a dynamic predicate is modified a write lock
is acquired.

This solves the main problem I have, namely that I should treat
static predicates that are multifile similar to dynamic predicates,
since they can be updated from different file consults.

The remaining problem here is that during dynamic predicate 
access it can happen that the index is extended. But this operation
can be done by multiple threads, and they will overwrite the index
and do unnecessary work twice in case the rebuild the same part.

But this unnecessary work, if it happens too often is much better 
than when threads wait for each other. No going to implement this idea.

**Comment by jburse** [comment]
I could use the daily build to verify that everything works fine now.
Both erase/1 and retract/1 have now a fixed concurrent semantic.

Cool! Here is some verification:
![erase_fixed](https://cloud.githubusercontent.com/assets/5411487/18105365/664732f6-6eff-11e6-8856-3cef60beacd1.gif)
