### ISSUE TITLE
Using read/1 on the toplevel commits unexpectedly

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#166]
Please try the following sample query:

```
?- read(T) ; X = hello.
```

When prompted for input, enter `test.` and confirm with `RET`:

<pre>
|: <b>test.</b>
</pre>

The whole interaction will look like this:

<pre>
?- read(T) ; X = hello.
|: <b>test</b>.

T = test .

?-
</pre>

Unexpectedly, this has **committed** to the first alternative.

For comparison, in GNU Prolog:

<pre>
| ?- read(T) ; X = hello.
test.

T = test ? <b>;</b>

<b>X = hello</b>

yes
</pre>

That is, GNU Prolog asks for alternatives, and also yields the alternative solution `X = hello`.

To make this work in SWI, I can apparently use `get_pending_char/1` to remove the pending RET from `stdin`.  However, if possible, please prevent the RET that is used to end the input from interfering with the toplevel control. Thank you!

**Comment by JanWielemaker** [comment]
There is a fix from about year old that makes read/1 read upto the '.', but __not read the white space that completes the fullstop__.   That is what the standard says.   That leads to the above behaviour.  One could try something to delete pending input, but that is likely to lead to timing issues in scripted settings.   Anyway, it is completely artificial, so why bother.

**Comment by triska** [comment]
A use case for this is found in *Building Expert Systems in Prolog* by Dennis Merrit: Some of the examples run with *Amzi!* Prolog and GNU Prolog, but **not** with SWI-Prolog. Here is the PDF file that contains examples which are broken due to the behaviour I posted, I hope it helps:

[**Building Expert Systems in Prolog**](http://www.inf.fu-berlin.de/lehre/SS09/KI/folien/merritt.pdf)

**Comment by JanWielemaker** [comment]
So, SWI-Prolog:

```
1 ?- read(X), get_code(C).
|: hello.
X = hello,
C = 10.
```

gprolog

```
| ?- read(X), get_code(C).
hello.
<hanging>
```

See 2315b3748fc755099a1687d6ea90eaf593e86650.  I don't recall who raised it, but it was to fix compatibility with some Prolog system (possibly SICStus?) and at least back then I was convinced that is what the standard says.   You know the standard is not holy to me but in this case it is a rather arbitrary choice IMO.

**Comment by triska** [comment]
It's OK that SWI leaves the whitespace pending after `read/1`, but it is, in my view, unfortunate that the toplevel control gets confused in such a way by this: As these examples show, we sometimes need `read/1` and still be able to get alternative solutions. Other users have also mentioned this, see for example [Wouter's comment](http://eu.swi-prolog.org/pldoc/doc_for?object=read/1).

For example, how many ways do we need on the toplevel to stop enumerating solutions? We already have:

- `c`
- `a`
- `.`
- *and* `RET`.

I suppose it would be too much to ask to reconsider what `RET` does on the toplevel, but still I find it unfortunate that the toplevel does not cooperate with `read/1` as required by these examples.

**Comment by JanWielemaker** [comment]
Wouter just repeats the standard.  This should be mentioned with read/1 and friends as it is not really obvious.   The right way for your toplevel is `read(T), get_code(_) ; X = hello.`   That is what is needed according to the standard.    This is a clear case where the standard leads to contra-intuitive behaviour.  Hopefully there are also cases were it is the right decision.  I don't know the motivation.

The alternative would be to force all toplevel responses to skip white space.   Using has, AFAIK, always done what it does and SPACE was proposed by you if I recall correctly.

**Comment by triska** [comment]
Let us take the standard for granted in this case. As I see it, it is the **toplevel** which can be significantly improved, in particular regarding how `RET` is handled. Currently, pressing `RET` does the same as `c`, `a`, *and*&nbsp;`.`: It&nbsp;*stops* the enumeration of answers. Personally, I have never even once used&nbsp;`RET` for this: I am using either `a` or&nbsp;`.`, and sometimes of course simply `C-c a`. Even so, there may be many users who use this feature. Well, the more there are, the more of them will stumble upon this exact issue with `read/1` that I am reporting. You can of course simply close all such issues, but I think there is a much better way out:

For example, I would very much prefer if pressing `RET` after an answer on the toplevel would show a small dialog like:

    more solutions: SPACE; back to toplevel: RET

This would have several benefits:

1. No more, or at least not as many as currently, questions of the "where are the other solutions?" kind, which have been repeatedly posted on Stackoverflow because users simply press&nbsp;`RET` and wonder where the other solutions&nbsp;are.
2. `read/1` would work much more nicely with the toplevel. Instead of simply committing in the case I outlined, users would see the dialog shown above, from where they can still either go back to the toplevel or obtain more answers.
3. It's *almost* backwards compatible with the current way: Users who currently like to press `RET` to stop enumeration would then press&nbsp;`RET RET`, which is *almost* as easy.
4. All other ways to stop the enumeration would still exist!
5. I very much like that `SPACE` asks for further answers, because `;` is much harder to type on many keyboard layouts. That would also still work!

I can perfectly well understand that you are reluctant to change the way the toplevel works because it was "always done" this way. On the other hand, you have already introduced extremely good changes as recently as only a few years ago, which have *much* more profoundly changed the behaviour of the toplevel, so to me it was worth raising this as an&nbsp;issue.

**Comment by triska** [comment]
I am reopening this issue because ECLiPSe has now solved this issue as follows:

<pre>
2017-06-26 13:20  jschimpf

	* Eclipse/Kernel/lib/toplevel.pl (1.11):

	Fixed problem caused by ISO-read semantics (and when not using a
	tty for input): <b>prevent blank space that was part of previous
	fullstop to be interpreted as subsequent toplevel command.</b>
</pre>

**For compatibility with ECLiPSe**, I would be grateful if this could be solved in SWI too!

**Comment by JanWielemaker** [comment]
It seems massively hacky to me.  All I can see is something like setting a flag after using read/1 on a stream that indicates we are in the middle of a fullstop and something like
`eat_full_stop_remainder(+Stream)` to be called before reading a toplevel command.  Then still, the system misbehaves on e.g.

```
?- read(X); X = hello.
|: hi.<space>RET
```
Possibly the `eat_full_stop_remainder(+Stream)` should read until (and including) RET?

I'm also confused by **(and when not using a tty for input)**.  I'd actually expect a hack when the input is a terminal.

Modifying the toplevel interaction is basically unrelated.   I see some point in changing the first RET to prompt, but I'm one of the people using that quite often and my code is generally deterministic if that is possible ...

**Comment by JanWielemaker** [comment]
As there doesn't seem to be a convincing solution that works properly in all scenarios I think this should be closed.
