### ISSUE TITLE
check_predicate_options/0 yields many errors due to undefined called_by/4

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#169]
Please see the following interaction:

<pre>
$ swipl -f none
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.27-9-g6b71ba1)
...

?- <b>check_predicate_options</b>.
ERROR: /usr/local/lib/swipl-7.3.26/library/pairs.pl:174: <b>Undefined procedure: prolog:called_by/4</b>
ERROR:   However, there are definitions for:
ERROR:         prolog:called_by/2
ERROR: /usr/local/lib/swipl-7.3.26/library/pairs.pl:152: <b>Undefined procedure: prolog:called_by/4</b>
ERROR:   However, there are definitions for:
ERROR:         prolog:called_by/2
ERROR: /usr/local/lib/swipl-7.3.26/library/pairs.pl:136: <b>Undefined procedure: prolog:called_by/4</b>
...
</pre>

Thank you for looking into this!

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.
