### ISSUE TITLE
Feature request more graphic or solo characters.

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#172]
On stackoverflow it has been observed that some mathematical
symbols are printed with quotes. Which can be a little bit annonying.
The question/answer was this one:

SWI-Prolog supports Unicode
http://stackoverflow.com/a/40318923/502187

I was digging a little further and figured out that the character
in question is not classified as graphic, but as prolog symbol.
I expect that this is the cause, but i am not 100% sure.

Here is the test run I was doing:

```
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.25-3-gc3a87c2)
Copyright (c) 1990-2016 University of Amsterdam, VU Amsterdam
?- op(1150, xfy, ⊢).
true.

2 ?- X=(a ⊢ b).
X =  (a'⊢'b).

3 ?- char_type(⊢, X).
X = prolog_symbol 
X = to_lower('⊢') 
X = to_upper('⊢') 
false.
```
Compare this with the behaviour in Jekejeke Prolog:

```
Jekejeke Prolog 2, Laufzeitbibliothek 1.1.7
(c) 1985-2016, XLOG Technologies GmbH, Schweiz

?- op(1150, xfy, ⊢).
Ja

?- X=(a ⊢ b).
X = (a⊢b)

?- use_module(library(misc/text)).
% 1 konsultiert und 0 entladen in 89 ms.
Ja

?- char_type(⊢, X).
X = graph
```

An alternative would be to classify it as solo. In either case as
graphic or as solo, no quotes would be neded when writing it.
But it might be that the quote decision algorithm needs an update.

**Comment by jburse** [comment]
Some further notes on the classification and the quotes decision
algorithm. In Java Unicode module classifies the character under
question as follows:

getType(RIGHT TACK 0x22A2) = Sm MATH_SYMBOL
http://www.fileformat.info/info/unicode/char/22a2/index.htm

I am mapping this to graphic in the Prolog scanner. To decide
when to put quotes around an atom, I am using an UAX #29 
inspired algorithm. 

Unicode Text Segmentation
http://unicode.org/reports/tr29/

This algorithm uses the scanner classification of characters,
i.e. solo, graphic etc.. and uses two pairing tables for word
starts and word ends. 

See also here: Methods wordBreak1() and singleToken()
https://github.com/jburse/jekejeke-devel/blob/master/utils/headless/matula/util/regex/CodeType.java

According to these algorithms am atom consisting of a
graphic chararacter doesn't need quotes, since it doesn't
contain a word break.

Since the algorithm is table based, it can be easily extended
to larger set of scanner character classification. But I am only
working with these classifications at the moment:

sys_type_name(0, white).
sys_type_name(1, control).
sys_type_name(2, inval).
sys_type_name(3, solo).
sys_type_name(4, score).
sys_type_name(5, upper).
sys_type_name(6, lower).
sys_type_name(7, other).
sys_type_name(8, digit).
sys_type_name(9, graph).
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/frequent/misc/text.p

**Comment by jburse** [comment]
Maybe the problem is that char_type/2 delivers prolog_symbol
and not prolog_prolog_symbol as is said here:
http://www.swi-prolog.org/pldoc/man?predicate=char_type/2

But then again I am confused the char_type/2 docu says they 
glue together, similar to graphic. Testing verifies this and shows
that they glue with graphic as well:

```
?- op(1150, xfy, ⊢⊢).
true.

?- X=(a⊢⊢b).
X =  (a'⊢⊢'b).

?- op(1150, xfy, ⊢=⊢).
true.

?- X=(a⊢=⊢b).
X =  (a'⊢=⊢'b).
```

**Comment by JanWielemaker** [comment]
write_term/1-3 did not respect the symbol character definition.  Fixed.  Otherwise the current definition is the result of several long discussions.  I'm not going to reconsider that other than for standardisation purposes.

**Comment by jburse** [comment]
After some initial struggling, I could verify that the issue can be closed. Oh its already closed!? Was using the daily build swipl-w64-2016-11-02.exe for testing.

With the font "Arial Unicode MS" I could even see the turnstyle. With other fonts, for example "Consolas" the result are basically the same, except that turnstyle symbol is not seen: 

![works_symbol_1](https://cloud.githubusercontent.com/assets/5411487/19950650/1afeb3d2-a159-11e6-85d4-a3de089bf06b.gif)

![works_symbol_2](https://cloud.githubusercontent.com/assets/5411487/19950652/1f8289b0-a159-11e6-94a8-23dd94850f89.gif)

![symbol_not_seen](https://cloud.githubusercontent.com/assets/5411487/19950653/233f8030-a159-11e6-951c-f0a9d5769cb3.gif)

**Comment by jburse** [comment]
Maybe a small glitch in SWISH. Is SWISH also using the daily build? Its seems that the writeq/1 is already correct in SWISH. But the symbols gets highlighted as outofsync. 

![symbol_marked_outofsync](https://cloud.githubusercontent.com/assets/5411487/19950979/69ea148a-a15b-11e6-88db-ae98b42a04ec.gif)

This doesn't happen if I use characters an ascii graph:

![foo_not_marked](https://cloud.githubusercontent.com/assets/5411487/19951079/ebb50d6c-a15b-11e6-8d4f-d27efb7d030c.gif)
