### ISSUE TITLE
pack_install/1 with wildcard version gives a generic error

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/swipl-devel#173]
Example:

```
?- pack_install('http://packs.rlaanemets.com/markdown/markdown-*.tgz').
% Querying "http://packs.rlaanemets.com/markdown/" to find new versions ...

Create directory for packages
   (1) * /root/lib/swipl/pack
   (2)   /swipl/lib/swipl/pack
   (3)   Cancel

Your choice? 
ERROR: atomic_list_concat/3: Arguments are not sufficiently instantiated
```

Tested with 7.3.28

According to documentation, this use case is still supported:

http://www.swi-prolog.org/pldoc/doc_for?object=pack_install/1

> HTTP URL of an archive file name. This URL may contain a star (*) for the version. In this case pack_install asks for the deirectory content and selects the latest version.

There is also typo in the documentation (deirectory -> directory).

Simply calling `pack_install(markdown)` works.

Original issue: https://github.com/rla/prolog-markdown/issues/8

**Comment by JanWielemaker** [comment]
Fixed with 0694aabfedba6c8df208d068b2fbf7cd3a938e9d
