### ISSUE TITLE
license doesnt have predefined proprietary license

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#176]
writing some proprietary code, and discover there's no license/1 predefined for proprietary.

http://www.swi-prolog.org/pldoc/man?section=softlicense

Says all other licenses reported as proprietary, but you can't actually give anything else wihtout defining a new license.

It'd be a convenience to have a proprietary predefined.

**Comment by JanWielemaker** [comment]
As we have no clue what proprietary license, use

```
:- multifile license:license/3.

license:licence(mine, ..., ...).
```

See license.pl for examples.

**Comment by Anniepoo** [comment]
my fault. misread documentation for second argument of license:license/3
