### ISSUE TITLE
Underscore aka digit grouping in numbers, floats missing?

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#177]
I am about to enhance my test cases, especially for reading terms and number_codes/2. 
It occured to me that in programming languages there was a recent trend to allow
digit grouping. For example JDK 1.8 allows the following:

        double d = 100_000.000_001;

So the underscore (_) is premitted in the mantissa and in the fraction. This seems not
to work inside SWI-Prolog, although it introduced the underscore recently:

      Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.31)
      Copyright (c) 1990-2016 University of Amsterdam, VU Amsterdam

      ?- X = 1_000_000.
      X = 1000000.

      ?- X = 1_000_000.000_001.
      ERROR: Type error: `dict' expected, found `1000000' (an integer)
     
      ?- number_codes(X, "1_000_000").
      X = 1000000.

      ?- number_codes(X, "1_000_000.000_001").
      ERROR: number_codes/2: Syntax error: Illegal number

I didn't lookup ISO 31.  If I remember well it allows spaces for digit grouping
which is also supported by SWI-Prolog, but again only works for integers and not
for floats in SWI-Prolog:

      ?- X = 1 000 000.
      X = 1000000.

      ?- X = 1 000 000.000 001.
     ERROR: Type error: `dict' expected, found `1000000' (an integer)

Any rational why digit grouping is only allowed for integers, or are there any plans
to extend it to floats as well.

**Comment by triska** [comment]
When working on this, please note, from [Decimal mark](https://en.wikipedia.org/wiki/Decimal_mark):

> The convention for digit group separators historically varied among countries, but usually seeking to distinguish the delimiter from the decimal mark. Traditionally, English-speaking countries employed commas as the delimiter – 10,000 – and other European countries employed periods or spaces: 10.000 or 10 000. Because of the confusion that could result in international documents, in recent years **the use of spaces as separators has been advocated** by the superseded SI/ISO 31-0 standard,[17] as well as by the International Bureau of Weights and Measures and the International Union of Pure and Applied Chemistry, which have also begun advocating the use of a "thin space" in "groups of three".[18][19] Within the United States, the American Medical Association's widely followed AMA Manual of Style also calls for a thin space.[15] In some online encoding environments (for example, ASCII-only) a thin space is not practical or available, in which case **a regular word space** or no delimiter are the alternatives. In 2014, the Metrication Board also proposed the system of using a space for separation in the United Kingdom and, while it is not universally adopted, it is standard within the country's construction industry.

Thumbs up for extending this to other numbers where applicable!

**Comment by jburse** [comment]
I just made open source today my Jekejeke implementation, with supports already digit grouping also for the fractional part of a number and even for the exponent. The use of the grouping separator is parameterizable through the underlying code_type/2 that is used, which is a predicate wrapper for Java Class CodeType and has a ISO default singleton. 

Currently its only Unicode connector_punctuation, which covers also the underscore (_):
http://www.fileformat.info/info/unicode/category/Pc/list.htm

I made the conversion part open source today, since I already had made the token scanner open source, which returns a String. So I wanted also to show how this String is converted to a Number. The open sourcing so far is in class ForeignAtom, there is for example a method toNumber(). The class TermAtomic plays also a role since it does some further normalization:
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/reference/structure/ForeignAtom.java
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/tools/term/TermAtomic.java

The result is seen here in the screenshot. For floats underscores in the exponent don't make any sense, since the exponent range is to low. But we support it anyway, and it makes sense for BigDecimal (has prefix 0d), because their exponent range can be much bigger:

![uderscore_number](https://cloud.githubusercontent.com/assets/5411487/20543471/3680d380-b106-11e6-91ed-1f800a995c0d.jpg)

Current decision  for number_codes/2 is to not support underscores, but this decision might need more consideration and we might change it. Similarly we might add more characters in the future that can act as a digit grouper in our ISO default singleton.

**Comment by jburse** [comment]
The space as a digit grouper is already seen in the wild. For example Windows 10 uses it in their file size display. And Wolfram Alpha uses it for their big numbers:

![wolfram_alfa](https://cloud.githubusercontent.com/assets/5411487/20543726/3aeed704-b107-11e6-8bab-0d1f233609ae.jpg)

What comes also to mind is a number continuator on a new line. In the above picture Wolfram Alpha uses a dotted slash. Maybe the back slash could be used to continue a number on a new line? Testing reveals:

![swi_cont](https://cloud.githubusercontent.com/assets/5411487/20543802/8a677944-b107-11e6-94b6-0f2538bb32d8.jpg)

But maybe there is some feature, that I don't know about?

**Comment by triska** [comment]
This works:

<pre>
?- X = 123<b>_</b>
57.
<b>X = 12357</b>.
</pre>

Quite nice!

**Comment by Anniepoo** [comment]
for what it's worth, our code at Simularity uses a lot of large integers, underscores as thousands separators is something we depend on quite a bit.   Lots of times of events in human scale times represented in nanoseconds, 60_000_000_000

**Comment by jburse** [comment]
And how about floats (the topic of this issue), do you thing underscore in float fractions is useful?

**Comment by Anniepoo** [comment]
yes, it definitely would be.

**Comment by triska** [comment]
Generally, I think the sooner you get rid of floats entirely, the better, so I see no value in improving their syntax. Floats are extremely hard to reason about, and an endless source of potentially very serious problems. I can only recommend to spend any time you want to work on this on getting rid of floats entirely. Unum is a promising alternative format with very satisfying properties. It would be a good fit for&nbsp;Prolog, as a native number format. A Prolog implementation that ships with it would attract a few extremely interesting applications!

**Comment by Anniepoo** [comment]
floats work for EModelWorks.

We're generally not itnerested in =:=, and rarely reason about the floats. We carry them along in structures, and reason about other elements of the structure.

**Comment by jburse** [comment]
floats are just integers in disguise, 1.234 is just a shorthand for 1234/1000 or 1234*10^(-3) (assuming decimal base as in BigDecimal). And the operations are just approximations of the infinite precision results (required by IEEE) like this. Means you can also model floats in CLP(FD) and maybe you need a little bit more logic. Its then a small step to an optimized CLP(FD) and maybe a little bit more logic that uses floats directly (as program extraction or realization of theorem), when the approximation parameters fit the float format.

**Comment by triska** [comment]
A huge problem with floats is that the results depend on flags that are not accessible in any&nbsp;way. Please read the Unum book for a good introduction. I am not surprised that people do not care a lot about correctness, but it's also not particularly heartening either.

**Comment by jburse** [comment]
For the Java Class BigDecimal all flags are accessible. I will also make the arithmetic unit of Jekejeke Prolog open source in a few weeks or months, I am not sure when this will happen. But the implementation of ceil/1, floor/1 etc.. heavily depends on being able to control everything, which is possible. The only thing I miss is a Java Class BigFloats which would have an exponent 2^n and not an exponent 10^n as tje Java Class BigDecimal does.

BiigDecimal and/or BigFloats are also available for GMP I guess:
http://stackoverflow.com/questions/4798777/is-there-a-c-equivalent-to-javas-bigdecimal

And you need such stuff also for Unums, in case you want to take that path. Since one of the features of Unums are also BigDecimal and/or BigFloat representation, namely we have:

a variable-width storage format for both the significand and exponent, and
https://en.wikipedia.org/wiki/Unum_%28number_format%29

I have currently only one accidential application of BigDecimals, in a total different field than in numerics, namely in natural language processing. I have an application where I need to preserve the scale, otherwise things don't work out so well. But it grates me that I didn't tap yet some further potential of such number representations.

**Comment by jburse** [comment]
Floats are correct via their approximation bounds, where the IEEE requirements are extremly hard.  I guess you mean exactness, not correctness. Of course an exact computation is not the same as an approximate computation. 

But if you have 1000 GPUs and only 32-bit floats representation instead 64-bit representation in the GP memory, but you know your image processing algorithm will stay in bounds and nothing will go numerically wrong, you will tap that power for good.

BTW: The 0f prefix in Jekejeke gives 32-bit, this is also seen in the now open source.

**Comment by JanWielemaker** [comment]
> Any rational why digit grouping is only allowed for integers, or are there any plans
> to extend it to floats as well.

Not really.  I see no real reason against this, but also no sufficient reason to spend time on it.  I'll leave it as an exercise to the user.

**Comment by jburse** [comment]
I got a new funny find. It seems that there were some proposals maybe 
prototypes, that used the underscore to denote intervals:

?- X is max(0.9__1.0, 0.8__1.1).
        X = 0.9__1.1

Richard A. O'Keefe - Tue, 21 Nov 2006 
http://eclipseclp.org/Specs/minmax/0018.html
