### ISSUE TITLE
Unicode in predicates not working on Windows 10 platform

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#178]
I just got a new Windows 10 machine, and was testing some of the unicode functionality of SWI-Prolog. But somehow it doesn't work. Is there a special option or setting to make it work?

Here are some example issues:

1) atom_codes/2 doesn't throw error message, just takes modulo. Current observable behaviour:
```
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.31)
Copyright (c) 1990-2016 University of Amsterdam, VU Amsterdam

?- atom_codes(X, [66574, 120173]).
X = 'Ў항'.
?- atom_codes(X, [66574, 120173]), atom_codes(X, Y).
X = 'Ў항',
Y = [1038, 54637].
```
Expected behaviour (one Deseret Character and one Mathematical Symbol) no modulo is taken:
```
?- atom_codes(X, [66574, 120173]).
X = '𐐎𝕭'
?- atom_codes(X, [66574, 120173]), atom_codes(X, Y).
X = '𐐎𝕭',
Y = [66574,120173]
```

2) Top level does not take modulo, but throws exception. Current observable behaviour:
```
?- X = '\x1040E\'.
ERROR: Syntax error: Illegal character code
ERROR: X = '\
ERROR: ** here **
ERROR: x1040E\' . 
```
Expected behaviour (one Deseret Character):
```
?- X = '\x1040E\'.
X = '𐐎'
```

3) char_code/2 does not take modulo, but throws exception. Current observable behaviour:
```
?- char_code(X, 120173).
ERROR: char_code/2: Cannot represent due to `character_code'
```
Expected behaviour (one Mathematical Symbol):
```
?- char_code(X, 120173).
X = '𝕭'
```

**Comment by JanWielemaker** [comment]
> Is there a special option or setting to make it work?

Insert a Linux USB stick into your computer.  The Windows version is broken as it basically handles wchar_t as USC-2, while in fact it is UTF-16.  Using UTF-16 kind of bypasses the whole idea of using wchar_t in the first place: address characters as an array.

There are to ways out.  One is to abandon Windows wchar_t, replace all wcs routines with our own that use USC-4 and support UTF-16 I/O conversion.  The other is to migrate all internals to UTF-8 and adjust all code for dealing with the multibyte consequences thereof.  It is not likely that any of this is going to happen any time soon unless some external developer or commercial party jumps in.

**Comment by jburse** [comment]
Could add a 16-bit range check in atom_codes/2 for windows, as long as there is no solution around. atom_codes/2 would then  consistently behave with string reading and char_code/2.
I just checked MacOS, there seems to be no problem with atom_codes/2 (I don't see something in the console on MacOS, but I can do copy paste):
```
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.25-3-gc3a87c2)
Copyright (c) 1990-2016 University of Amsterdam, VU Amsterdam

?- atom_codes(X, [66574, 120173]).
X = '𐐎𝕭'.

2 ?- atom_codes(X, [66574, 120173]), atom_codes(X, Y).
X = '𐐎𝕭',
Y = [66574, 120173].
```
And judging from MacOS, the error terms are (type_error, representation_error and syntax_error). I am using my MacOS machine, and too lazy to switch to Windows 10 machine:
```
?- catch(atom_codes(X, [0x110000]), E, true).
E = error(type_error(character_code, 1114112), context(system:atom_codes/2, _G4197)).

?- catch(char_code(X, 0x110000), E, true).
E = error(representation_error(character_code), context(system:char_code/2, _G2089)).

?- catch(read(X), E, true).
'\x110000\'.
E = error(syntax_error('Illegal character code'), stream(user_input, 27, 6, 847)).
```
I guess on Windows 10 and other windows OSes, as long as there is no solution around, the max value is 0xFFFF, on other platforms the max value is 0x10FFFF. On windows there seems to be possibly a glitch that atom_codes/2 doesn't do the type check for 0xFFFF.

**Comment by jburse** [comment]
I don't think this safety net would break some applications, although I might be wrong. BTW: UTF-16 support is tedious but not impossible. It can slowdown some string operations, for example do we want to return the number of codepoints in atom_length/2 or the number of 16-bit words?

I have made already my UTF-16 support partially open source, its seen through out Java Classes such as ScannerToken, ForeignAtom. UTF-16 support doesn't slow down sensitively serial operations that are not based on some codepoint counting random access indexes.

Since Java demands it the approach is to only use UTF-16 and no more strings with 8-bit characters. UTF-16 is simple, codepoints above 0xFFFF are encoded as surrogate pairs. But since linux has strings with 32-bit characters, I guess one doesn't want to loose this advantage either.

**Comment by JanWielemaker** [comment]
Added some tests.  That indeed cannot hurt.  Using type error now for > 0x10ffff and representation error for > 0xffff on Windows.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/windows-unit-test-fails-for-semweb-ntriples/5197/1
