### ISSUE TITLE
term_string unsafe

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#179]
term_string/3 is not sandbox safe.

That seems wrong to me.  Isn't it call that needs extra care? There are a thousand ways to make
a suspicious predicate, trying to prevent formation of the suspect term seems wrong.

**Comment by JanWielemaker** [comment]
I think `term_string/3` is safe.  Added.   There surely are many more predicates that are safe and are not declared as such.

**Comment by Anniepoo** [comment]
Maybe we can add some 'voting' system so logged in users can vote things safe. Or build a SWISH application that lets you register a predicate as safe. Then we can manually curate the list.

**Comment by JanWielemaker** [comment]
Sounds like a lot of work.  Possibly less involved is something that logs the encountered unsafe predicates from actual queries.  I don't have the impression it is that much of an issue though.

**Comment by Anniepoo** [comment]
It's a 'stone in the shoe'. You're happily coding along in swish and you get a no permission error, and to fix it you have to wire around it, and it doesn't make for the best consumer experience.
The log is a good idea.
