### ISSUE TITLE
pl-variant.c:172: bad test ?

### ISSUE THREAD

**Issue by dcb314** [SWI-Prolog/swipl-devel#180]
pl-variant.c:172]: (style) A pointer can not be negative so it is either pointless or an error to check if it is not.

Source code is

    DEBUG(CHK_SECURE, assert(n > 0));

Maybe better code

    DEBUG(CHK_SECURE, assert(n != 0));

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.
