### ISSUE TITLE
Non-quality issue or random artefact in conversion of rationals to floats?

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#183]
Sorry for reporting this bug without providing a better solution. So far I only stepped over a problem but I don't know yet exactly what is the cause, and what would be the cure. The problem is very simple, we have two bignums A and B, and we perform A/B, which gives a float.

What is the correct float? Here is a strange number which works not perfectly:

SWI-Prolog:
```
?- X is 244124086793065425827/147573952589676412928, Y is X^3+2*X^2-10.
X = 1.6542491578567584,
Y = -3.552713678800501e-15.
```

Jekejeke Prolog:
```
?- X is 244124086793065425827/147573952589676412928, Y is X^3+2*X^2-10.
X = 1.6542491578567586,
Y = 0.0
```

So there is a difference in the last digit of `X`. Now what is the better digit 4 or 6? We don't need the polynom `X^3+2*X^2-10` which made me find the rational number first hand. We can just use the resulting float `F ~ A/B`, and recompute the error `F*A-B`:

SWI-Prolog:
```
?- Z is 147573952589676412928*16542491578567584-244124086793065425827*10000000000000000.
Z = -293356650782460674048.
```

Jekejeke Prolog:
```
?- Z is 147573952589676412928*16542491578567586-244124086793065425827*10000000000000000.
Z = 1791254396892151808
```

So the digit 6 is the better digit, than choosing a last digit 4 (I know the float is binary so it will be some bit that differs). I looked up what algorithm I am using in Jekejeke. It is that I am blindly using `(double)A / (double)B`. Maybe the result is random, but such things shouldn't be too much random.

I didn't look-up what SWI-Prolog is using. And I also didn't yet explore another solution, which would probably do first some bignum division and then do some float conversion. But I guess the requirement for `A/B` is, that it should pick the closest float F possible. 

A further cause could be some internal 80-bit computation in Java although the result is 64-bit. But I think the likelyhood for this cause is rather small. But I could compare the result for example on different machines, and see what happens.

**Comment by JanWielemaker** [comment]
Floats are scruffy by definition.   SWI-Prolog uses libgmp for rationals and native C double arithmetic for floats.  If you don't agree with the answers, figure out what precisely is called and argue with the gmp developer or the producer of your CPU.

**Comment by jburse** [comment]
The problem is probably that the `Function: double mpq_get_d (const mpq_t op)` uses rounding towards zero. If this is consistent behaviour a work around could be the call it with (A+sign(A)*B/2) rdiv B instead of A rdiv B, to get rounding to the nearest double.

**Comment by jburse** [comment]
Well the issue isn't that simple. Maybe blame it on Rio. The A/B is a particular rational number, since the B is a power of 2. We have for B the following equality:
```
?- X is 1<<67.
X = 147573952589676412928
```
This means that theoretically the denumerator B can be losslessly represented as a float. So mostlikely the float conversion for big nums is already broken. Here is some comparison, now only converting the numerator A, and not anymore dealing with the denumerator B:

SWI-Prolog:
```
?- X is float(-244124086793065425827).
X = -2.441240867930654e+20.

?- X is 244124086793065425827.0.
X = 2.4412408679306543e+20.
```

Jekejeke Prolog:
```
?- X is float(-244124086793065425827).
X = -2.4412408679306543E20
?- X is 244124086793065425827.0.
X = 2.4412408679306543E20
?- X is float(244124086793065425827)-244124086793065425827.0.
X = 0.0
```
So I was not able to show you the error with some reference to the ISO core standard. Since the ISO allows implementation dependent rounding functions, and defines (/)/2 based on the implementation dependent rounding functions. 

But I was able to show you the error in terms of the float reading procedure which does high fidelity rounding to the nearest float. It seems that the SWI-Prolog float/1 function does mostlikely do a round towards zero, which has in average a greater error, that a round towards nearest float. 

Maybe there is somewhere a parameter or flag, in the realization of float/1, so that this can be improved.

**Comment by jburse** [comment]
Ulrich Neumerkel has recently published some test results here:
http://www.complang.tuwien.ac.at/ulrich/iso-prolog/stc#floatreadrounding 

But I cannot verify his results for ECLiPSe Prolog:

```
Version 6.1 #224 (x86_64_nt), Fri Nov 25 19:15 2016
[eclipse 1]: writeq(
        244124086793065425827.0).
2.4412408679306543e+20
Yes (0.00s cpu)
[eclipse 2]: X is 244124086793065425827
        -244124086793065425827.0.

X = -32768.0
Yes (0.00s cpu)
[eclipse 3]:
```

**Comment by JanWielemaker** [comment]
This is a SWI-Prolog issue page, **not** a standards forum.

**Comment by jburse** [comment]
Hi, 

I have a new implementation for X/Y with even higher precision than I had before. I am now using multi precision arithmetic in case either X or Y is a bigger integer. So there ar now two cases:

1) Case 1: X and Y are small:
         I compute X/Y as float(X)/float(Y)
2) Case 2: X and Y are large:
        I convert X in a multi precision 34 digits decimal number A.
        I convert Y in a multi precision 34 digits decimal number B.
        I do a multi precision 34 digits division C = A/B.
        The result is then float(C)

I did some investigations multi precision 16 digits doesn't work, there results are not uniformly enought for the test cases.  The 34 digits I am using corresponds to IEEE 754R Decimal128, and the 16 digits I rejected corresponds IEEE 754R Decimal64.

Here are the test results for the current release of SWI-Prolog 7.5.1:

![swi_div](https://cloud.githubusercontent.com/assets/5411487/23093514/38537fc6-f5e6-11e6-9106-4736d11fe2f3.gif)

Here are the test results for the upcoming release of Jekejeke Prolog 1.1.8:

![jekejeke_div](https://cloud.githubusercontent.com/assets/5411487/23093515/3de97e90-f5e6-11e6-8a3b-1b57b9f868fe.gif)

My own explanation of the results:
- The digit flare in the first test case in SWI-Prolog might be the same error why I have opened this ticket.
- The error in the second test case is a new problem, I didn't think of when opening this ticket. 

I recently expected the overflow error since I observed that for example float(10^1000) anyway fails since it is outside of the float range. The exponent range of decimals is much bigger, so converting integers to decimals does the job.

**Comment by jburse** [comment]
I have come to the following conclusion, since these problems are not only subject to the division operator (/)/2 but also there can be problems lurking with comparison predicates (<)/2. So I will rollback my changes of the division operator (/)/2 and my new strategy is:

- Comparison Predicate: The end-user can use decimal/1 to improve comparison, this does change from radix 2 to radix 10 with unlimited precision, and does allow exact compare.

- Division Operator: The end-user can use decimal/2 to improve division, this does change from radix 2 to radix 10 with limited precision, and does allow better division.

Besides that I still wish for a better float/1 evaluable functions in SWI-Prolog, and hence different results in the division as of now. There still seem some problems around which are for example seen in the following test cases:

```
Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.1)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.

?- Y is 10^50, X is float(Y).
Y = 100000000000000000000000000000000000000000000000000,
X = 9.999999999999999e+49.

?- Y is 10^50+10^34, X is float(Y).
Y = 100000000000000010000000000000000000000000000000000,
X = 1.0e+50.

?- Y is 10^50+2*10^34, X is float(Y).
Y = 100000000000000020000000000000000000000000000000000,
X = 1.0e+50.
```

On the other hand I get, using only BigInteger.doubleValue():

```
Jekejeke Prolog 2, Runtime Library 1.1.7
(c) 1985-2016, XLOG Technologies GmbH, Switzerland

?- Y is 10^50, X is float(10^50).
Y = 100000000000000000000000000000000000000000000000000,
X = 1.0E50

?- Y is 10^50+10^34, X is float(Y).
Y = 100000000000000010000000000000000000000000000000000,
X = 1.0E50

?- Y is 10^50+2*10^34, X is float(Y).
Y = 100000000000000020000000000000000000000000000000000,
X = 1.0000000000000003E50
```
