### ISSUE TITLE
Bug in format_time/3 with %f

### ISSUE THREAD

**Issue by edechter** [SWI-Prolog/swipl-devel#195]
[`format_time/3` ](http://www.swi-prolog.org/pldoc/doc_for?object=format_time/3) with format argument containing `%<N>f` in the following case: 

``` prolog
bash-3.2$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 7.3.34-14-gd1d5c6b-DIRTY)
(...snip...)
?- Stamp = 0.9999, format_time(current_output, '%T %3f', Stamp).
19:00:00 1000
Stamp = 0.9999.
```

Either the number of milliseconds should be 999 or 000 with the number of seconds rounded up to 1.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with ac87e4d9c68f7fe3cf37fd98585e584a950da146.  We now round down.  
Rounding would require a two pass process, first checking that %f rounds up to a full second, then
adjust the time stamp and finally do the usual thing.  I think that is a bit of an overkill.
