### ISSUE TITLE
Disable escape sequences when posting goals

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#196]
As of SWI 7.5, I get the following behaviour when posting a query in [**ediprolog**](https://www.metalevel.at/ediprolog/):

<pre>
?- X = "x".
%@  X = "x"<b>^H^H^H".^M</b>
%@ X = "x".<b>^M</b>
</pre>

Is there any way to disable this "jumping via escape sequences"? I do *not* want to use `-tty`, because I want the prompt to interact like on a terminal, in the way it worked with readline, without interference when posting a query itself.

**Comment by JanWielemaker** [comment]
If this is only caused by the _electric caret _ handling, we could disable that if we are running under Emacs.    See library(editline) (it is all in Prolog) and propose a patch.

B.t.w. the completion handling is also in Prolog, so you could call that rather than using the command line editor.

**Comment by triska** [comment]
Yes, this is due to the **electric caret**. 

I have looked into the source code, and a patch would be easy if there were a way to detect cases in which we *don't* want the electric caret. However, `ediprolog` invokes SWI-Prolog like any other process, exactly as it would be run from the **regular** shell. Therefore, there is no `INSIDE_EMACS`, and no `EMACS` environment variable when SWI-Prolog is invoked by `ediprolog`. From the point of the Prolog subprocess, everything is exactly like on a system terminal, so that the interaction works in the same way as on a terminal.

Thus, it seems that a change to ediprolog will unfortunately be necessary, since the new SWI default behaviour with `libedit` is *not* backwards compatible with previous versions.

What should `ediprolog` do to disable the electric caret? One way to do it is to automatically post (if the predicate exists):

<pre>
?- el_unwrap(current_input).
</pre>

A disadvantage of this is that even posting this goal already **triggers the electric caret**, when the closing parenthesis is encountered!

In particular, we get with `libedit`:

<pre>
?- el_unwrap(current_input).
<b>%@  el_unwrap(current_input^M?ediprolog-  el_unwrap(current_input)^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H(current_input).^M
%@ true.</b>
</pre>

From then on, everything works exactly as expected:

<pre>
?- X = "abc".
<b>%@ X = "abc".</b>
</pre>

The above is definitely not very beautiful, so ideally, I would like to provide an elegant way to disable the caret **before** it is ever invoked.

One additional point: I would like to retain the regular SWI toplevel as far as possible, so that `ediprolog` remains as close to the SWI default behaviour as possible, to benefit also from its future improvements. Therefore, I would like to avoid shipping complex custom toplevel definitions with `ediprolog`. The electric caret must be somehow avoided though, because it interferes with the queries that are automatically sent to the Prolog subprocess.

**Comment by JanWielemaker** [comment]
I guess ediprolog must start the Prolog some way.  That should allow it to set some environment variable that we can pick up, no?  I'm not really against an environment variable that disables the electric caret.

Alternatively some command line argument may do?

**Comment by triska** [comment]
I would prefer a command line argument, if possible, because this means that every user can easily configure this by changing only the invocation options (i.e., `ediprolog-program-switches`), without even having to upgrade `ediprolog`.

Maybe this opportunity can be used to enable more general configuration via command line arguments. Personally, I frequently need the setting `double_quotes=chars`, and so maybe an option like `--flag Flag=Value` could be very useful:

<pre>
swipl --flag double_quotes=chars \
      --flag editline_electric_caret=false \
      --flag toplevel_residue_vars=true
</pre>

**Comment by JanWielemaker** [comment]
Hmmm.  `--flag flag=value` seems to deviate further from the common command line parsing options.  I know SWI-Prolog's command line option parsing isn't de-facto standard (mostly for historical reasons), but at least recent changes make it more rather than less compliant.   Setting flags by means of command line arguments looks attractive, but we already have too many flags and too many that can do almost anything you like.

Not having to upgrade ediprolog doesn't seem to be a strong argument as you'll have to tell your users to change things anyway unless we find a way to make it work without change.   I wonder why this worked with the readline interface as that also has electric caret facilities.  Does it by magic recognise not to use these?  How?   I'm happy to make changes to editline that improve the compatibility, if I only knew how ...

Do you expect any help from the command line editor?   The only thing I can imagine is support for query completion.  Emacs modes are already recognised from the environment.  A small test indicates that ediprolog is not setting any environment, but that should be easy and won't break using ediprolog with older Prolog versions.

And, of course, you can process the ^H and ^M ...

**Comment by triska** [comment]
It seems a bit more involved than only handling `^H` and `^M`: For example, suppose (for testing) I simply comment out `bind_electric(Input)` (line&nbsp;107) in `editline.pl`, and then start a fresh `ediprolog` instance on the following query (use `M-x ediprolog-dwim RET` with point on the query):

<pre>
?- X = a.
</pre>

Please visit the buffer `*ediprolog-history*` to see the whole interaction:

<pre>
Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.0-8-g1a0ff1b-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- set_prolog_flag(color_term, false),'$set_prompt'('?ediprolog- ').<b>^M</b>
true.<b>^M</b>
<b>^M</b>
</pre>

So far, everything seems quite normal, except that the <b>^M</b> are uncalled for and do not occur when using `readline`. By the way, *cyan* text in `*ediprolog-history*` is text that is *sent* to the Prolog process. Regular text is *emitted* by the Prolog process.

This initiates the Prolog system, and now the actual query is posted:

<pre>
?ediprolog-  X = a.
<b> X = a.</b>^M
X = a.^M
^M
</pre>

This seems odd to me: Where does the ` X = a.` that is *emitted* by the process come from? It seems that the system re-emits the query that was posted.

Also, how does this all work on other platforms? If possible, I would prefer a way to obtain the straight-forward input/output sequence that is available with readline. It is true, I could make `ediprolog` behave more like a terminal and make it process such escape sequences, and I will do that as a last&nbsp;resort if no alternative is available.

I have never observed the electric caret with `readline`, and `ediprolog` also would not benefit from it at all, because at the time `ediprolog` is invoked, the query is already fully stated in the Emacs buffer itself (at least it is intended to work on full queries). At best, the electric caret only inadvertently and unnecessarily *delays* the Prolog process when sending the query. Any feedback the electric caret could provide is never available to users, and cannot help in this case, because the query is already fully spelt out: Emacs's own facilities are intended to help with composing the query and navigating within&nbsp;it.

**Comment by JanWielemaker** [comment]
I read this as "ediprolog doesn't need command line editing".   Now, if I force using readline and run Prolog under script(1), I see readline also does electric caret, being it with different escape sequences.  Now the question is: does ediprolog/emacs handle the readline escape sequences or does readline somehow detect it runs under emacs and disables itself?

SWI-Prolog tries to figure out whether it is running inside emacs by looking for `EMACS` and `INSIDE_EMACS` and if one of these is found it should not initialise line editing.  This however holds for both readline and editline (assuming no implementation errors).  Could it be that the readline library itself detects emacs somehow?  The only clue I can find is `_=/usr/bin/emacs`.  That seems a rather fragile way to detect emacs.

See also `setupGNUEmacsInferiorMode()` in `pl-init.c`.   My line of thinking is that we should somehow get rid of command line editing when running under ediprolog and ideally I do that by using and/or extending the `setupGNUEmacsInferiorMode()`

**Comment by triska** [comment]
I think I have found a good way to solve this issue: We can disable the electric caret before the toplevel interaction even starts by invoking SWI-Prolog with the `-g`&nbsp;switch, for example as follows:

<pre>
$ swipl <b>-g 'set_prolog_flag(readline, false)'</b>
</pre>

We can benefit from this in `ediprolog`, by invoking the Prolog interpreter in this way.

However, there is one drawback: Currently, there can only be a **single** occurrence of `-g`, the others are *ignored*:

<pre>
$ swipl <b>-g 'writeln(hi)' -g 'writeln(ho)'</b>
<b>ho</b>
</pre>

Therefore, if `ediprolog` itself uses `-g` to disable the electric caret, it *precludes* users from configuring their own `-g` option in case they need it.

A way out would be to allow **multiple occurrences** of `-g`, to be processed in order. Would you consider adding this as a feature?

Note that for example GNU Prolog **allows this** already:

<pre>
$ gprolog <b>--entry-goal 'write(hi)' --entry-goal 'write(ho)' --entry-goal halt</b>
GNU Prolog 1.3.0
By Daniel Diaz
Copyright (C) 1999-2007 Daniel Diaz
<b>hiho</b>
</pre>

**Comment by triska** [comment]
Regarding readline: I have never even once seen the electric caret when using `readline`, despite having tested `ediprolog` on several different platforms (including OSX and Debian) and with many different versions of SWI-Prolog.

Moreover, the "repeated query" phenomenon still seems surprising to me with `libedit`, and I have likewise never seen this with `readline` on any platform:

<pre>
?ediprolog-  X = a.
<b> X = a.^M</b>
X = a.^M
^M
</pre>

**Comment by JanWielemaker** [comment]
readline on a normal terminal definitely does electric caret.  My suspicion is that it somehow detects why it shouldn't do that or possibly why it disables itself completely.

Dunno why editline repeats the query.  I definitely do not ask for that and didn't see an option.  On the other hand, it does and that is not a problem if you talk to a proper terminal.   This give me one hint, possibly emacs/ediprolog set $TERM and we can use the termcap infrastructure to discover the terminal can't do much and thus we should disable command line editing?

**Comment by JanWielemaker** [comment]
> A way out would be to allow multiple occurrences of -g, to be processed in order. Would you consider adding this as a feature?

It does make sense.  I need to have a look as the way `-g` processed and communicated to the various parts of the system (e.g., saved states) doesn't allow for multiple values.  Probably I can create a conjunction out of them, so `-g a -g b` becomes the single init goal `(a), (b)`

**Comment by JanWielemaker** [comment]
Bingo!  emacs sets `$TERM` to `dumb`.   Added a condition to stop looking for command line editing options available if this is the case.   Current git also supports multiple `-g goal`.  I think this is a good idea, but given the size of the changes I wonder whether I should or should not move this to 7.4.0-rcX
