### ISSUE TITLE
Error on goal specified by `-t' cause infinite loop

### ISSUE THREAD

**Issue by dram** [SWI-Prolog/swipl-devel#203]
Error on goal specified by `-t` for `swipl` will cause an infinite loop, e.g.:

```
% swipl -q -t 'halt(foo)'
ERROR: halt/1: Type error: `integer' expected, found `foo' (an atom)
ERROR: halt/1: Type error: `integer' expected, found `foo' (an atom)
ERROR: halt/1: Type error: `integer' expected, found `foo' (an atom)
...
```

According to @pmoura's comments on LogtalkDotOrg/logtalk3#39, SWI-Prolog treats differently for errors caused by **defined** and **undefined** procedures, which I think is not quite reasonable.

Also, an infinite loop for this case is not quite friendly.

I'm using SWI 7.2.3.

**Comment by JanWielemaker** [comment]
As raised with the Logtalk discussion, the toplevel is __restarted__ on errors.   It is intended for interactive
usage, where restarting is the sensible action.   So I think this behaviour is completely fine.   There are many ways to make Prolog loop :)

The latest 7.5 and 7.4 releases have changed the semantics of `-g goal` to stop execution with status other than `0` if `goal` fails or throws an error.  That allows for this to get the often wanted behaviour

    swipl -g mygoal1 -g mygoal2 ... -t halt

**Comment by dram** [comment]
Thanks, have tried 7.5.1, a nice improvement.
