### ISSUE TITLE
if statement maybe incorrect

### ISSUE THREAD

**Issue by maddin200** [SWI-Prolog/swipl-devel#206]
\src\pl-ntconsole.c line 370
additional semikolon

if ( (s = WinError()) );

**Comment by JanWielemaker** [comment]
Thanks.  It is indeed incorrect.  Luckily it only gets triggered if writing to the console fails (can it?) and the only consequence is that the error message will be misleading.  Fixed.

**Comment by maddin200** [comment]
perfect
