### ISSUE TITLE
maybe side effect in sizeof

### ISSUE THREAD

**Issue by maddin200** [SWI-Prolog/swipl-devel#207]
src\os\windows\uxnt.c line 624

for(i=0; *mode && i < sizeof(m-1); )
    m[i++] = (*mode++)&0xff;

sizeof is calculated during compile time

**Comment by JanWielemaker** [comment]
Oops.  Should have been `sizeof(m)-1`, but that is wrong as we need to divide by `sizeof(TCHAR)`.  Harmless in practice though.  Fixed with 787f9b27c2b5a3b228efd55dc21c4c0d51714d86 (not tested)
