### ISSUE TITLE
authorization removes sandbox

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#209]
I can imagine many situaitons where you want the sandbox but want authorization.

Example: we have some private swish server that lets you control a bunch of stuff in our factory, say.
We want to have authorization to get on this server, for obvious reasons. But still want the sandbox - we don't want some fumble fingered user calling halt.

**Comment by JanWielemaker** [comment]
This is a swish issue.  The core just provides the sandbox.  SWISH is about when to call this.  If you look at the still quite immature `auth` branch you'll find this issue is being addressed.   Will take at least another week before the dust settles I'm afraid.

**Comment by Anniepoo** [comment]
Oops, sorry, thought I was filing on swish  ~8cD
