### ISSUE TITLE
absolute_file_name/3 gives existence error for files with different permissions

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#212]
Searching for a read-only file with option `access(write)` of `absolute_file_name/3` should throw a permission error i.o. an existence error.

Reproducible case:

```prolog
?- setup_call_cleanup(open(aap, write, Out, [create([read])]), format(Out, "aap\n", []), close(Out)).
?- absolute_file_name(aap, X, [access(write)]).
ERROR: source_sink `aap' does not exist
```

**Comment by JanWielemaker** [comment]
Works fine for me.   As I cannot imagine there is anything in the logic dealing with digits I suspect there
is something wrong with your file permissions.

**Comment by wouterbeek** [comment]
@JanWielemaker You're right.  Only a minor problem remains: the exception is not informative/misleading.  I've updated the issue accordingly.

**Comment by JanWielemaker** [comment]
Not entirely clear.  You search for a file in several places that satisfies certain conditions.  If that fails no such file/location _exists_.   That this is due to a permission error can be regarded a secondary issue.
Having only one error also simplifies error handling.
