### ISSUE TITLE
No error when calling non-existance module

### ISSUE THREAD

**Issue by dram** [SWI-Prolog/swipl-devel#213]
For following code, SWI-Prolog run without any warning or error, which I think is not quite reasonable, as `foobarbaz` does not exist.

```
?- foobarbaz:append([a], [b], L).
L = [a, b].

?-
```

I'm using version 7.5.2-16-gdc20d77.

**Comment by JanWielemaker** [comment]
append/3 is subject to auto loading.

**Comment by dram** [comment]
Thanks!

I found that there is a flag `autoload` which can be used to turn off it.

BTW, it would be nice if we can also have a flag to disable module auto creation, as currently the error message is not quite relevent:

```
?- set_prolog_flag(autoload, false).
true.

?- foobarbaz:append([a], [b], L).
ERROR: Undefined procedure: foobarbaz:append/3
ERROR:     However, there are definitions for:
ERROR:         append/1
false.

?-
```

**Comment by JanWielemaker** [comment]
> I found that there is a flag autoload which can be used to turn off it.

But don't do so.  As you are noticing, lots of things stop working.  To make all that work would slow down startup and increase memory usage significantly.   In some cases you want to disable autoloading and typically also the `unknown` flag and possibly change the _default_ module for a particular module in which you want to perform classical horn-clause logic.

Similarly, preventing automatic creation of modules would break a lot of code and compatibility.

**Comment by dram** [comment]
Sorry, I'm not aware of the performance impact.

How about make `autoload` flag module-aware? So that we can make specific modules do not load predicates automatically. Sometimes, correctness and clarity are more important than performance.

This mechanism can also apply to "module auto creation".

**Comment by JanWielemaker** [comment]
If you call set_prolog_flag/2 from the module it applies to the module.  From another module use
`set_prolog_flag(mymod:autoload, false)`.   I don't see how this applies to module creation and -again- we are dealing with a de-facto standard.  I see no reason to deviate from this.

**Comment by dram** [comment]
OK, I give up for the module creation issue, as I find that YAP also do the same, although ECLiPSe will report a "module does not exist" error.

Regarding to module-aware `autoload`, I find that the effect of `set_prolog_flag(autoload, false)` will be global even if I put it inside a module definition, is that a bug? e.g.:

```
% cat foobarbaz.pl
:- module(foobarbaz, []).

:- set_prolog_flag(autoload, false).
```

```
% swipl -q
?- [foobarbaz].
true.

?- foobarbaz:append([a], [b], L).
ERROR: Undefined procedure: foobarbaz:append/3
ERROR:     However, there are definitions for:
ERROR:         append/1
false.

?- use_module(library(filesex), []).
ERROR: /home/dram/prolog/swi/master/lib/swipl-7.5.2/library/filesex.pl:62:
        catch/3: Undefined procedure: files_ex:use_foreign_library/2
Warning: /home/dram/prolog/swi/master/lib/swipl-7.5.2/library/filesex.pl:62:
        Goal (directive) failed: files_ex:use_foreign_library(foreign(files),install_files)
ERROR: Exported procedure files_ex:link_file/3 is not defined
ERROR: Exported procedure files_ex:set_time_file/3 is not defined
true.

?-
```

**Comment by JanWielemaker** [comment]
My fault.  It  you should change the `unknown` flag to `fail`.   That stops generating undefined predicate errors for the target module and with that autoloading.  Autoloading itself is indeed global.   That is the route if you want a module with a logical theory where missing rules are equal to failure.  If you want to make sure your program nicely imports everything you need you can use the built-in editor, which indicates by color that a predicate will be autoloaded or use `gxref`, which can flag autoload predicates.

**Comment by dram** [comment]
Interesting. I'll have a look at `unknown` and `gxref`. Thanks!
