### ISSUE TITLE
installing old version on Mac OS X

### ISSUE THREAD

**Issue by anyaa431** [SWI-Prolog/swipl-devel#217]
Hi,
I installed Prolog in Mac OS X through the below command:
brew install swi-prolog
It installed version 7.4.1 of Prolog. when I run my program I have the below error:

libpl (shared) not found. Possible reasons:
SWI-Prolog not installed as a shared library. Install SWI-Prolog (5.6.34 works just fine)

How can I install old version of Prolog on mac OS X?

**Comment by JanWielemaker** [comment]
Dunno brew, but possibly it is simply because the core library changed name from libpl.dylib to
libswipl.dylib.

**Comment by anyaa431** [comment]
Thanks for your reply.
I renamed files "libswipl.a" and "libswipl.dylib" to "libpl.a" and "libpl.dylib", but still I have an error.
what should I do?

**Comment by JanWielemaker** [comment]
You should update and recompile the thing that links to SWI-Prolog.   The interface is not binary compatible anyway and I don't think you can simply rename a .dylib file on MacOS.  Even if you could, you break Prolog itself.

Please use the mailinglist for user questions.  This is not an issue with SWI-Prolog.
