### ISSUE TITLE
portray_clause/3 does not respect option variable_names/1

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#218]
The documentation of [`portray_clause/3`](http://eu.swi-prolog.org/pldoc/doc_for?object=prolog_listing%3Aportray_clause/3) states:

> If *Options* is provided, the option-list **is passed to `write_term/3`** that does the final writing of arguments.

With `write_term/3`, we have in connection with `variable_names/1`:

<pre>
?- write_term(current_output, f(X) :- g(X), [<b>variable_names(['X'=X])</b>]).
<b>f(X):-g(X)</b>
true.
</pre>

In contrast, with `portray_clause/3`, we have:

<pre>
?- portray_clause(current_output, f(X) :- g(X), [<b>variable_names(['X'=X])</b>]).
<b>f(A) :-
        g(A).</b>
true.
</pre>

If possible, please make `portray_clause/3` *respect the option `variable_names/1`*. Thank you!

**Comment by JanWielemaker** [comment]
Added by 3ea505a8ee016c57a360dfc0c95bd881ff7e9340
