### ISSUE TITLE
Overeager goal expansion

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#220]
With Ulrich Neumerkel's `library(lambda)`, I get:

<pre>
?- _+\(L=3).
<b>true.</b>
</pre>

This works exactly as expected. However, when I instead use the CLP(FD) constraint `(#=)/2`, I&nbsp;get:

<pre>
?- _+\(L#=3).
<b>L = 3.</b>
</pre>

This unexpectedly displays a binding for `L` which *should* have been a *local* variable.

I have not yet looked into the exact cause of this, but from a first impression, #170 may be&nbsp;related.

**Comment by JanWielemaker** [comment]
Well, lamdba.pl says `:- meta_predicate +\(?,0)`, which means we do goal expansion on L#=3 and
after loading clpfd we have

```
8 ?- expand_goal(L#=3, X).
L = 3,
X = true.
```

So, this is what to expect.   I guess goal_expansion/2 in clpfd is too aggressive, which indeed also seems to cause #170.   I leave the issue open, but I guess you should self-assign :)

**Comment by triska** [comment]
OK, I have self-assigned this. However, there is also a more general issue here: The SICStus  goal&nbsp;expansion mechanism is quite different, and [CLP(Z)](https://github.com/triska/clpz) works correctly with `library(lambda)` in SICStus.

Do you have any plans to provide SICStus compatibility of goal&nbsp;expansion in the&nbsp;future?

**Comment by JanWielemaker** [comment]
On 04/25/2017 10:34 PM, Markus Triska wrote:
> OK, I have self-assigned this. However, there is also a more general
> issue here: The SICStus goal expansion mechanism is quite different, and
> CLP(Z) <https://github.com/triska/clpz> works correctly with
> |library(lambda)| in SICStus.
>
> Do you have any plans to provide SICStus compatibility of goal expansion
> in the future?

I don't know where they differ currently.  The idea of using goal
expansion was derived from SICStus.  Over time features were added
to SWI-Prolog's implementation and probably also to SICStus.  Three
things drive changes:

   - Make it _better_ (not always easy to define what that means
     and it often doesn't mean the same for different people)
   - Compatibility with other systems
   - Compatibility with older versions

I don't know why this works for SICStus.  Logically speaking if
clp(fd) expands `3#=L` expands to binding `L` to `3` and leaving
a goal `true`, this will be the result.  If SICStus doesn't goal
expand arguments to meta-predicates labeled `0`, I consider that
a shortcomming.

	Cheers --- Jan
