### ISSUE TITLE
Allow the build script to auto-answer all questions

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#221]
Allow the build script to auto-answer all questions with positive answers like `y' and `1`, e.g.:

```sh
./build --yes-we-can
```

This is useful for building SWI-Prolog from a script, e.g., when creating a Docker image.

**Comment by JanWielemaker** [comment]
`build` doesn't ask questions (AFAIK).  `prepare` does and can be silenced using `./prepare --yes`.  So,
this should build Prolog without asking questions:

```
git clone ...
cd swipl-devel
./prepare --yes
./build.templ
```

**Comment by wouterbeek** [comment]
Thanks Jan!  It work perfectly that way.  Closing...
