### ISSUE TITLE
rename_file/2 does not work between Linux partitions

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#222]
When `From` and `To` are locations of different Linux partitions, `rename_file(From, To)` gives the following error:

```
ERROR: file `'<NAME>'' does not exist (Invalid cross-device link)
```

Expected: the same behavior as `mv <FROM> <TO>`, which allows files to be renamed between partitions.

**Comment by JanWielemaker** [comment]
rename_file/2 maps to the POSIX rename function that provides an _atomic_ rename that is fast and preserves all attributes, etc.   Operating systems do not provide primitives to do that across file systems.  You can of course get close using OS and filesystem dependent  primitives.  Most programming languages do not offer that.   Normal applications typically avoid that, making sure the rename is on the same file system.  You typically do that if (1) you do not want to expose the incomplete file or (2) you want to modify a file atomically in place.  In both cases you typically create a new file in the same directory with some naming convention, delete the file on failure and rename it to the target file on success.

If you really need a cross-device move you can use copy_file/2 from library(filesex) and/or 

```
process_create(path(mv), [file(From), file(To)], []).
```

(which doesn't work on Windows).

**Comment by wouterbeek** [comment]
Thanks for the info!
