### ISSUE TITLE
CLPFD transpose/2 displays strange behavior on non-matrix input

### ISSUE THREAD

**Issue by JCumin** [SWI-Prolog/swipl-devel#225]
@triska 

```
?- transpose([[1,2],[3]],Z).
false.
```

makes sense, however:

```
?- transpose([[1],[2,3]],Z).
Z = [[1, 2]]
```

does not.

I expected the predicate to fail in both case.

(This was found by  [ais523](http://chat.stackexchange.com/transcript/message/37234867#37234867))

**Comment by triska** [comment]
It should work as you expect as of 201404365942e011d40e897494fa4b8db8a3a602, please have a look. Thank you!

**Comment by JCumin** [comment]
@triska Thanks!
