### ISSUE TITLE
Please provide gcdext/5: GMP binding for mpz_gcdext

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#238]
The [**extended Euclidean algorithm**](https://en.wikipedia.org/wiki/Extended_Euclidean_algorithm) is of extreme importance in cryptographic applications. One of its most prominent applications is to compute **modular multiplicative inverse elements** in finite fields such as&nbsp;GF(p<sup>n</sup>) and elliptic curves&nbsp;E(F<sub>p<sup>n</sup></sub>), which are widely used for encryption, signing and related operations.

GMP provides the extended Euclidean algorthim via the function <a href="https://gmplib.org/manual/Number-Theoretic-Functions.html">`mpz_gcdext`</a>:

<blockquote>
Function: <b>void mpz_gcdext (mpz_t g, mpz_t s, mpz_t t, const mpz_t a, const mpz_t b)</b><br><br>
Set g to the greatest common divisor of a and b, and <b>in addition set s and t to coefficients satisfying a*s + b*t = g</b>. The value in g is always positive, even if one or both of a and b are negative (or zero if both inputs are zero). The values in s and t are chosen such that normally, abs(s) < abs(b) / (2 g) and abs(t) < abs(a) / (2 g), and these relations define s and t uniquely. There are a few exceptional cases:

If abs(a) = abs(b), then s = 0, t = sgn(b).

Otherwise, s = sgn(a) if b = 0 or abs(b) = 2 g, and t = sgn(b) if a = 0 or abs(a) = 2 g.

In all cases, s = 0 if and only if g = abs(b), i.e., if b divides a or a = b = 0.

If t is NULL then that value is not computed.
</blockquote>

It works similarly to the already available arithmetic function `gcd/2`, and moreover computes and makes available the Bézout&nbsp;coefficients s and&nbsp;t.

Please make this important GMP function available as a Prolog predicate.

For Prolog, I suggest the following argument order: `gcdext(+A, +B, ?G, ?S, ?T)`, where:

- `G` is the computed GCD of `A` and&nbsp;`B`
- `S` and `T` are the Bézout coefficients.

**Comment by JanWielemaker** [comment]
Hi Markus,

Isn't there something to do this in OpenSSL?   If so, I'd prefer to add the functionality there.  One of the reasons is the GMP license issue that in due time will ask for a replacement.  That gets harder as we depend more on it.   If GMP is the only (realistic) route I fear that the core system is the only option.

**Comment by triska** [comment]
The most important use case of this feature, namely computing modular multiplicative inverses, is available in `library(crypto)` as of commit  https://github.com/SWI-Prolog/packages-ssl/pull/104/commits/28c6e12df0a243537e1525a3a990d8ee3c439490, so I am closing this&nbsp;issue. Thank you!
