### ISSUE TITLE
The top level is buggy with multiple queries

### ISSUE THREAD

**Issue by JCumin** [SWI-Prolog/swipl-devel#241]
This works fine:

```
?- X = 1. X = 1. 

X = 1.

X = 1.
```

With 3 or more queries, the spacing is somehow wrong (1 extra new line) for all but the last 2 results:

```
?- X = 1. X = 1. X = 1.

X = 1.


X = 1.

X = 1.
```

With a simple predicate definition that introduces choice points: `a(X) :- X = 1 ; X = 2.`, we get:

```
 ?- a(X). a(X).

X = 1 .

% ... 1,000,000 ............ 10,000,000 years later
% 
%       >> 42 << (last release gives the question)
```

With a 2 args predicate like `a(X,Y) :- X = 1, Y = 2 ; X = 2, Y = 3.`, we get:

```
?- a(1,X). a(2,X).

X = 2 .

ERROR: residue_vars/2: Type error: `callable' expected, found `2,_G1507' (a compound)
```

or even:

```
?- a(X,Y). a(X,Y).

X = 1,
Y = 2 .

ERROR: '<meta-call>'/1: Arguments are not sufficiently instantiated
```

With the following predicate:

```
s(A,B):-A<10,B=A;divmod(A,10,Q,R),s(Q,T),B is T+R.
p(A,B):-A<10,B=0;s(A,S),p(S,T),B is T+1.
```

and the following query, we get:

```
?- p(1,A). p(12,B). p(99,C). p(9999,D).

A = 0 [print]
A = 0 
Unknown action: ( (h for help)
Action? 
Unknown action: 1 (h for help)
Action? 
Unknown action: 2 (h for help)
Action? 
Unknown action: , (h for help)
Action? 
Unknown action: B (h for help)
Action? 
Unknown action: ) (h for help)
Action? .


C = 2 [print]
C = 2 
Unknown action: ( (h for help)
Action? 
Unknown action: 9 (h for help)
Action? 
Unknown action: 9 (h for help)
Action? 
Unknown action: 9 (h for help)
Action? 
Unknown action: 9 (h for help)
Action? 
Unknown action: , (h for help)
Action? 
Unknown action: D (h for help)
Action? 
Unknown action: ) (h for help)
Action? .
```

I understand that this usage of the top level is not very idiomatic, but it's strange nonetheless that it is not rejected by the top level yet not parsed properly.

**Comment by JanWielemaker** [comment]
The toplevel reads a query and then executes it.  Whatever input is left after the query is interpreted as input for the query, so you __can__ do

    ?- read(X). a(1).
    X = a(1).

Multiple queries on a single line thus only work if the query doesn't read and its execution does not require any form of user interaction, i.e., iff there is a single deterministic result or no result and the query doesn't read any input.

Whatever one tries to do `fixing' this most likely creates its own problems.
