### ISSUE TITLE
Where is V7.4.2 tag?

### ISSUE THREAD

**Issue by bryant1410** [SWI-Prolog/swipl-devel#244]
7.4.2 appears to download as a stable version, but there's no tag :smile:

**Comment by JanWielemaker** [comment]
Stable versions are in swipl.git

**Comment by bryant1410** [comment]
> Stable versions are in swipl.git

why having 2 repos for the same thing?

**Comment by JanWielemaker** [comment]
History ...  Eventually I may drop that, but there is no hurry.  For your own purposes, just clone one and 
fetch the other and you've got it all in one.
