### ISSUE TITLE
Inconsistency of `char_type/2` modes

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#248]
There seems to be an inconsistency between the `char_type/2` modes `(+,+)` and `(-,+)`.

MWE:

```prolog
?- char_type(λ, alnum).
true.
?- char_type(Char, alnum), Char = λ.
false.
```

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 2f7a7816da6944481bf0354cdc30d5a75eaebe0c.  Also added a comment in the docs
as this mode is rather slow.
