### ISSUE TITLE
uuid support broken on OpenBSD

### ISSUE THREAD

**Issue by vext01** [SWI-Prolog/swipl-devel#251]
Hi,

With 7.2.3 on OpenBSD/amd64,  many tests are failing like this:
```
gmake[2]: Entering directory '/usr/local/pobj/swi-prolog-7.2.3/swipl-7.2.3/packages/pengines'
../swipl.sh -q -f test_pengines.pl -g test_pengines,halt -t 'halt(1)'
ERROR: /usr/local/pobj/swi-prolog-7.2.3/swipl-7.2.3/packages/clib/uuid.pl:53:
        '$open_shared_object'/3: File not found
Warning: /usr/local/pobj/swi-prolog-7.2.3/swipl-7.2.3/packages/clib/uuid.pl:53:
        Goal (directive) failed: uuid:use_foreign_library(foreign(uuid))
ERROR: /usr/local/pobj/swi-prolog-7.2.3/swipl-7.2.3/packages/pengines/pengines.pl:88:
        Exported procedure uuid:uuid/2 is not defined
ERROR: /usr/local/pobj/swi-prolog-7.2.3/swipl-7.2.3/packages/pengines/test_pengines.pl:63:
        test simple: received error: pengines:pengine_uuid/1: Undefined procedure: uuid:uuid/2
  However, there are definitions for:
        uuid:uuid/1
...
```

After seeing this the first time, I then tried installing libuuid (http://www.ossp.org/pkg/lib/uuid/). When that didn't work, I tried setting the `LD_LIBRARY_PATH=/usr/local/lib`, which is where libuuid is installed (and not in the link path by default).

Looks like SWI is having issues loading that shared object, which presumably will expose `uuid/2`?

Thanks, and sorry for all the OpenBSD reports :)

(more to come when I find time).

**Comment by JanWielemaker** [comment]
Hard to say.  One needs to know the locations of the library and the link commands.   Most likely OpenBSD has a tool similar to Linux `ldd` that analyses  shared library dependencies.

P.s. why trying to build 7.2?  7.4 stable is along for a while.  7.5 is already much better and will become 7.6 stable in not too long (couple of months may be).

**Comment by vext01** [comment]
Woops, I'll try a newer release and let you know how I get on.

**Comment by vext01** [comment]
I've figured out, this works on OpenBSD as long as you have the ossp-uuid package installed, otherwise SWI is built against the OpenBSD implementation, which causes issues.

**Comment by JanWielemaker** [comment]
So, we can close this?

**Comment by vext01** [comment]
Yep. I think so.
