### ISSUE TITLE
QA notice when compiling SWI

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#252]
When compiling SWI I get the following notification that I have not see earlier:

```
$ make distclean
$ ./build
QA Notice: Package triggers severe warnings which indicate that it
           may exhibit random runtime failures.
/home/wbeek/git/swipl-devel/packages/xpce/src/rgx/regcomp.c:406:4: warning: null argument where non-null required (argument 1) [-Wnonnull]
```

I've recently upgraded to Fedora 26 with GCC 7.1.1.  I'm not sure whether this is what caused the notification to appear.  Are others seeing this notice as well?

**Comment by JanWielemaker** [comment]
We're many compilers further :)  Closing.
