### ISSUE TITLE
Please add Base64 conversion predicate without padding

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#253]
For functionality I will soon add to `library(crypto)`, I need to be able to parse *and* generate data in Base64 encoding *without&nbsp;padding*.

This is similar but not identical to Base64URL encoding.

Please consider providing this in `library(base64)`, possibly as a new predicate with option `padding(false)`. Thank you!

**Comment by wouterbeek** [comment]
Hi @triska, it would indeed be nice to have this functionality!  Looking at `library(base64)` the padding seems to be introduced in only two places in the DCG, e.g.:

```prolog
encode([I0]) -->
  !,
  [O0, O1, 0'=, 0'=],
  { A is (I0<<16),
    O00 is (A>>18) /\ 0x3f,
    O01 is (A>>12) /\ 0x3f,
    base64_char(O00, O0),
    base64_char(O01, O1)
  }.
```

Maybe we could add a Boolean argument to `encode//1` that determines whether or not the `0'=` padding characters are emitted?

The documentation of `base64url/2` contains the following:

```
The use "-" instead of "+", "_" instead of "/" and do not use padding.  This implies
that the encoded value cannot be embedded inside a longer string.
```

Apart from the grammar issue in the former sentence, I do not understand what the latter sentence means?  What is means with "longer string" here?

**Comment by triska** [comment]
As I understand it, the second sentence alludes to the fact that without padding, we cannot concatenate two Base64 strings unambiguously. I think the wording can definitely be improved.

When considering options, please also note that other variants of Base64 could also be naturally covered with options, and Base64URL could be handled as simply a special case of a more general conversion predicate.

In fact, I also think you are ideally well suited to implement this, and I hope you could take a look! I would gladly help with testing it and will soon use it in important crypto functionality!

**Comment by triska** [comment]
Here is a sample implementation, using 13 lines of code for the omnidirectional core logic:

**https://www.metalevel.at/base64.pl**

This covers the usage modes I need: In particular, I need to convert lists of *bytes* (i.e., integers between 0 and&nbsp;255).

**Comment by wouterbeek** [comment]
@triska Cool stuff!  Can you finish this issue then, I don't have time to look into this ATM and I do not want to block your works with SSL.

**Comment by triska** [comment]
For SSL, I will for now use my custom implementation (linked above), and then simply move to `library(base64)` once it provides this functionality. Therefore, please leave this issue open for&nbsp;now.

**Comment by JanWielemaker** [comment]
Provided with 173bcf66417b328d64957fe145f4246e58bb2452
