### ISSUE TITLE
Consistent encoding options among different predicates

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#254]
Somehow this works:

```
 ?- xml_quote_attribute('\n',X,'utf8').
X = '\n'.
```
But this doesn't work:

```
?- xml_quote_attribute('\n',X,'utf-8').
ERROR: Domain error: `encoding' expected, found `'utf-8''
ERROR: In:
ERROR:    [8] sgml:xml_quote_attribute('\n',_6874,'utf-8')
ERROR:    [7] <user>
```

On the other hand I can use the encoding 'utf-8' in load_xml/3.

**Comment by triska** [comment]
One additional datapoint: `utf8` is used throughout in [**library(crypto)**](http://eu.swi-prolog.org/pldoc/man?section=crypto).

**Comment by jburse** [comment]
I did a double check, its indeed 'utf-8' for load_xml/3.  You find it in this source line for example:

Line 101: encoding(oneof(['iso-8859-1', 'utf-8', 'us-ascii']))
http://eu.swi-prolog.org/pldoc/doc/_SWI_/library/sgml.pl?show=src

Maybe the solution would be to allow encoding aliases which are somehow normalized. 
So a setter could be 'utf8', but a getter would return 'utf-8'. Like here:

https://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html#aliases%28%29
-- Every charset has a canonical name and may also have one or more aliases. The canonical name is returned by the name method of this class. 
-- Some charsets have an historical name that is defined for compatibility with previous versions of the Java platform. A charset's historical name is either its canonical name or one of its aliases.
