### ISSUE TITLE
(^)/2 without GMP unexpectedly yields float

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#257]
When compiling SWI without GMP support, I get:

<pre>
?- X is 2^3.
<b>X = 8.0.</b>
</pre>

For comparison, I get with SICStus Prolog:

<pre>
| ?- X is 2^3.
<b>X = 8</b>
</pre>

If possible, please consider yielding an **integer** in such cases.

**Comment by JanWielemaker** [comment]
SWI-Prolog arithmetic without GMP is pretty much flawed.  There is no concrete plan on how to fix that.  The entire idea of limiting to bounded arithmetic seems wrong, so most likely we'll need a (partial) GMP replacement.  What and how depends on opportunities and most likely on someone willing to invest with time and/or money.   Until then, if arithmetic matters to you, make sure you bind to GMP.
