### ISSUE TITLE
Where in the build script is PATH update?

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#259]
I'm used to `~/bin/swipl` being on `PATH` after I build SWI-Prolog.  But on a machine with Ubuntu 17.04, `~/bin/swipl` is installed but `~/bin` does not seem to have been added to `PATH`.

Which part of the build script is responsible for updating `PATH`?  Is it possible that his step is skipped sometimes?

**Comment by JanWielemaker** [comment]
On 08/08/2017 10:48 PM, Wouter Beek wrote:
> I'm used to |~/bin/swipl| being on |PATH| after I build SWI-Prolog. But 
> on a machine with Ubuntu 17.04, |~/bin/swipl| is installed but |~/bin| 
> does not seem to have been added to |PATH|.
> 
> Which part of the build script is responsible for updating |PATH|? Is it 
> possible that his step is skipped sometimes?

Nothing.  The installation doesn't mess with your PATH or anything else.
It is just that some installations add ~/bin to your $PATH by default
and others don't.  For developers I guess it is generally a good idea
to have a private place for your programs.

	Cheers --- Jan

**Comment by wouterbeek** [comment]
@JanWielemaker Thanks for the info.  From this I gather that a generic SWI installation script should also check whether PATH should be extended.

**Comment by JanWielemaker** [comment]
I have added a check to check_installation/0 that warns if `swipl` is not in `$PATH` or not the first `swipl` on `$PATH`.
