### ISSUE TITLE
open_string/2 uses changing encodings

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#260]
To implement functionality in `library(crypto)`, I would like to obtain in Prolog predicates the **UTF-8&nbsp;sequence** that encodes a given atom or list of characters.

Here is what I tried so far: I use `open_string/2` to open such an atom for reading, and use **octet** as the encoding.

This works exactly as expected for example for:

<pre>
?- open_string(◯, S),
   set_stream(S, encoding(octet)),
   read_stream_to_codes(S, Cs).
<b>Cs = [226, 151, 175].</b>
</pre>

However, please consider the following in contrast:

<pre>
?- open_string(ä, S),
   set_stream(S, encoding(octet)),
   read_stream_to_codes(S, Cs).
<b>Cs = [228].</b>
</pre>

This is not the UTF-8 sequence I expect here ([0xc3, 0xa4]), probably because, by sheer coincidence, this character is covered by Latin&nbsp;1 as well. It still comes as a surprise to me that different encodings seem to be used in the two different answers.

Is there a way to reliably obtain the UTF-8 sequence of such atoms?

**Comment by JanWielemaker** [comment]
That is not going to work reliably.  For relatively short strings, utf8_codes//1 is the way to go.  For large amounts of data this becomes costly.  Memory files provide a more scalable solution in that case: create one, add the text and use `memory_file_to_codes(MF, Codes, octet)`.  Memory files do provide supported encoding conversion, strings not.

**Comment by wouterbeek** [comment]
Is it not better to always use UTF-8 as the default encoding for human-facing data in SWI?  Why are some strings stored in Latin-1 anyway?  TWISI Unicode is the future and all other encodings are legacy.

I agree that we should support legacy encodings for 10+ years, but only for converting old to new content.  New content should always be Unicode.  IIUC when I store the `Codes` in `string_codes("ä", Codes)` to file I am -- in the default case at least -- storing non-Unicode data, IOW I am making the problem of converting all data in the world to Unicode bigger.

**Comment by JanWielemaker** [comment]
To the user, strings (and atoms) are arrays of Unicode code points.  How this is represented is internal.  At the moment they are represented as either a `char` array (if all code points are =< 255) or a `wchar_t` array.   This is a completely internal matter though.   Human facing is `atom_codes/2`, etc that to exactly what you want and the stream encoding mechanism that translates the data to a representation suitable for the external world.  This by default using the system locale functions.   If you use a lot of international text, make sure to have a UTF-8 based locale and you are completely fine.  This is the default on many modern Linux distros.

The C interface functions allow exchanging text in the principal encodings supported, including UTF-8.

**Comment by wouterbeek** [comment]
This is not the case on my machine though.  My locate is all UTF-8 (Fedora sets this automatically I believe, on older distros I sometimes had to set it myself):

```bash
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
Yet `string_codes("ä", Codes)` gives the same result that Markus got; Latin-1 encoding.

**Comment by JanWielemaker** [comment]
That is what it must do.  It must give the Unicode code point.  Unicode is simply a superset of ISO latin 1 (which is a superset of ASCII).   UTF-8 is just an encoding of a sequence of Unicode code points in a sequence of bytes (which is ultimately what a file is).   You don't want to work with that.  You want the nth-character of a string and not the nth byte and you want to know properties of this code point, while the UTF-8 bytes have no meaningful properties.  As I said, an atom/string is __an array of Unicode code points__.   That is the case in most moern languages that deal with text.

**Comment by triska** [comment]
There are a few important points still open as far as I am concerned, and I would like to mention them:

First, please consider my use case: These questions arose during the development of [**`library(crypto)`**](http://eu.swi-prolog.org/pldoc/man?section=crypto), where in some cases either **atoms** *or* **strings** *or* **lists** of integers can be used as arguments.

The question, to me, is: *What should these lists of *integers* mean in the context of `library(crypto)`*? Code points that are to be internally encoded via UTF-8, *or* plain integers that must be in the range 0..255 and can be stored as **octets**? Obviously, the DEC-10 answer is that such lists of integers are typically *code&nbsp;points*, and in the (Western) modern view thus are best encoded as UTF-8 internally (other parts of the world will disagree vehemently with this).

But, and that is the point: **In the context of `library(crypto)`**, this would cause **security&nbsp;issues** in application&nbsp;code, because encoding a list of integers in the range 0..255 as UTF-8 will **decrease the effective key length in general**. For example, suppose I need a key of length 3, and specify it as the list of integers `[253,254,255]` to one of the `crypto` predicates. *If*, internally, `library(crypto)` were to regard such a list of integers as **code&nbsp;points** *and&nbsp;if* it were to use UTF-8 internally for such lists, we would *internally* have:

<pre>
?- phrase(utf8_codes([253,254,255]), [A,B,C|_]).
<b>A = C, C = 195,
B = 189.</b>
</pre>

Thus, a key where each integer was originally unique is converted to (you must truncate at the right) a list where **two** elements are identical, *and* the sequence has become more predictable in general because some sequences are *invalid* in UTF-8 and therefore cannot&nbsp;occur!

For this reason, I **don't** regard such lists of integers as code points, but typically as **octets** if they occur in sensitive areas, such as keys and initialization vectors. From your message, I get now that I *could* also use an atom or string in such cases, because those are internally stored as *char* **if that is possible**, *without applying UTF-8* encoding, but if I understand correctly, this may change at some point. From such considerations, I get the strong impression that **lists of octets** are the most reliable way to reason about such lists. I have designed the `library(crypto)` API in accordance with these observations, and there are many predicates that let you reason about such lists of *bytes* (as they are called in `library(crypto)`) that smoothly work together. Still, each time I write a predicate that accepts atoms or strings *as well as* lists of integers, I must decide how to interpret such lists, and so I would appreciate a few comments. I can give more details and concrete examples if you need&nbsp;them. 

The main question I still have: Suppose users indeed *want* to use the actual UTF-8 sequence. If there is a more scalable approach to obtain that (which you explain above), then why doesn't `utf_codes//1` use it?

**Comment by JanWielemaker** [comment]
Not really sure what you are after.  Yes, typical cryptographic functions operate on lists of bytes.  Unicode text is a list of Unicode code points (0..0x10ffff) and thus you cannot just crypt Unicode text.  You have to define a mapping from an array of Unicode code points to bytes.   Some of such encodings do give a hint about valid an invalid byte sequences (most do) and therefore make brute force attacks easier.   Nothing new there.  I think this means there is no single encryption of Unicode text and most standards that deal with the encryption of Unicode text also define how this must be mapped to a byte sequence.

And yes, there are two ways to do UTF-8 mapping, utf8_codes//1 and using memory files.  The first is a nice pure Prolog way that implies a list of code points and a list of _bytes_.  The route through memory files deals with these things as C strings and does the processing in low-level C code.  That is faster if large amounts of text need to be handled.  The involved objects make is slower for short amounts of text.  Both approaches have their own merits.  I don't really see a problem.
