### ISSUE TITLE
help/1 does not help

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#262]
I get:

<pre>
?- help(#=).
Warning: The online help files (helpidx.pl, MANUAL) are not installed.
<b>Warning: If you installed SWI-Prolog from GIT/CVS, please consult
Warning: README.doc and README.git in the toplevel of the sources.</b>
true.
</pre>

However, neither `README.doc` *nor* `README.git` are available in the toplevel&nbsp;directory.

When I run `./prepare`, I get:

<pre>
$ ./prepare
All submodules are up-to-date
<b>Your kit is prepared.</b>
Please consult INSTALL for further instructions.
</pre>

Please update the instructions so that they explain a way to install the documentation.

**Comment by JanWielemaker** [comment]
How did you get to this state?   Somehow `prepare` thinks the docs are downloaded, but apparently
they do not exist any more.  Any idea Why?

**Comment by JanWielemaker** [comment]
That sounds unlikely as none of that deletes the documentation.   Anyway, you probably get back into a proper state using

    ./prepare --man

I'll see how I can improve this later.

**Comment by JanWielemaker** [comment]
Works fine now and the whole building has changed since.  Closing.
