### ISSUE TITLE
Markdown parser in pack page?

### ISSUE THREAD

**Issue by fnogatz** [SWI-Prolog/swipl-devel#263]
The Markdown for the package [xsd](http://www.swi-prolog.org/pack/list?p=xsd) is not parsed correctly. Consider the section `Usage with SWI-Prolog`. The sentence beginning with `The library(xsd/flatten) exports...` is not recognized as new paragraph, and some text is used as source code. [GitHub's markup](https://github.com/jonakalkus/xsd/blob/master/README.md#usage-with-swi-prolog) is correct.

I would have considered to fix it myself, but I have no idea where and in which repository the code for the Markdown parser is located at.

**Comment by JanWielemaker** [comment]
The markdown parser is in `packages/pldoc/doc_wiki.pl`  There is quite a bit of discussion about it on the package issue page.  The bottom line is that the markdown parser is the result of trying to mix several old and new wiki/markdown languages.  It badly needs reconsideration.  I've tried too many ad-hoc changes that typically fix one thing and break two.  In this case the distance between the `*` and the real text seems to be too long and the bullet content is taken as indented code text.  Use somthing like this and it will work

```
  * hello
    world
```

Please follow up on the packages-pldoc issue pages.
