### ISSUE TITLE
Buggy interaction between options of `absolute_file_name/3`

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#265]
It is possible to enumerate file names using options `expand/1` and `solutions/1`:

```
?- absolute_file_name('data/*.hdt', File, [access(read),expand(true),solutions(all)]).
File = '/home/wbeek/git/WebSPARQL/data/default.hdt';
```

It is also possible to retrieve one file using option `relative_to/1`:

```
?- absolute_file_name('default.hdt', File, [access(read),relative_to(data)]).
File = '/home/wbeek/git/WebSPARQL/data/default.hdt'.
```

However, it is not possible to use the three options together:

```
?- absolute_file_name('*.hdt', File, [access(read),expand(true),relative_to(data),solutions(all)]).
false.
```

**Comment by JanWielemaker** [comment]
Handling wildcharts was never intended in absolute_file_name/3 and I doubt it is a good idea to do so.  The `expand(true)` option got there when SWI-Prolog stopped expanding $var and ~ in file names to avoid ambiguities.  Using this option it was still feasible for people to run code that relied on this feature nearly compatible.   Updated the docs, deprecating `expand(true)` (which btw. describes exactly what happens which implies the above doesn't work).
