### ISSUE TITLE
Fine tuning of goal expansion?

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#266]
Possibly fine tuning of goal expansion could yield some very little
speed in consult. It seems that directive goals are expanded twice:

```
Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.8)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.

?- [user].
goal_expansion(X, _) :- write('goal '), write(X), nl, fail.
|: :- p.
goal p
goal p
```

**Comment by JanWielemaker** [comment]
Fixed with 515c28144fe62ae3b5b7eb29eb726914b586bec6.  It is harmless as goal_expansion/2 is called until fixed point is reached, so calling it once more should never harm.  It is not elegant to call it twice though.
