### ISSUE TITLE
Stream Property Non-Determinism: ?- stream_property(Err,file_no(1)).

### ISSUE THREAD

**Issue by logicmoo** [SWI-Prolog/swipl-devel#274]
version 7.5.13

`stream_property/2` does good in guessing when it can be deterministic in most cases:

````
?- stream_property(S,alias(current_input)).
S = <stream>(0x7febe7562f00).

?-
````

But here are a couple cases it seems to be missing:

````
?- stream_property(S,file_no(1)).
S = <stream>(0x7febe7563000) ;
false.

?- stream_property(S,file_no(2)).
S = <stream>(0x7febe7563100) ;
false.

?-
````

**Comment by logicmoo** [comment]
Other notes:

````
?- stream_property(Err,file_no(0)).
Err = <stream>(0x7febe7562f00).
````

Filenum 0 is deterministic.
1 and 2 are not

**Comment by JanWielemaker** [comment]
That is kind of luck.  I pushed 50300c4010ac8d4bc56ccdf3a219b4a74f3989bc, which I think should guarantee that `stream_property(-,+)` doesn't leave choice points if there are no more answers.
