### ISSUE TITLE
What is the intended behavior of `mv/2`?

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#275]
I was under the impression that `mv/2` could be used to rename a file into a file that does not yet exist.  However, the following fails:

```prolog
?- mv('a', 'b').
Warning: "b" does not exist
```

Is this indeed the intended behavior.  IOW can `mv/2` only be used to *overwrite* existing files?

**Comment by JanWielemaker** [comment]
Fixed with a3bba720f4baeeae8a21945dc5c774a95d1a1e3a
