### ISSUE TITLE
What is the meaning of the word "order"?

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#276]
The documentation of `pairs_keys_values/3` includes the following description:

> Deterministic if any argument is instantiated to a finite list and the others are either free or finite lists. All three lists are in the same order.

Does the word "order" mean length here?

If order does not mean length the the following is a counter example to the predicate description: `pairs_keys_values([1-a,1-b,2-b], [1,2], [a,b])`.

**Comment by JanWielemaker** [comment]
It means the nth element of each of the lists create a triple {K-V, K, V}.  It also means they have
the same length.  Not really sure how to keep this concise.  Possibly this is so obvious it is better
to delete this sentence?
