### ISSUE TITLE
tty_clear not working on Windows

### ISSUE THREAD

**Issue by yoava333** [SWI-Prolog/swipl-devel#277]
I'm using  `SWI-Prolog version 7.6.0 by Jan Wielemaker (jan@swi-prolog.org)`
My machine is `Windows 10 x64`

I tried to use tty_clear predicate on windows, I got the following error:
```
?- clear_tty.
ERROR: Undefined procedure: clear_tty/0 (DWIM could not correct goal)
?- tty_clear.
ERROR: Undefined procedure: tty:tty_get_capability/3
ERROR: In:
ERROR:   [10] tty:tty_get_capability(cl,string,_1588)
ERROR:    [9] tty:string_action(cl) at c:/program files/swipl/library/tty.pl:80
ERROR:    [7] <user>
ERROR: 
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
   Exception: (10) tty:tty_get_capability(cl, string, _1676) ? abort
```

I assumed that problem was the windows shell, but it seems swi prolog is running inside emacs terminals. could this be solved?

**Comment by JanWielemaker** [comment]
These predicates rely on the Unix terminal access routines (ncurses) and are not available on Windows.
This is (a bit briefly) documented in http://www.swi-prolog.org/pldoc/doc/_SWI_/library/tty.pl
