### ISSUE TITLE
Calling an engine_destroy/1 closes the Emacs editor and Thread Monitor

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#279]
Hi people!

I was using the engine-stuff to implement an certain idea. Idea works, but somehow the engine_destroy/1 closes all XPCE windows like Emacs and Threads Monitor. 

run:
setup, engine_destroy( myfunc_eng ).

This was in 7.5.13 version also and is also in the version 7.7.2 (threaded, 32 bits), I have a Windows 10 Home on a dual-core cheap HP laptop. 

[myfunc – kopio.txt](https://github.com/SWI-Prolog/swipl-devel/files/1451436/myfunc.kopio.txt)

EDIT 1:
Changing this from false to true stops the closing of windows. 
:- set_prolog_flag(xpce_threaded, true). %was false

EDIT 2:
Having a high cpu problems while xpce_threaded is true after I run these two lines:
?- setup,A=2,1 myfunc A  myfunc 1 myfunc 1 myfunc 1 ,result(R).
A = 2,
R = 6.

?- edit.
true.

?-

**Comment by xpxaxsxi** [comment]
It was missing some cuts.

**Comment by xpxaxsxi** [comment]
Well **this** I believe to be a bug and not some programming error by me

My intention (for this report) is to set up  an engine that remembers some data and gives it out once. The last engine_next/2 is needed to clean up things. 

The emacs never shows up and swipl-win.exe prcess has high cpu usage

```

Welcome to SWI-Prolog (threaded, 32 bits, version 7.7.2)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- engine_create(T,(engine_fetch(T),engine_yield(T)), Id,  []), engine_post(Id,test),engine_next(Id,A), engine_next(Id,_).
Id = <engine>(3,02E1F9A8),
A = test.

?- current_engine(E).
false.

?- emacs.
```

**Comment by JanWielemaker** [comment]
> ?- current_engine(E). false.

This is correct.  An engine that has sent its last reply is considered death.   

> ?- engine_destroy( $Id). OOPS: PL_unregister_atom('¨ú��'): invalid atom

This is fixed a couple of days ago and in the current git version.  You can grab the daily build for Windows.

**Comment by xpxaxsxi** [comment]
the version 7.7.2-15-gf2caeb2 has fixed my bug
