### ISSUE TITLE
UTF-8 sequences in clpfd.pl

### ISSUE THREAD

**Issue by JanWielemaker** [SWI-Prolog/swipl-devel#281]
library/clp/clpfd.pl contains non-ASCII characters at line 5463 and 6119.  This prevents loading in non-UTF-8 environments.  There are two solutions:

  - Rephrase using ASCII
  - put `:- encoding(utf8).` at the top of the file.   I think SWI-Prolog recognizes this anywhere in
    the file, after it holds for the remainder.  There was some standards work only accepting this
    as very first term of the file (before comments even).

I don't care much which route is taken.  Using pure ASCII is the most robust, but also a bit outdated.

**Comment by triska** [comment]
I have installed a fix (the `encoding/1` directive), please have a look. Thank you!

**Comment by JanWielemaker** [comment]
Thanks Markus.   It was merely a warning about a comment, but it doesn't look good ...
