### ISSUE TITLE
date(Y,M,D) in rdf_canonical_literal/2 

### ISSUE THREAD

**Issue by grsjst** [SWI-Prolog/swipl-devel#282]
hello,

`X = date(2017,9,1), rdf_canonical_literal(X,Y).`

gives me:

`ERROR: Type error: `rdf_object' expected, found `date(2017,9,1)' (a compound)
ERROR: In:
ERROR:   [12] throw(error(type_error(rdf_object,...),_71938))
ERROR:    [9] rdf11:rdf_canonical_literal(date(2017,9,1),_71976) at /home/geurts/lib/swipl-7.7.5/library/semweb/rdf11.pl:1330 ...`

Whereas I expected `date(2014, 5, 20)^^xsd:date`

This should work right?

I am using SWI-Prolog (threaded, 64 bits, version 7.7.5-39-gd49133d)

thanks,
Joost

**Comment by wouterbeek** [comment]
Glancing over the implementation, you are required to specify the datatype IRI using Turtle notation (`^^`) in the following way:

```prolog
?- rdf_canonical_literal(date(1,1,1)^^xsd:date, X).
X = date(1, 1, 1)^^'http://www.w3.org/2001/XMLSchema#date'.
```

Specifications without a datatype IRI are only support for integers, floats, strings, and Booleans.  Support for date compound terms could be added as an extra clause to `pre_ground_object/2`.  Feel free to submit such a change as a pull request!

It may also be a good idea to allow `pre_ground_object/2` to be hooked.  People are then free to add support for shorthand notation themselves.

**Comment by grsjst** [comment]
Thanks for looking into this Wouter! 

I assumed from the documentation, which mentions date/3 among other formats (see http://www.swi-prolog.org/pldoc/doc_for?object=rdf_canonical_literal/2) that this was supported, but I have to admit I didn't dive into the code. Adding the datatype works for me. 
Thanks!
joost

**Comment by wouterbeek** [comment]
I've added a pull request that adds support for the documented XSD date/time notations.

**Comment by grsjst** [comment]
Excellent! thanks a lot Wouter
