### ISSUE TITLE
Undefined procedure: apply_macros:(in)/2

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#285]
Let `vs.pl` consist of:

<pre>
:- use_module(library(clpfd)).

vs(Vs) :-
        maplist(in, Vs, [3\/1..0, 1\/1..0]).
</pre>

With a recent git version of SWI-Prolog, I get:

<pre>
<b>$ swipl -f none vs.pl</b>
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.8-19-gf925246-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

<b>?- vs(Vs).</b>
ERROR: Undefined procedure: apply_macros:(in)/2
ERROR: In:
ERROR:   [10] apply_macros:(_6922 in 3\/1..0)
ERROR:    [9] '__aux_maplist/3_apply_macros:(in)+0'([_6966|_6968],[3\/ ...,...]) at /Users/mt/vs.pl:4
ERROR:    [7] <user>
ERROR:
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
</pre>

On the other hand, the following works as intended:

<pre>
<b>$ swipl -f none</b>
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.8-19-gf925246-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

<b>?- use_module(library(clpfd)).</b>
true.

<b>?- maplist(in, Vs, [3\/1..0, 1\/1..0]).</b>
Vs = [3, 1].
</pre>

**Comment by JanWielemaker** [comment]
Goes wrong of the closure is subject to goal expansion that qualifies the closure.   Looks like a typo.  I think it is fixed with da048e2a6a5e76f801b170f11c7c720e5a9d574c.  Surely this one works and no tests fail.  Please have a look that I haven't missed anything and close if you agree.

**Comment by triska** [comment]
Thank you Jan, it seems to work now!

**Comment by JanWielemaker** [comment]
There is some progress ...
