### ISSUE TITLE
No 'make uninstall' target

### ISSUE THREAD

**Issue by kozross** [SWI-Prolog/swipl-devel#289]
This is a bit of a problem, as it's very hard to read Autotools-generated makefiles to determine exactly what does and doesn't get installed.

**Comment by JanWielemaker** [comment]
Uninstallation is typically the task of package managers as it is quite common to either clean or
remove the source after installation from source.   It is fairly simple though:

  - Remove `<prefix>/lib/swipl[-<verswion>`
  - Remove `<prefix>/bin/swipl*`
