### ISSUE TITLE
format/[1-3] tilde sequence directly following a tilde

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#291]
The tilde sequences supported by `format/1-3` are a great tool for programmers, e.g:

```prolog
?- format('~5f', 1.0).
1.00000
```

However, if we want to print the tilde character itself directly in front of a tilde sequence, the tilde sequence is no longer evaluated:

```prolog
?- format('~~5f', 1.0).
~5f
```

Expected: behavior identical to the following:

```prolog
?- format('~c~5f', [0'~,1.0]).
~1.00000
```

**Comment by JanWielemaker** [comment]
```
?- format('~~~5f', 1.0).
~1.00000
```
