### ISSUE TITLE
Http server that serves documents is not working properly

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#293]
While starting the document server from the menu Swi-prolog outputs a warning. Also the CSS-styling of the web page is weird on Firefox.  
The 7.7.11 shows the same warning in both 32 and 64-bit versions
The stable version of Swi-prolog 7.6.4 is okay. 
I have a cheap laptop with Windows 10 Home

> Welcome to SWI-Prolog (threaded, 32 bits, version 7.7.10-29-g1a18023a7)
> SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
> Please run ?- license. for legal details.
> 
> For online help and background, visit http://www.swi-prolog.org
> For built-in help, use ?- help(Topic). or ?- apropos(Word).
> 
> ?- 
> Warning: c:/program files (x86)/swipl/library/http/http_dispatch.pl:58:
>         c:/program files (x86)/swipl/library/http/mimetype.pl:272: Initialization goal failed
> % Started server at http://localhost:51216/

**Comment by JanWielemaker** [comment]
The warning is fixed but should -in theory- be rather harmless.  I
do not have Windows around which makes testing a bit harder.  Can you
see anything in the browser console?

	Cheers --- Jan

**Comment by JanWielemaker** [comment]
Oh, just realized I could something that might mimic the issue in Linux.  That worked.  Fixed in the HTTP package.
