### ISSUE TITLE
`argv` flag includes stack-size options

### ISSUE THREAD

**Issue by texttheater** [SWI-Prolog/swipl-devel#298]
It appears that recent versions of SWI-Prolog erroneously include command-line options that control the stack size into the `argv` flag value:

```
ke@unut:~$ swipl -S4g -g "current_prolog_flag(version_git, Version), write(Version), nl, current_prolog_flag(argv, Argv), write(Argv), nl, halt"
7.7.14
[-S4g]
```

**Comment by JanWielemaker** [comment]
`-S4g` is not a stack-size option.  As things needed to change anyway, there is now (only)
`--stack_limit=4g`.  As already documented, unrecognised options are passed to `argv`.
