### ISSUE TITLE
Documentation is out-of-date wrt. stack-size options

### ISSUE THREAD

**Issue by texttheater** [SWI-Prolog/swipl-devel#299]
See: http://www.swi-prolog.org/pldoc/man?section=stacksizes

The stack-size options documented there apparently no longer exist.

**Comment by JanWielemaker** [comment]
Thanks for pointing out.  That existed somewhere during the rewrite.  As I was making changes to the commandline options anyway and was pointed at other issues there I decided to reorganise the whole lot and get rid of old options conventions.
