### ISSUE TITLE
Installation Build Error

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#300]
I get:

Error:
Output folder: C:\Program Files\swipl\bin
....
ERROR: c:/program files/swipl/library/cql/sql_parser.pl:515:42: Syntax error: Operator expected
Completed

Version:
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.14)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.

Platform:
Windows 1803

**Comment by JanWielemaker** [comment]
Discussed on list and resolved.
