### ISSUE TITLE
After a ODBC call some system files are compiled with make

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#303]
I open up swipl-win with this file (database.pl) 
```
:-module(database,[]).
assert_all:-
	odbc_connect(nku,Conn,[]),
	forall(
	    odbc_query(Conn,'SELECT fMediaFullPath,fImageId,fMediaPixelWidth,fMediaPixelHeight FROM ImageTable',_Row),
	  true
),

	odbc_disconnect(Conn).
```
Then I call assert_all.
`?- assert_all.`

Now I get with 
```
?- make:modified_file(F).
F = 'c:/program files (x86)/swipl/swipl-win.rc' ;
F = 'c:/program files (x86)/swipl/library/win_menu.pl' ;
F = 'c:/program files (x86)/swipl/library/lists.pl' 
%more files here
```
After some debugging I found this:
```
?- source_file_property(A,modified(B)),time_file(A,TF_B).
A = 'c:/program files (x86)/swipl/swipl-win.rc',
B = 1526306404.0000012,
TF_B = 1526306404.000002 ;
A = 'c:/program files (x86)/swipl/library/win_menu.pl',
B = 1526306230.0000012,
TF_B = 1526306230.000002 ;
```
So the '$syspreds':'source_file_property/2 and system:time_file/2 are off by some millionths of a second. 

The make:modified_file/2 is using those two file times. Here is a listing of modifiled_file/2
```
modified_file(File) :-
    source_file_property(Source, modified(Time)),
    \+ source_file_property(Source, included_in(_,_)),
    Time > 0.0,                     % See source_file/1
    (   source_file_property(Source, derived_from(File, LoadTime))
    ->  true
    ;   File = Source,
        LoadTime = Time
    ),
    (   catch(time_file(File, Modified), _, fail),
        Modified > LoadTime
    ->  true
    ;   source_file_property(Source, includes(Included, IncLoadTime)),
        catch(time_file(Included, Modified), _, fail),
        Modified > IncLoadTime
    ->  true
    ).
```
I am using a 32-bit version of swipl, in a 64-bit system. I have now a swipl 7.7.14 installed, but this "bug" has been around for a year or something. I have a really cr*appy HP laptop with Windows 10 Home with all sorts of weird problems (with Windows software), but I finally debugged this, I am not sure where the problem is??? It could be my laptop????!

**Comment by JanWielemaker** [comment]
What is mostly weird is that you claim ODBC to be responsible for this.  Can you make absolutely sure this is the case and thus `make:modified_file/1` is silent before loading your program and still silent before calling `assert_all/0`?

**Comment by xpxaxsxi** [comment]
Here is what I did 5 minutes ago:
`Welcome to SWI-Prolog (threaded, 32 bits, version 7.7.14)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- make_modified_file(F).
ERROR: Undefined procedure: make_modified_file/1 (DWIM could not correct goal)
?- make:modified_file(F).
ERROR: Undefined procedure: make:modified_file/1 (DWIM could not correct goal)
?- use_module(library(make)).
true.

?- make:modified_file(F).
false.

?- assert_all.
Correct to: "database:assert_all"? yes
true.

?- make:modified_file(F).
F = 'c:/program files (x86)/swipl/swipl-win.rc' ;
F = 'c:/program files (x86)/swipl/library/win_menu.pl' ;
F = 'c:/program files (x86)/swipl/library/lists.pl' ;
F = 'c:/program files (x86)/swipl/library/error.pl' .`

**Comment by JanWielemaker** [comment]
Smells convincing :(   Doesn't make much sense at first sight ....  I'll think about it.

**Comment by xpxaxsxi** [comment]
I don't know the  internals but the '$time_source_file'/3 is reporting the same modified times.
```
?- source_file_property(A,modified(M)),'$time_source_file'(A,M2,user),time_file(A,M3).
A = 'c:/program files (x86)/swipl/swipl-win.rc',
M = M2, M2 = 1526306404.0000012,
M3 = 1526306404.000002 ;
A = 'c:/program files (x86)/swipl/library/win_menu.pl',
M = M2, M2 = 1526306230.0000012,
M3 = 1526306230.000002 ;
A = 'c:/program files (x86)/swipl/library/lists.pl',
M = M2, M2 = 1526306230.0000012,
M3 = 1526306230.000002 .
```

**Comment by xpxaxsxi** [comment]
And I am pretty sure that I have seen  this extra compiling in other cases also, that is to say, while not ODBC-calling but doing something else. But this time I can reproduce the extra compiling.

**Comment by JanWielemaker** [comment]
Which of these calls (source_file_property or time_file) changes value?  I do have one hypothesis: SPECTRE mitigating jitter in the timing.  SWI-Prolog does that as well, but only for the walltime and
cpu time, not for file time stamps.   Maybe Windows does this too?

**Comment by xpxaxsxi** [comment]
source_file_property and '$time_source_file' have same values.  time_file/2 has changes.

**Comment by JanWielemaker** [comment]
That is to be expected.  Compilation stores the time and source_file_property uses  '$time_source_file'.  It seems `GetFileTime()` doesn't return consistent values.   That is almost certainly a Windows bug or feature.  Now the question is what is causing this and, more importantly, how much can it differ?

**Comment by xpxaxsxi** [comment]
Well this could be a rounding error from 64-bit integer to  float?????! 

I am not an expert on floating point math, I have done some Google searching and thinking, so I'll open this issue. If someone knows that this is NOT a rounding issue, I will accept that.

**Comment by xpxaxsxi** [comment]
Playing With WolframAlpha:
At my laptop the "c:/program files (x86)/swipl/swipl-win.rc" has these (double precision) floats as a "file modification date"
1526306404.000002 and 1526306404.0000012

WolframAlpha converts these to rational approximation, and the rational approximation can be used at Swipl-commandline with rdiv/2 
[https://www.wolframalpha.com/input/?i=1526306404.000002](url)
[https://www.wolframalpha.com/input/?i=1526306404.0000012](url)

Using the Rational Approximation from WolframAlpha and using the rdiv/2 
This is the 1526306404.0000012
```
A is float(1271921494564533 rdiv 833333 + 1 rdiv 833333).
A = 1526306404.0000024.
```

This is 1526306404.000002
```

B is float(763153202000001 rdiv 500000 + 1 rdiv 500000).
B = 1526306404.0000038.
```

So when  WolframAlpha converts 1526306404.0000012 to a rational approximation 
and swi-prolog converts them back from rdiv/2 expressions to float,  
they have lost some precision??

1526306404.0000012  --> rational approximation --> rdiv/2 --> 1526306404.0000024

What about if dates are compared as a 64-bit integers instead of floats???

**Comment by JanWielemaker** [comment]
Yes, there is a conversion from 64-bit int to double.  What I do not really get is why this results in two different answers unless the ODBC driver somehow plays with the CPU float configuration.  If this is a float rounding issue we can be more relaxed in the comparison.  I'm not 100% convinced it is, although it is close to the double precision.   It surely is unlikely to be caused by your laptop hardware.  It seems a Windows issue or a C runtime issue.

**Comment by JanWielemaker** [comment]
For now, pushed 09a0396a72cf5ba758d08a174612ec0dc37c9c6f.  That should fix it while relying on better than 1ms resolution for updating files and running make in scripted scenarios is non-portable anyway.   Should be in tomorrows daily.
