### ISSUE TITLE
ediprolog does not work on Windows build

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#304]
Please help me make [**ediprolog**](https://www.metalevel.at/ediprolog/) usable with the *Windows build* of SWI-Prolog. I am currently running into two issues with it. Steps to reproduce:

1. Install the latest released version of Emacs (**26.1**), and the latest development version of SWI-Prolog (7.7.15).
2. In Emacs, install *ediprolog* with `M-x package-install RET ediprolog RET`
3. Put the following in your `~/.emacs`, and evaluate these forms (please adapt the path if necessary) :

       (global-set-key [f10] 'ediprolog-dwim)
       (setq ediprolog-program "C:\\Program Files\\swipl\\bin\\swipl.exe")

Now, in a **blank** buffer, press **`F10`**.

Issue (1): **Emacs hangs**, waiting for process output. Interrupt it with `C-g`.

Switch to the buffer `*ediprolog-history*` to inspect the interaction. It is observable that **no&nbsp;prompt** is emitted by the underlying Prolog process. This is *different* from the result of the exact same interaction on other platforms, such as OSX and also on Debian.

Please switch to the ediprolog source definitions with `C-h f ediprolog-dwim RET`, and then clicking on `ediprolog.el`.

We can fix this first issue by changing line 232f of `ediprolog.el` to (changes highligted in **bold**):

<pre>
         (ediprolog-send-string
          (format "set_prolog_flag(color_term, false),   \
<b>set_stream(user_input, tty(true)), set_stream(user_output, tty(true)), \</b>
                  '$set_prompt'('%s').\r\n" ediprolog-prompt)))
</pre>

So, apparently it is necessary to set `tty` to `true`. Can this be avoided?

If you make this change and re-evaluate the function `ediprolog-run-prolog` (or, alternatively, re-evaluate the whole `ediprolog.el` buffer), then we get further. First, **stop** the underlying ediprolog process (recall that we are still waiting for its output!) with `C-0 F10`, and then press `F10` again in a *blank* buffer. You should see the message `Buffer consulted` in the minibuffer, and you can inspect the whole interaction that took place behind the scenes in `*ediprolog-history*`.

To reproduce issue (2), please write the following query in any buffer:

    ?- X = a ; X = b.

Place point on the query, and press `F10`. You should see the first solution:

<pre>
<b>%@ X = a </b>
</pre>

But nothing you do will let you *interact* with the underlying Prolog process, again in contrast to what happens on other platforms if you press for example `RET`, `a`, `SPACE` or anything else to interact with the toplevel.

What is going on? Is there a way to make SWI-Prolog behave like on other platforms for this use case? 

We get a slightly different interaction if we change line 417f of `ediprolog.el` to (changes highlighted):

<pre>
                                    (read-char))))
                 ;; char-to-string might still yield an error (C-0 etc.)
                 (setq str <b>(concat</b> (char-to-string char) <b>"\n")</b>))
             (error
              (message "Non-character key")
</pre>

but this is again not ideal: Even if we do this, the underlying SWI-Prolog process behaves differently from what can be observed on other platforms. For example, if we press `a` after the first solution, we get the following interaction (observable in the `*ediprolog-history*` buffer):

<pre>
?ediprolog-  X = a ; X = b.
X = a a

?ediprolog- 
</pre>
Note that, unexpectedly, **no dot** (`.`) is emitted by the process in this case!

If possible, please have a look, and let me know how I can make ediprolog work on Windows. Thank&nbsp;you!

**Comment by JanWielemaker** [comment]
This is not very easy.  Where on posix systems emacs creates a pseudo tty and all looks natural from both sides, this is not the case in Windows.   There is, AFAIK, no console attached when running as an Emacs sub-process (you would see a Windows console if that was the case), so as far as Prolog is concerned it is attached to a pipe and non-interactive.  Setting `tty(true)` makes it think it can play interactive anyway.   You can safely add this to ediprolog as on systems where tty is already true this simply has no effect.

The second issue seems related to interacting with a query without return, no?  This too is to be expected as there is no console and thus it cannot switch between _cooked_ and _raw_ mode.  The most promising solution is probably to also put the POSIX one in the interaction mode where it requires a return.  You can achieve that using `swipl --notty` (recent versions, `swipl -tty` in old versions).  Possibly more portable and friendlier to the user is to call

    ?- set_prolog_flag(tty_control,false).

That should bring both platforms in sync where Prolog thinks it is talking to a terminal and won't try to use the terminal in _raw_ mode.

**Comment by triska** [comment]
Thank you for looking into this!

I have tried to make ediprolog work with `tty_control` set to **false**, and it works to some extent. However, the toplevel differs significantly when I disable the TTY, even when I change ediprolog to automatically send a "\n" after each keypress.

For example, please consider:

    $ swipl --notty

and then the query:

<pre>
1 ?- <b>X = a ; X = b.</b>
X = a  
</pre>

I now want to get the next solution, so I press `SPACE`, followed by `RET`. But then I get:

<pre>
2 ?- 
</pre>

i.e., it returns to the toplevel! I expected instead:

<pre>
X = b.
</pre>

Could this be improved in the toplevel?

Alternatively, is there a different solution that allows me to use TTY also on Windows? It's OK if a console appears for this use case.

**Comment by JanWielemaker** [comment]
Thought I commented on this?  Anyway:

  - Adding a Windows console won't help; you'll loose the ability to interact from Emacs.  Windows consoles are not POSIX pttys.
  - Using _space_ _return_ doesn't work.  AFAIK, the non-raw interaction reads a line, strips white space and executes the resulting command.  This is empty in this case, which is interpreted as _done_.  So, use `;` _return_.   That should work in all versions.   If I understand it right, it is ediprolog that decides what to send on which keystroke from the user anyway, so sending a longer command should not harm.  We could consider a dedicated set of command aliases intended for machine interaction which we guarantee to be stable.   This is unlike the rest of the toplevel that is directed to humans and for which we accept some level of incompatibility.
