### ISSUE TITLE
OpenID2.0 support going away from Google

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#31]
https://support.google.com/accounts/answer/6135882 

We'd love to find someone who'se more expert than we on OpenID and such and can help us migrate our libraries off of OpenID2.0  

Thsi would be a great bug for somebody who'se new to Prolog but interested, and knows the OpenID / OAuth world.

Read more about our cry for help at

http://www.swi-prolog.org/news/337e9ee0-8509-11e4-95da-00144fee017c

**Comment by Anniepoo** [comment]
doing this apparently will get us some time

https://developers.google.com/accounts/docs/OpenID#shutdown-timetable

**Comment by Anniepoo** [comment]
Jan, please label this issue outside-help-needed   as it's being watched by OpenHatch, I'm hoping we attract help through that means.

**Comment by JanWielemaker** [comment]
On 01/23/2015 04:48 AM, Anne Ogborn wrote:
> doing this apparently will get us some time
>
> https://developers.google.com/accounts/docs/OpenID#shutdown-timetable

Added.  If you still get a warning from Google that Google is 
terminating OpenID services, please drop a message.

	Cheers --- Jan

**Comment by JanWielemaker** [comment]
Fixed long ago, closing.
