### ISSUE TITLE
File autocomplete throws arithmetic error

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#311]
Steps to reproduce:

  1. Type the following in SWI top level (substituting the directory names for ones that exist on your machine), with four forward slashes, and a forward slash at the end: `open('/home/wbeek/Documents/`
  2. Press the `TAB` key.
  3. Observed the following error message:

```
ERROR: ///2: Arithmetic: evaluation error: `zero_divisor'
```

**Comment by JanWielemaker** [comment]
Can't reproduce.  Four slashes seem an unlikely condition.  Did have a look at the source.  You can trigger such an error if the longest file name is longer than the console width.    Pushed a fix for that.

**Comment by wouterbeek** [comment]
Thanks Jan!  This seems to be fixed now.
