### ISSUE TITLE
explain/1 at command prompt exits Swi-prolog

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#312]
threaded, 32 bits, version 7.7.15  / Windows Home 10

`explain(writeln).`

`writeln is an atom.`

%few seconds and Swi-Prolog exits without any error message 

This doesn't exit but nothing happens

`explain(writeln/1).`

`true.`

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 452399108fa9f876290a36b535525a1bfc815962
