### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [SWI-Prolog/swipl-devel#314]
Hi,

The Swipl docker package is building and running fine at my end for ARM64v8 architecture.

Branch used to build is: Stable: latest: 
````
7.7.14/stretch
````

Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by JanWielemaker** [comment]
It should ...  I doubt @ninjarobot (why is this not linked in GitHub?) is watching this.  He takes care of the Docker library.  Might be better to move this issue to https://github.com/SWI-Prolog/docker-swipl
