### ISSUE TITLE
There are more list predicates that would deserve a length(X,X) treatment

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#315]
I was researching the length(X,X) goal, and what the behaviour should
be. I found some old Richard O'Keefe notes and also check my own
system implementation. My own system implementation was running
into a loop and started to hang, so I saw that 

```
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.17)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.

?- length(X,X).
false.
```
which I think is one possible solution to the problem. But unfortunately there 
are couple of other list predicates, that could also profit from such a special 
treatment. I picked nth0/3 and observed that it hangs:

![grafik](https://user-images.githubusercontent.com/5411487/42399380-e317112a-816d-11e8-9ccb-6fac43ead72b.png)

**Comment by jburse** [comment]
Based on the old Richard O'Keefe notes I tried succ/2. I was simply replacing
some N is M+1 by succ(M, N) and by the error checking in 
succ/2, the loop was avoided. It seems that this simple trick 
works for both length/2 and nth0/3 (Preview):

![grafik](https://user-images.githubusercontent.com/5411487/42399453-2a6c2aec-816e-11e8-8445-724f38667560.png)

I am currently sifting through the lists module, and probing other
predicates whether they would also deserve such a treatment.

**Comment by jburse** [comment]
After an observation by Ulrich Neumerkel I have rolled back my change,
but for some system there might be still an issue. Sorry for disturbing.

> I have rolled back my changes to length/2. I think
> your observation in the Tau Prolog issue, that both:
> 
>    ?- length(X, L), X = L.
> 
> And:
>  
>    ?- length(X, X).
> 
> Can loop, tells me aswell that looping is ok. But
> since the predicate is tail recursive, it will not
> consume a lot of stack, and loop quite long,
> 
> but its still interuptible, since it is written
> in Prolog, so it responds to thread signal. For
> a more low level implementation, the
> 
> loop might be a vulnerability, since it might
> possibly crash the system. So a SWISH length(X,X)
> might really be a problem for the system. Not sure.

**Comment by Jim-Fan** [comment]
Considering definition length(?List, ?Int), X in length(X, X) cannot be unified to a list and int simultaneously. For me giving false is very intuitive.

**Comment by jburse** [comment]
What about nth0/3 and nth1/3. Whats your opinion there?

**Comment by triska** [comment]
For comparison, here is a table that shows the answers of several systems on various cases, including `length(L, L)`:

http://www.complang.tuwien.ac.at/ulrich/iso-prolog/length

In particular, check out XSB, which draws a **type&nbsp;error** for `length(L, L)` on the grounds that `L` cannot satisfy the required type constraints!

**Comment by jburse** [comment]
But there is no comparison of nth0/3 and nth1/3, this ticket is not about length/2 but about possible other predicates that would need treatment. I guess I will close it, since it is already 6 months old.
