### ISSUE TITLE
export/1 could be broken

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#317]
I am not 100% sure. But it might be that export/1 is broken. From
the documentation I have somehow the feeling it should accept
multiple predicate indicators one way or the other:

![grafik](https://user-images.githubusercontent.com/5411487/42688162-87960fe4-869b-11e8-8334-2653f594e181.png)

**Comment by jburse** [comment]
But I couldn't make it run. I try the following two variants, the 
predicate indicators are not considered, its rather that some
type checks are in the way:

![grafik](https://user-images.githubusercontent.com/5411487/42688197-a3b7b326-869b-11e8-89c6-3e4c99480489.png)

**Comment by JanWielemaker** [comment]
:- export((p/1, q/2)).

**Comment by jburse** [comment]
Ok, I see. I was doing reasoning from this here, which works:

![grafik](https://user-images.githubusercontent.com/5411487/42689649-7e3a874e-86a1-11e8-9343-793a26b1650b.png)

**Comment by jburse** [comment]
I guess only supporting sequence and not list is an error, I
read in the ISO module standard:

![export](https://user-images.githubusercontent.com/5411487/42693793-8a659b4e-86b0-11e8-9dc7-fb343749c81b.png)
