### ISSUE TITLE
`pack_install/[1,2]` hangs when SWI is started from Applications on OS X

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/swipl-devel#32]
The `pack_install(Pack)` hangs with any pack on OS X if SWI is started from Applications. It creates an empty directory under `~/lib/swipl/pack` but does not install pack files. It does not hang and installs the pack correctly when started from Terminal as `swipl` command. Version 7.1.29. As I do not have permanent access to a Mac, I cannot debug further.

**Comment by Anniepoo** [comment]
I believe this to be a dup of https://github.com/SWI-Prolog/swipl-devel/issues/11

**Comment by wouterbeek** [comment]
@rla can you try to reproduce this issue?  If it now works then this may indeed me a duplicate of #11 as @Anniepoo suggests and we can just close this one.

**Comment by rla** [comment]
@wouterbeek No, I cannot test as I have no access to OS X. #11 is about naming packs but this happened with normal and correctly named packs as well. There was a post on SWI list where someone else had the similar behavior. I can't find it now tho.

**Comment by wouterbeek** [comment]
@rla In that case we leave this open for an OS X user to reproduce.  I'll create a OS X tag for such cases.

**Comment by JanWielemaker** [comment]
This was related to OpenSSL failing when called from the application context.   Doesn't seem to be a problem anymore.  Why remain an open question: we have a new build system, newer OpenSSL, newer Qt, etc.   Closing.
