### ISSUE TITLE
Doc error about "standard ports" of tracer

### ISSUE THREAD

**Issue by dram** [SWI-Prolog/swipl-devel#320]
"2.9 Overview of the Debugger" section (http://www.swi-prolog.org/pldoc/man?section=debugoverview) of manual says that:

> SWI-Prolog has a 6-port tracer, extending the standard 4-port tracer [ . . . ] The optional unify port [ . . . ] The exception port [ . . . ]
> 
> The standard ports are called `call`, `exit`, `redo`, `fail` and `unify` [ . . . ]

Which I think *unify* does not belong to *standard ports*.

**Comment by JanWielemaker** [comment]
Thanks.  Pushed some fixes.  Will be in the manual with the next release
