### ISSUE TITLE
feature request clause variables names also when consulting from user

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#323]
I noticed that the clause variable names feature now works neatly. Can this 
be also enabled for consult from user? I was using this DCG as a test case:

File foldl2.pl:
```
foldl2(_,[]) --> [].
foldl2(C,[X|Y]) --> call(C,X), foldl2(C,Y).
```

The result also nicely creates new variables for the DCG translation,
it avoids the already used variable C and makes a variable D:

![grafik](https://user-images.githubusercontent.com/5411487/43525910-4495545e-95a3-11e8-8e0c-d72044951d0b.png)

**Comment by jburse** [comment]
Unfortunately the feature doesn't work when consulting from user.
The variable names C, X and Y get lost:

![grafik](https://user-images.githubusercontent.com/5411487/43525994-73001478-95a3-11e8-8d60-ac8e38c5ebc4.png)

**Comment by jburse** [comment]
Maybe the problem is that variable_names is empty in the top-level:

![grafik](https://user-images.githubusercontent.com/5411487/44498733-94f66300-a680-11e8-8440-05e1d33d9981.png)

**Comment by JanWielemaker** [comment]
Clause info is based on lazy partial reexamining of the original sources.   These are not kept for `user` and I see little reason to change that.

**Comment by jburse** [comment]
Thats strange, you could just store the prolog_load_context(variable_names), together with a clause. Would eat up more memory, but well, memory is cheap. It would not be nessesary for clauses that are added via assertz/1. Of course the situation can get more involved if there are auxiliary clauses generated on the fly. But depending on what API is provided this shouldn't be either a problem.
