### ISSUE TITLE
new version udp_broadcast not respecting scope

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#324]
The new udp_broadcast is not respecting scope.
Test performed using two computers, 192.168.254.47, 16.04 Ubuntu and 7.7.18 installed via swivm, 
and 192.168.254.65 on a Raspberry Pi 3 on Raspbian/NOOBS using HEAD of 3 Aug 2018
compiled from source.

## terminal A, host 192.168.254.47
`
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.18)
?- udp_broadcast_initialize(ip(192,168,254,255), [scope(foobar)]).
true.
?- listen(baz(X), between(1,5, X)).
true.
`

## terminal B, host 192.168.254.47
`
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.18)
?- udp_broadcast_initialize(ip(192,168,254,255), [scope(dogword)]).
true.
?- listen(baz(X), between(42,48,X)).
true.
`

## terminal C, host 192.168.254.65
`
Welcome to SWI-Prolog (threaded, 32 bits, version 7.7.18-18-g82c1e95)
?- udp_broadcast_initialize(ip(192,168,254,255), [scope(dogword)]).
true.
?- findall(X, broadcast_request(udp(dogword, baz(X))), List).
List = [1, 42, 2, 43, 3, 44, 4, 5, 45|...].
`
*EXPECTED:* List=[43,43,44,45,46,47,48]
*OBSERVED:* List = [1, 42, 2, 43, 3, 44, 4, 5, 45|...].

**Comment by JanWielemaker** [comment]
Very old issue.  If I read this correctly, the observed behavior is simply due to UDP not obeying order and not guaranteeing anything arrives.  This notably shows if you flood the system with requests.  Closing.

**Comment by Anniepoo** [comment]
No, this definitely isn't due to UDP being unreliable. 
The behavior is quite consistent, though I haven't tested it in a couple years. 

The problem is that the **scope** option is ignored.

I've assigned to myself, and will attempt to fix soon.

**Comment by JanWielemaker** [comment]
Had a little look at the code.  Scopes do not directly define who is talking to who.  They merely allow setting up multiple UDP networks on the same process using udp_broadcast_service/2 and friends.  This allows a process to talk to two subnets, a subnet and multicast network or a unicast network, etc.

If anything, I guess the docs need to be more explicit about that from the start rather than somewhere deep down.

**Comment by Anniepoo** [comment]
Ah!  ok, yes, that could be more explicit
