### ISSUE TITLE
Memory leak in copy_stream_data/2

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#326]
For some files `copy_stream_code/2` uses a lot of memory (well over a gigabyte).  TWIUI `copy_stream_data/2` should not have a noticeable memory overhead since it is a streaming operation.  I'm suspecting a memory leak in this predicate.

I have published two text files that can be tested with the below Prolog script:
  - Calling `test_bad/0` uses well over 1GB of memory.
  - Calling `test_good/0` uses no noticeable amount of memory whatsoever, even though this file is comparable in size to the one that uses a lot of memory.

```prolog
:- use_module(library(http/http_open)).
:- use_module(library(zlib)).

http_open:redirect_code(307).

test_bad :-
  test_('https://demo.triply.cc/wouter/memory-leak/assets/5b72c6bda7caa8028f4e05bd').

test_good :-
  test_('https://demo.triply.cc/wouter/memory-leak/assets/5b72c6d3a7caa8028f4e05c0').

test_(Uri) :-
  http_open(Uri, In1, [status_code(Status)]),
  assertion(Status =:= 200),
  call_cleanup(
    setup_call_cleanup(
      (
        zopen(In1, In2, []),
        gzopen('copy.gz', write, Out)
      ),
      copy_stream_data(In2, Out),
      (
        close(In2),
        close(Out)
      )
    ),
    close(In1)
  ).
```

The redefinition of `http_open:redirect_code/1` is necessary, since the server uses a redirect code that is not yet supported by SWI (see https://github.com/SWI-Prolog/packages-http/pull/115).

The file used by `test_good/0` was created to be somewhat comparable to the file used by `test_bad/0`; it was generated by the following Prolog code:

```prolog
:- use_module(library(random)).
:- use_module(library(zlib)).

create_dummy_file :-
  setup_call_cleanup(
    gzopen('dummy.nq.gz', write, Out),
    forall(
      between(1, 1 431 150, _),
      (
        forall(
          between(1, 266, _),
          (
            random_between(32, 126, Code),
            put_code(Out, Code)
          )
        ),
        put_char(Out, '\n')
      )
    ),
    close(Out)
  ).
```

**Comment by JanWielemaker** [comment]
Fixed in the zlib package.   The `test_bad` file is the concatenation of many small zip files.  Unzipping is supposed to restart if the input is not complete, but the memory allocated by the previous decompression was not released.
