### ISSUE TITLE
(@)/2 should yield instantiation errors

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#336]
Sample query:

<pre>
?- @(_,_).
<b>ERROR: Out of local stack</b>
</pre>

In such cases, I expect the predicate to throw an **instantiation error** on the grounds that the goal is *not&nbsp;callable*.

Throwing such an error would also reduce surprises when using `in_temporary_module/3`:

<pre>
?- in_temporary_module(M, _, _).
<b>%@ ERROR: Stack limit (1.0Gb) exceeded
%@ ERROR:   Stack sizes: local: 0.8Gb, global: 0.1Gb, trail: 0Kb
%@ ERROR:   Stack depth: 3,355,350, last-call: 0%, Choice points: 4</b>
</pre>

**Comment by JanWielemaker** [comment]
That was a nasty one.  I think it is fixed with 5c17c451ecdaf6c7c11882849cd8748f51e7acca
