### ISSUE TITLE
SWI-Prolog crashes 

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#34]
On Windows 7 SP1
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.1.29-5-g0a3d88a)

https://github.com/eazar001/yesbot/commit/7bb15192f64a020e887c6d237bfe07b34554e990

Reliably crashes (about 75% of time - it's probably a race condition) SWI-Prolog. Attached is a screen shot of it dying.  
![prologcrash](https://cloud.githubusercontent.com/assets/146569/6084712/323ef252-ade8-11e4-9e64-3de1fe60a81f.png)

We're currently debugging yesbot, more info forthcoming with  https://github.com/eazar001/yesbot/issues/2

**Comment by JanWielemaker** [comment]
From the stack, this could be an attempt to join a detached thread that is dying.  Would that make sense?  Note that it is not allowed to join a detached thread (in fact, just about anything you try to
do with the handle of a detached thread is dangerous because it can terminate at any time).

**Comment by eazar001** [comment]
You are correct in assuming that there are detached threads present, however I don't attempt to make any joins at all. I'll see what else I might be doing to 'handle' these detached threads.

**Comment by Anniepoo** [comment]
on yesbot's end. https://github.com/eazar001/yesbot/issues/2
