### ISSUE TITLE
absolute_file_name/3 failing for directory

### ISSUE THREAD

**Issue by erlanger** [SWI-Prolog/swipl-devel#345]
SWI Prolog version 7.7.19

`absolute_file_name/3` fails for a directory while `absolute_file_name/2` works properly. 
The strange thing is that `access_file/2` works properly for that same directory.

Look at this session:

```prolog
44 ?- absolute_file_name('/tmp',X,[access(read)]).
ERROR: source_sink `'/tmp'' does not exist
ERROR: In:
ERROR:   [11] throw(error(existence_error(source_sink,'/tmp'),_2054))
ERROR:    [7] <user>
ERROR:
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.

45 ?- absolute_file_name('/tmp',X).
X = '/tmp'.

46 ?- shell('ls -ald /tmp').
drwxrwxrwt 20 root root 560 Oct 10 14:05 /tmp
true.

47 ?- access_file('/tmp',read).
true.

```

Very strange.

This bug breaks the `http_pwp.pl` handling of `index.pwp`, in such a way that the demo_pwp.pl fails to load properly from `localhost:5000` but it works if one says `localhost:5000/index.pwp`. It will break many other apps which use the `access(X)` option with a directory.

**Comment by pmoura** [comment]
Try instead:

```
?- absolute_file_name('/tmp',X,[access(read), file_type(directory)]).
X = '/tmp'.
```

From the documentation on the `file_type/1` option: "This predicate only returns non-directories, unless the option file_type(directory) is specified.".

**Comment by erlanger** [comment]
Then the code in [http_pwp.pl]( https://github.com/SWI-Prolog/packages-http/blob/539027338e9a43ed6e32d54aa64fb2e2a3a70d80/http_pwp.pl#L143) has a bug. Because it says:

```prolog
pwp_handler(QOptions, Request) :-
    [...]
    absolute_file_name(Term, Path, [access(read)]),
    [...]
```

And `Term` can certainly point to a directory as it does in the pwp examples.

**Comment by erlanger** [comment]
Thanks @pmoura, I'll submit a pull request to fix the http pwp handling.
Appreciate your quick reply.

**Comment by erlanger** [comment]
Will wait for pull request to be merged before closing issue...
Thanks!
