### ISSUE TITLE
SWI Output on Terminal can't be Piped to `less`

### ISSUE THREAD

**Issue by firefrorefiddle** [SWI-Prolog/swipl-devel#346]
I have this silly little dirwalker:

    dir_entry_rec(Dir, Entry) :-
        directory_files(Dir, Entries),
        member(Entry0, Entries),
        \+ member(Entry0, ['.', '..']),
        dir_entry_rec(Dir, Entry0, Entry).

    dir_entry_rec(Dir, Entry,  Dir-Entry).
    dir_entry_rec(Dir, Entry0, Entry) :-
        atomic_list_concat([Dir, '/', Entry0], Subdir),
        exists_directory(Subdir),
        \+ read_link(Subdir, _, _),
        catch(dir_entry_rec(Subdir, Entry),
    	  Error,
	          (writeln(Error), fail)).

    main :- foreach(dir_entry_rec('/home/mike', E), writeln(E)), halt.

    :- initialization(main).

I can run it on the terminal and also pipe some output: 

    $ swipl src/prolog/dirwalk.pl | nl 
         1	/home/mike- .gitconfig.mine
         2	/home/mike- .pam_environment
         3	/home/mike- .lesshst
         4	/home/mike- .xinputrc
         5	/home/mike- .emacs~
         6	/home/mike- .IdeaIC2018.2
         7 ...

Performance is quite good, BTW. I takes only twice as long as `find`. However, when I call it with 

     $ swipl src/prolog/dirwalk.pl | nl | less

Then the writeln seems not to block correctly until the write buffers empty or something like that. The first lines are displayed, and after pressing "q" on the keyboard to see the rest of the output, I get:

     $ swipl src/prolog/dirwalk.pl | nl |less

     ERROR: /home/mike/src/prolog/dirwalk.pl:18: Initialization goal raised exception:
     ERROR: writeln/1: I/O error in write on stream user_output (Broken pipe)
     Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.19)
     SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
     Please run ?- license. for legal details.

     For online help and background, visit http://www.swi-prolog.org
     For built-in help, use ?- help(Topic). or ?- apropos(Word).

     ERROR: I/O error in write on stream user_output (Broken pipe)
     ERROR: In:
     ERROR:    [8] ttyflush
     ERROR:    [7] '$history':prompt_history('~! ?- ') at /usr/lib/swi-prolog/boot/history.pl:153
     ERROR:    [6] '$history':read_history(h,'!h',[trace,end_of_file],'~! ?- ',_1710,_1712) at /usr/lib/swi-prolog/boot/history.pl:61
     ERROR: I/O error in write on stream user_output (Broken pipe)
     ERROR: In:
     ERROR:    [8] ttyflush
     ERROR:    [6] '$history':read_history(h,'!h',[trace,end_of_file],'~! ?- ',_5884,_5886) at /usr/lib/swi-prolog/boot/history.pl:61
     ERROR: 

This is swipl 7.7.19 on Ubuntu 18.04.

I think SWI is actually a really great scripting language, aside from little issues like that!

**Comment by JanWielemaker** [comment]
The main problem is that foreach/2 is a complicated predicate.  Then there is some stuff tio get arguments, signals and output correct.  Below is a nice version.  See docs for the various bits and pieces for the why.

```
:- use_module(library(main)).

dir_entry_rec(Dir, Entry) :-
    directory_files(Dir, Entries),
    member(Entry0, Entries),
    \+ member(Entry0, ['.', '..']),
    dir_entry_rec(Dir, Entry0, Entry).

dir_entry_rec(Dir, Entry,  Dir-Entry).
dir_entry_rec(Dir, Entry0, Entry) :-
    atomic_list_concat([Dir, '/', Entry0], Subdir),
    exists_directory(Subdir),
    \+ read_link(Subdir, _, _),
    catch(dir_entry_rec(Subdir, Entry),
	  Error,
          (print_message(error, Error), fail)).

main([File]) :-
    current_prolog_flag(argv, [File]),
    catch(forall(dir_entry_rec(File, E), writeln(E)),
          error(io_error(_,_), _), true).

:- initialization(main, main).
```

**Comment by firefrorefiddle** [comment]
Thank You!
