### ISSUE TITLE
how to get the intermediate unification result?

### ISSUE THREAD

**Issue by GraceGay** [SWI-Prolog/swipl-devel#347]
If I query 'ancestor(a,b)', the return is true or false, but I want to get the intermediate variable binding results, one of which may be 'father(a,c), father(c,b)', how can I do to achieve this?

**Comment by JanWielemaker** [comment]
Use the debugger.  See trace/0 and gtrace/0.   This is not a place for questions.  Please put these on the mailinglist or stackoverflow.
