### ISSUE TITLE
set_prolog_flag/2 has a small Windows file access check problem

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#351]
windows_file_access_check/2 option works with access-option and openclose-option, but gives an error when trying to set an filesecurity-option

 Welcome to SWI-Prolog (threaded, 32 bits, version 7.7.19-10-g8b9477530)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- set_prolog_flag(win_file_access_check,openclose).
true.

?- set_prolog_flag(win_file_access_check,access).
true.

?-  

?- set_prolog_flag(win_file_access_check,filesecurity).
ERROR: Domain error: `win_file_access_check' expected, found `filesecurity'
ERROR: In:
ERROR:    [8] set_prolog_flag(win_file_access_check,filesecurity)
ERROR:    [7] <user>
?- 
%

**Comment by JanWielemaker** [comment]
Thanks.  Must be `getfilesecurity` according to the implementation.  Fixed docs with 97e0e53415a4b2ea98b9a241b8dc262b3b7c420e
