### ISSUE TITLE
Library CHR cannot be used interactively

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#355]
I was using library(chr) from the top-level, and I noticed that it is not
usable interactively. I get the following result. The warnings are very
long and a little cryptic. Not sure what the should mean:

![grafik](https://user-images.githubusercontent.com/5411487/47738777-27644580-dc74-11e8-9d43-52cae348cfbd.png)

**Comment by jburse** [comment]
The same works for SICStus Prolog, except that it removes the old p,q. But
it doesn't show the same warnings:

![grafik](https://user-images.githubusercontent.com/5411487/47738809-3ba84280-dc74-11e8-80a4-2c583bb9285e.png)

**Comment by JanWielemaker** [comment]
The notion of compiling vs recompiling is poorly defined for [user].  If I recall well, it generates a pseudo filename for every [user] consult.   AFAIK you cannot load multiple CHR programs into the same module and thus you loose.  Use files.  That is what they are for.  Using SWISH is also a food alternative.
