### ISSUE TITLE
building foreign library in pack on macos 10.14 with xcode 10.1

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swipl-devel#357]
Building fails because of buildenv.sh:
the compiler set by bulindenv.sh
CC='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc'
LD='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc'
don't find stdio.h
setting CC=clang or CC=cc works.
Running 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -v 
and
cc -v
gives the same result so I don't know what is the problem
Moreover,
LDSOFLAGS=' -shared '
misses the library directory, as in
LDSOFLAGS=' -shared -L"/Users/rzf/lib/swipl/lib/x86_64-darwin/"'

**Comment by JanWielemaker** [comment]
Don't know about using `cc` from Xcode.app.  I did push two fixes to fix linking to `-lswipl`, which makes creating foreign packages work for me on MacOSX.   Not sure what do do about the `cc`.  I take the c compiler detected by `cmake`.  Possibly I should merely take the base name thereof?

On most modern systems `cc` should be just fine, I guess.  I'll give it some more thought before taking action.

**Comment by pmoura** [comment]
On macOS 10.14.1 (latest version) with the latest Xcode version:

```shell
20:41 $ ll `which cc`
lrwxr-xr-x  1 root  wheel  5 Sep 25 03:20 /usr/bin/cc -> clang
20:42 $ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Thus, using `cc` is using `clang` is using Xcode, at least by default.

**Comment by JanWielemaker** [comment]
Thanks.  I know all that.  Just, why is the one on $PATH working for Fabrizio and absolute path not?
@pmoura can you try `?- pack_install(environ).`    This is a very minimal package, but does check the basic linking of foreign code.   Should work (only) with the latest git version on MacOSX.

**Comment by pmoura** [comment]
```
20:42 $ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.21-3-g08fd7acf3-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- pack_install(environ).
% Contacting server at http://www.swi-prolog.org/pack/query ... ok
Install environ@1.0 from http://www.swi-prolog.org/download/pack/environ-1.0.tgz Y/n? 
% Contacting server at http://www.swi-prolog.org/pack/query ... ok
% "environ-1.0.tgz" was downloaded 30 times
Package:                environ
Title:                  Demo package with C code, fetching the program environment
Installed version:      1.0
Author:                 Jan Wielemaker <jan@swi-prolog.org>
Home page:              http://www.swi-prolog.org/howto/ForeignPack.html
Download URL:           http://www.swi-prolog.org/download/pack/environ-*.tgz
Install "environ-1.0.tgz" (1,084 bytes) Y/n? 
% /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -pthread -I"/Users/pmoura/lib/swipl/include"   -c -o c/environ.o c/environ.c
% mkdir -p lib/x86_64-darwin
% /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -shared -L"/Users/pmoura/lib/swipl/lib/x86_64-darwin" -o lib/x86_64-darwin/environ.so c/environ.o -lswipl
% make: Nothing to be done for `check'.
% make: Nothing to be done for `install'.
true.

?- use_module(library(environ)).
true.

?- environ(X).
X = ['MANPATH'='/Users/pmoura/Documents/Prolog/qp10.1/doc/man::/opt/local/share/man', 'TERM_PROGRAM'='Apple_Terminal', 'GEM_HOME'='/Users/pmoura/gems', 'ASDF_DIR'='/usr/local/opt/asdf', 'SHELL'='/bin/bash', 'TERM'='xterm-color', 'HISTSIZE'='10000', 'TMPDIR'='/var/folders/w9/0h2yhwgh8xj42v0059bpn5h00000gn/T/', ... = ...|...].
```

**Comment by friguzzi** [comment]
Thanks.
I have the same settings as Paulo. Paulo, does building a pack with a foreign language library work for you? Can you try bddem? If it works, then it's a problem with my installation of xcode

**Comment by pmoura** [comment]
```
?- pack_install(bddem).
% Contacting server at http://www.swi-prolog.org/pack/query ... ok
Install bddem@4.2.0 from GIT at https://github.com/friguzzi/bddem.git Y/n? 
% Cloning into '/Users/pmoura/lib/swipl/pack/bddem'...
% Contacting server at http://www.swi-prolog.org/pack/query ... ok
% "bddem.git" was downloaded 1 times
Package:                bddem
Title:                  A library for manipulating Binary Decision Diagrams
Installed version:      4.2.0
Author:                 Fabrizio Riguzzi <fabrizio.riguzzi@unife.it>
Download URL:           https://github.com/friguzzi/bddem/releases/*.zip
Run post installation scripts for pack "bddem" Y/n? 
% Found foreign libraries for target platform.
% Use ?- pack_rebuild(bddem). to rebuild from sources
true.

?- pack_rebuild(bddem).
% checking build system type... 
% x86_64-apple-darwin18.2.0
% checking host system type... 
% x86_64-apple-darwin18.2.0
...
% no check
% mkdir -p lib/x86_64-darwin/
% cp bddem.so lib/x86_64-darwin/
true.
```

**Comment by JanWielemaker** [comment]
Seems Fabrizio should first closely examine how `cc` and the broken one in Xcode.app are related.  First
 step is to check for links.  Next you may wish to add `-v` to the CC commandline which (I think) causes it to print the search process for include files (and more).

**Comment by friguzzi** [comment]
I reinstalled Xcode from scratch but I still get the same error. It's a problem of directory search but I don't know why I get the difference


Fabrizios-MBP:cudd-3.0.0 rzf$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc l.c -v
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.14.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name l.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0 -fdebug-compilation-dir /Users/rzf/lib/swipl/pack/bddem/cudd-3.0.0 -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.14.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/3b/x80h0q3d3v7059h38xbtccxh0000gn/T/l-f9a0bd.o -x c l.c
clang -cc1 version 10.0.0 (clang-1000.11.45.5) default target x86_64-apple-darwin18.2.0
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
l.c:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
Fabrizios-MBP:cudd-3.0.0 rzf$ cc -v l.c
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.14.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name l.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/usr/local/include -fdebug-compilation-dir /Users/rzf/lib/swipl/pack/bddem/cudd-3.0.0 -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.14.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/3b/x80h0q3d3v7059h38xbtccxh0000gn/T/l-acaf42.o -x c l.c
clang -cc1 version 10.0.0 (clang-1000.11.45.5) default target x86_64-apple-darwin18.2.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.14.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -o a.out /var/folders/3b/x80h0q3d3v7059h38xbtccxh0000gn/T/l-acaf42.o -L/usr/local/lib -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a

**Comment by friguzzi** [comment]
when I deleted xcode cc was not working, so it has reinstalled it but cc differs from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc that is called with the wrong search path

**Comment by JanWielemaker** [comment]
A C compiler that cannot find `stdio.h` is very close to broken ...  I have little clue what is going on and whether this is a local issue on your machine or it is mine and Paulo's having even more copies of `stdio.h` from older packages (according to `locate /stdio.h | wc`, my system has 50 copies ..)

The quick work-around is to put in `~/.swiplrc`

    :- set_prolog_flag(c_cc, cc).

Of course in the end we want to know whether this is a good default in general or not.  I'm tempted to think so.  On most platforms it doesn't matter to much which C compiler you use.  Only on Windows you may have to deal with MSVC or MinGW where MinGW uses mostly the Unix conventions ans MSVC is completely different.

**Comment by pmoura** [comment]
@friguzzi I assume you have installed also the command-line tools? If not, type in a shell `xcode-select --install`. You may need `sudo`. Also, do you accepted the Xcode license? If not (sure), type `sudo xcodebuild -license accept`.

**Comment by friguzzi** [comment]
My installation of Xcode is broken, I tried all suggestion by @pmoura with no luck. I will investigate further.

**Comment by friguzzi** [comment]
I don't understand then why building swipl does not give an error, running cmake I get
Fabrizios-MBP:build1 rzf$ cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -G Ninja 
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works

**Comment by friguzzi** [comment]
Instead I get
Fabrizios-MBP:cudd-3.0.0 rzf$ cat m.c
#include <stdio.h>

main()
{
printf("ciao");
}
Fabrizios-MBP:cudd-3.0.0 rzf$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc m.c 
m.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.

**Comment by pmoura** [comment]
```
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc m.c -v
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.14.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name m.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0 -fdebug-compilation-dir /Users/pmoura -ferror-limit 19 -fmessage-length 120 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.14.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/w9/0h2yhwgh8xj42v0059bpn5h00000gn/T/m-dfdbf6.o -x c m.c
clang -cc1 version 10.0.0 (clang-1000.11.45.5) default target x86_64-apple-darwin18.2.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
m.c:3:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
main()
^
1 warning generated.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.14.0 -o a.out /var/folders/w9/0h2yhwgh8xj42v0059bpn5h00000gn/T/m-dfdbf6.o -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a
```

**Comment by friguzzi** [comment]
Progessing: see
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes
command line tools-> new features
Probably @pmoura you have headers from previous versions of xcode, can you do
`ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
ls /usr/local/include
ls /usr/include`

**Comment by pmoura** [comment]
```
$ ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
FlexLexer.h	c++		swift
```

```
$ ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
__clang_cuda_builtin_vars.h		avx512vnniintrin.h			pkuintrin.h
__clang_cuda_cmath.h			avx512vpopcntdqintrin.h			pmmintrin.h
__clang_cuda_complex_builtins.h		avx512vpopcntdqvlintrin.h		popcntintrin.h
__clang_cuda_intrinsics.h		avxintrin.h				prfchwintrin.h
__clang_cuda_math_forward_declares.h	bmi2intrin.h				ptrauth.h
__clang_cuda_runtime_wrapper.h		bmiintrin.h				rdseedintrin.h
__stddef_max_align_t.h			cetintrin.h				rtmintrin.h
__wmmintrin_aes.h			clflushoptintrin.h			s390intrin.h
__wmmintrin_pclmul.h			clwbintrin.h				sanitizer
adxintrin.h				clzerointrin.h				shaintrin.h
altivec.h				cpuid.h					smmintrin.h
ammintrin.h				cuda_wrappers				stdalign.h
arm64intr.h				emmintrin.h				stdarg.h
arm_acle.h				f16cintrin.h				stdatomic.h
arm_fp16.h				float.h					stdbool.h
arm_neon.h				fma4intrin.h				stddef.h
armintr.h				fmaintrin.h				stdint.h
avx2intrin.h				fxsrintrin.h				stdnoreturn.h
avx512bitalgintrin.h			gfniintrin.h				tbmintrin.h
avx512bwintrin.h			htmintrin.h				tgmath.h
avx512cdintrin.h			htmxlintrin.h				tmmintrin.h
avx512dqintrin.h			ia32intrin.h				unwind.h
avx512erintrin.h			immintrin.h				vadefs.h
avx512fintrin.h				intrin.h				vaesintrin.h
avx512ifmaintrin.h			inttypes.h				varargs.h
avx512ifmavlintrin.h			iso646.h				vecintrin.h
avx512pfintrin.h			limits.h				vpclmulqdqintrin.h
avx512vbmi2intrin.h			lwpintrin.h				wmmintrin.h
avx512vbmiintrin.h			lzcntintrin.h				x86intrin.h
avx512vbmivlintrin.h			mm3dnow.h				xmmintrin.h
avx512vlbitalgintrin.h			mm_malloc.h				xopintrin.h
avx512vlbwintrin.h			mmintrin.h				xsavecintrin.h
avx512vlcdintrin.h			module.modulemap			xsaveintrin.h
avx512vldqintrin.h			msa.h					xsaveoptintrin.h
avx512vlintrin.h			mwaitxintrin.h				xsavesintrin.h
avx512vlvbmi2intrin.h			nmmintrin.h				xtestintrin.h
avx512vlvnniintrin.h			opencl-c.h
```

```
$ ls /usr/local/include 
Magick++		gettext-po.h		ltdl.h			sgml			tclTomMathDecls.h
Magick++.h		graphviz		magick			sql.h			tdbc.h
Yap			itcl.h			mysqlStubs.h		sqlext.h		tdbcDecls.h
autosprintf.h		itcl2TclOO.h		ntfs			sqlspi.h		tdbcInt.h
autotest.h		itclDecls.h		ntfs-3g			sqltypes.h		tk.h
ciao_prolog.h		itclInt.h		odbcStubs.h		sqlucode.h		tkDecls.h
fakemysql.h		itclIntDecls.h		odbcinst.h		tcl.h			tkPlatDecls.h
fakepq.h		itclMigrate2TclCore.h	odbcinstext.h		tclDecls.h		uninameslist.h
fakesql.h		itclTclIntStubsFcn.h	osxfuse			tclOO.h			unixodbc_conf.h
freetype2		libintl.h		png.h			tclOODecls.h		uodbc_extras.h
ft2build.h		libltdl			pngconf.h		tclPlatDecls.h		uodbc_stats.h
fuse			libpng12		pqStubs.h		tclThread.h		wand
fuse.h			libwmf			pteid			tclTomMath.h		yaml.h
```

```
$ ls /usr/include
AppleTextureEncoder.h	curl			ldap.h			panel.h			stringlist.h
AssertMacros.h		curses.h		ldap_cdefs.h		paths.h			strings.h
Availability.h		cxxabi.h		ldap_features.h		pcap			struct.h
AvailabilityInternal.h	db.h			ldap_schema.h		pcap-bpf.h		sys
AvailabilityMacros.h	default_pager		ldap_utf8.h		pcap-namedb.h		sysdir.h
Block.h			device			ldif.h			pcap.h			sysexits.h
CommonCrypto		dirent.h		libc.h			pexpert			syslog.h
ConditionalMacros.h	disktab.h		libcharset.h		php			tar.h
Darwin.apinotes		dispatch		libexslt		poll.h			tcl.h
MacTypes.h		dlfcn.h			libgen.h		printerdb.h		tclDecls.h
NSSystemDirectories.h	dns.h			libkern			printf.h		tclPlatDecls.h
TargetConditionals.h	dns_sd.h		libproc.h		profile.h		tclTomMath.h
Xplugin.h		dns_util.h		libunwind.h		protocols		tclTomMathDecls.h
__cxxabi_config.h	dtrace.h		libxml2			pthread			term.h
__wctype.h		editline		libxslt			pthread.h		term_entry.h
_ctype.h		err.h			limits.h		pthread_impl.h		termcap.h
_locale.h		errno.h			localcharset.h		pthread_spis.h		termios.h
_regex.h		eti.h			locale.h		pwd.h			tgmath.h
_stdio.h		execinfo.h		mach			python2.7		tic.h
_types			expat.h			mach-o			ranlib.h		tidy
_types.h		expat_external.h	mach_debug		readline		time.h
_wctype.h		fcntl.h			machine			readpassphrase.h	timeconv.h
_xlocale.h		fenv.h			malloc			regex.h			tk.h
aio.h			ffi			math.h			removefile.h		tkDecls.h
aliasdb.h		float.h			membership.h		resolv.h		tkIntXlibDecls.h
alloca.h		fmtmsg.h		memory.h		rpc			tkMacOSX.h
apache2			fnmatch.h		menu.h			rpcsvc			tkPlatDecls.h
apr-1			form.h			miscfs			rune.h			ttyent.h
ar.h			fsproperties.h		module.modulemap	runetype.h		tzfile.h
architecture		fstab.h			monetary.h		sandbox.h		ucontext.h
arpa			fts.h			monitor.h		sasl			ulimit.h
asl.h			ftw.h			mpool.h			sched.h			unctrl.h
assert.h		get_compat.h		nameser.h		search.h		unistd.h
atm			gethostuuid.h		nc_tparm.h		secure			unwind.h
bank			getopt.h		ncurses.h		security		util.h
bitstring.h		glob.h			ncurses_dll.h		semaphore.h		utime.h
bootparams.h		grp.h			ndbm.h			servers			utmp.h
bootstrap.h		gssapi			net			setjmp.h		utmpx.h
bsm			gssapi.h		net-snmp		sgtty.h			uuid
bzlib.h			hfs			netdb.h			signal.h		vfs
c++			histedit.h		netinet			simd			vis.h
cache.h			i386			netinet6		slapi-plugin.h		voucher
cache_callbacks.h	iconv.h			netkey			spawn.h			vproc.h
checkint.h		ifaddrs.h		nfs			sqlite3.h		wchar.h
com_err.h		inttypes.h		nl_types.h		sqlite3ext.h		wctype.h
complex.h		iso646.h		nlist.h			stab.h			wordexp.h
compression.h		kern			notify.h		standards.h		xar
copyfile.h		krb5			notify_keys.h		stddef.h		xattr_flags.h
corpses			krb5.h			ntsid.h			stdint.h		xlocale
cpio.h			langinfo.h		objc			stdio.h			xlocale.h
crt_externs.h		launch.h		odmodule		stdlib.h		xpc
ctype.h			lber.h			opendirectory		strhash.h		zconf.h
cups			lber_types.h		os			string.h		zlib.h
```

**Comment by JanWielemaker** [comment]
I think the picture becomes clear.  I'm tempted to simply set the C compiler to `cc`.  That works on most platforms and is AFAIK also what `make` does.  If you want a different compiler simply set the `c_cc` flag in your `~/.swiplrc`.  Not sure what to do on Windows.  Possibly we can figure out what is installed at runtime.

Does that make sense?

**Comment by friguzzi** [comment]
@JanWielemaker I think that would work on Mac and also on Windows if you compile with mingw (but to compile with mingw I had to comment the line setting the PATH in buildenv.sh).
Or get the right compiler options from cmake, but I don't know  how

**Comment by JanWielemaker** [comment]
Closing as too old, mostly resolved and probably no longer relevant.
