### ISSUE TITLE
swipl -v not working with 7.7

### ISSUE THREAD

**Issue by fnogatz** [SWI-Prolog/swipl-devel#362]
Hi Jan,

I built versions 7.7 using [swivm](https://github.com/fnogatz/swivm). Everything works as expected, besides that the `swipl -v` short flag has no effect:

```sh
> swipl -v    
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.22)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

    CMake built from "/home/fnogatz/.swivm/versions/7.7.22/build"

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- 
```

With `swipl --version` the output is correct:

```sh
> swipl --version
SWI-Prolog version 7.7.22 for x86_64-linux
```

I tried versions `7.7.{16,19,21,22}`, none is working with `-v`. With `7.6.4` it works as expected.

**Comment by JanWielemaker** [comment]
swipl 7.6.4 also allows for `--version`.  This was part of a general cleanup of flags and initialization.
If there are still references to `-v`, please let me know,

**Comment by fnogatz** [comment]
I know that I can always use `--version`. Howerver, it is still pointed to at the CLI help:

```sh
> swipl --help
swipl: Usage:
    1) swipl [options] prolog-file ... [-- arg ...]
    2) swipl [options] [-o executable] -c prolog-file ...
    3) swipl --help     Display this message (also -h)
    4) swipl --version  Display version information (also -v)
...                                                 ^^^^^^^^^
```

**Comment by JanWielemaker** [comment]
Thanks.  removed.   Guess this can be closed.
