### ISSUE TITLE
plunit

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swipl-devel#364]
Jan,
did you change something in package plunit?
On Swipl 7.7.21-5-gb78e03b48

I get when running `library(cplint_test/pita)`

```l
ERROR: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:16:
	catch/3: Undefined procedure: plunit_coin:pita/0
Warning: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:16:```

It seems that pita/0 is not term_expanded by the pita module

**Comment by friguzzi** [comment]
Problem:
if I define the term_expansion in system in pita I get

```
?- [library(examples/coin)].
true.

?- prob(heads(coin),P).
ERROR: Undefined procedure: heads/3
ERROR:   However, there are definitions for:
ERROR:         heads/1
ERROR: 
ERROR: In:
ERROR:   [18] heads(coin,141264,_1834)
```
If i define them in module pita I get
```
?- [library(examples/coin)].
ERROR: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:16:
	catch/3: Undefined procedure: pita/0
Warning: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:16:
	Goal (directive) failed: user:pita
ERROR: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:19:
	catch/3: Undefined procedure: begin_lpad/0
Warning: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:19:
	Goal (directive) failed: user:begin_lpad
ERROR: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:21:
	No permission to modify static procedure `(;)/2'
	Defined at /Users/rzf/lib/swipl/boot/init.pl:218
ERROR: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:24:
	No permission to modify static procedure `(;)/2'```

Shall I move the pack folder?

**Comment by friguzzi** [comment]
By keeping user in term_expansions, examples work individually but not in plunit, I get
```
ERROR: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:16:
	catch/3: Undefined procedure: plunit_coin:pita/0
Warning: /Users/rzf/lib/swipl/pack/cplint/prolog/examples/coin.pl:16:```
```
It seems that pita/0 is not term_expanded by the pita module

**Comment by JanWielemaker** [comment]
It is probably wise to resolve this issue as people may have packs everywhere.   Should work fine to move to system, unless some other handler in user is interfering.  As is, expansion is a chain of transformations by modules.  This follows the default module notion, so it is typically `(test unit)/user module[/user]/system`.  In each module, the first solution of term_expansion/2 is used.

**Comment by friguzzi** [comment]
If I use system clauses don't get expanded, I get

ERROR: /Users/rzf/lib/swipl/pack/cplint/prolog/cplint_test/test_pita.pl:240:
	test r_d: received error: plunit_simpson:'$goal0'/2: Undefined procedure: plunit_simpson:recovery/2
  However, there are definitions for:
        plunit_simpson:recovery/0

meaning that recovery/0 is not expanded to recovery/2

**Comment by JanWielemaker** [comment]
All I can advice is to put some debug statements in the rules to see what is fired when.  I think you can also trace through expand_term/2 and get the user code in the tracer.   Term expansion isn't trivial to debug though.

**Comment by friguzzi** [comment]
My term_expansion rules fail because of this call

`apply_macros:expand_apply((multifile'$tabled'/1), _5838, _5840, _5842) `

which however is not in my code, is it from plunit?

**Comment by friguzzi** [comment]
The problem is due to a predicate to_table that is called by my term_expansion rules for expanding tabling directive generated by me, the predicate calls system:term_expansion

```
to_table(M,Heads,ProcTabDir,Heads1):-
  maplist(tab_dir(M),Heads,TabDirList,Heads1L),
  append(TabDirList,TabDir),
  maplist(system:term_expansion,TabDir,ProcTabDirL),
  append(ProcTabDirL,ProcTabDir),
  append(Heads1L,Heads1).
```

**Comment by friguzzi** [comment]
Solved, it was a bug in my code, thanks Jan

**Comment by JanWielemaker** [comment]
Great!
