### ISSUE TITLE
Feature request, paging of help text

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#372]
I just typed `?- help(xpath).` The output goes very fast, and its longer
than the scroll buffer. So I don't see everything. 

The usual unix man pager stops after one page, and asks for more. 
Wouldn't something similar be possible for SWI-Prolog?

Or whats the workaround, is there a ghelp, graphic help, which
shows the help online documentation as before?

![image](https://user-images.githubusercontent.com/5411487/48946337-a96f2380-ef2d-11e8-89f9-52115d6dffb4.png)

**Comment by erlanger** [comment]
There is a `help_pager` prolog flag. Check it out.

**Comment by jburse** [comment]
On Windows 10, the following has no effect:

```
?- set_prolog_flag(help_pager, more()).
true.
```

**Comment by jburse** [comment]
Submitted solution, use SWI7 before release 7.7.20?

**Comment by JanWielemaker** [comment]
There you had no online help for `xpath` at all.  

See https://github.com/SWI-Prolog/swipl-devel/tree/master/src/win32/console

You probably need `regedit`, although we can also bind this to some Prolog predicate.
