### ISSUE TITLE
PORT: Android NaN

### ISSUE THREAD

**Issue by erlanger** [SWI-Prolog/swipl-devel#373]
Investigating the NaN problem in Android/Arm discussed in #358.

Where are the CMake variables `WORDS_BIGENDIAN` and `FLOAT_WORDSBIGENDIAN` defined?
I can see in `src/config.h.cmake`
```c
#cmakedefine FLOAT_WORDS_BIGENDIAN @FLOAT_WORDS_BIGENDIAN@
```
but can't find where cmake defines this.

**Comment by erlanger** [comment]
Okay, I found out what the problem is. There is no problem per se with the prolog code, **but the test is ignoring the sign bit**, which is left after the exponent is changed to 0x3ff. 

Even in the same machine the `nan` representation can change, but the exponent is always 0x7ff. When you take the bias off, and set the exponent to 0x3ff you end up with a number between 1 and 2, but it **can be negative**.

This is because a double is represented like this:
[`SEEEEEEEEEEEMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`](https://stackoverflow.com/questions/4353580/android-smali-question)

The `S` is the sign bit, 0 is positive, 1 is negative. 
`E` is the 2 base exponent.
`M` is the Mantissa. 

When the double becomes a `NaN` the exponent is 0x7ff and the rest can change in a myriad of ways. 

In order to test I ran the following program in three architectures:
```c
#include <stdio.h>
#include <stdlib.h>

void print_bytes(double d, const char* name) {
  union nanu {
    double d;
    unsigned char bytes[8];
  };
  union nanu u;
  u.d = d;

  printf("\"%s\" %lf :\t", name, d);
  for (int i = 0; i < 8; ++i) {
    printf("%02x,",u.bytes[i]);
  }
  printf("\n");
}

double zero_div_zero() { return 0l/0l; };

int main()
{
  print_bytes(0.0l/0.0l, "0.0/0.0");
  print_bytes(strtod("NaN",NULL), "strtod(\"NaN\",0)");
}
```
Here is the output for the different architectures:

```
x86-64
---------------
"0.0/0.0"           -nan :      00,00,00,00,00,00,f8,ff,
"strtod("NaN",0)"    nan :      00,00,00,00,00,00,f8,7f,

Android 5/Arm
--------------------
"0.0/0.0"            nan :      00,00,00,00,00,00,f8,7f,
"strtod("NaN",0)"    nan :      ff,ff,ff,ff,ff,ff,ff,ff,

Raspberry Pi/Arm
-----------------------
"0.0/0.0"            nan :      00,00,00,00,00,00,f8,7f,
"strtod("NaN",0)"    nan :      00,00,00,00,00,00,f8,7f,
```

1st column: expression used to generate the NaN.
2nd column: how the C library prints the NaN (with `printf`)
3rd column: The actual bytes in memory

As you can see, for the representation for some NaNs can change even in the same architecture (but they all have 0x7ff as the exponent). You can see that in the x86_64 the `0/0` NaN has a negative sign, while the `strtod` NaN has a positive sign. The prolog code uses `strtod` expression to generate the NaN.

Solution
-----------
I'll fix the test so that it accepts negative numbers.

NB: I still don't know how `WORDS_BIGENDIAN` and `FLOAT_WORDS_BIGENDIAN`  are generated by cmake, would love to hear your answer (although this is not the cause of the NaN problem).

**Comment by JanWielemaker** [comment]
Seems `FLOAT_WORDS_BIGENDIAN` is defined by `src/ac/ax_c_float_words_bigendian.m4` which is now deleted but used to do this for autoconf.    Must be ported to CMake.  `WORDS_BIGENDIAN` is set by the autoconf macro `AC_C_BIGENDIAN`.  Need to figure out how that is handled in CMake.

**Comment by erlanger** [comment]
I was thinking how to do define endianness in a cross-compiling environment without a usable emulator. An option is to use the c preprocessor doing something like this (copied from ieee754.h):
```c
#include <features.h>
#include <endian.h>
#if     __BYTE_ORDER == __BIG_ENDIAN
#   error "define WORDS_BIGENDIAN"        
#endif                          /* Big endian.  */
#if     __BYTE_ORDER == __LITTLE_ENDIAN
# if    __FLOAT_WORD_ORDER == __BIG_ENDIAN
#   error "define FLOAT_WORDS_BIGENDIAN"                
# endif
#endif         

```

Using the output from the `#error` directive to determine what flag to set. This will work in the crosscompiling environment without any emulator.

**Comment by JanWielemaker** [comment]
I'm not convinced this is a good idea.  There is nothing related to the `features.h`, `endian.h` or `ieee754.h` documentation that tells us we can expect these macros an their `__` name also indicates we cannot rely on these.   Of course we can use this on Android.     We can be fairly sure if the
macros `__BYTE_ORDER`, `__BIG_ENDIAN` and `__LITTLE_ENDIAN` are defined that the above
works.  Note that `endian.h` might be in various places on various OSes, but on Linux it consumes these macros rather than producing them.

I'll investigate a little more.

**Comment by JanWielemaker** [comment]
Included standard cmake test providing `WORDS_BIGENDIAN` and copied float tests from https://github.com/ntamas/unibinlog (MIT license).  This, like the old autoconf test I used is based on the idea to compile a program with a magic float embedded and check that the binary contains some bit pattern.

Please close if this works for Android.
