### ISSUE TITLE
Bogus var_branches error

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#376]
1. I can't suppress the message using :`- style_check(-var_branches).`
2. The error message is bogus.

Version 7.7.22

This generates an error message: `Singleton variable in branch: X`

```
foo(In) :-
    (  bar(In, X)
    -> zot1(X)
    ;  zot2(X)
    ).

```

**Comment by pmoura** [comment]
Why do you say that the warning is bogus? `X` is a singleton variable in the *else*  branch.

**Comment by kamahen** [comment]
You're right ... it took me a few minutes to see why. (And I've even had my coffee today.)

But I still want to be able to suppress the message. ;)

**Comment by kamahen** [comment]
PS: This came from trying to isolate a weird bug, by rewriting `setup_call_cleanup/3` where setup was `catch(open(Path, read, Stream), _, fail)`  and cleanup was `catch(close(Stream), _, true)`.

**Comment by JanWielemaker** [comment]
You can only disable all singleton checking.  I do not see much reason to only switch of the semantic version.

**Comment by kamahen** [comment]
Is there any point in having the var_branches style check? It seems that it's completely controlled by singleton checking.

**Comment by JanWielemaker** [comment]
It does something different.  It checks that if you use a variable _after_ a branch it is introduced in
all branches (or none).   I.e., it warns against

```
    (   X = 1
    ;   true
    ),
    Y is X + 1.
```

It is by default disabled though as it is quite common for a branch to fail or throw an exception.
