### ISSUE TITLE
exists_file(File) not same as access_file(File, exist)

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#378]
The [documentation](http://www.swi-prolog.org/pldoc/doc_for?object=exists_file/1) states that `exists_file(File)` is the same as `access_file(File, exist)`. 
For a directory, this is not true:

```
?- exists_file('/tmp').
false.

?- access_file('/tmp', exist).
true.
```

The first sentence "True if File exists and is a regular file." seems to imply that directories should fail `exists_file/1`. So, the documentation might be wrong.

**Comment by JanWielemaker** [comment]
Indeed a documentation error.  Thanks. Should be fixed with 0303f875b55737e63dd6b0576470fe8caa85e7dd
