### ISSUE TITLE
absolute_file_name/3 documentation is poor for directory option

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#379]
The sentence "This predicate only returns non-directories, unless the option file_type(directory) is specified." is under file_type(Type).

I think it would be better if this sentence were in the full description of the predicate. (It took me a bit of searching ... for example, I would have expected access(execute) to have worked for directories, given Unix file semantics.)

**Comment by JanWielemaker** [comment]
Thanks.  Improved.  Not sure what you mean with access(execute):

    ?- absolute_file_name(., P, [file_type(directory),access(execute)]).
    P = '/home/janw/src/swipl-devel/linux'

**Comment by kamahen** [comment]
By "access(execute)" I meant that most directories have "x" set to allow access to the file information - "access(read)" only allows reading the file names.
https://en.wikipedia.org/wiki/File_system_permissions#Permissions
https://www.hackinglinuxexposed.com/articles/20030424.html

**Comment by JanWielemaker** [comment]
I know.  Using access(execute) with directories is not that meaningful.  Ideally one would abstract to a higher level ...   I don't think it is worth spending more time though.

**Comment by kamahen** [comment]
Agreed.
I have confirmed that `absolute_file_name(foo, P, [file_type(directory), access(execute)])` works as expected if the directory doesn't have the "execute" bit set.
