### ISSUE TITLE
pack_install with manual invalid answer selection prints "Warning: Unknown message: menu(reply(1,2))"

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/swipl-devel#38]
This happens when you select out of range answer (3) for a question like:

```
Select download location for hello@0.0.1
   (1) * http://files.dropbox.com/u/1397729/projects/pack/hello-0.0.1.zip
   (2)   Cancel
```

Happens with 7.1.29 and possibly with earlier too.

**Comment by JanWielemaker** [comment]
Earlier, sure.  Was broken from the start.  Fixed in 147828b384b2b9783f3debc07c5c31d085914d0b
