### ISSUE TITLE
Warning message during 'make' in CLI.

### ISSUE THREAD

**Issue by likelion** [SWI-Prolog/swipl-devel#386]
Since 7.7.2x I noticed a strange warning appearing after I use CLI in a plain terminal on MacOS for a while in a mixed REPL and graphical (XPCE in XQuartz) debugging mode, and then issue `make` command to consult changed files:

```
?- make.
% Updating GIT version stamps in the background.
Warning: The predicates below are not defined. If these are defined
Warning: at runtime using assert/1, use :- dynamic Name/Arity.
Warning:
Warning: emacs_application:emacs_chrome_server/0, which is referenced by
Warning: 	/usr/local/Cellar/swipl/7.7.25/lib/swipl/xpce/prolog/lib/emacs/application.pl:351:4: emacs->chrome_server
true.
```

If I restart `swipl` and run `make` immediately it works fine, but after several REPL actions the warning appears again.

**Comment by JanWielemaker** [comment]
Thanks.   Seems that something in your config tells `list_undefined/1` to  also scan the libraries.  Pushed a fix, making all silent again.
