### ISSUE TITLE
pack_install/2: package_directory option is not applied to dependencies

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/swipl-devel#39]
Can be tested with:

```
pack_install(julian, [package_directory('/tmp/pack-test-location')]).
```

Package julian is installed to /tmp/pack-test-location but dependencies delay, list_util and typedef are installed to ~/lib/swipl/pack.

**Comment by JanWielemaker** [comment]
Fixed in d86e0d9fef2a4e76f0c4c4ad93ca4b44191534ec.  The value is limited though as the pack system cannot really deal with packs in multiple locations.  I think this can only be used meaningfully to populate a pack directory from a Prolog installation that has no packages installed elsewhere.
