### ISSUE TITLE
pack_remove/1 should not try to delete contents from symlinked directories

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/swipl-devel#40]
pack_remove uses delete_directory_and_contents/1 which descends into symlinked directories and attempts to delete their contents. Packs from tar and git sources could contain symlinks. Symlinks should be removed but not their targets.

I would add a big warning to delete_directory_and_contents/1 documentation about symlinks too.

**Comment by JanWielemaker** [comment]
Oops.  Rather than warning the user in the documentation nobody reads, I decided to make the
behaviour consistent with rm -r, where symlinks are deleted, but deletion does not recurse into
symlinks.  Pushed.
