### ISSUE TITLE
Strange predicate duplicates in online docu

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#401]
I am little bit at loss. Are there two modules gui_tracer?

![bildschirmfoto 2019-01-03 um 05 28 03](https://user-images.githubusercontent.com/5411487/50623680-a72eba80-0f18-11e9-9b35-517a181af296.png)

**Comment by JanWielemaker** [comment]
Old bug in documentation server.

**Comment by JanWielemaker** [comment]
That was fixed long ago, but this was documented in two places.  Fixed.
