### ISSUE TITLE
http is missing files

### ISSUE THREAD

**Issue by DennisMitchell** [SWI-Prolog/swipl-devel#402]
http seems to be missing a pair of files:

* packages/http/figs/httpserver.pdf
* packages/http/figs/httpserver.png

`make` fails with

```[ 78%] Generating figs/httpserver.png
Error copying file (if different) from "/opt/prolog-swi/build/packages/http/figs/httpserver.png" to "figs/httpserver.png".
make[2]: *** [packages/http/CMakeFiles/http.doc.html.dir/build.make:198: packages/http/figs/httpserver.png] Error 1
make[1]: *** [CMakeFiles/Makefile2:5384: packages/http/CMakeFiles/http.doc.html.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

and, after creating a dummy file to keep the build going, with

```[ 79%] Generating figs/httpserver.pdf
Error copying file (if different) from "/opt/prolog-swi/build/packages/http/figs/httpserver.pdf" to "figs/httpserver.pdf".
make[2]: *** [packages/http/CMakeFiles/http.doc.html.dir/build.make:194: packages/http/figs/httpserver.pdf] Error 1
make[1]: *** [CMakeFiles/Makefile2:5384: packages/http/CMakeFiles/http.doc.html.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by JanWielemaker** [comment]
Oops.  The figure was deleted from the sources as it is outdated and wrong, but it was still in CMakeLists.txt.   Removed.   Thanks.

**Comment by DennisMitchell** [comment]
I tried again, but I'm still getting the same errors.

**Comment by JanWielemaker** [comment]
did you run cmake?  Also, this is the HTTP package, so you need git pull and git submodule update.

**Comment by JanWielemaker** [comment]
A `git grep httpserver` revealed some more traces.  Removed.   Sorry ... A fresh clone is a bit of an overkill.  See notable `git reset --hard` and `git clean -xfd` to make sure a git tree is completely consistent with the origin.

**Comment by DennisMitchell** [comment]
It's working now. Thanks!

Deleting everything is just a habit. I have build scripts for 467 programming languages and the `rm -rf` approach works for all of them.
