### ISSUE TITLE
Subtle error in listing dcg rules

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#403]
Just by accident, I stepped over this little bug. I was investigating whether the debugger <DCG...> is also seen during listing. So I used the following DCG rule:

![unbenannt](https://user-images.githubusercontent.com/5411487/50692617-cfabd700-1034-11e9-953a-da6a49cf1b72.PNG)

When I consult the above text, and then do a listing inside SWI-Prolog the listing result is wrong. It does show a closed list [X] and a check A=[]. That it is wrong is seen when using clause/2:

![image](https://user-images.githubusercontent.com/5411487/50692659-f10cc300-1034-11e9-8e32-545baf7e7bb1.png)

As the screenshot shows I tested with version 7.7.25. Maybe I should upgrade.

**Comment by jburse** [comment]
Here is a comparison with GNU Prolog:

![image](https://user-images.githubusercontent.com/5411487/50692889-a17ac700-1035-11e9-9926-3e4ce3fa6dbc.png)

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 3845cb6a04ef009fa9e160bbf9262da18c1cece7.  Please stop including images for things where you can copy/paste the text.   That makes Google find the content and allows me to copy/paste rather than retype programs.

**Comment by jburse** [comment]
You could use OCR in case you really want to have plain text from some images.
OmniPage Ultimate is a nice product. https://en.wikipedia.org/wiki/OmniPage

**Comment by wouterbeek** [comment]
![screenshot from 2019-01-04 19-03-53](https://user-images.githubusercontent.com/1685012/50703157-86b74b00-1053-11e9-97b1-45f18eb59304.png)
