### ISSUE TITLE
Feature request: reversible atomic_list_concat/[2,3] with empty separator

### ISSUE THREAD

**Issue by jariazavalverde** [SWI-Prolog/swipl-devel#405]
SWI Prolog throws an instantiation error when you call to `atomic_list_concat/2` with the first argument being a variable. Same for `atomic_list_concat/3` with an empty separator.

![captura de pantalla de 2019-01-08 01-50-12](https://user-images.githubusercontent.com/5055295/50802715-d3b34f80-12e7-11e9-9e8d-d24183620443.png)

Perhaps it makes more sense to split the atom into characters instead of throwing an exception.

![seleccion_072](https://user-images.githubusercontent.com/5055295/50803051-4bce4500-12e9-11e9-8d37-b48207c180e1.png)

In fact, this is the behaviour of the `split` function in other languages, like JavaScript:

```js
console.log("abc,def".split(",")); // ["abc","def"]
console.log("abc,def".split("")); // ["a","b","c",",","d","e","f"]
```

**Comment by JanWielemaker** [comment]
The atomic_list_concat/2,3 come from a standardisation initiative called Prolog Commons, which defined the predicate a single moded.  atomic_list_concat/3 splits in SWI-Prolog for historical reasons.  Given the fact that the left hand is a list of _atomic_ values, the split is ambigous and hence dubious:

    ?- atomic_list_concat([a, 2], ' ', X),
       atomic_list_concat(L, ' ', X).
    X = 'a 2',
    L = [a, '2'].

I.e., the predicate doesn't do a proper roundtrip.   More sensible is the string variant derived from ECLiPSe providing atomics_to_string/3 and split_string/4.  Now we still have a problem:

    ?- split_string("hello", "", "", L).
    L = ["hello"].

And 

    ?- atomic_list_concat(L, '', hello).
    ERROR: Domain error: `non_empty_atom' expected, found `'''

Neither of this is what JavaScript does.  I'm not entirely sure whether that is good or bad.  Splitting over the empty string seems a little ambiguous to me.  Prolog has the ISO atom_chars/2 if you want to split an atom into its characters.

Possibly the cleanest solution is to add split_atom/4 after split_string/4 and raise a domain error on an empty separator.  I'll point the ECLiPSe people at this thread.

**Comment by jburse** [comment]
I think atom_split/3 is also a candidate. From the naming atomic_list_concat, it should parse numbers. But it doesn't do at the moment in SWI-Prolog:

Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.25)

?- atomic_list_concat([1,2,3],', ',X).
X = '1, 2, 3'.

?- atomic_list_concat(X,',','1,2,3').
X = ['1', '2', '3'].

**Comment by jburse** [comment]
Prolog commons suggests:

**atom_split(+Atom, +Delimiter, ?Subatoms)**
Split Atom over Delimiter and unify the parts with Subatoms.

**Comment by jburse** [comment]
Does SWI-Prolog have atom_replace/4 ?

If you Prolog system has atom_split/3, you can bootstrap 
atom_replace/4 from it. You need a bidrectional version of it. 
Namely you can then define:

atom_replace(Source, Old, New,Target) :-
    atom_split(Source, Old, List),
    atom_split(Target, New, List).

This is an atom replace without going regex. Here are 
some example runs:

?- atom_replace('1\\2\\3','\\','/',X).
X = '1/2/3'

?- atom_replace('s/t/a/c/k', '/', '\\', X), write(X), nl.
s\t\a\c\k
X = 's\\t\\a\\c\\k'
