### ISSUE TITLE
cmake based build misses submodule init

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#407]
Perhaps related to #79 ?

cmake version [6806f413](https://github.com/SWI-Prolog/swipl-devel/commit/59f48b0f8a73a5db9453b7fe629837b86806f413) doesn't pull submodules.

swivm unload
git clone 
cd swipl-devel
mkdir build
cd build
cmake ..

 Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Check floating point format
-- Check floating point format - IEEE-754, little endian
-- The following SWI-Prolog packages are disabled because the required sources are not installed:
chr clib clpqr inclpr cpp http ltx2htm nlp paxos PDT pengines pldoc plunit protobufs RDF semweb sgml table utf8proc zlib archive odbc cql bdb pcre yaml jpl ssl tipc swipl-win xpce libedit readline
Use one of the commands below to add all packages or specific packages

   git -C .. submodule update --init  
   git -C .. submodule update --init packages/<pkg>

-- Added packages  ltx2htm pldoc nlp: required for online documentation.  Use -DINSTALL_DOCUMENTATION=OFF to avoid this dependency
-- Added packages  clib: Required by package ltx2htm
-- Added packages  http pengines sgml: Required by package pldoc
-- Added packages  ssl: Required by package http
-- Added packages  zlib: Required by package ssl
CMake Error at cmake/PackageSelection.cmake:297 (message):
  No source for some required packages.  Please run the command below from
  the top directory and retry

     git -C .. submodule update --init  packages/ltx2htm packages/pldoc packages/nlp packages/clib packages/http packages/pengines packages/sgml packages/ssl packages/zlib

Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

-- Configuring incomplete, errors occurred!
See also "/home/anniepoo/swipl-devel/build/CMakeFiles/CMakeOutput.log".

**Comment by erlanger** [comment]
I think you're supposed to pull the modules manually. This is why it gives that instruction.

**Comment by JanWielemaker** [comment]
Yes.  Dedicated applications may not wish them all or even wish to have none.   For the common desktop build though, simply run `git submodules update --init`.
