### ISSUE TITLE
pack_install/1 does not check if pack server sends Prolog term

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/swipl-devel#41]
Minor issue in https://github.com/SWI-Prolog/swipl-devel/blob/9f079249cf84d76e7a248a999864b609ee97c383/library/prolog_pack.pl#L1509 where you get "Syntax error: Operator expected" when pack server sends HTML error page instead of a Prolog term. Maybe it's enough to check Content-Type.

**Comment by JanWielemaker** [comment]
Indeed not crucial.  Enhanced with e7407d94c3d4ed02600ede2c2118355cbf845f6b
