### ISSUE TITLE
Compiling 32-bit version on 64-bit Ubuntu

### ISSUE THREAD

**Issue by JanWielemaker** [SWI-Prolog/swipl-devel#411]
I'm trying to compile the 32-bit version on 64-bit Ubuntu, but CMake seems to insist on many `i86_64` libs.
This seems to be the best starting point I found so far:

```
add_compile_options("-m32")
link_libraries("-m32")
set(CMAKE_FIND_LIBRARY_CUSTOM_LIB_SUFFIX "/i386-linux-gnu")
```

@erlanger seemd to have this working in #358.

**Comment by JanWielemaker** [comment]
Got a lot further.  Now only OpenSSL fails.  Using

```
set(CMAKE_C_FLAGS -m32)
set(CMAKE_LIBRARY_ARCHITECTURE i386-linux-gnu)
```

**Comment by JanWielemaker** [comment]
Managed to get it to work with 9e6fe9141e0d0ddddd4cb8bddcd3b5e47b85786f (tested on Ubuntu 18.04)

**Comment by erlanger** [comment]
Right, this is what I used in the termux build:
```
           export LDFLAGS=-m32
           export CFLAGS=-m32
           export CXXFLAGS=-m32
           CMAKE_EXTRA_DEFS="-DCMAKE_LIBRARY_PATH=/usr/lib/i386-linux-gnu"
```
which has the same effect as what you did (I  think CMAKE_C_FLAGS sets the linker flags also). I really didn't need CXXFLAGS but put it there for completeness.
