### ISSUE TITLE
Cross-running saved state on android - shared library names

### ISSUE THREAD

**Issue by erlanger** [SWI-Prolog/swipl-devel#414]
What function/file loads the shared libraries when running a saved stated with the `-x` flag for `PL_initialise()` argv? 

I am having a problem running a host-built saved state on the android target device. I build the saved state on the 64-bit development host machine; then I run the apk builder (which I am working on) which produces a packaged installable apk file that includes the saved state along with other needed files. I am able to load and mostly run the saved state, but I have a problem:

The saved state  is unable to load the shared libraries `libpthread.so.0` and `libc.so.6`. The reason is that on android those libraries are called `libc.so` and `libpthread.so` and they are located in `/system/lib`, but I want to run the saved state which was built on the host machine, and _there_ the shared library names are `libc.so.6` and `libpthread.0` and they are in `/usr/lib`. Remember here there is no `swipl` executable running:  I am running directly from JPL  (which loads  `libswipl.so`) and then runs `PL_initialise(...)` within the android app.

I was thinking about modifying the code that loads the shared libraries to make it try library names without the number suffix if the original name fails. Perhaps also try different directory names, if it is needed. So if `libc.so.6` fails try `libc.so`, if that fails try  `/system/lib/libc.so`.... and so on.

Can you point me to the code/function that loads shared libs for the saved state (couldn't find it after a quick search)? 
Or perhaps  you have a better idea/approach on how to solve it? 
Any other gotchas when cross-running a saved state (besides the 32bit/64bit issue, and of course shared library compatibility)?

**Comment by JanWielemaker** [comment]
I don't have time to insert all I know right here and now, but these are some observations

  - Extension (e.g. socket.so) and loaded eventually through dlopen(), called from open_shared_object/2 through `library(shlib)`.
  - If Java loads a shared object it does so normally using `RTLD_LOCAL`, which means that the Prolog core symbols are not added to the global symbol table and subsequent `dlopen()` for extensions go wrong.  I don't know whether Java provides a way around.  For toplevel apps, a way around is to preload Prolog using the `LD_PRELOAD` environment variable, but this won't work here (I fear).   Possibly we can dlopen() libswipl.so ourselfs with `RTLD_GLOBAL`?
  - Dev environments bind to *.so, which is a symlink to *.so.<version>.  The resulting binary binds to
*.so.<version>, so it will run in environments with multiple versions installed alongside.  If Android only provides *.so in the distributions this seems very strange to me.  I guess it should be possible to find out how people deal with this somewhere on the web ...

Hope this helps (a little).

**Comment by JanWielemaker** [comment]
The runtime step I surely agree.    I'm not yet sure about the `Architecture-SourceList`.  I'll think a little about that.   Things that come to mind is to use Prolog's `file_search_path` and/or a hook that finds stuff that needs to go into the state.  Note that is is a zip file, so you can use Prolog's s archive or simply `zip` to modify the state.

**Comment by erlanger** [comment]
I really like the hook idea, since many times we need to get the file from a remote server. So the option could be something like `foreign(arch(ListOfArches))` and the hook could be `qsave_find_shlib(Arch, LibFile)`

what do you think?

**Comment by JanWielemaker** [comment]
I think that is a promising approach.  Just try it and see where it leads us to!

**Comment by erlanger** [comment]
Done, closing!
