### ISSUE TITLE
Missing error message for unrecognized read option

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#416]
It could be that the following read option is not recognized. But I
dont get an error message:

![image](https://user-images.githubusercontent.com/5411487/51547461-a4afe880-1e66-11e9-9997-b9f7940f383c.png)

**Comment by JanWielemaker** [comment]
You never get error messages from unrecognised options.   That is quite deliberate as it is practically impossible to write portable code if you generate error messages for that.  I know it is not ISO compliant.

**Comment by jburse** [comment]
In ECLiPSe Prolog I get an error message when a read option isn't
recognized. Although its not the ISO recommended error, from 
the section 8.14.1.3 Errors.

![image](https://user-images.githubusercontent.com/5411487/51547857-623adb80-1e67-11e9-9377-9d09d5e4f1ae.png)
