### ISSUE TITLE
pack_install: cannot install from local directory containing a version number

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/swipl-devel#42]
Clause https://github.com/SWI-Prolog/swipl-devel/blob/edd23f50cb8f7e65c0a9234c25d422e1b147f38d/library/prolog_pack.pl#L443 should come before the previous clause, otherwise

```
pack_version_file(Pack, Version, URL),
download_url(URL)
```

succeeds when URL is a local directory containing a version identifier such as `testpack/standalone-0.0.1`. Currently it results in error:

```
ERROR: Domain error: `url' expected, found `'testpack/standalone-0.0.1''
```

Directory without a version number inside the name does not cause the issue.

**Comment by JanWielemaker** [comment]
Thanks.  Swapped
