### ISSUE TITLE
Concatenated JSON fails

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#422]
I was using this test case from Wikipedia:

`{"some":"thing\n"}{"may":{"include":"nested","objects":["and","arrays"]}}`
https://en.wikipedia.org/wiki/JSON_streaming#Concatenated_JSON

But I couldn't parse it with SWI-Prolog:

![image](https://user-images.githubusercontent.com/5411487/51702404-05c8ef00-2014-11e9-8958-2546dc4bfe58.png)

**Comment by JanWielemaker** [comment]
Concatenated JSON is not part of JSON, but for consistency with e.g,, Prolog read_term/3 it makes sense not to read the character that follows the JSON document.  Pushed a patch for that.  Also allows for returning a eof term rather than throwing an exception.
