### ISSUE TITLE
help/1 formatting bad

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#431]
1. start swipl 8.1.0 on ubuntu 18.0.4
2. query help(numlist/3).
EXPECTED: properly formatted description of numlist/3
OBSERVED: 
numlist description is shown, nicely colored, then a bunch of lines with one tilde each, then
the man page style (END) block.

possibly related to #384

**Comment by JanWielemaker** [comment]
You probably set $PAGER to `vi` or something like that.  Check our the comments to see how it determines the pager and set it to something reasonable (typically `less`).

**Comment by Anniepoo** [comment]
thanks
