### ISSUE TITLE
Request: add system primitives nb_linkval and nth_integer_root_and_remainder to sandbox

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#432]
SWIP v8.1.1

Add `system:nb_linkval` and `system:nth_integer_root_and_remainder` as safe primitives in `sandbox.pl`, i.e.,
```
safe_primitive(system:nb_linkval(Var,_)) :-
	safe_global_variable(Var).
safe_primitive(system:nth_integer_root_and_remainder(_,_,_,_)).
```
While this is easy enough to workaround in an application, it seems a little inappropriate for an app to be declaring system predicates safe.

`nb_setval` could be used in place of `nb_linkval`, but the latter is slightly faster so it is preferred for implementing counters in frequently called predicates (for operational measurements purposes).

**Comment by JanWielemaker** [comment]
Added.  Please send pull requests for such issues.  That is quicker to handle and keeps a better trail.
