### ISSUE TITLE
current_prolog_flag/2  and Swish: command line arguments are visible etc. ???

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#434]
I feel uncomfortable with current_prolog_flag/2 showing lots of internal things about Swi-Prolog when using Swish.

**Comment by JanWielemaker** [comment]
Not sure whether there is anything too sensitive.  Note that SWISH isn't something you should be running without obligatory login on a public host without putting it inside a proper OS sandbox anyway.   The only way around would be to define a wrapper around the system current_prolog_flag/2 that hides some flags as programs may wish to inspect various flags.

The few things I can think of for hiding are the OS arguments and some version details, such as the OpenSSL version.  I do not think it is really worthwhile though.
