### ISSUE TITLE
files.so: undefined symbol: PL_new_atom

### ISSUE THREAD

**Issue by ssardina** [SWI-Prolog/swipl-devel#438]
I don't know much what is happening, but code that used to run well in 7.6.4 it now gives:

`/usr/lib/jvm/java-8-oracle//bin/java: symbol lookup error: /usr/local/swipl-git/lib/swipl/lib/x86_64-linux/files.so: undefined symbol: PL_new_atom
`
Note this is happening when I am running JPL and in a code that has `open/3` query:

```
		// Format of file to dump: kb_directory_path/
		val query = String.format("
					prolog_to_os_filename(\"%s/kb-%s-%s.pl\", _FileName),
					open(_FileName, write, _F), set_output(_F), listing, close(_F)", kb_dump_dir, id,
			formatter.format(new Date()))

		// When we prove query, we basically execute a listing/0 sending the output to a file with timestamp and id
		if (!Query.hasSolution(add_module(query))) {
			error("Dumping the database did not work!")
		}
```

Will investigate more but wanted to record it before I forget. Maybe Jan will guess what is happening in `files.so` :-)

**Comment by ssardina** [comment]
gee seems it is an issue with `LD_PRELOAD`. 

The use and interaction of `LD_PRELOAD`, `SWI_HOME_DIR` and `LD_LIBRARY_PATH` is far from trivial and quite unclear yet to me... :-( I need to understand their role for SWI

**Comment by JanWielemaker** [comment]
Java loads .so files such that they do not see each others symbols.  LD_PRELOAD for libswipl.so makes its symbols available.
