### ISSUE TITLE
library(aggregate) choking when non-ground witness

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#443]
Hi,

I am testing library(aggregate). The semantics of aggregate/3 is based on the
semantics of bagof/3. In as far SWI-Prolog seems to work correctly. For
example I get the following results:

![image](https://user-images.githubusercontent.com/5411487/53922778-02df0680-4076-11e9-9183-f9245bb8effe.png)

**Comment by jburse** [comment]
But somehow the thingy doesn't scale. If I increase the between/3,
i get extremly long runtimes, like here:

![image](https://user-images.githubusercontent.com/5411487/53922807-230ec580-4076-11e9-8203-c92686d47c91.png)

**Comment by jburse** [comment]
I have implemented the same predicate aggregate/3 with some
variant comparison based Java tree map, known from tabling, and 
I get the following timing:

![image](https://user-images.githubusercontent.com/5411487/53922860-53eefa80-4076-11e9-9f67-9cab7791e8b9.png)

**Comment by JanWielemaker** [comment]
I don't like retyping your queries.  Issues with meaningless screens shots are ignored.
