### ISSUE TITLE
Github syntax in a Readme.md 

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#444]
I made my first pack and  noticed that Readme.md is copied literally when installing a pack. So there should be a conversion from Github syntax to Pldoc syntax or a Swipl policy that recommends to not use Github syntax???

**Comment by JanWielemaker** [comment]
The idea is that PlDoc syntax and Github syntax should have enough in common to avoid this complication.  Gradually, PlDoc incorporates more of the dominant Markdown conventions.
What causes the problem?

**Comment by xpxaxsxi** [comment]
Great! 

I found out that the code fencing  (like: ``` prolog  ) is accepted at Github site, but not locally at Swipl. So I'll just remove the whitespace between the three ticks and prolog 

https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting]()
