### ISSUE TITLE
feature request hidden(true) module flag

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#446]
Hi,

It could increase the user experience if the module system would 
provide a flag hidden(true) that is understood by the debugger.

See also:
[Stackoverflow - Hide Module/Package from Trace](https://stackoverflow.com/q/55110407/502187)

The precedent would be SICStus Prolog, but I am using a similar
source property sys_notrace/0 in my system.

See also:
[SICStus Prolog - 4.11.3 Defining a Module](https://sicstus.sics.se/sicstus/docs/4.2.0/html/sicstus/ref_002dmod_002ddef.html#ref_002dmod_002ddef)

**Comment by JanWielemaker** [comment]
Use `:- set_prolog_flag(generate_debug_info, false).` inside a module you want to hide.  That will only show calls to/from the module, but not the internal ones and nor those to other modules that use this flag.

**Comment by jburse** [comment]
Would something like <module>:set_prolog_flag(generate_debug_info, false) also work, and change a library module setting without modifying the library module source code?

**Comment by JanWielemaker** [comment]
The flag is scoped over source files.  So, if you declare it in the module/file loading the modules you want to hide you should be fine.

**Comment by jburse** [comment]
Works partially, but it is already a progress:

**Comment by JanWielemaker** [comment]
> How do I switch off CLP(FD) inlining?

I don't think you can.
