### ISSUE TITLE
small glitch in debugging mode indicator

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#449]
Hi,

Want to go from trace mode to debug mode. But the prompt [trace] doesn't change.

![image](https://user-images.githubusercontent.com/5411487/54866253-c697ef80-4d71-11e9-84fd-628c3cd9fcdb.png)

**Comment by jburse** [comment]
Usually in debug mode the prompt is [debug]:

![image](https://user-images.githubusercontent.com/5411487/54866258-d7486580-4d71-11e9-9a73-babb1661d2fa.png)

**Comment by JanWielemaker** [comment]
You are tracing debug/0.  That is fine.  I will delete all issues with nonsense images from now on.

**Comment by jburse** [comment]
Well the error is in the prompt, after debug/0 is executed:
