### ISSUE TITLE
REPL autocompletion

### ISSUE THREAD

**Issue by XVilka** [SWI-Prolog/swipl-devel#452]
To autocomplete available clauses at the current level with TAB.

**Comment by JanWielemaker** [comment]
Where?  Autocompletion based on atoms and filenames is part of the toplevel, depending on the OS and which command line editor the system was built with.   For the preferred `libedit`, autocompletion can be programmed in Prolog. See `library(console_input)`.

**Comment by XVilka** [comment]
Ok, I can confirm, sorry, it was probably a glitch and works now.
