### ISSUE TITLE
bug in onGlobalArea?

### ISSUE THREAD

**Issue by erlanger** [SWI-Prolog/swipl-devel#454]
Should `lBase` be changed to `gBase` here (`pl-incl.h`)?:

```c
#define onGlobalArea(addr) \
	((char *)(addr) >= (char *)gBase && \
        (char *)(addr) < (char *)lBase)
```

https://github.com/SWI-Prolog/swipl-devel/blob/830a1481e80a19c39ce63698c0fbaaaa64e96265/src/pl-incl.h#L2066

**Comment by JanWielemaker** [comment]
That is correct.  The local stack is always right above the global one.
