### ISSUE TITLE
graphical interface for prebuilt Linux packages

### ISSUE THREAD

**Issue by insanitywholesale** [SWI-Prolog/swipl-devel#460]
We use swi-prolog in university and while the windows version comes with a graphical interface, the packages in the debian and ubuntu repositories as well as the ones in the PPA don't provide a graphical interface. I couldn't find swipl-win anywhere and had to build it from source. It would be nice if a package could be added. Thank you and have a good day.

**Comment by JanWielemaker** [comment]
Did you install the package `swi-prolog-x`?  That still only provides `swipl`, but does support all graphical tools to be started from the Prolog command line.   The sources do contain the Qt based `swipl-win` that is indeed not part of the normal packages, mostly as it doesn't add much on Linux.   If, after trying, you think differently we could consider adding a package with the Qt interface.

**Comment by insanitywholesale** [comment]
I meant the Qt interface when saying graphical interface. I have seen the swi-prolog-x package but that's not what I need. I would be grateful if you could package the Qt interface since compiling from source isn't ideal for everyone. Thank you for the timely answer

**Comment by JanWielemaker** [comment]
I'll consider this.  No guarantees though and it surely won't be soon.  In the meanwhile, you can easily create a monolithic .dep or .rpm using the instructions in CMAKE.md.

**Comment by JanWielemaker** [comment]
The snap package provides a version with the graphical interface.   `snap install swi-prolog`.
