### ISSUE TITLE
how deep is deep indexing

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#463]
Hi,

I tried the following code:

```
deci([1],[]).
deci([1,B|Bs],[0,B|Bs]) :-
   ends_with_one(Bs, B).
deci([0|Bs],[1|Ds]) :-
   deci(Bs, Ds).
```

With the following query, and it leaves a choice point:

```
Welcome to SWI-Prolog (threaded, 64 bits, version 8.1.3)

?- deci([1],X).
X = [] ;
false.
```

Why is this so? How deep is deep indexing? Somehow
I have the expectation that [1] and [1,B|Bs] viewed as
list cells, have a different functor in the tail. 

The [1] has [] as tail, and the [1,B|Bs] has [B|Bs] as tail.
So if this tail would be also indexed, then the predicate
would be 3-way without choice point.

**Comment by JanWielemaker** [comment]
See http://www.swi-prolog.org/pldoc/man?section=jitindex.  Short: too few clauses to make it think it is worthwhile.

**Comment by jburse** [comment]
Thats a pitty, since a low number of clauses increases sensitivity of an index. Its an easy mathematical relation, if an index selects k clauses out of m clauses, the ratio k/m is of course higher if m is smaller.

Also a smaller m means that not so much memory is needed for the index, so that somehow its cost is not so high. I mean its only 3 clauses, so why not give it a deeper index?
