### ISSUE TITLE
gxref/0 error on non-existing files

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/swipl-devel#464]
The `gxref/0` predicate fails with an error when there are loaded Prolog files that no longer exist on disk. This happens notably when Logtalk is loaded as temporary Prolog files (generated from the compilation of Logtalk source files) are deleted by default. A simple fix is to modify the definition of the `xref_all/1` predicate in `pce_xref.pl` to:

```prolog
xref_all(F) :->
    "Run X-referencer on all files"::
    forall((source_file(File), exists_file(File)),
           send(F, xref_file, File)).
```

If there's no downside on this fix, I can submit it as a PR.

**Comment by JanWielemaker** [comment]
Applied.  Thanks
