### ISSUE TITLE
SWI-Prolog 8.1.3 in main termux repo now

### ISSUE THREAD

**Issue by erlanger** [SWI-Prolog/swipl-devel#465]
Hi @JanWielemaker 

   Looks like SWI-Prolog [finally made](https://github.com/termux/termux-packages/commit/b6d690a9a5f018f127f3445c7562f949603f2d5f) it into the termux main repo. They are keeping two repos now: the newer one for Android 7 and forward, and another branch for Android 5 (and 6).

They should be picked up automatically from whatever device you use. I hope they are committed long term support for older devices (Android 5).

**Comment by JanWielemaker** [comment]
Congrats!
