### ISSUE TITLE
glitch in pretty printing of SWI-packages

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#467]
I was looking at the details of the roman package:

http://www.swi-prolog.org/pack/file_details/roman/prolog/roman.pl?show=src

And it showed me:

![image](https://user-images.githubusercontent.com/5411487/56866613-89abc200-69db-11e9-963c-096bdee1b5fe.png)

Usually the problem can be solved by meta_predicate declarations.
For example if one defines {}/3 as '{}'(0,?,?) meta_predicate. A pretty
printer or code beautifier can detect that the argument of the 

DCG {}/1 is a goal, and can then detect that (in)/2 and (#>=) are
known operators. Strange thing is that the second {}/1 doesn't show
some error. Maybe because only the first error is shown?

**Comment by jburse** [comment]
I found a further small glitch. But since the drop-box link dowsn't work
anymore, I cannot figure out whats going on. Its tha SWI-Package
"hello", and there is a period "." missing in the last line:

**Comment by jburse** [comment]
That the drop-box link is not anymore working is seen here. SWI-Prolog could
check existence first via a HEAD request, and then not ask Y/n. Instead of
asking Y/n and then throwing a large error.

![image](https://user-images.githubusercontent.com/5411487/57180944-0c29fb00-6e8e-11e9-83b3-7398d8086b5d.png)

**Comment by jburse** [comment]
Whats the policy for SWI-prolog website mediate packages? Should I contact 
the original author, like in the case of package "hello", Kaarel Kaljurand 
<kaljurand@gmail.com>. Let me check, maybe he is on GitHub.

**Comment by Kaljurand** [comment]
I'm on GitHub.

The source code of the hello package is:

```
:- module(hello, [ main/0 ]).

main :-
	writeln('hello world!').
```
i.e. it includes the dot.

I can confirm that the Dropbox link no longer works (because Dropbox stopped offering such public URLs a few years ago). I propose to remove the hello-package from the repository, as it is no longer maintained and there probably exist better packages that demonstrate (among other things) how to package a library for SWI-Prolog.

**Comment by jburse** [comment]
Thanks for your response. Somehow, even if its not 
"alive", it still somehow serves as a nice example.
