### ISSUE TITLE
SWISH open hangout shows error and stays empty

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#468]
Possibly a JSON parser/unparser error:

![Bildschirmfoto 2019-04-29 um 03 18 47](https://user-images.githubusercontent.com/5411487/56872942-bfc66180-6a2e-11e9-86c1-028f0601b343.png)

After the error, the hangout looks broken.

**Comment by JanWielemaker** [comment]
Some fixes were not yet installed.  Updated the server. Seems ok again.
