### ISSUE TITLE
Using non-numeric values for pattern `min/1` in `aggregate_all/3` gives a warning that is not very illustrative

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#47]
Using non-numeric values for pattern `min/1` in `aggregate_all/3` gives a warning that is not very illustrative:

``` prolog
?- aggregate_all(min(V), member(V, [a,b]), X).
ERROR: is/2: Arithmetic: `a/0' is not a function
```

**Comment by JanWielemaker** [comment]
`?- catch(aggregate_all(min(V), member(V, [a,b]), X), E, true)` correctly gives

    E = error(type_error(evaluable, a/0), context(system:(is)/2, _66290)).

Since this bug report we display the stack which shows arithmetic evaluation happens.   I think it is hard to do more.   Closing.
