### ISSUE TITLE
Wrong source code links in documentation

### ISSUE THREAD

**Issue by fnogatz** [SWI-Prolog/swipl-devel#470]
Searching for *number* on the website returns Section A.12 about `library(dcg/basics)`: http://www.swi-prolog.org/search?for=number&in=man&match=summary&resultFormat=summary
Although there are no source code links in the [original A.12 Section](http://www.swi-prolog.org/pldoc/man?section=basics), they are in the search results, and even in the `?doc_for` direct links like http://www.swi-prolog.org/pldoc/doc_for?object=number//1.

But at least for `number//1`, `digit//1`, `digits//1`, and `float//1` they link to sources from packages provided by users instead of the actual `library(dcg/basics)` :(

**Comment by fnogatz** [comment]
Of the same kind is the problem that the source code link for [`time/1` here](https://www.swi-prolog.org/pldoc/doc_for?object=time/1) refers to [`library/dialect/ifprolog.pl?show=src#time/1`](https://www.swi-prolog.org/pldoc/doc/_SWI_/library/dialect/ifprolog.pl?show=src#time/1) instead of [`library/statistics.pl?show=src#time/1`](https://www.swi-prolog.org/pldoc/doc/_SWI_/library/statistics.pl?show=src#time/1).

**Comment by JanWielemaker** [comment]
Bit late ...  Pushed some patches that should fix this.  Will be active on next release.

**Comment by fnogatz** [comment]
As always, thank you @JanWielemaker! :owl:
