### ISSUE TITLE
bug fix: faster randset

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#472]
Was playing around with randset/3, its really slow:

![image](https://user-images.githubusercontent.com/5411487/57322974-1bff4480-7105-11e9-85a5-9a78e0c95d4f.png)

The SWI-Prolog source code reads:

```
randset(K, N, S) :-
    must_be(nonneg, K),
    K =< N,
    randset(K, N, [], S).

randset(0, _, S, S) :- !.
randset(K, N, Si, So) :-
    random(N) < K,
    !,
    J is K-1,
    M is N-1,
    randset(J, M, [N|Si], So).
randset(K, N, Si, So) :-
    M is N-1,
    randset(K, M, Si, So).
```

**Comment by jburse** [comment]
Here is a bug fix to make it run much faster:

![image](https://user-images.githubusercontent.com/5411487/57323031-3f29f400-7105-11e9-856c-df6818d6c7e1.png)

Try this code:

```
randset(K, N, L) :-
   randset(K, N, [], L).

randset(0, _, L, R) :- !, R = L.
randset(K, N, L, R) :-
   X is random(N)+1,
   adjust_element(X, L, H),
   J is K-1,
   M is N-1,
   randset(J, M, H, R).

adjust_element(X, [Y|Z], L) :- X < Y, !, L = [X,Y|Z].
adjust_element(X, [Y|Z], [Y|T]) :- U is X+1, adjust_element(U, Z, T).
adjust_element(X, [], [X]).
```

**Comment by jburse** [comment]
I don't know how to pull push SWI-Prolog source,
so you would need to apply a patch on your own.

**Comment by JanWielemaker** [comment]
Current implementation uses different strategies depending on the input.
