### ISSUE TITLE
Package zlib. Subset of unit test failing on Windows. Carriage Return 0x13 filtered out from stream.

### ISSUE THREAD

**Issue by EricGT** [SWI-Prolog/swipl-devel#473]
This is more of a note/warning for those using package [zlib ](https://github.com/SWI-Prolog/packages-zlib) on Windows. 

Running the test cases for [test_zlib.pl](https://github.com/SWI-Prolog/packages-zlib/blob/master/test_zlib.pl) on Windows results in

```prolog
?- consult('C:/Users/Eric/Downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl').
true.

?- run_tests.
% PL-Unit: zlib 
ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:29:
        test gunzip_ascii: failed

ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:36:
        test gunzip_utf8: failed

..
ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:56:
        test gunzip_low_compression: failed

ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:63:
        test gunzip_high_compression: failed

.
ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:76:
        test gunzip_eof: failed

ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:95:
        test gzip_ascii: failed

ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:106:
        test gzip_utf8: failed

...
ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:154:
        test deflate_ascii: failed

ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:168:
        test deflate_utf8: failed

..
ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:208:
        test deflate_low_compression: failed

ERROR: c:/users/eric/downloads/swipl-8.0.2/swipl-8.0.2/packages/zlib/test_zlib.pl:220:
        test deflate_high_compression: failed

... done
% 11 tests failed
% 11 tests passed
false.
```

The error is when the values 0 - 127 are compared. In each case the Carriage Return character (13 - 0xD) is stripped from the `Codes` value in the [comparison](https://github.com/SWI-Prolog/packages-zlib/blob/master/test_zlib.pl#L34).

It seems that read_stream_to_codes/2 executes get_code/2 and get_code/2 strips the CR as near as I can figure.

In writing a local copy of [pl_read_stream_to_codes/2](https://github.com/SWI-Prolog/swipl-devel/blob/master/library/readutil.pl#L201)  that uses [get_byte/2](http://www.swi-prolog.org/pldoc/man?predicate=get_byte/2) seems to fix the problem Carriage Return problem, but  now have to separately convert the raw bytes to encoded text.

**Comment by JanWielemaker** [comment]
Yeah, the test set in general requires a lot of fixes to make it full run on Windows :cry:   I pushed a fix that uses an explicit `set_stream(S, newline(posix))` to fix the zlib tests.  They now pass.

**Comment by EricGT** [comment]
After [cloning ](https://github.com/SWI-Prolog/swipl-devel#forking-cloning-and-submitting-patches) update with Git and running test on Windows 10 it works.

```prolog
?- consult('C:/.../SWI-Prolog/swipl-devel/packages/zlib/test_zlib.pl').
true.

?- run_tests.
% PL-Unit: zlib ...................... done
% All 22 tests passed
true.
```
