### ISSUE TITLE
number_chars accepts whitespace in integers

### ISSUE THREAD

**Issue by jal-frezie** [SWI-Prolog/swipl-devel#477]
Version 8.0.2
Documentation for number_chars says it accepts leading but not trailing whitespace. But it also accepts embedded whitespace in integers, e.g., 
?- number_chars(N, ['3', ' ', '1', ' ', '8']).
N = 318.
This does not happen with decimals, whether the space is before or after the point. Similar predicates like number_codes/2 and name/2 also affected.

**Comment by JanWielemaker** [comment]
number_chars/2 and friends accept Prolog numbers and SWI-Prolog allows for white space in numbers to better facilitate unbounded integers.
