### ISSUE TITLE
problem with is_lambda/1

### ISSUE THREAD

**Issue by slagop** [SWI-Prolog/swipl-devel#478]
Predicate is_lambda/1 (from yall) does not work well with a lambda expression which omits the optional set of free-variables:

?- E = [X,Y]>>(Y is 2*X), call(E, 3, R).
E = [X, Y]>>(Y is 2*X),
R = 6.

?- E = [X,Y]>>(Y is 2*X), is_lambda(E), call(E, 3, R).
false.

?- E = {}/[X,Y]>>(Y is 2*X), is_lambda(E), call(E, 3, R).
E = {}/[X, Y]>>(Y is 2*X),
R = 6.

**Comment by pmoura** [comment]
The bug is in the `is_lambda/1`  auxiliary predicate `is_lamdba_params/1`:

The current definition is:

```prolog
is_lamdba_params(Var) :-
    var(Var), !, fail.
is_lamdba_params(Free/Params) :-
    !,
    is_lambda_free(Free),
    is_list(Params).
```

But it should be:

```prolog
is_lamdba_params(Var) :-
    var(Var), !, fail.
is_lamdba_params(Free/Params) :-
    !,
    is_lambda_free(Free),
    is_list(Params).
is_lamdba_params(Params) :-
    is_list(Params).
```

This change will cover the case you mention where there are no lambda free variables. @JanWielemaker can you add the missing third clause?

**Comment by JanWielemaker** [comment]
Thanks.  Added and pushed.
