### ISSUE TITLE
call_residue_vars/2 invents new variables

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#479]
Hi,

Was trying to use call_residue_vars/2. But it seems to invent 
new variables. For example this CLP(FD) test case here:

```
test :- _*_ #= 7.
?- call_residue_vars(test, L).
```

I guess it should return 2 variables. But I get:

```
L = [_16034, _16040, _16046, _16052, _16058, _16064, _16070, _16076, _16082|...],
_16034 in 1..7,
_16040*_16034#=7,
_16040 in 1..7,
_16046 in -7.. -1,
_16052*_16046#=7,
_16052 in -7.. -1,
_16058 in 1..7,
_16064*_16058#=7,
_16064 in 1..7,
_16070 in -7.. -1,
_16076*_16070#=7,
_16076 in -7.. -1,
_16082 in 1..7,
_16088*_16082#=7,
_16088 in 1..7,
_16094 in 1..7,
_16100*_16094#=7,
_16100 in 1..7,
_16106 in -7.. -1,
_16112*_16106#=7,
_16112 in -7.. -1,
_16118 in 1..7,
_16124*_16118#=7,
_16124 in 1..7,
_16130 in -7.. -1,
_16136*_16130#=7,
_16136 in -7.. -1,
_16142 in 1..7,
_16148*_16142#=7,
_16148 in 1..7,
_16154 in -7.. -1,
_16160*_16154#=7,
_16160 in -7.. -1,
_16166 in 1..7,
_16172*_16166#=7,
_16172 in 1..7,
_16178 in -7.. -1,
_16184*_16178#=7,
_16184 in -7.. -1,
_16190 in -7.. -1,
_16196*_16190#=7,
_16196 in -7.. -1,
_16202 in 1..7,
_16208*_16202#=7,
_16208 in 1..7,
_16214 in -7.. -1,
_16220*_16214#=7,
_16220 in -7.. -1,
_16226 in -7.. -1\/1..7,
_16232*_16226#=7,
_16232 in -7.. -1\/1..7.

```
Here is a screenshot:

![Bildschirmfoto 2019-06-09 um 02 10 27](https://user-images.githubusercontent.com/5411487/59153566-445bc500-8a5c-11e9-99bf-928da8fec109.png)

**Comment by triska** [comment]
During propagation, multiplication posts many constraints to deduce the strongest bounds it can for variables. See `min_max_factor/8`. These are all remaining constraints that, from the system's perspective, may or may not be consistent, and which must therefore reported.

These variables are all collected by `call_residue_vars/2`, this behaviour is correct.

You are right that only two variables are involved in top-level constraints.

There is an extensible predicate **`project_attributes/2`**, with which all these attributes could, at least in theory, be projected to top-level variables. However, constraint projection is not implemented for CLP(FD), it is a very hard problem. It works for CLP(B).

**Comment by jburse** [comment]
I still think there is a bug. I get:

?- call_residue_vars((X*Y#=100), L), call_residue_vars(X=20, R).
X = 20,
Y = 5,
L = [_15384, _15390, _15396, _15402, _15408, _15414, _15420, _15426, _15432|...],
R = [],
_15384 in 1..100,
_15390*_15384#=100,
_15390 in 1..100,
_15396 in -100.. -1,
_15402*_15396#=100,
_15402 in -100.. -1,
_15408 in 1..100,
_15414*_15408#=100,
_15414 in 1..100,
_15420 in -100.. -1,
_15426*_15420#=100,
_15426 in -100.. -1,
_15432 in 1..100,
_15438*_15432#=100,
_15438 in 1..100,
_15444 in 1..100,
_15450*_15444#=100,
_15450 in 1..100,
_15456 in -100.. -1,
_15462*_15456#=100,
_15462 in -100.. -1,
_15468 in 1..100,
_15474*_15468#=100,
_15474 in 1..100,
_15480 in -100.. -1,
_15486*_15480#=100,
_15486 in -100.. -1,
_15492 in 1..100,
_15498*_15492#=100,
_15498 in 1..100,
_15504 in -100.. -1,
_15510*_15504#=100,
_15510 in -100.. -1,
_15516 in 1..100,
_15522*_15516#=100,
_15522 in 1..100,
_15528 in -100.. -1,
_15534*_15528#=100,
_15534 in -100.. -1,
_15540 in -100.. -1,
_15546*_15540#=100,
_15546 in -100.. -1,
_15552 in 1..100,
_15558*_15552#=100,
_15558 in 1..100,
_15564 in -100.. -1,
_15570*_15564#=100,
_15570 in -100.. -1.
