### ISSUE TITLE
Typo in documentation theYr should be theIr

### ISSUE THREAD

**Issue by wvxvw** [SWI-Prolog/swipl-devel#48]
A small thing I encountered when reading the online documentation here: 
http://www.swi-prolog.org/pldoc/doc_for?object=section%283,%274.16.1%27,swi%28%27/doc/Manual/IO.html%27%29%29
```
Newly created threads inherit these stream aliases from theyr parent. 
-----------------------------------------------------------^
```
Also notice how the title of the page is rendered. The title might be rendered this way due to the link, which I clicked to get to this page: http://www.swi-prolog.org/pldoc/doc_for?object=section%282,%274.16%27,swi%28%27/doc/Manual/IO.html%27%29%29 (this is how Google knows this page).

**Comment by edechter** [comment]
the typo has been fixed
