### ISSUE TITLE
call_resdiue_vars/2 not compatible with SICSTus Prolog

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#486]
Hi,

I have recently changed residue variables in my system, and I am still working on the API. It seems that SWI-Prolog and SICStus Prolog have incompatible implementations of the predicate call_residue_vars/2.

For SWI-Prolog I get:

```
?- call_residue_vars(X#=Y+1, L), call_residue_vars(X#=Z+1, R).
L = [X, Y],
R = [Z, X],
```

For SICStus Prolog I get:

```
| ?- call_residue_vars(X#=Y+1,L), call_residue_vars(X#=Z+1,R). 
L = [Y,X],
R = [Z],
```
Is this a bug or feature? I mean is there a dependency on how the CLP(FD) library is implemented and could there be a discrepancy between SWI and SICStus, or is it more the call_residue_vars/2 predicate itself?

**Comment by jburse** [comment]
To easily see the versions I was using I made some screenshots:

SWI-Prolog:

![image](https://user-images.githubusercontent.com/5411487/60951433-69f91a00-a2f9-11e9-9b72-950aebd42c75.png)

SICStus Prolog:

![image](https://user-images.githubusercontent.com/5411487/60951452-72515500-a2f9-11e9-8734-a00d5ac7e09b.png)

**Comment by JanWielemaker** [comment]
This can just as well be a difference between the two clp(fd) systems.
