### ISSUE TITLE
feature request thread groups/thread group time

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#487]
I was testing on my machine, a i7-6700HQ with 8 logical threads:

```
?- time((primes(1 000 000, L, 8), length(L, N))).
% 157,006 inferences, 0.094 CPU in 2.993 seconds (3% CPU, 1674731 Lips)
L = [1, 2, 3, 5, 7, 11, 13, 17, 19|...],
N = 78499.
```

This from code by Jan W. [here](https://swi-prolog.discourse.group/t/how-would-you-parallelize-between-1-20-n-prime-n/957/12?u=j4n_bur53).

I wonder whether time/1 could show something else in such cases.
I assume now that it shows by 0.094 CPU the thread CPU time of 
the master thread, and then gets from it 3% CPU utilization.

But the problem uses a master thread and then many slave threads,
called workers in the Jan W. code. Is there a way to identify them as a
group and have the time consumption of the group added to the 

master thread and then shown this number?

**Comment by JanWielemaker** [comment]
Threads have no real master/slave relation.   The most sensible thing to do might be to collect the child thread time in the thread calling thread_join/2 on some thread.    There may be no joiner though (detached) and the creator may not be the joiner.   So, the general case is rather ambiguous.   For timing you can typically use the statistics/2 key `process_cputime` (the default is `thread_cputime`).

**Comment by jburse** [comment]
Well since you mention thread_join/2. The thread that calls thread_join/2 on some other thread, is the master, and the other thread is the slave. This relationship exists and a time/1 could return data concerning this relationship. Here is an example of some book keeping more or less during thread_join/2:

/* perfect numbers */
perfect2(X) :-
   Y is X//2,
   aggregate_all(sum(Z), (between(1,Y,Z), X rem Z=:=0), X).
?- time((balance((between(1,20000,X), perfect2(X))), fail; true)).
% Up 3,571 ms, GC 26 ms, Threads 26,418 ms (Current 07/18/19 13:46:48)
Yes

More data can be obtained when the releation ship gets already communicated to the system while threads get. Its then also possible to collect data while the slaves did not yet join back the master. The feature request is such to provide means to communicate such a relation to the system. If the relation is known, also thread cpu snapshots can be taken:

?- time((balance((between(1,20000,X), perfect2(X))))), fail; true.
% Up 48 ms, GC 0 ms, Threads 0 ms (Current 07/18/19 13:49:14)
% Up 1 ms, GC 0 ms, Threads 0 ms (Current 07/18/19 13:49:14)
% Up 0 ms, GC 0 ms, Threads 0 ms (Current 07/18/19 13:49:14)
% Up 543 ms, GC 1 ms, Threads 4,437 ms (Current 07/18/19 13:49:15)
% Up 2,754 ms, GC 7 ms, Threads 21,886 ms (Current 07/18/19 13:49:17)
Yes

**Comment by JanWielemaker** [comment]
There might be some virtue in having a optional master/slave relation between threads.   If that would be around it makes sense to propagate times as well.    Until then, I see little point in implementing something that is not quite right to begin with.   I don't see this getting high enough on the priority list anytime soon though, so if you want it you should implement it.

**Comment by jburse** [comment]
Thread groups can establish a relation ship. At least they can group slaves. I don't know why it did not yet enter Prolog. It is common in Java, there is a Java class ThreadGroup. 

The measurement on the other hand, was build on top of Java class ThreadGroup. It is not delivered by a JVM already. There might be indeed situations where using

ThreadGroups breaks. For example if there were thread pool, and the slaves change release and acquire threads from a pool. Then you would need replace ThreadGroup by something else.

**Comment by JanWielemaker** [comment]
Well, the POSIX C API has no such notion and, AFAIK, explicitly states that threads have no such relation.   Of course you can write it on top, but as said, I see too little reason to spend time on that.    If you need it, implement it or pay someone to do so.   That is how open source works :)

**Comment by jburse** [comment]
IBM payed $38 billion for Red Hat last year, I am still waiting that 
somebody pays me. My system is also open source. The snapshot 
computation is here on GitHub:

**private static long snapshotThread(Interpreter inter)**
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/swing/jekpro/platform/swing/ForeignStatistics.java

**Comment by jburse** [comment]
Some unix variants seem to also have thread groups:

> Thread groups were a feature added in Linux 2.4 to support the 
> POSIX threads notion of a set of threads that share a single PID. 
> Internally, this shared PID is the so-called thread group identifier 
> (TGID) for the thread group. Since Linux 2.4, calls to getpid(2) return 
> the TGID of the caller.

https://unix.stackexchange.com/a/364663/56827

But I don't know anything about them.

**Comment by JanWielemaker** [comment]
Linux thread groups are there such that getpid() on different threads in a process return the same value as demanded by POSIX threads.   Before that, Linux threads where actually processes that share a number of memory areas.   To a large extend, they still are.  All this is unrelated to what you want.
