### ISSUE TITLE
toplevel - autoindent in `[user].` mode

### ISSUE THREAD

**Issue by XVilka** [SWI-Prolog/swipl-devel#488]
If you type in the query mode as a multiline statement, it will indent the following lines e.g. after `,`.
But if you switch into `[user].` mode, it will not indent neither after `:-`, nor after `,`. Would be awesome to do the same as in the query mode, but in the `[user].` mode.

**Comment by JanWielemaker** [comment]
There are many ways to run SWI-Prolog (terminal, editor buffer and various IDEs).   Editing a query is not done by Prolog itself, so it all depends on the environment it is used in.

**Comment by XVilka** [comment]
@JanWielemaker it is for terminal, Linux, zsh to be precise.

**Comment by JanWielemaker** [comment]
Ok.  In that case I'm afraid you need to be a bit more precise in what you see and what you expected for me to understand what you are after.

**Comment by XVilka** [comment]
See the screenshot:
![image](https://user-images.githubusercontent.com/203261/61956545-e7a67080-afef-11e9-96fc-b8c75afed236.png)

**Comment by JanWielemaker** [comment]
What you see is just the _continuation prompt_ that is printed if input is not complete.   In query mode this is ``| `` with 4 spaces, in compilation mode it is ``|:`` with 1 space.  The prompts are some sort of old tradition that was just copied and never reconsidered.   It would be possible to implement proper indentation on top of the line editor, but nobody cared enough.   I hardly ever use ``?- [user].``  Just put the stuff in a file is much more comfortable.

**Comment by XVilka** [comment]
I usually put everything in files too, but seems `[user].` is useful for quick and dirty checks. Would be nice to have indenting here too. I might check it myself, if you can point me to the place it implemented.

**Comment by JanWielemaker** [comment]
The commandline editing is in [editline](https://www.swi-prolog.org/pldoc/man?section=editline).  Some stuff for programming it is in library(console_input).  This will be pretty hard though.  You'll have to use the history to figure out the lines you already sent.
