### ISSUE TITLE
setting/4 behaving oddly

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#49]
Here's a file:

``` prolog
:- setting(foo, atom, blah, 'foo setting'). 
:-setting(debug_port, number, 7777, 'Port to run server on'). 
```

When I start SWI-Prolog I get:

```
ERROR: c:/docs/prolog/educationaboutprolog/ludumdare32/debug_start.pl:1: 
Wrong context: setting/4 can only be used in a directive
Warning: c:/docs/prolog/educationaboutprolog/ludumdare32/debug_start.pl:1: 
Goal (directive) failed: user:setting(foo,atom,blah,'foo setting') 
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.1.35-9-g55e4738) 
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam 
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software, 
and you are welcome to redistribute it under certain conditions. 
Please visit http://www.swi-prolog.org for details. 

For help, use ?- help(Topic). or ?- apropos(Word). 

1 ?-
```

This also works with the first line only, or the second non-blank line only.

If I add a blank and `C-s C-c C-m` it, it compiles fine.  If I then exit SWI-Prolog and double click load it, it gives the same error.  Inspection of the file with another editor (Notepad++) with a 'show all symbols' feature that makes everything printable doesn't reveal any hidden odd characters.

bafflement abounds.

baffle... baffle... baffle....

eazar001 reports this is reproducible on 7.1.36 linux

**Comment by Anniepoo** [comment]
Jan sez:

:- setting(...) is term-expanded. There is also a predicate that can (of
course) be auto-loaded and that is just there to tell you you're doing
something wrong. To declare settings you always need a

    :- use_module(library(settings)).

    Cheers --- Jan

So lets change this bug to 'need to improve error message' - "Wrong context: setting/4 can only be used in a directive " left me pretty baffled.

**Comment by wouterbeek** [comment]
The first setting/4 statement auto-loads the module.  That's why the second setting/4 does not give an error.

To verify this, the first current_module/1 call fails, but the second one succeeds:

```prolog
:- current_module(settings).
:- setting(a, atom, a, "a").
:- current_module(settings).
:- setting(b, atom, b, "b").
```

Maybe we can use the -- currently unused -- error context for this?

**Comment by wouterbeek** [comment]
My idea to use the context for this was not generic enough.  I'll wait for @JanWielemaker to come up with a more general solution.

**Comment by JanWielemaker** [comment]
Pushed 93723cbe32c38e5239a11df6a528008a9ba8f3b2, which as step in preparing term expansion of directives checks whether the directives contains undefined but autoloadable goals and autoloads these.  This pulls in the required term expansion.     Of course, only if autoloading is enabled.
