### ISSUE TITLE
current_table/2 doesn't work for tabled predicate inside modules

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#494]
Hi,

I started testing tabled predicates inside modules. I used the followig module:

```
:- module(alpha, [concat2/3]).

:- table concat2/3.
concat2([], X, X).
concat2([X|Y], Z, [X|T]) :- concat2(Y, Z, T).
```

Consulting the module and running the tabled predicate concat2/3 is fine:

```
?- concat2(X,Y,[1,2,3]).
X = [],
Y = [1, 2, 3] ;
X = [1],
Y = [2, 3] 
``` 

What I couldn't make work is current_table/2.

**Comment by jburse** [comment]
I tried various variants, but to no avail:

```
?- current_table(V,R).
false.

?- current_table(concat2(A,B,C),R).
false.

?- current_table(alpha:concat2(A,B,C),R).
false.
```

Here is a screenshot:

![image](https://user-images.githubusercontent.com/5411487/62301003-0dac9480-b478-11e9-8d20-b49d1be1dbab.png)

**Comment by JanWielemaker** [comment]
```
25 ?- current_table(A:H, T).
A = alpha,
H = concat2(_7998, _8000, []),
T = <trie>(0x55ca955b3cd0) ;
A = alpha,
H = concat2(_7998, _8000, [3]),
T = <trie>(0x55ca955b3750) ;
A = alpha,
H = concat2(_7998, _8000, [2, 3]),
T = <trie>(0x55ca955b3180) ;
A = alpha,
H = concat2(_7998, _8000, [1, 2, 3]),
T = <trie>(0x55ca955b27d0).
```

That said, this interface, AFAIK copied from YAP, is a bit broken.  I'll probably adopt the XSB interface providing get_call/2,3 and get_calls/2,3.   These are in `library(dialect/xsb/tables)`

**Comment by jburse** [comment]
Ok I see:
http://xsb.sourceforge.net/shadow_site/manual1/node102.html
