### ISSUE TITLE
goal output differs when some libraries are autoloaded

### ISSUE THREAD

**Issue by IanUtley** [SWI-Prolog/swipl-devel#495]
The following sample code runs differently from the command line via:
swipl -s daily.pl -g bonus
depending on whether the yall and apply libraries are autoloaded.
This is also true for the first time the goal is ran in the REPL environment, until the first edit.

Note that the extract1.txt file mentioned in the code is the file available at:
https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt

Note renamed daily.pl to daily.txt for upload.
[daily.txt](https://github.com/SWI-Prolog/swipl-devel/files/3476396/daily.txt)

SWI-Prolog version 8.1.11 for x86_64-darwin

**Comment by JanWielemaker** [comment]
A little research shows the key problem with the one that is auto-loaded (this seems to be the wrong one):

    ?- smorse("incriminatory", Morse).
    Morse = "".

This calls >>/4, where unify_lambda_parameters/5 fails.  This seems wrong to me, but I'll leave that to the expert.  @pmoura ?

**Comment by pmoura** [comment]
The commented out libraries are not auto-loaded (using SWI-Prolog 8.1.11):

```
$ swipl
...

?- set_prolog_flag(verbose_autoload, true).
true.

?- [daily].
true.
```

By explicitly loading them (uncommenting lines 3 and 4 in the `daily.pl` file), I get:

```
$ swipl
...

?- set_prolog_flag(verbose_autoload, true).
true.

?- [daily].
true.

?- smorse("incriminatory", Morse).
% autoloading user:flatten/2 from /Users/pmoura/lib/swipl/library/lists
Morse = "..-.-.-..-...--..-..-----.-.-.--".
```

I assume that's the expected result?

**Comment by JanWielemaker** [comment]
Hi Paulo,

Thanks for looking into this.  They are autoloaded.  Autoloading happens at _call_ time, not _load_ file:

```
swipl daily.pl
...
3 ?- set_prolog_flag(verbose_autoload, true).
true.

4 ?- smorse("incriminatory", Morse).
% autoloading user:convlist/3 from /home/jan/src/swipl-devel/linux/home/library/apply
% autoloading user:(>>)/4 from /home/jan/src/swipl-devel/linux/home/library/yall
% autoloading user:flatten/2 from /home/jan/src/swipl-devel/linux/home/library/lists
Morse = "".
```

And we end up calling >>/4 rather than expanding it at compile time.  That should give the same result (I assume).

**Comment by IanUtley** [comment]
Note I also see the issue when I just comment out the apply library line, but keep the yall library explicitly loaded. So it could be a more general thing?

**Comment by JanWielemaker** [comment]
It has the same effect: using yall through meta calling instead of source-to-source translation.   If library(apply) is not loaded, Prolog doesn't know convlist/3 is a meta-predicate and won't try to expand the first argument.  If apply is loaded, but yall not it does try to expand, but as yall is not loaded it has no expansion rules.  So, only if both are present you get the compile time translation.

This surely implies you want both loaded for performance.  Still, the semantic should not be affected.

**Comment by pmoura** [comment]
The bug is in the definition of the `smorse/2` predicate. It should be:

```logtalk
smorse(X,Y) :-
    !,
    string_chars(X,L),
    convlist([A,B]>>letter(A,B,[]),L,Z),
    flatten(Z,F),
    string_codes(Y,F).
```

I.e. the lambda parameters should not be variables shared with the rest of the clause. With this fix and with:

```logtalk
%:- use_module(library(yall)).
%:- use_module(library(apply)).
```

we get the expected result:

```text
?- [daily].
true.

?- smorse("incriminatory", Morse).
Morse = "..-.-.-..-...--..-..-----.-.-.--".
```

**Comment by IanUtley** [comment]
That does fix/demonstrate the issue thanks Paulo. Although I originally didn't think it was a mistake as the documentation states that variables aren't shared between the lambda and the context unless introduced via {...}, and hence the X and Y in the original code would be free variables. I guess this is a strange edge-case (though I imagine that X,Y,Z are common lambda variables names). I won't get caught out again in the future. Thanks for writing and contributing the 'yall' library though, I find it invaluable!

**Comment by pmoura** [comment]
You welcome. Please don't forget to close this issue.

**Comment by JanWielemaker** [comment]
Note that the compiled version could have spotted this problem.  SWI-Prolog provides access to the entire term using `prolog_load_context(term, Term)`.  This is a global variable that actually shares variables with the term that is being expanded.   I guess it is hard to discover this issue in the runtime version.  Possibly you could ask for the variable list to be unbound?  XSB provides `is_most_general_term(@Term)` for this.   This is now in the XSB emulation, but considering it is both rather useful and can be time critical I think I'll move it to C, which allows for a much more efficient implementation.

**Comment by pmoura** [comment]
I considered adding this check in the original implementation of these lambda expression syntax in Logtalk. But never found a way to do it that is not cumbersome to implement and costly. We need to be able to "subtract" the goal(s) contain lambda expressions from the clause and then compare the resulting term variables with the variables in the lambda expression parameters. This "subtraction" requires walking the clause body. "Logtalk also provides a `logtalk_load_context(term, Term)` but that's just a starting point.

**Comment by JanWielemaker** [comment]
You are right.   It is of course doable, but not really trivial.  SWI-Prolog does provide var_property/2 that can tell you during goal expansion that the variable is not shared with anything before it (including the clause head).   It doesn't mean the variable isn't used afterwards.   I think though that yall doesn't bind the var as it copies the terms, so usage of the same variable after the expression is safe.
