### ISSUE TITLE
Possible bug: set_prolog_flag(double_qoutes,codes) and write_canonical/1

### ISSUE THREAD

**Issue by EricGT** [SWI-Prolog/swipl-devel#497]
Possible bug: set_prolog_flag(double_qoutes,codes) and write_canonical/1

Using: SWI-Prolog (threaded, 64 bits, version 8.0.3)

These work as expected

```Prolog
?- write_canonical("Hello").
"Hello"
true.

?- write_canonical(`Hello`).
[72,101,108,108,111]
true.
```
This does not work as expected

```Prolog
?- set_prolog_flag(double_qoutes,codes).
true.

?- write_canonical("Hello").
`Hello`
true.
```

expected

```Prolog
?- write_canonical("Hello").
[72,101,108,108,111]
true.
```

**Comment by pmoura** [comment]
Just a typo in the flag name:

```text
?- set_prolog_flag(double_quotes,codes).
true.

?- write_canonical("Hello").
[72,101,108,108,111]
true.
```

What's problematic is the absence of a domain error in your query with the typo. SWI-Prolog allow creating new flags using the `create_prolog_flag/3` built-in predicate but IMO should not allow it from a call to the `set_prolog_flag/2`built-in predicate :

```text
?- set_prolog_flag(xpto, 42).
true.

?- current_prolog_flag(xpto, 42).
true.
```

**Comment by EricGT** [comment]
LOL,

Silly me, thanks.

**Comment by JanWielemaker** [comment]
> but IMO should not allow it from a call to the `set_prolog_flag/2`built-in predicate

I don't know.  Not being able to define new flags as ISO seems worse.  I tend to consider prolog flags similar to OS environment variables or C macros (`#define`), both of which do allow to introduce them on the fly and misspelling causes them to have no effect.    PceEmacs colors them red when they are not defined.  The `create_prolog_flag/3` was, if I recall correctly, a compromise with YAP.   It has advantages, but I'm afraid too much will break if we force it.
