### ISSUE TITLE
term_singletons/2 - second argument unification

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#498]
SWI-Prolog v8.1.11
MacOS 10.13.6 (High Sierra)

1. term_singletons/2 does not unify the second argument as documented, e.g.
```
?- term_singletons(X+Y,S).
S = [X, Y].

?- term_singletons(X+Y,[S]).
X = S.
```
I would expect the second query to fail (`[X,Y] \= [X]`) as `term_variables/2` does.

2. Second query above crashes when `X` and `Y` have attributes, e.g.,
```
?- freeze(X,print(unfreeze(X))),freeze(Y,print(unfreeze(Y))),term_singletons(X+Y,S).
S = [X, Y],
freeze(X, print(unfreeze(X))),
freeze(Y, print(unfreeze(Y))).

?- freeze(X,print(unfreeze(X))),freeze(Y,print(unfreeze(Y))),term_singletons(X+Y,[S]).
***CRASH***
```

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with dbe3c18e4ca528a6ae9076263aab8d44d1edaffd
