### ISSUE TITLE
Tabling crash on MacOS

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#499]
Hi,

I was trying this example:

```
Jekejeke Prolog 4, Runtime Library 1.4.0 (20 August 2019)

/* first call, it will table some subgoals */
?- time(ack(3,12,X)).
% Up 2,900 ms, GC 1,106 ms, Threads 1,681 ms (Current 08/28/19 15:44:45)
X = 32765

/* second call, the query subgoal is already tabled */
?- time(ack(3,12,X)).
% Up 0 ms, GC 0 ms, Threads 1 ms (Current 08/28/19 15:44:48)
X = 32765 
```

The code is:

```
:- table ack/3.
ack(0, N, X) :- !, X is N+1.
ack(M, 0, X) :- !, H is M-1, ack(H, 1, X).
ack(M, N, X) :- H is M-1, J is N-1, ack(M, J, Y), ack(H, Y, X).
```

When I try the same in SWI-Prolog on MacOS I get a crash.

**Comment by jburse** [comment]
The crash report is here:
[swi-crash.txt](https://github.com/SWI-Prolog/swipl-devel/files/3551276/swi-crash.txt)

I was using:
`Welcome to SWI-Prolog (threaded, 64 bits, version 8.1.12)
`

**Comment by JanWielemaker** [comment]
Seems the GUI version as smaller C-stacks?  Works fine in the command line version and on Linux.  Pushed 612ae5fab9a5699a3d5f7f05b3c02a3715d5311c which avoids recursion on the C stack for free_component().
