### ISSUE TITLE
[Semweb] pceEmacs coloring of module imports

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#5]
`use_module` is not recognized by pce-Emacs coloring when it is only used in the `format` option of `rdf_load`.

![rdf_format_coloring](https://cloud.githubusercontent.com/assets/1685012/3101360/9e267c66-e632-11e3-86c5-ba4acc04b205.png)

**Comment by Anniepoo** [comment]
It might be wisest to just admit that Prolog is a powerful language that often bridges the use-mention boundary in ways that are hard for the compiler to understand, and provide a declaration "I really do need this"

My own code's dotted with the occasional
% needed by foo, don't remove even if red

8cD Of course that means it's sure to be deleted when a refactor turns half the file red and I delete it.

**Comment by JanWielemaker** [comment]
Note that the reddish background indicates that none of the exports are used.  That is correct, you are using the plugin extension provided by the file.  Use `:- use_module(..., [])` in such cases to indicate you know that you don't use the exports.

**Comment by wouterbeek** [comment]
Wow I didn't know the `:- use_module(..., []).` trick!  I'm adding this to the documentation.

**Comment by Anniepoo** [comment]
Did this get added to the documentation? Not showing as of this morning (US)

**Comment by wouterbeek** [comment]
No.  I'm not that fast ;-)
