### ISSUE TITLE
xpce emacs is not reading Defaults-file while parsing quasi-quoted code???

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#500]
I might have made a really inefficient quasi quotation code and _that_ is the real problem. I am using phrase_from_quasi_quotation/2 in the quasi quoting code.  

I open a file and I am editing it. The file uses the qq module. I press cursor key right, and cursor does not advance ~~Emacs calls 1000 times the quasi quoting code . Why is it calling the qq-code, I haven't even edited anything??? This happens every where in the file, not just in sections that are quasi-quoted. Cursor get stuck in editor window and does not go forward until I release a key~~

The xpce emacs has settings about when Prolog checks the syntax in Defaults-file

> ! When to highlight syntax errors in PceEmacs Prolog mode.  One of
! typing (always), pause (on whole-buffer scan) or never.  Default
! is typing

>emacs_prolog_mode.show_syntax_errors: pause

The quasi quoting handling in Pce Emacs doesn't read this setting from Defaults file, that would fix all my problems.

**Comment by JanWielemaker** [comment]
`show_syntax_errors` doesn't prevent the parse.  Just tells the system not to show an ugly orange field on a syntax error.

Note that you can check for the prolog flag `xref` to be `true` when your code is called from the cross-referencer or the highlighter.   You could opt for a quicker scan in that case.  You can also opt for caching, for example using tabling, or figure out why your parser is so slow.

**Comment by xpxaxsxi** [comment]
The [phrase_from_quasi_quotation/2](https://www.swi-prolog.org/pldoc/doc_for?object=phrase_from_quasi_quotation/2) has a '$quasi_quoting'/3 term in a Content argument. 

I was able to write code that caches the results from phrase_from_quasi_quotation/2. Used the xref-flag. But I needed another thread that   cleans up the cache in every 5 seconds. No more lagging in PCE emacs. 

If I use tabling with some predicate that has '$quasi_quoting'/3 terms, will the tabled predicate get garbage collected automatically?? 


If I
