### ISSUE TITLE
Duplicated use_module directive for lists

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/swipl-devel#501]
Playing with compiling Prolog modules as Logtalk objects, exposed the following duplicated `use_module` directives for the same module, `lists`:

https://github.com/SWI-Prolog/swipl-devel/blob/9b578bf13d91cb385d100c53ee812e55d71b2860/library/ansi_term.pl#L41-L43

Is there any point on the last directive above given the first one?

**Comment by JanWielemaker** [comment]
Nope.  Good catch!  cleaned.
