### ISSUE TITLE
No matching clause for goal: ansi_color(h(A),B)

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/swipl-devel#503]
In the `ansi_term` module, there are several calls to the local `ansi_color/2` predicate such as:

https://github.com/SWI-Prolog/swipl-devel/blob/000d5c427f571d1bbcbefa5508b7f646b45ed580/library/ansi_term.pl#L247

But there's no matching clause for the predicate when the first argument is `h(_)`. The predicate is also not declared as dynamic or multifile.

**Comment by JanWielemaker** [comment]
Thanks.  That is a real bug.  The funny thing is that check/0 also spots this, but I don't run it very often (only make/0 which looks for undefined predicates and things such as meta_predicate declarations for undefined predicates.  Fixed.
