### ISSUE TITLE
Warning about swipl-win.exe wants to recompile pce_manual.qlf in a Program Files

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#504]
This doesn't happen with swipl.exe. This is not a warning just in 8.1.13 but previously also. I had 8.1.09 installed previously, it did not anymore show this warning.  I have done some coding with running swipl-win.exe with Administrator rights also. This was after a fresh installation of the 8.1.13 running with Normal rights.

Off-topic: 
I do have a crappy cheap  laptop that has  Windows 10 Home, possibly very much like some poor computer student could have.  I am a bit shy to report any bugs, because I always first suspect my laptop. I have been wondering how many of  you developers here are using Swi-Prolog on some Windows version? It would also be a generally interesting to see some download statistics from swi-prolog.org about different OSs 
 
> Welcome to SWI-Prolog (threaded, 64 bits, version 8.1.13)
> SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
> Please run ?- license. for legal details.
> 
> For online help and background, visit http://www.swi-prolog.org
> For built-in help, use ?- help(Topic). or ?- apropos(Word).
> 
> ?- make.
> true.
> 
> ?- tell('tmp1000.pl'),writeln('hello.'),told.
> true.
> 
> ?- [tmp1000].
> true.
> 
> ?- make.
> true.
> 
> ?- edit(tmp1000). %edited hello to hello2 
> true.
> 
> ?- 
> % c:/users/xpxaxsxi/documents/prolog/tmp1000 compiled 0.00 sec, 0 clauses
> Warning: [Thread pce] 'c:/program files/swipl/xpce/prolog/lib/pce_manual': can not recompile "c:/program files/swipl/xpce/prolog/lib/pce_manual.qlf" (access denied)
> Warning: [Thread pce]   Loading from source
> Warning: [Thread pce] The predicates below are not defined. If these are defined
> Warning: [Thread pce] at runtime using assert/1, use :- dynamic Name/Arity.
> Warning: [Thread pce] 
> Warning: [Thread pce] prolog_colour:save_settings/2, which is referenced by
> Warning: [Thread pce]   c:/program files/swipl/library/prolog_colour.pl:419:8: 1-st clause of prolog_colour:prolog_colourise_query/3

**Comment by JanWielemaker** [comment]
Apparently still some time management issue.   The save_setting/2 issue is a bit that has been fixed since.   It is harmless for local usage (affects SWISH though).   

These messages are harmless.   I'll how they can be avoided

**Comment by xpxaxsxi** [comment]
Well now that you mentioned setting/4, the settings are not saved anymore, this started happening some versions  ago, maybe month ago, maybe more than a month.  

I just did a quick test program to confirm this to myself. I change a setting,  exit swipl-win.exe and restart swipl-win.exe, I have a original value in settings. Both swipl.exe and swipl-win.exe behaved like this 30 minutes ago.  

I don't know where the problem is that nobody has not reported this? Am I the only one running Swi-Prolog development versions  in Windows OS here at this Github project? It seems that 1)I am the only Windows user or 2)I have a such a weird laptop that the laptop has these problems.  The weird laptop explanation has been my reason to not report possible bugs. Well really if I  am the only Windows user, then I will be glad to report possible bugs more eagerly.
