### ISSUE TITLE
 tmp_file/2  (deprecated) has changed behaviour

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#512]
tmp_file('test/',Tmp) used to give a filename like a Tmp= 'test/2'. Now it gives Tmp='test2'. 

I was making temporary directories with the previous behaviour. Well if this change is a planned change then a fix would be like
```
?- tmp_file('test/tmp',A).
A = 'c:/users/anonymity_lover/appdata/local/temp/test/tmp3
```

**Comment by JanWielemaker** [comment]
Seems the move to support Unicode tmp directories may have caused this.  The _tempnam() seems to support longer _prefixes_, _wtempnam() truncates the given prefix at 3 characters and seems to strip e.g. `/`.  

Anyway, it is a temporary _file_ interface, not a temporary _directory_ one.  AFAIK, the system uses the OS calls to find the temporary directory dir.  You can change that using the Prolog flag `tmp_dir` in recent versions.  win_folder/2 can be used to get the standard Windows locations.
