### ISSUE TITLE
pack_install: postinstall option?

### ISSUE THREAD

**Issue by rla** [SWI-Prolog/swipl-devel#515]
When a pack is installed directly from source repository, and there is a Makefile for some reason, then target "all" is attempted to be run in this Makefile if the user chooses "Y" (default) for running postinstall scripts. In the current case the Makefile is used for building and testing the pack and is not supposed to be included in the final pack tarball nor to be used for post-install actions.

Also, when "n" is chosen, then pack_install predicate fails, although pack files are still installed.

Maybe it would be possible to introduce `postinstall` term in `pack.pl` file to indicate whether the given pack has post-install scripts. It would be tricky to introduce it for existing packs without breaking compatibility tho.

Original report and more details: <https://github.com/rla/rdet/issues/8>

**Comment by JanWielemaker** [comment]
The Makefile is not dedicated for building, but for installing.  A simple work around would be to reserve `all` for the (post) install tasks and e.g., `build` for the build process.  You can make `build` the first (default) target and all would work nicely, no?

**Comment by rla** [comment]
I added empty `all`, `check`, and `install` targets. Build targets were already with other names. Installing the pack from git works now.
