### ISSUE TITLE
Missing set_prolog_flag(double_quotes,codes) directive?

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/swipl-devel#516]
The `progman` module seems to require a ` set_prolog_flag(double_quotes,codes)` directive, which is missing:

https://github.com/SWI-Prolog/swipl-devel/blob/6718ecfeba1f0ea793e18876b326300313efb6ac/library/progman.pl#L218

This possible issue was raised by the Logtalk linter:

```text
*     No matching clause for goal: char(",",A,B)
*       while compiling object progman
*       in file /Users/pmoura/Documents/Prolog/swipl-devel/library/progman.pl between lines 217-220
```

**Comment by JanWielemaker** [comment]
Updated the source to avoid the need for char//1.   Thanks.
