### ISSUE TITLE
Crash during assertz/1.

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#517]
I am currently doing some work around assertz/1. I noticed that
SWI-Prolog crashes without any notice for this test case:

```
Welcome to SWI-Prolog (threaded, 64 bits, version 8.1.11)

?- [user].
deep_and(0, foo).
deep_and(N, (X,bar)) :- N>0, M is N-1, deep_and(M, X).
^D
?- deep_and(100000,X).
X =  ((((((((((..., ...), bar), bar), bar), bar), bar), bar), bar), bar), bar) .

?- deep_and(100000,X), assertz((test3:-X)).
%%% crash, good bye without any notice, even history gets lost
```

I guess the crash is due to the fact that assertz tries to flatten
the conjunction. I don't know how it does that, maybe it is exhausting
the native C stack. That it indeed flattens conjunctions is seen here:

```
?- X = ((a,b),c), assertz((test3:-X)).
X =  ((a, b), c).

?- clause(test3, X).
X =  (a, b, c).
```

**Comment by JanWielemaker** [comment]
Yes, the compiler is (still) using the native C stack.
