### ISSUE TITLE
PLSOPATH hardcoded to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by LyzardKing** [SWI-Prolog/swipl-devel#518]
I'm trying to set PLSOPATH to the correct value, in both cases where swipl is built with the so in system paths or not.
I cannot find the correct env variable to set in the Cmake sources
It would be better if instead of a hardcoded string this pointed to the proper path there the SO is ultimately copied.
I can try to change it, but I'm no cmake expert..

**Comment by JanWielemaker** [comment]
Not sure I get this.  `PLSOPATH` defines the variable the OS uses to find shared objects, _not_ the location of `libswipl.so`.   It comes through the Prolog flag `shared_object_search_path` which is set from the CMake variable `SO_PATH`, which is set by default to `LD_LIBRARY_PATH` and overruled in `port/Darwin.cmake` as well as `port/Windows.cmake` to `DYLD_LIBRARY_PATH` or `PATH`.

If you have an OS with a different var, extend the setup used for the other ports.

**Comment by LyzardKing** [comment]
But by default LD_LIBRARY_PATH (and I believe DYLD_LIBRARY_PATH as well) is not set
since it is only used for overrides to the standard paths...
So if it's previously not set it's setting an empty string..
If it is set somwhere else then it's fine, but if not it seems to me that it cannot be used..
Am I wrong?
I noticed this looking at the snap package

**Comment by JanWielemaker** [comment]
The variable is intended for scripts to add directories to search for shared objects as this is often needed for deployment.   Not sure how this relates to snaps.   This does remind me to pick up the snap distribution shortly.

The variable `PLLIBDIR` tells you where libswipl.so resides.   That is intended to be used by scripts that compile C/C++ code that must link against libswipl.

Still wondering what the problem is ....

**Comment by LyzardKing** [comment]
So it is intended to be blank and can be used to add libraries then.
got it.. I misunderstood the intention behind the env name.
I was looking at the snap and the termux build.. trying to find the path to the libswipl.so
for integration with another program (https://github.com/yuce/pyswip).
That does some parsing of different hardcoded paths to find the .so
and I wondered if there was an env with the full path

**Comment by JanWielemaker** [comment]
Not really, but `PLLIBDIR` gives the dir and `PLSOEXT` the extension.  So, the full path is

    eval `swipl --dump-runtime-variables`
    ls -l $PLLIBDIR/libswipl.$PLSOEXT

Please close if this satisfies you.

**Comment by LyzardKing** [comment]
I don't have the PLLIBDIR in the variable dump in the snap..
It solves the issue in the termux build.
Do I need to set something different at build time to set the variable?

```
swipl --dump-runtime-variables
CC="gcc";
PLBASE="/usr/lib/swi-prolog";
PLARCH="amd64";
PLLIBS="";
PLLIB="-lswipl";
PLCFLAGS="-pthread -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600";
PLLDFLAGS="-rdynamic -Wl,-Bsymbolic-functions -Wl,-z,relro -g -O2 -fdebug-prefix-map=/build/swi-prolog-igqPM5/swi-prolog-7.6.4+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -pthread  ";
PLSOEXT="so";
PLSOPATH="LD_LIBRARY_PATH";
PLVERSION="70604";
PLSHARED="yes";
PLTHREADS="yes";
```

**Comment by JanWielemaker** [comment]
Ah.  The snap build installs libswipl.so in the default global OS location.   I don't know how to get that in a portable way.   It should be possible to extract from CMake, I guess.

**Comment by LyzardKing** [comment]
I tried building the snap without the INSTALL_IN_LIB option
and it seems to work..
with that turned off the env variable appears in the list.
I'll close and test the "new" snap package as is
This should make it easier to link with other programs as well.
Thanks!
