### ISSUE TITLE
Firefox blocks SWI-Prolog download websites

### ISSUE THREAD

**Issue by mb720** [SWI-Prolog/swipl-devel#520]
Hi!

When I visited https://www.swi-prolog.org/download/devel using Firefox 70.0 I saw this scary warning:

![Firefox blocks site](https://i.imgur.com/lbspzul.png)

The same goes for the stable release website at https://www.swi-prolog.org/download/stable

**Comment by erlanger** [comment]
It is a false positive.

**Comment by mb720** [comment]
I figured.
It still looks terrible and will cause people to not use SWI-Prolog.

**Comment by JanWielemaker** [comment]
See https://swi-prolog.discourse.group/t/parts-of-website-blocked-by-google-safe-browsing/1365/38
Is ok for now, though we still worry this will happen again.
