### ISSUE TITLE
How hide start_tabling/3 and trie_gen_compiled/2 from tracing?

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#522]
I am currently experimenting with tracing tabling predicates. I
am using this test code here:

```
:- table fib/2.
fib(0, 1) :- !.
fib(1, 1) :- !.
fib(N, X) :- M is N-1, fib(M, Y), L is M-1, fib(L, Z), X is Y+Z.
```
I would like to get a compact trace like here:

![image](https://user-images.githubusercontent.com/5411487/68376850-a0309400-0149-11ea-81f5-c9f8cd96b6ec.png)

But by default the trace looks like this here:

![image](https://user-images.githubusercontent.com/5411487/68376884-b0487380-0149-11ea-944e-aa0d832df6ba.png)

**Comment by jburse** [comment]
I tried to hide start_tabling/3 and trie_gen_compiled/2 from tracing. But somehow this doesn't work.

![image](https://user-images.githubusercontent.com/5411487/68376986-e71e8980-0149-11ea-9988-f695f7a0afcb.png)

Maybe I used the wrong predicate indicator? Also obtaining information in which module start_tabling/3 is located, seems not to work:

![image](https://user-images.githubusercontent.com/5411487/68377134-277e0780-014a-11ea-9b66-81c255326ba4.png)

**Comment by JanWielemaker** [comment]
Tracing and tabling combine poorly.  Possibly that will be improved a little, but not before the tabling implementation is stable.
