### ISSUE TITLE
Chrome is marking the windows download as dangerous

### ISSUE THREAD

**Issue by Cricycle** [SWI-Prolog/swipl-devel#524]
Hello,

Chrome is marking the download of swipl-8.1.15-1.x64.exe as dangerous.  And it also says the same thing about the entire daily builds website.  Just fyi.

Thanks,
Alex

**Comment by JanWielemaker** [comment]
Thanks for reporting.   See https://swi-prolog.discourse.group/t/parts-of-website-blocked-by-google-safe-browsing/1365 for further discussion.   We're looking for a solution.  Suggestions are welcome!

**Comment by JanWielemaker** [comment]
Seems resolved for now.   See above forum link for status.
