### ISSUE TITLE
pack_install/2 prints error

### ISSUE THREAD

**Issue by damianoazzolini** [SWI-Prolog/swipl-devel#535]
I'm trying to install a package through `pack_install/2`. However, i get:
```
% Unknown option: -C
% usage: git [--version] [--help] [-c name=value]
%            [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
%            [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
%            [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
%            <command> [<args>]
ERROR: Unhandled exception: error(process_error(git,exit(129)))
```
After that, the pack is correctly installed (i can see it with `pack_list_installed/0` after reloading swi). This error is caused by a git version that does not support the flag `-C` (mine is `1.8.3.1`).

**Comment by JanWielemaker** [comment]
I think it is a bit of an overkill to ask complicated version inquiry and work-around to support a 6 years old version of `git`.   Sorry ...
