### ISSUE TITLE
hidden types in (is)/2 while computing with rational numbers

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#538]
There is some hidden types somewhere. Possibly rdiv(A,1) is displayed as A. Or somewhere inbetween converted to A. I get this “error”. First it tells me the sub result is 3.

```
Welcome to SWI-Prolog (threaded, 64 bits, version 8.1.19)

?- X is 13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2).
X = 3.
```
Now I use the sub result to get the final result:

```
?- Y is 1/3.
Y = 0.3333333333333333.
```
If I do it in one go I get the following result:

```
?- Z is 1/(13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2)).
Z = 1 rdiv 3.
```
Thats a little strange.

**Comment by jburse** [comment]
The decomposition mismatch also happens here:

```
?- X is 13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2), Y is 1/X.
X = 3,
Y = 0.3333333333333333.
```
So its something that happens between (is)/2 invocations already inside the Prolog system, and is not a top-level copy paste artefact.

**Comment by JanWielemaker** [comment]
Same as your message on discourse https://swi-prolog.discourse.group/t/future-of-support-for-rational-numbers/1779/6

**Comment by jburse** [comment]
The error is here:

This

```
?- Z is 1/(13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2)).
Z = 1 rdiv 3.
```

and this:

```
?- X is 13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2), Y is 1/X.
X = 3,
Y = 0.3333333333333333.
```

Should give the same result.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/future-of-support-for-rational-numbers/1779/10

**Comment by jburse** [comment]
The topic of the discourse thread is something else, not this bug. I only 
discovered the bug while thinking about what is discussed. 
And I made a screenshot since you closed the defect prematurely.
So I think you didn’t believe me, that there is a defect.

Better don’t close defects prematurely, before the defect is
analyzed thoroughly. Also closing defects after a fix is made,
without regression testing is a bad practice as well. This is all
disrespectful towards those who do the testing and reporting.

**Comment by JanWielemaker** [comment]
I now see what you mean.  This indeed is a bug.  I'll re-open it for the record, but I think it is a better idea to property support rationals than fixing this.  And no, screen shots have no added value, so please stop using them.

**Comment by jburse** [comment]
Yes, sure. If you change the rationals, things might turn out differently. B
ut it might be a while until this happens.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/using-screen-shots-and-images/1783/2

**Comment by jburse** [comment]
The (^)/2 operator is also affected:

```
?- X is (13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2))^(-1).
X = 1 rdiv 3.

?- Y is 13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2), X is Y^(-1).
Y = 3,
X = 0.3333333333333333.
```
