### ISSUE TITLE
feature request: it should not be possible to disable all check boxes during install

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#540]
During install I can disable all check boxes. The corresponding
wizard step on windows allows me to do this here:

![grafik](https://user-images.githubusercontent.com/5411487/73598101-16b81480-4534-11ea-94a5-8ad1ca695d4e.png)

After install I get this here:
```

+- D:\Software\Logic\swipl
    +- Uninstall.exe
```

Thats all. Could the installer provide some hints what the minimal
components are to have a Prolog top-level without any extras?

Some installers disable unchecking what is minimal.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/parts-of-website-blocked-by-google-safe-browsing/1365/45

**Comment by jburse** [comment]
Thats how ECLiPSe Prolog does it:

![grafik](https://user-images.githubusercontent.com/5411487/74029606-573ce580-49ad-11ea-9462-3ee47b44ee75.png)
