### ISSUE TITLE
Mac top-level broken, since it cannot read keystroke

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#543]
I get a strange error in a mac, when using SWI-Prolog toplevel.
I just downloaded the standard SWI-Prolog version from devel.

When I type ';' the search does not advance, show another
solution. And typing ';' + newline helps somehow, but aborts
search. You best see the problem in screenshot:

<img width="513" alt="Bildschirmfoto 2020-02-13 um 20 46 28" src="https://user-images.githubusercontent.com/5411487/74472279-f2e4bf00-4ea1-11ea-9888-f7664b00af42.png">

I should be able to step through 10 solutions, but I
guess this is not possible step by step anymore.

**Comment by jburse** [comment]
Does SWI-Prolog require xcode or some such installed?
I am using a fresh mac without such stuff. Also its a

OS catalina  10.15.3 mac. The new catalina has some parts 
of the hard disk read-only, which wasn't the case before.

**Comment by JanWielemaker** [comment]
Thanks.  Pushed a fix.  This is related to migrating terminal control to be stream specific rather than global to support multiple SSH connections.  Xcode should only be needed to built it, not to run.
