### ISSUE TITLE
GMP rounding mode for mpX_get_d() functions

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#545]
In informal testing of  the rational tripwire in 8.1.22 and  I discovered that the GMP `mpX_get_d()` functions do not heed the hardware rounding mode, instead they always truncate (round to zero). This is a bug IMO.

SWIP can workaround the bug by wrapping calls to these functions in a call to something like:

```
double mpX_round(double d) {
  switch (fegetround()) {
    case FE_UPWARD  : return (d>=0) ? nexttoward(d, INFINITY) : d;
    case FE_DOWNWARD: return (d<=0) ? nexttoward(d,-INFINITY) : d;
    default: return d;
  }
}
```

For example, replace `mpz_get_d(r->value.mpz)` with `mpX_round(mpz_get_d(r->value.mpz))` .

There are 4 such calls in pl_arith.c and probably a few more elsewhere (promoteToFloatNumber() ?).

**Comment by jburse** [comment]
I dont know whether nexttoward solves the problem. I am expecting 
that promotion uses "nearest". So that in the end we have for example:

```
/* should be true */
?- 3.0E23 =:= 3*10^23.
false.

?- 3.0E22 =:= 3*10^22.
true.
```

**Comment by ridgeworks** [comment]
I think it does solve the problem for `to_positive` and `to_negative`modes. In these cases, depending on the sign of the value, you know whether the rounding was incorrect or not. The function has no effect if the mode is `nearest` since you don't know whether the rounding was incorrect, as your example demonstrates.

**Comment by JanWielemaker** [comment]
I'll happily handle pull requests :)

**Comment by jburse** [comment]
Yes. But I doubt that `nexttoward` would do something useful, like
for example converting "towards_zero" into "away_zero". Try:

    ?- 123 =:= 123.0
    true

As you observed yourself, you would need to know whether 
rounding was exact, and only act up, when it wasn't exact.
What you could do for "nearest", add a float ULP/2 to the 

number before doing "toward_zero". You would possibly get
"half_down". For "half_even" you could adopt this code,
which inspects the limbs of the number and does not

really perform the float ULP/2 addition:

**OpenJDK - BigInteger**
[https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/math/BigInteger.java#l3929](https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/math/BigInteger.java#l3929)

**Comment by ridgeworks** [comment]
For interval arithmetic it's incredibly useful. In fact it's critical for mathematical soundness. And since the GMP rounding is only in one direction (towards zero), it can be corrected for modes `to_positive` and `to_negative`. If GMP rounding was `nearest` that wouldn't be possible.

For other rounding modes the GMP result is unchanged. `to_zero` is already done. If `neaarest`, the result will either be exact or 1 ULP low. Which is the current behaviour and that doesn't change. 

> @JanWielemaker 
> I'll happily handle pull requests :)

I'll put it on my list.

**Comment by JanWielemaker** [comment]
I think this is all dealt with.  Closing.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/careful-with-the-floats/4212/2
