### ISSUE TITLE
rational numbers and atom_number/2

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#548]
I got this error. The second query result is wrong:

```
SWI-Prolog (threaded, 64 bits, version 8.1.22)

?- atom_number('1r2', X).
X = 1r2.

?- atom_number(X, 1r2).
X = '12'.
```
**Edit 17.02.2020:**
Same problem with number_codes/2:

```
?- number_codes(X, "1r2").
X = 1r2.

?- number_codes(1r2, X).
X = [49, 50].
```

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/atom-number-bug/1874/3
