### ISSUE TITLE
GMP binding: truncated integer root

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#55]
Please add support for the GMP function [`mpz_root`](https://gmplib.org/manual/Integer-Roots.html).

For the binding, I suggest the Prolog predicate `integer_nth_root(I, N, R, Exact)`, with description:

> **`integer_nth_root(+I, +N, ?R, ?Exact)`**
>
> `R` is the truncated integer part of the `N`-th root of the integer `I`.
>
> `Exact` is `true` if the computation was exact, i.e., `R^N =:= I`, otherwise `Exact` is `false`.

**Examples**:

    ?- integer_nth_root(10, 3, Root, Exact).
    Root = 2,
    Exact = false.

    ?- integer_nth_root(27, 3, Root, Exact).
    Root = 3,
    Exact = true.

This functionality is needed for example in the propagation of the CLP(FD) constraints *multiplication* and *exponentiation*, and the GMP binding allows us to simplify and speed up some of the current code.

**Comment by JanWielemaker** [comment]
Added as nth_integer_root_and_remainder(N, I, Root, Rem) after comments on Prolog standard list.

**Comment by jburse** [comment]
Without knowing I have recently added isqrt/2 to my Prolog system:

?- X is isqrt(1000).
X = 31

Now I can do it as follows:

?- nth_integer_root_and_remainder(2, 1000, R, _).
R = 31.
