### ISSUE TITLE
swipl-win.exe: nl/0 from the welcome message and license/0 produces uninitialized data

### ISSUE THREAD

**Issue by pd-robgee** [SWI-Prolog/swipl-devel#551]
Building `swipl-win.exe` I noticed that the newlines in the welcome message and in the `license/0` message produce garbled data. This happens both when built under MinGW and under MSVC. Only `swipl-win.exe` suffers from this, `swipl.exe` does not. Decoding the data shows that the binary data written to the console is `0xCC0D 0xCC00 0xCC0A 0xCC00`, where `0xCC` is a common value of uninitialized memory on my system.

`swipl-win.exe` is not a requirement for my use-case, so this issue is very low priority for me, however I did want to share the results of my limited debugging.

I have traced the issue to `static ssize_t Srlc_write(void *handle, char *buffer, size_t size)` in `pl-ntmain.c`, the comment above it is related:
```C
/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The user streams for swipl-win.exe run  using the 'wchar' encoding. This
means size must be a multiple of   sizeof(wchar_t),  but not if the user
cheats and either switches the encoding   or uses put_byte/1 or similar.
The flushing code will remember `half'   characters  and re-send them as
more data comes ready. This means however  that after a put_byte(X), the
wchar_t stream is out-of-sync and produces   unreadable  output. We will
therefore pad it with '?' characters to re-sync the stream.

The downside of this is  that  Sputc()   and  Sputcode()  do not work on
unbuffered streams and thus Serror  must   be  locked before using these
functions.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
```

For some reason the newlines in those messages are processed unbuffered (`if ( s->buffer )` in `pl-stream.c: static int S__flushbufc(int c, IOSTREAM *s)` is false) leading to the `put_byte`s from `put_code` to be sent separately as `WCHAR`s.

Furthermore `Srlc_write` tries to pad single bytes to `TCHAR` width by adding ASCII `?` in the spare space, however I believe that the `rlc_write` call on `pl-ntmain.c:242` incorrectly uses `buffer` instead of the just padded `buf`. I believe this leads to the output of `0xCC` instead of `0x3F` (`?`).

I have not been able to identify:
* Why the newlines (and not the other text) in those two messages are handled unbuffered
* Where this issue should be patched (should it be `swipl-win.exe` specific, or should it be handled in `IOSTREAM`)

My CMake arguments are as follows:
```Sh
cmake -DMINGW_ROOT=<zlib location> \
      -DCMAKE_INSTALL_PREFIX=../swipl-install \
      -DMULTI_THREADED=OFF \
      -DUSE_SIGNALS=ON \
      -DUSE_GMP=OFF \
      -DSWIPL_SHARED_LIB=ON \
      -DSWIPL_INSTALL_IN_LIB=OFF \
      -DSWIPL_M32=OFF \
      -DSWIPL_PACKAGES=OFF \
      -DSWIPL_PACKAGES_BASIC=OFF \
      -DSWIPL_PACKAGES_ODBC=OFF \
      -DSWIPL_PACKAGES_JAVA=OFF \
      -DSWIPL_PACKAGES_X=OFF \
      -DBUILD_TESTING=OFF \
      -DINSTALL_TESTS=OFF \
      -DINSTALL_DOCUMENTATION=OFF \
      ..
```

![MSVC](https://user-images.githubusercontent.com/59055751/74756635-26926100-5275-11ea-88e4-7cd8452befd6.png)
![MinGW](https://user-images.githubusercontent.com/59055751/74756680-3c078b00-5275-11ea-8324-cb7d0768126b.png)

**Comment by JanWielemaker** [comment]
Turns out the Slock()/SUnlock() to provide the temporary buffer for unbuffered streams was not used in single threading mode.  I have enabled that.  As far as I can tell, this doesn't any real locking, but it does provide the buffer.

> however I believe that the `rlc_write` call on `pl-ntmain.c:242` incorrectly uses `buffer` instead of the just padded `buf`

Well, spotted.  Fixed.
