### ISSUE TITLE
rationalize/1 needs to be tighter

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#555]
Now I could track down a first bug in SWI-Prolog rationalize/1. I was only looking at cases for absolute error. Thus I was using an x with 1=<x<2. Here is the result:
```

?- X is rationalize(8*(pi-3)).
X = 51546562r45506035.

?- X is 8*(pi-3), X =:= float(rationalize(X)).
false.
```

On the other hand in ECLiPSe Prolog I get:
```

 [eclipse 1]: X is rationalize(8*(pi-3)).
 X = 121642183_107387442
 Yes (0.00s cpu)

 [eclipse 2]: X is 8*(pi-3), X =:= float(rationalize(X)).
 X = 1.1327412287183449
 Yes (0.00s cpu)
```

The error is you need to check abs(x-r) < eps/2 and not only abs(x-r) < eps. I could verify this in my system. I had originally the termination criteria:

```
rat_find(R, _, _, M, Y) :-
   abs(R-M) < 1#4503599627370496, !,
   Y = M.
```

Now I changed it to:

```
rat_find(R, _, _, M, Y) :-
   abs(R-M) < 1#9007199254740992, !,
   Y = M.
```

With this change I guess I can replicate ECLiPSe Prolog behaviour when the argument is in the range 1=<x<2. I am still working on extending the range, so that I can cover full ECLiPSe Prolog behaviour.

**Comment by jburse** [comment]
We can also make sure that its not a float/1 problem. Since the result that SWI-Prolog delivers aint working as well in ECLiPSe Prolog:

```
[eclipse 3]: X is 8*(pi-3), X =:= float( 51546562_45506035 ).
No (0.00s cpu)
```

**Comment by JanWielemaker** [comment]
These are fixed, closing.
