### ISSUE TITLE
signal in rational/1 makes SWI-Prolog instable

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#558]
If I do the following, tested on Windows 10 with
new version SWI-Prolog (threaded, 64 bits, version 8.1.22):

```
?- X is inf, Y is rational(X).
ERROR: Caught signal 8 (fpe)
...
?- X is inf, Y is rational(X).
```

the system exists. The system exists when I press enter here:

![quit](https://user-images.githubusercontent.com/5411487/75060046-67d97980-54de-11ea-95d3-44c857935473.png)

Its an exit without some special exit message:

![nomsg](https://user-images.githubusercontent.com/5411487/75060123-8b042900-54de-11ea-8fc7-7e53c0c2a44e.png)

**Comment by jburse** [comment]
In ECLiPSe Prolog there is no such problem:

```
[eclipse 1]: X is 1/0, Y is rational(X).
arithmetic exception in rational(1.0Inf, Y)
Abort
[eclipse 2]: X is 1/0, Y is rational(X).
arithmetic exception in rational(1.0Inf, Y)
Abort
```

**Comment by JanWielemaker** [comment]
Long fixed. closing.
