### ISSUE TITLE
feature request lcm/2 evaluable function

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#559]
I just noticed that SWI-Prolog has gcd/2 evaluable function,
but no lcm/2 evaluable function. I get this result:

```
SWI-Prolog (threaded, 64 bits, version 8.1.22)

?- X is lcm(10,6).
ERROR: Arithmetic: `lcm/2' is not a function
```
lcm/2 is often handy. I find it in ECLiPSe Prolog, it features also
some border cases when one of the arguments is zero:

```
ECLiPSe Version 7.0 #52 (x86_64_nt)

[eclipse 1]: X is lcm(10,6).
X = 30
Yes (0.00s cpu)

[eclipse 2]: X is lcm(10,0).
X = 0
Yes (0.00s cpu)

[eclipse 3]: X is lcm(0,6).
X = 0
Yes (0.00s cpu)
```

**Comment by JanWielemaker** [comment]
Added with badf2e83532ae1ee1cf4b6c57138a33b9970174b
