### ISSUE TITLE
consider aligning getbit/2 with ECLiPSe Prolog

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#562]
I get this documented behaviour in SWI-Prolog:
```
   SWI-Prolog (threaded, 64 bits, version 8.1.23)

   ?- X is getbit(-100,3).
   ERROR: Domain error: `not_less_than_zero' expected, found `-100'

   ?- (-100)/\(1<<3)=\=0.
   true.
```

But the latest ECliPSe Prolog can do more:
```
   ECLiPSe Version 7.0 #54:

   [eclipse 5]: X is getbit(-100,3).
   X = 1
   Yes (0.00s cpu)

   [eclipse 7]: (-100)/\(1<<3)=\=0.
   Yes (0.00s cpu)
```

**Comment by JanWielemaker** [comment]
I don't see much of a convincing use case.   getbit/2 is first of all intended for bitmaps represented as a large integer and why would you use negative numbers for these?   It is also not well defined.   I.e., SWI-Prolog stores small integers as C int64_t using 2-complement negatives, but large ones as GMP MPZ numbers which AFAIK represent the sign separately (by using a negative size).

Well, mpz_tstbit() docs say it behaves _as if_ 2-complement representation is used.

**Comment by jburse** [comment]
How does ECLiPSe Prolog do it?

**Comment by jburse** [comment]
According to this [source code](https://chromium.googlesource.com/native_client/nacl-gcc/+/0afad64e4ceb9bf762feced38cae2fa8e4c4e44f/gmp-4.3.1/mpz/tstbit.c), mzp_testbit() can do it already.

Case 1: bit index too large, just the sign:

if (limb_index >= abs_size)
--
