### ISSUE TITLE
order_by/2 does reorder not shared variables

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#574]
The spec of order_by/2 says: The ordering of solutions of Goal 
that only differ in variables that are not shared with Spec is not changed. 

I can verify this for a ground problem:

```
data(a,b,1).
data(b,c,3).
data(a,b,4).
data(b,c,2).


?- order_by([asc(X),asc(Y)], data(X,Y,Z)).
X = a,
Y = b,
Z = 1 ;
X = a,
Y = b,
Z = 4 ;
X = b,
Y = c,
Z = 3 ;
X = b,
Y = c,
Z = 2.
```

But then for a non ground problem, it doesn't work:

```
pr2(X, Z, Z, Y) :-
     between(1, 1000, A),
     Y is xor(A*13,A),
     X is Y mod 100. 

?- order_by([asc(X),asc(Y)], pr2(X,Y,Z,T)).
X = 0,
Y = Z,
T = 12900 .

?- pr2(0,Y,Z,T).
Y = Z,
T = 900 .
```

**Comment by JanWielemaker** [comment]
order_by/2 uses findall/3 and thus doesn't preserve variables.    Will add that to the docs.
