### ISSUE TITLE
dupl argument of parsort/4 is inverted

### ISSUE THREAD

**Issue by edmcman** [SWI-Prolog/swipl-devel#582]
From XSB's manual on `parsort/4`:

> If ElimDupl is nonzero, merging of multiple occurring elements
> takes place (i.e., duplicate (whole) terms are eliminated in the output). If ElimDupl
> is zero, then no merging takes place. 

SWI's implementation sends zero values to `@<` and `@>` which remove duplicates, and the opposite for non-zero values.

**Comment by JanWielemaker** [comment]
Thanks.  Pushed 24e3e2260065f98e6f97a96b03166dc58527302c.  Hope I got it right this time.

**Comment by edmcman** [comment]
Looks good to me, thanks Jan.
