### ISSUE TITLE
No permission to calll sandboxed in SWISH

### ISSUE THREAD

**Issue by dvberkel** [SWI-Prolog/swipl-devel#584]
I was revisiting a notebook on SWISH that worked before and when executing a query I was greeted with the following error message.

```
No permission to call sandboxed `'$get_predicate_attribute'(_14144,_14146,_14148)'
Reachable from:
	  system:'$set_pattr'(A,B,C,D)
	  system:'$set_pattr'((as)/2,A,B)
	  non_terminal((as)/2)
```

I created a [minimal notebook](https://swish.swi-prolog.org/p/wTcRwfTr.swinb) that demonstrates the problem as well, and I double checked the code locally, which behaves according to my expectations

**Comment by JanWielemaker** [comment]
Thanks.  Fixed and restarted swish.
