### ISSUE TITLE
Maximum length of Prolog Pack documentation

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#587]
One of my libraries ([prolog_graphviz](https://github.com/wouterbeek/prolog_graphviz)) has a top-level README file that documents various features and contains multiple examples.  When I visit the library in Prolog Packs I see the following message:

```
Readme file README.md too large (22,546 bytes; maximum size is 20,000)
```

Would it be possible to either increase this limit a little bit, or to use ellipsis or folding.  It is somewhat common for Git repo's to have such a longer top-level README, but at the same time it would be nice to have some documentation on the Prolog Packs page too.

**Comment by JanWielemaker** [comment]
Raised to 50k.  That seems the quickest fix :)
