### ISSUE TITLE
Intellisence support

### ISSUE THREAD

**Issue by Alvin-Seville** [SWI-Prolog/swipl-devel#588]
Please add simple [Intellisence](https://code.visualstudio.com/docs/editor/intellisense) like in modern IDE's and editors.

**Comment by JanWielemaker** [comment]
Nice idea.   Not that likely to happen soon though (al least on my roadmap, anyone can submit a PR).  Note that the built-in emacs clone support M-/ (typically Alt-/) to complete.  This isn't very intelligent, but it does complete from the context (dynamic abbreviation) and from built-in and public library predicates.
