### ISSUE TITLE
Menu doesn't disappear after making a screenshot of it with Snipping Tool

### ISSUE THREAD

**Issue by Alvin-Seville** [SWI-Prolog/swipl-devel#589]
Menu doesn't disappear after clicking out of the Prolog IDE window. For instance I've opened `Browse` menu:
![image](https://user-images.githubusercontent.com/42812113/82104308-c0c15280-9759-11ea-9cea-3c2bb4c7c0d2.png)

and than clicked out of the window and what I've seen:

![image](https://user-images.githubusercontent.com/42812113/82104425-37f6e680-975a-11ea-926d-14a1abded64b.png)

Reproduction algorithm:
- Open `Snipping Tool`
- Select some `Delay` and `Window Snip` mode
- Then try make a screenshot of some opened menu (for instance - `Browse`)
- After previous action menu will overlay everything until some point of it is chosen

**Comment by JanWielemaker** [comment]
Doesn't reproduce.  Which OS (version)?

**Comment by Alvin-Seville** [comment]
Windows 10.

**Comment by JanWielemaker** [comment]
All I can say is that it works fine here, both running under Wine and in a Windows 10 VM (I don't have physical machines running Windows).   Sorry.

**Comment by Alvin-Seville** [comment]
I wrote reproduction algorithm above.

**Comment by JanWielemaker** [comment]
Well, I'll happily leave that to a Windows expert ...
