### ISSUE TITLE
Snippets support

### ISSUE THREAD

**Issue by Alvin-Seville** [SWI-Prolog/swipl-devel#590]
Please add interactive snippets support like in [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets?view=vs-2019).

**Comment by JanWielemaker** [comment]
I have tried something like that for SWISH, but I'm not entirely convinced about the usefulness for Prolog.  The language has very few tricky and elaborate syntax fragments.   The most useful might be to have quick access to the argument names and modes of a predicate which would often avoid a lookup in the manual.
