### ISSUE TITLE
Code formatting support 

### ISSUE THREAD

**Issue by Alvin-Seville** [SWI-Prolog/swipl-devel#591]
Please introduce code formatting support like in `Visual Studio` or another modern IDE.

**Comment by JanWielemaker** [comment]
There is a VSCode plugin.  See https://swi-prolog.discourse.group/t/any-visual-studio-code-users/359

The Emacs way of doing is mostly to hit the TAB on a line to adjust the indentation of that line.   I've hardly ever felt the need for more.  Prolog clauses are typically short and don't have a lot of tricky indentation.
