### ISSUE TITLE
Docker swipl missing a libncursers.so.5

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#594]
I have a Google Cloud Run instance (Ubuntu) with Docker Swipl that starts up a http server and serves stuff. I built it last time in April 1st succesfully. Just a hobby project. 

I a beginner with Cloud Run and Docker, this could be a beginner error with them, but, the April 1st build worked fine, no big changes.  

```
/usr/bin/swipl: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

**Comment by JanWielemaker** [comment]
?  I see nothing wrong?

```
janw (~) 7_> docker run -it swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.1.30)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- 
```

**Comment by xpxaxsxi** [comment]
Ok, thanks. I commented out stuff from Dockerfile and left only swipl-related things, swipl is working. I had soms beginners luck in April 1st with uncommented Dockerfile.

I have a Debian Stretch and 'sudo docker run -it swipl' is showing that swipl  is a version 8.1.12

**Comment by JanWielemaker** [comment]
> swipl is a version 8.1.12

I think you have to do a `docker pull swipl`

**Comment by xpxaxsxi** [comment]
You are right, now I have a 8.1.30

I'll close this issue and study Docker more. Thanks.
