### ISSUE TITLE
SWISH Markdown does not support blockquote

### ISSUE THREAD

**Issue by dvberkel** [SWI-Prolog/swipl-devel#596]
When I use a [blockquote](https://daringfireball.net/projects/markdown/syntax#blockquote) in a SWISH notebook Mardown cell, it renders it as a plain paragraph.

For example, if I write

```plain
> This is a blockquote.
```

At the moment SWISH renders

```html
<p>
> This is a blockquote.
</p>
```

But I would have expected something like

```html
<blockquote>
<p>
This is a blockquote
</p>
</blockquote>
```

And have it show up like

> This is a blockquote.

**Comment by JanWielemaker** [comment]
SWISH gets its markdown from PlDoc.   I'm not really against, but I do not see that much need for block quotes in the context of documentation and notebooks.   What is the use case?

**Comment by dvberkel** [comment]
I usually refer to a definition in a block quote as a way to focus the narrative. An [example](https://swish.swi-prolog.org/p/STRIPS%20Block%20World.swinb) of how I use it can be found on SWISH.

I can totally relate not supporting every feature

**Comment by JanWielemaker** [comment]
Please revisit your example and enjoy :smile:

**Comment by dvberkel** [comment]
Super nice!
