### ISSUE TITLE
PL_initialise and getopt()

### ISSUE THREAD

**Issue by drbeco** [SWI-Prolog/swipl-devel#60]
Hello devels,

Just inquiring: is there any particular reason not to use `getopt(argc, argv, "opts")` or ` getopt_long` in function `PL_initialise()`?

Thanks. (can't seem to label this. Is a `question` label)

**Comment by JanWielemaker** [comment]
On 06/23/2015 06:46 PM, Ruben Carlo Benante wrote:
> Hello devels,
> 
> Just inquiring: is there any particular reason not to use |getopt(argc,
> argv, "opts")| in function |PL_initialise()|?

History, I suppose.  Possibly the portability too (Windows).  From tradition
SWI-Prolog inherited e.g. -G2g to get 2 gig global stack.  I don't see many
reasons to break this.  Surely I would have used getopt if it was available
back then.

	Cheers --- Jan

**Comment by drbeco** [comment]
Ok. Thanks. I'll take a look into it in the next vacation.
