### ISSUE TITLE
Interactive code metrics analysis

### ISSUE THREAD

**Issue by Alvin-Seville** [SWI-Prolog/swipl-devel#602]
Please add code metrics analysis like in professional IDE ([Rider](https://www.jetbrains.com/help/rider/Code_Vision.html) for instance).

**Comment by JanWielemaker** [comment]
Please use vscode if you want vscode.   There are surely good points in all of these.   Prolog is a rather different language than most other common languages though and not all of this transfers easily or is anywhere near the top of the priority list.   A lot of code metrics is part of the reflection interface of Prolog itself.

**Comment by Alvin-Seville** [comment]
Thanks for the answer. Got it.
