### ISSUE TITLE
swipl-ld Function not implemented

### ISSUE THREAD

**Issue by zavalyshyn** [SWI-Prolog/swipl-devel#604]
I'm trying to compile a C code with a bridge to SWI-Prolog using swipl-ld and I'm getting the following error on one of the machines I'm using. On other machine the very same command works fine and produces a binary. 

```
# swipl-ld -cc gcc -o main main.c appmodel.pl 
swipl-ld: failed to run swipl --dump-runtime-variables: Function not implemented*** swipl-ld exit status 1
```

If I check the runtime variables I get this:
```
# swipl --dump-runtime-variables
CC="gcc";
PLBASE="/usr/local/lib/swipl-7.7.8";
PLARCH="x86_64-linux";
PLLIBS="";
PLLIB="-lswipl";
PLCFLAGS="-pthread -fPIC ";
PLLDFLAGS="-rdynamic  -pthread -Wl,-rpath=/usr/local/lib/swipl-7.7.8/lib/x86_64-linux ";
PLSOEXT="so";
PLSOPATH="LD_LIBRARY_PATH";
PLVERSION="70708";
PLSHARED="yes";
PLTHREADS="yes";
```

While there is clearly something wrong with the toolchain on my machine, I'm not sure where this error "Function not implemented" comes from. Could you please point me to the right direction? I suspect `swipl-ld` can't access some shared library and fails because of that.

**Comment by JanWielemaker** [comment]
`Function not implemented` doesn't appear in the SWI-Prolog source code.   Add `-v` to see what happens.   This version is also so old that it is most likely just some old bug.  Doesn't ring a bell though.

**Comment by zavalyshyn** [comment]
SWI-Prolog documentation on [Linking Foreign Modules](https://www.swi-prolog.org/pldoc/man?section=foreignlink) says the following:
```
a new executable may be created by compiling this file and linking it to libpl.a from the runtime directory and the libraries required by both the extensions and the SWI-Prolog kernel. **This may be done by hand**, or by using the swipl-ld utility described in section 12.5. If the linking is performed by hand, the command line option -dump-runtime-variables (see section 2.4) can be used to obtain the required paths, libraries and linking options to link the new executable. 
```

Could you please describe the "by hand" procedure? If swipl-ld fails on me maybe I could do it manually instead.

**Comment by JanWielemaker** [comment]
On modern platforms there is not much needs except for linking to -lswipl (might still be -lpl on this old version).   Add -I and -L flags to find the include file and library.    Next create a saved state (optionally) and add it to the end of the executable.   Possibly `swipl-ld -vf ...` tells you want it would do.

**Comment by zavalyshyn** [comment]
> Possibly `swipl-ld -vf ...` tells you want it would do

This is excellent! I will try to repeat the same commands and check exactly where it fails. 

Thanks a lot

**Comment by zavalyshyn** [comment]
Found the problem. Wrong symlink to a compiler. Thanks a lot, again.
