### ISSUE TITLE
Update ability within the IDE

### ISSUE THREAD

**Issue by Alvin-Seville** [SWI-Prolog/swipl-devel#605]
Please introduce an ability to update IDE to the latest version within itself (only environment restart is needed).

**Comment by JanWielemaker** [comment]
Dear Alvin,  As said before making a long list on what vscode can do and the SWI-Prolog native tools not likely to result in anything happening.   These are not bugs, neither small omissions.   If you want this addressed I guess you should get your hands dirty or find help on the Discourse list and get things done with a bunch of users.   There are lots of Prolog IDE projects and the native tools are for a large part written in Prolog, so just hack away.   If you get something nice working with reasonably clean code I'm more than happy to merge it.

I'm going to close these things as this just pollutes the issue list.

**Comment by Alvin-Seville** [comment]
But I haven't said that they are bugs. =) They are suggestions at most.
