### ISSUE TITLE
Strange performance degradation

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#611]
Tested today 05.06.2020, on same machine:

![grafik](https://user-images.githubusercontent.com/5411487/83822749-3a51be00-a6d2-11ea-9501-5e04d0f11d31.png)

![grafik](https://user-images.githubusercontent.com/5411487/83822798-65d4a880-a6d2-11ea-8227-750bfd2cf97b.png)

Thats around 30% slower. :-(

**Comment by JanWielemaker** [comment]
For some time SWI-Prolog for Windows was built using PGO (Profile Guided Optimization).  That is unfortunately broken for in recent distributions of the MinGW cross compilation toolchain.   There are no significant changes to the core Prolog VM that can explain performance changes for these benchmarks.

**Comment by jburse** [comment]
Should there therefore be no difference on mac or linux?
Didn't check yet.

**Comment by JanWielemaker** [comment]
On the Mac we switched from clang to gcc and activated PGO.   That is, for the bundle.  The Macport build uses clang and is about 30% slower, notably as XCode 11.5 produces significant slower code for SWI-Prolog than the older versions.

As stated, nothing much relevant to these benchmarks changed.   A small degradation in meta-calling to support the new wrap_predicate/4 feature, a couple of bugfixes that may have added a few cycles and probably a few minor optimizations one sometimes spots while working on something else.

**Comment by jburse** [comment]
New release 8.3.6 the problem is gone. Cool!
```
SWI-Prolog 8.3.6 Total 3102 (0 gc) ms
```
But the impact of your new LCO special casing is minimal. I get today on 30.08.2020:
```
嘀user:dummy      in 0    (0 gc) ms
user:nrev       in 94   (0 gc) ms
user:crypt      in 359  (0 gc) ms
user:deriv      in 188  (0 gc) ms
user:poly       in 172  (0 gc) ms
user:sortq      in 237  (0 gc) ms
user:tictac     in 219  (0 gc) ms
user:queens     in 342  (0 gc) ms
user:query      in 777  (0 gc) ms
user:mtak       in 203  (0 gc) ms
user:perfect    in 266  (0 gc) ms
user:calc       in 245  (0 gc) ms
Total   in 3102 (0 gc) ms
```
The old nrev for 7.3.26 was 125 ms. But otherwise I don't find
something significantly different above noise level. Possibly
because the LCO special casing isn't applicable elsewhere.
