### ISSUE TITLE
How about HTTP/1.1 in http_open?

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#618]
Did some testing with a servlet that prints the request protocol:

```
?- http_open('http://localhost:8080/deployweb/servlet/Plain', S, []), 
    read_line_to_string(S, X), close(S).
S = <stream>(0000000006E92900,0000000006E911A0),
X = "Protocol: HTTP/1.0".
```

Is there a way to request a higher protocol?

**Comment by JanWielemaker** [comment]
Please do not confuse issues with questions and use Discourse for questions.   

> Is there a way to request a higher protocol?

I don't know.  You can send additional request parameters.  Guess that should do it?

**Comment by jburse** [comment]
The protocol is sent in the first line of a HTTP request, its not a request header. 
Currently http_open/3 seens to send this here:

```
GET / HTTP/1.0
```

How can I change this? There is no option in the option list to choose the protocol, right?

**Comment by JanWielemaker** [comment]
Load `library(http/http_stream)`.   This installs hooks in module `http` that support content and transfer encoding handling and causes http_open/3 to send HTTP version 1.1.

**Comment by jburse** [comment]
Ok, interesting.
