### ISSUE TITLE
autoload loop error for lists/must_be/2

### ISSUE THREAD

**Issue by sasjonge** [SWI-Prolog/swipl-devel#621]
After the update on Ubuntu 18.04 to version 8.2.0 we get the following error if we run our project:

```
ERROR: autoload loop:
ERROR:   lists:must_be/2
ERROR:   lists:must_be/2
```

I could pinpoint the problem to the following minimal example:

```
:- use_module(library(lists)).

user:message_hook(_, _, Lines) :-
	append(Lines,_).
```

**Comment by JanWielemaker** [comment]
Thanks for the small example.   The problem is message hook being called by the compiler.  This particular one is easily fixed.  I'll think about a more general solution,   A simple work around is to load library(error) early in your project.   Otherwise, this is harmless.

**Comment by sasjonge** [comment]
Thanks for the fast answer. I'm not completely sure how your work around would work. If I change my minimal example in the following way I still get the same error:

```
:- use_module(library(error)).
:- use_module(library(lists)).

user:message_hook(_, _, Lines) :-
	append(Lines,_).
```

**Comment by JanWielemaker** [comment]
I had a closer look.  What happens is that `library(lists)` autoloads `must_be/2` when `append/2` is called.  As you define a completely generic message hook, this message hook is called by autoloading `must_be/2`, which causes it to be trapped recursively.   There are roughly two ways out:

  - Make sure your hook is not triggered by the messages used for loading files.
  - Make sure everything your hook uses is loaded such that no autoloading is needed.  This has two solutions:
    - Switch off autoloading using `:- set_prolog_flag(autoload, false).`
    - Force a dummy goal to do the necessary autoloading, i.e.,

```
:- use_module(library(lists)).
:- append([], _).

user:message_hook(_, _, Lines) :-
	append(Lines,_).
```

I don't think this is really a bug.   Lazy loading for hooks that are used by the compiler (the message infrastructure and term/goal expansion) require some care.   If you think you have something clever to make this more robust, please share.  The only thing I can think of is to signal silent failure of the predicate that is subject to recursive autoloading.   It feels shaky.  On the other hand, one only gets recursive autoloading from compiler hooks while trying to autoload predicates required to run the hook.   Surely, for this situation silent failure would work.
