### ISSUE TITLE
Strange unhandled exception messaging order (setup_call_catcher_cleanup/4)

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#623]
It seems unhandled exceptions are not messaged where
they are unhandled. I get this strange reordering:

```
?- catch(throw(ball),E,(write(hit), nl, throw(E))).
hit
ERROR: Unhandled exception: ball

?- call_cleanup(throw(ball),V,(V=exception(_)->write(hit),nl; true)).
ERROR: Unhandled exception: ball
hit
```

Doesn't happen when the exception is handled:

```
?- catch(catch(throw(ball),E,(write(hit), nl, throw(E))), F, true).
hit
F = ball.

?- catch(call_cleanup(throw(ball),V,(V=exception(_)->write(hit),nl; true)), F, true).
hit
F = ball.
```

**Comment by JanWielemaker** [comment]
I see nothing wrong.  The first gets it unhandled exception from the throw in the recovery call.   In the (decprecated) call_cleanup/3 case the exception is immediately considered unhandled as the system knows call_cleanup and friends do not catch exceptions.
