### ISSUE TITLE
Is library(settings) missing a flush_output in save_settings/1 ??

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#625]
I have a threaded, 64 bits, version 8.1.28 running in Windows 10. I believe that I do have seen settings that are persisted, but not for a year or two.

**Comment by JanWielemaker** [comment]
Nothing calls save_settings/0,1 if the application doesn't do so.   flush_output/1 should not be needed as the code correctly calls close/1 which flushes possible pending output (but should use safer coding using setup_call_cleanup/3; will change that).

**Comment by xpxaxsxi** [comment]
Thanks. I hope you emphasize in the  documentation that settings are not automatically persisted.

**Comment by JanWielemaker** [comment]
Updated docs accordingly.   Thanks.
