### ISSUE TITLE
Submodules not all up to date

### ISSUE THREAD

**Issue by sei-mwd** [SWI-Prolog/swipl-devel#628]
After a checkout of the repo today (f36918acd725016140adca525d3efaf94a9d27f5), `git submodule update --init` fails as follows:
```
fatal: remote error: upload-pack: not our ref eb5d5a2c12bb54c9dd0ec9a433009b115411255a
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'packages/jpl', but it did not contain eb5d5a2c12bb54c9dd0ec9a433009b115411255a. Direct fetching of that commit failed.
```
I believe commit f36918acd725016140adca525d3efaf94a9d27f5 started the problem.  Did you forget to push the subrepos?

**Comment by JanWielemaker** [comment]
Sorry, failed to push submodule.  Please pull again and update the submodules.

**Comment by sei-mwd** [comment]
Got jpl now, but failed for ssl.

**Comment by sei-mwd** [comment]
Given the nature of the commit, you may want to check swipl-win as well.

**Comment by JanWielemaker** [comment]
Sorry.  It was not my day (trying to make a docker to build the Windows version).  Should be all fine again.  Please close if you agree.

**Comment by sei-mwd** [comment]
Fixed.  Agreed.  Thanks!
