### ISSUE TITLE
cua keybindings missing in xpce under linux

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swipl-devel#63]
I am forever wedded to c-x c-c c-v to move text around, and c-s to save data.

c-v binding for paste is missing in linux.
c-s binding for save is missing in linux.

**Comment by Anniepoo** [comment]
ah - bad feedback. You have to completely exit swipl and restart to take effect.

**Comment by wouterbeek** [comment]
Jan give the following tip on the mailing list:

`M-x key_binding_style` and choose `"cua"`.

To make it permanent, open Edit/Editor preferences, uncomment (remove !) and restart: `!key_binding.style:     cua`.

**Comment by JanWielemaker** [comment]
Dealt with by the reply from @wouterbeek.  Closing.
