### ISSUE TITLE
Specifying predicate in C outdated documentation

### ISSUE THREAD

**Issue by sebdumancic** [SWI-Prolog/swipl-devel#633]
Hi,

could you update the information of the foreign function interface, and specifically how to specify a predicate as a C function?
If I understand correctly, since 8.2.0 version `PL_register_foreign` takes a function with the return with `pl_function_t` instead of `foreign_t`.  The documentation and tests ([here](https://github.com/SWI-Prolog/swipl/blob/master/src/Tests/foreign/hello.c)) do not reflect that change.

I would appreciate if you could give a small example of the correct usage. I tried to modify the `hello` example you provide, but unsuccessfully.

Thank you!

**Comment by JanWielemaker** [comment]
There is no change for this.  For C, we have ``typedef foreign_t (*pl_function_t)();`` (in `SWI-Prolog.h`).   There are two changes in 8.2: arity is now by default `size_t` instead of `int` and several of the constants have been renumbered (breaking binary compatibility).
