### ISSUE TITLE
gtrace kills SWI instantly

### ISSUE THREAD

**Issue by Wouter1** [SWI-Prolog/swipl-devel#634]
Reproduce:

Mac OSX 10.14.6 (18G95)
SWI-Prolog (threaded, 64 bits, version 8.0.3)

Open SWI prolog (double click the owl icon)
enter "gtrace" and press enter.

Expected: trace turns on.
Actual: The app terminates instantly. There is some error flashing by but you can't read it because the window closes instantly.

NOTE: I'm following the instructions on https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/plunit.html%27) and that requires gtrace.

**Comment by JanWielemaker** [comment]
Doesn't reproduce in the current version.  Might be an old problem, might be an incompatibility with XQuartz.  I'd first try 8.2.1.   If that fails too, check XQuartz is up to date.   You can also try from the command line version and hope it reproduces so you can read the error message.

**Comment by Wouter1** [comment]
Thanks for the quick reply!

That's quite surprising, I installed this version only a few weeks ago . But I'll test the latest version and report back.

**Comment by Wouter1** [comment]
I downloaded the latest from https://www.swi-prolog.org/download/stable. Unzipped and dragged the SWI-Prolog app into applications.

Behaviour is the same, instant crash.

>check XQuartz is up to date

There is no /usr/X11R6 directory. Otherwise I have no clue on how to test this. Is it possibly not installed? Otherwise the SWI-Prolog app runs fine.

**Comment by JanWielemaker** [comment]
XQaurtz creates /opt/X11.  If that isn't installed graphics won't work.

**Comment by Wouter1** [comment]
That directory was not there.

I installed XQuartz and now it does not crash.
So thanks for the help in figuring out what's going on here!

May I suggest adding a check somewhere instead of causing a blunt crash ?

**Comment by Wouter1** [comment]
But now it crashes in a different way

reproduce:

gtrace.
['blabla'].

Again, briefly a (now different) exception and then a system exit.

**Comment by JanWielemaker** [comment]
Try the commandline version (`swipl` somewhere in the application bundle).  That at least gives a message that doesn't disappear.   

Using ?- gtrace. and then normal commands also gets pretty confusing traces from possible user hooks into the environment, so better use (replace mygoal with what you want to debug).

   ?- gtrace, mygoal.

> May I suggest adding a check somewhere instead of causing a blunt crash ?

Sure, but dynamic link errors are not easy to recover from ...

**Comment by Wouter1** [comment]
I tried the command line and it shows the error (and also exits immediately)
```
[trace]  ?- ['blabla'].
[PCE fatal: @display/display: Failed to connect to X-server at `0.0': malformed address: 0.0
*********************************************************************
* You MUST be running the X11 Windowing environment.  If you are,   *
* check the setting of your DISPLAY environment variable as well    *
* the access rights to your X11 server.  See xauth(1) and xhost(1). *
*********************************************************************
	in: 	<No exception goal>
]
Host stack:
 [15] pce_principal:send(@emacs_mark_list/emacs_bookmark_editor, append(new(_25346, dialog)))
 [14] Send-method on @emacs_mark_list/emacs_bookmark_editor: emacs_bookmark_editor->initialise
 [13] '$c_call_prolog'
 [12] pce_principal:new(@emacs_mark_list/emacs_bookmark_editor, emacs_bookmark_editor)
 [11] Send-method on @emacs/emacs: emacs->initialise(@emacs_buffers/dict)
% The following threads wouldn't die: [main]
```

**Comment by JanWielemaker** [comment]
Means XQuartz is not started properly.   Normally this should autostart if it is installed, but possibly you need to reboot your Mac to get that working.  Its long ago.  See XQuartz documentation.

**Comment by Wouter1** [comment]
Ah, yes, XQuartz does not say but apparently there now is a XQuartz application added to my /Applications/Utilities folder. If I double click that first the menu bar changes to XQuartz (until you click somewhere). After that has been done, the tool now does seem to work. 

I don't think it will start automatically though. I'll reboot and test again.

**Comment by Wouter1** [comment]
Just to confirm that the XQuartz system does indeed start automatically after I rebooted. 
Thanks for your help!
