### ISSUE TITLE
incoherence between the ^ and 0 concerning dict translation

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#637]
There is a incoherence between the ^ and 0 meta argument 
specifier. You can try this:

    :- meta_predicate bar(?,^,?).
    test_bar(D,L) :- bar(K-V,(V=D.K),L).
    :- meta_predicate baz(?,0,?).
    test_baz(D,L) :- baz(K-V,(V=D.K),L).

And then listing:

    ?- listing(test_bar/2).
    test_bar(A, E) :-
        '.'(A, B, D),
        bar(B-C, C=D, E).
    true.

    ?- listing(test_baz/2).
    test_baz(A, E) :-
        baz(B-C,
            ('.'(A, B, D), C=D),
            E).
    true.

I don't know whether this is a bug or feature. My guess is that ^ 
doesn't implement the blocking of function expansion side goal. 

Credits dtonhofer: 
https://swi-prolog.discourse.group/t/getting-all-key-value-pairs-out-of-a-dict-using-bagof-3-fails-but-succeeds-with-findall-3/2642

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/getting-all-key-value-pairs-out-of-a-dict-using-bagof-3-fails-but-succeeds-with-findall-3/2642/3

**Comment by jburse** [comment]
The spec of ^ says "It is processed similar to ‘0', but leaving the  `^` /2 
intact.", in case of dict it could automatically add existential variable,

by taking term variables difference between before and after
expansion of the goal argument. And if there are new variables add 

them via a further `^` /2 operator.

**Comment by JanWielemaker** [comment]
Fixed with 4ee28abda5e826a3d98791cd588d7ff7ac885e3a

**Comment by jburse** [comment]
Didn’t look at the code how it was done, and hope my shoot
from the hip doesn’t do more harm than good.

Might or might not work if a bagof/3 contains another bagof/3
and dicts are also involved.

Maybe it will only have some redundant existential quantifiers.
Dunno. Would need some test/experimentation.
