### ISSUE TITLE
predicate_property gives wrong imported_from, file, line_count

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#644]
```
$ cat t2.pl
p5(1).
p5(2).

$ swipl t2.pl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.3.4)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

1 ?- predicate_property(p5/1, imported_from(I)), predicate_property(p5/1, file(F)), predicate_property(p/5, line_count(LC)).
I = yall,
F = '/usr/lib/swi-prolog/library/yall.pl',
LC = 275.

2 ?- listing(p5/1).
p5(1).
p5(2).

true.
```

**Comment by kamahen** [comment]
Also gets number_of_clauses and number_of_rules wrong (and size?):
```
?- forall(predicate_property(p5/1, P), format('~q~n', [P])).
interpreted
visible
static
imported_from(yall)
transparent
meta_predicate? / 0
file('/usr/lib/swi-prolog/library/yall.pl')
line_count(275)
number_of_clauses(1)
number_of_rules(1)
last_modified_generation(5172)
defined
size(384)
true.
```

**Comment by kamahen** [comment]
Also $predicate_property doesn't doesn't work (returns false).
And the documentation of wrap_predicate/4 mentions predicate_property but should instead mention $predicate_property and/or current_predicate_wrapper/4

**Comment by JanWielemaker** [comment]
predicate_property/2 takes a _head_, not a _predicate indicator_.  As library(yall) defines /(_,_) as a predicate you get the propreties from there.

**Comment by kamahen** [comment]
Yet another reason why I don't like autoload. ;)
And I also feel stupid.

Anyway, `$predicate_property` doesn't seem to work. Also, `wrap_predicate` doesn't show in the drop-down index for the documentation (although it is found when I search).

**Comment by JanWielemaker** [comment]
`$predicate_property` is internal, so whether or not it works should only be observable through predicate_property/2, which seems to work fine :smile: 

The website drop-down has some issues at the moment for libraries that are only documented in the source.   Not really sure what is going on there.   Doesn't reproduce when I run the web server locally :cry:

**Comment by kamahen** [comment]
The drop-down for wrap_predicate/4 now works for me. Maybe some kind of stale cache?
https://www.swi-prolog.org/pldoc/doc_for?object=prolog_wrap%3Awrap_predicate/4

`$predicate_property` is mentioned in the documentation - I suggest removing it. ;)
(I misunderstood the documentation and thought that I needed `$predicate_property` to get the "wrapped" property) 

https://www.swi-prolog.org/pldoc/doc/_SWI_/library/prolog_wrap.pl
https://www.swi-prolog.org/pldoc/doc_for?object=%27$predicate_property%27/2

**Comment by JanWielemaker** [comment]
> Maybe some kind of stale cache?

No, an upgrade problem causing part of the library not to be loaded and indexed.

> I suggest removing it. ;)

I think that is a good suggestion.  Thanks for spotting.
