### ISSUE TITLE
test error on cplint

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swipl-devel#647]
When testing pita in cplint, running
```
cd pack/cplint/prolog/cplint_test
swipl test_pita
test_pita.
```
I get one test failing with
```
ERROR: /Users/fabrizio/.local/share/swi-prolog/pack/cplint/prolog/cplint_test/test_pita.pl:349:
	test t_c1_p1: received error: call/1: Unknown procedure: plunit_uwcse:prob/2
```
on mac with swipl 8.3.5, while all tests pass on linux.

**Comment by JanWielemaker** [comment]
Hmm.  Doesn't reproduce.   It is also very unlikely to have platform dependencies for this type of issue.   I guess this indicates that the pita term expansion has not done its work?   How did you install the Mac version?

**Comment by friguzzi** [comment]
It's a module problem, prob/2 belongs to the pita module, in all other tests the unit module is correctly replaced with pita when running the test. I installed swipl compiling from sources from swipl-devel. I noticed it uses clang

**Comment by JanWielemaker** [comment]
I see.  It suggests the `:-ensure_loaded(library(examples/uwcse)).` has no effect.   That would be the case if this file is already loaded in some other context.   You could use `consult`.   If it is already loaded that should complain it is abolishing predicates from the context it was loaded before.

I think using `include` is more appropriate than `ensure_loaded` in test_pita.pl.

**Comment by friguzzi** [comment]
If I use consult or include the bug does not go away.
If I use include for all tests, I get 7 failures

**Comment by JanWielemaker** [comment]
All pretty odd.  Bit hard to comment as long as I cannot reproduce it :cry:  I'm happy to have a look, but I guess the only option is if you give me access to the machine as it works fine on my Mac.   I can send my ssh public key.  If you want to go this way, I propose further discussion by email.
