### ISSUE TITLE
The SWI-Prolog github repository is currently borked, more precisely, the `bench` submodule seems to have a problem:

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#649]
The SWI-Prolog github repository is currently borked, more precisely, the `bench` submodule seems to have a problem:

When trying to clone the submodules (I have added line breaks):

```text
Cloning into 'tmp.V2HYd2beHX/swipl-devel_original/packages/zlib'...
fatal: remote error: upload-pack: 
not our ref 3fd9cb5301f3667b82d4c505c8ab60b59e855eec
e-band side-band-64k ofs-delta shallow deepen-since
deepen-not deepen-relative no-progress include-tag
multi_ack_detailed allow-tip-sha1-in-want
allow-reachable-sha1-in-want no-done 
symref=HEAD:refs/heads/master filter agent=git/github-gd72361c7e766
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'bench', but it did not contain
3fd9cb5301f3667b82d4c505c8ab60b59e855eec. 
Direct fetching of that commit failed.
Error while cloning submodules in 'tmp.V2HYd2beHX/swipl-devel_original' -- exiting
```

See also this discussion: [Why does git submodule update fail with “fatal: remote error: upload-pack: not our ref”?](https://stackoverflow.com/questions/61163082/why-does-git-submodule-update-fail-with-fatal-remote-error-upload-pack-not-o)

> Your superproject is asking for the hash ID `[elided]` in the Git repository you can clone from [some repo]. That commit *simply does not exist* in that repository, so it's not in any clone you make either.
>
> Do you know why your superproject lists this commit hash ID, even though it does not exist? (I certainly don't.) You cannot get it from their Git, because they don't have it. That's what all these error messages are telling you.

The log says `bench` was changed this very morning, there was probably a problem at that point.

Shouldn't happen, but, eh, computers, networking and all that.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/swi-prolog-github-repository-bench-submodule-is-currently-borked/2770/3

**Comment by JanWielemaker** [comment]
Fixed.  Happens now and then.  I'll close this one.
