### ISSUE TITLE
plunit code does not handle failing assertion/1 well

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#650]
What it should do:

1. Write the backtrace of the failed assertion
1. Break the test off and fail the test unconditionally

What it does

1. Writes backtrace of the failed assertion
1. Continues with the body
1. The test fails anyway

Very weird. 

Note the lonesome `A`  in the output:

```prolog
:- debug(assertion_info).

:- begin_tests(assertion_test).

% This test will succeed!

test(1) :-
   assertion(false),
   debug(assertion_info,"Now past failed assertion",[]).

:- end_tests(assertion_test).
```
Then:

```
?- run_tests.
% PL-Unit: assertion_test 
ERROR: /home/user/test_assertion.pl:7:
        test 1: assertion failed
        Assertion: false
% Now past failed assertion
A done
% 1 assertion failed
% 1 test failed
% 0 tests passed
false.
```

**Comment by dtonhofer** [comment]
Woah I just found out that it's working as intended:

https://eu.swi-prolog.org/pldoc/man?section=testassertion

But the lonesome "A" is still weird. Is it a replacement for the "."?

**Comment by JanWielemaker** [comment]
> But the lonesome "A" is still weird. Is it a replacement for the "."?

Yes.  '.' means success.   There are a number of other characters that indicate various forms of failures.   Whether stopping the test on the first failure is a good or bad idea, I do not know.   Both have their (dis)advantages.
