### ISSUE TITLE
read_history '%w' does not display history number

### ISSUE THREAD

**Issue by genivia-inc** [SWI-Prolog/swipl-devel#658]
The [read_history/6](https://www.swi-prolog.org/pldoc/doc_for?object=read_history/6) documentation shows this example:
~~~
?- read_history(h, '!h', [trace], '%w ?- ', Goal, Bindings).
~~~
but this does not display the history number, rather just a `%w`:
~~~
%w ?- 1.
Goal = 1,
Bindings = [].
~~~

**Comment by JanWielemaker** [comment]
Thanks.  Must be ``~!`` instead of ``%w``.  Updated the docs.
