### ISSUE TITLE
Feature request, sys_print_map Prolog flag

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#659]
There are at least two use cases already:

1) prove/1 predicate for Quine solver, when using Prolog logical variables.

```
prove(A) :- current_prolog_flag(sys_print_map, N), 
     write_term(A, [variable_names(N)]), nl, 
     eval(A, B), term_variables(B, L), prove(B, L).
```

2) debugger might also profit:

SWI-Prolog, variable names from the top-level get lost during debugging:

```
?- trace.
true.

[trace]  ?- X=1; X=2.
   Call: (11) _10946=1 ? creep
   Exit: (11) 1=1 ? creep
X = 1 ;
   Call: (11) _10946=2 ? creep
   Exit: (11) 2=2 ? creep
X = 2.
```
Jekejeke Prolog, variable names do not get lost:

```
?- trace.
Yes

?- X=1; X=2.
  0 Call X = 1 ? 
  0 Exit 1 = 1 ? 
X = 1 ;
  0 Call X = 2 ? 
  0 Exit 2 = 2 ? 
X = 2
```

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/implementing-quines-algorithm/2830/72

**Comment by JanWielemaker** [comment]
Interesting thought.  Wouldn't be a Prolog flag probably as values there are copies.   Might be implemented as a global variable.   I'll think about it.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/implementing-quines-algorithm/2830/86

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/swi-prolog-php-html/2937/14
