### ISSUE TITLE
FATAL ERROR: Too many stacked strings

### ISSUE THREAD

**Issue by vakker** [SWI-Prolog/swipl-devel#660]
I'm getting `FATAL ERROR: Too many stacked strings` error while I'm using PySwip.
I opened an [issue](https://github.com/yuce/pyswip/issues/102) there, but it seems like the issue originates from `libswipl`.
As I mentioned in the original issue, I could not reproduce the same error just using Prolog, so any input is much appreciated on how to solve this.
Thanks!

**Comment by JanWielemaker** [comment]
I don't know much about the Python interface.  API calls that may trigger Prolog to create temporary strings should be in blocks separated by PL_STRINGS_MARK() and PL_STRINGS_RELEASE() (these are two macros in SWI-Prolog.h).

**Comment by vakker** [comment]
Thanks a lot, that did help to resolve the issue.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/swi-prolog-fatal-error-at-mon-sep-28-1132-2020-too-many-stacked-strings/2981/5

**Comment by vakker** [comment]
@Marco299 the fix was introduced in PySwip, not in SWI-Prolog. If you're using PySwip, then install it from master and see if you're still experiencing the issue.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/too-many-stacked-strings/4219/31
