### ISSUE TITLE
Annoying warnings with library(clpr) 

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#662]
I have been tolerating these warnings because everything works fine, but now I had some spare time and interest to report this. Also tried today to really seriously search Swi-prolog.org documentation how to suppress these, but could not find any fix. It would be nice to suppress these warnings if they are meaningless.

Cannot say when they started to appear, very possibly I have had these for half a year or more. I am running Windows 10,

Example. I have a file called tmp103.pl.  Well now I notice that the first load does not cause these warnings, make/0 does.

```
:- module(tmp103,[calc/1]).

:-use_module(library(clpr)).

calc(X):-
{2.345 +  X  = 4.01}.

```

```
Welcome to SWI-Prolog (threaded, 64 bits, version 8.3.6-4-gb6e96240c)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- [tmp103].
true.

?- calc(A).
A = 1.6649999999999996;
false.

?- make.
Warning: The predicates below are not defined. If these are defined
Warning: at runtime using assert/1, use :- dynamic Name/Arity.
Warning: 
Warning: bv_q:detach_bounds/1, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/redund.pl:285:30: 1-st clause of detach_bounds/2
Warning: bv_q:dump_nz/5, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/itf.pl:100:29: 1-st clause of dump_nz/6
Warning: bv_q:dump_var/6, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/itf.pl:85:33: 1-st clause of dump_v/7
Warning: bv_q:intro_at/3, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/redund.pl:288:29: 1-st clause of intro_at/4
Warning: bv_q:pivot/5, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/project.pl:208:44: 1-st clause of pivot/6
Warning: bv_q:var_intern/2, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/ordering.pl:111:21: 2-nd clause of join_class/2
Warning: fourmotz_q:fm_elim/3, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/project.pl:95:43: 1-st clause of fm_elim/4
Warning: itf_q:do_checks/8, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/itf.pl:122:14: 1-st clause of do_checks/9
Warning: store_q:indep/2, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/project.pl:205:32: 1-st clause of indep/3
Warning: store_q:renormalize/2, which is referenced by
Warning:        c:/program files/swipl/library/clp/clpqr/project.pl:211:37: 1-st clause of renormalize/3
true.
```

**Comment by JanWielemaker** [comment]
They are correct warnings.  The modularization of the clpr code is broken.  It loads stuff that relies on clpq.  Ok, this is never really called, but that is beyond the analysis of make/0.  If you load both clpr and clpq make/0 is silent.

Feel free to figure out a way to fix this and make a PR.

**Comment by xpxaxsxi** [comment]
If I load both as below I get No permission to import errors, so the documentation needs updating, documentation says that " It is allowed to use both libraries in one program, but using both CLP(Q) and CLP(R) constraints on the same variable will result in an exception."
```
:- module(tmp106,[]).

:-use_module(library(clpq)).
:-use_module(library(clpr)).
```

But the code below this seems to work, I am happy with this, I just use_module the empty clpq_fix-module. I no more get warnings and  my other code works fine.  I am a newbie with clp-programming so  I can't edit these libraries, although it seems that problem is about modularization. Well I am now below doing modularization changes though, well I have a really simple use case of library(clpf), maybe this empty module could break something advanced stuff.
```
:- module(clpq_fix,[]).

%referring to clpq module stops make/0
%from showing certain warnings
:- use_module(library(clpq)).
```

**Comment by JanWielemaker** [comment]
You can use `:- use_module(library(clpq), []).` in the same module.

This is not a solution for the library.   The support modules need to be split correctly so we can load the code we need.   Just adding the above merely hides the problem :(

**Comment by xpxaxsxi** [comment]
Yes, that works, thanks. Somebody with deeper knowledge about clp-programming should rewrite modularization
