### ISSUE TITLE
read_history/6 fails with syntax error when read_term/2 succeeds with module-local ops

### ISSUE THREAD

**Issue by genivia-inc** [SWI-Prolog/swipl-devel#665]
I have a module `husky` that defines the operator `::` with:
~~~
op(970,  xfy, husky:[:=, ::, ->])
~~~
However, invoking `read_history/6` fails with a syntax error:
~~~
5 ?- read_history(history, '!history', [module(husky), end_of_file], '~!> ', Term, Bindings).
6> a::num.
ERROR: Syntax error: Operator expected
ERROR: 
ERROR: ** here **
ERROR: a::num .
~~~
But `read_term/2` succeeds for the same input:
~~~
4 ?- read_term(X, [module(husky)]).
|: a::num.

X = ::(a, num).
~~~
Even more strange, `read_history/6` succeeds for operator `:=` that has the same precedence and associativity as `::`:
~~~
5 ?- read_history(history, '!history', [module(husky), end_of_file], '~!> ', Term, Bindings).
6> a:=num.
Term =  (a:=num),
Bindings = [].
~~~
Note that in this case though `:=` is also defined in the user module, which may explain this perhaps.

It could be that `read_history/6` does not obey option `module(husky)` as `read_term/2` does. The [manual](https://www.swi-prolog.org/pldoc/man?predicate=read_history/6) says that `read_history/6` is similar to `read_term/2`. So I would expect `read_history/6` to behave like `read_term`.

**Comment by JanWielemaker** [comment]
read_history/6 uses the _typein module_, which is `user` unless redefined using `module/1`.   I don't know whether this poses a problem to you.   It is a very old predicate with lots of arguments rather than an option list :cry:   I'm not against giving this a modern interface and add the old predicate to the backward compatibility library.   On the other hand, if there is no problem, don't fix it :smile:

**Comment by genivia-inc** [comment]
I'm using `module(husky)` before running `read_history/6`, which works, but is an ugly workaround.

It is a bit disappointing that `read_history/6` does not support the `read_term/2` options, or some of them at least, especially `module()`. This is really needed to support the relatively new module-local operators which simply don't work otherwise. I am not sure how many applications use `read_history/6`, but it is very useful for applications that have user input. In particular for the REPL of an interpreter/emulator.

PS. I can't find the list of `read_history/6` options in its [documentation](https://www.swi-prolog.org/pldoc/man?predicate=read_history/6) and some links circle back to that page. Also `?- help(read_history)` is brief.

PPS. module-local operators seems really a must with newer SWI-Prolog versions, since libraries are dynamically loaded. Those will fail to load if operators are globally declared and clash with the libraries/modules, such as the `library(lists)` module that fails when declaring `op(1100, fx, (prefix))` in an application. Preloading `library(lists)` does not help in this case either. I understand that porting older Prolog programs that declare operators in the `user` module should use module-local operators instead. But this assumes that all IO can handle that, including `read_history/6`. Just my 2 cents.

**Comment by JanWielemaker** [comment]
Pushed db19e5a7243afb3d4f36948766f5b51a6023649b which provides read_term_with_history/2 that can do all this stuff.  Moved the read_history/6 to libarry(backcomp).

> since libraries are dynamically loaded

If all is right, libraries inherit operators and other syntax settings from the `system` module.   There was a bug in a series of versions that stopped this from working for the xpce (GUI) library.

Surely, one should use module-local operators unless compatibility with some system that doesn't have them is desired.  Notably SICStus has only global operators AFAIK.
