### ISSUE TITLE
pl-gc.c: makePtr: Assertion failed (crash)

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#67]
Please see the self-contained [crash example and backtrace](https://github.com/triska/clpb/tree/master/trail_crash).

Use `swipl -f crash.pl` to reproduce.

I can reproduce the crash with SWI 7.3.4, using Debian 8.1 (64-bit) and OSX Yosemite.

**Comment by JanWielemaker** [comment]
Thanks.  Was tricky, but should be fixed with ef416046c97437a57c2d685570898aaba27750c1
