### ISSUE TITLE
Table renderer doesn't show spaces

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#670]
Try this:
```
?- falsify_how(a+ ~b, R).
a+~b        
~b        
0
```
https://swish.swi-prolog.org/p/CannedQuine2.swinb

The table renderer removes the space between + and ~.
And this can lead to problems when copy pasting terms:
```
?- use_module(library(clpb)).
true.

?- sat(a+~b).
ERROR: Syntax error: Operator expected
ERROR: sat(
ERROR: ** here **
ERROR: a+~b) . 
```

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/swi-prolog-php-html/2937/29

**Comment by jburse** [comment]
In case spaces are removed. Might also consider replacing
them by \&nbps\; HTML entity. This prevents line breaks.

**Comment by JanWielemaker** [comment]
Fixed in Pengines package of SWI-Prolog.  Thanks for spotting.
