### ISSUE TITLE
Feature: The toplevel shortens "large lists" with ellipses, but doesn't hold back for "large dicts"

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#674]
Case:

Generate a large dict and bind a variable visible at the toplevel to it: The whole dict is printed. This is different than for a list, which is only printed up to a length specified via

```
set_prolog_flag(answer_write_options,[max_depth(100)]).
set_prolog_flag(debugger_write_options,[max_depth(100)]).
```

For example, this simple reader hoovers up a file in `main/4` and creates a large dict, with one entry per character. The toplevel then takes a long time to print the dict if it is somewhat large (... but how large can a dict reasonably be?)

```
main(Filename,LargeDict,Chars,Length) :-
    attempt(
	Filename,
	LargeDict,
	Chars,
	Length).

attempt(Filename,LargeDict,Chars,Length) :- 
    read_my_file(Filename,Chars,Length),    
    Max is Length-1,    
    findall(X,between(0,Max,X),Indexes),
    maplist([Char,Idx,(Idx-ch{idx:Idx,ch:Char})]>>true,Chars,Indexes,Pairs),
    dict_pairs(LargeDict,full,Pairs).

read_my_file(Filename,Chars,Length) :-
    open(Filename,read,Stream,[type(text),encoding(utf8)]),
    read_string(Stream,Length,String),
    close(Stream),
    atom_chars(String,Chars).
```

**Comment by JanWielemaker** [comment]
This is similar to compound terms of high arity, long atoms, long strings, and huge integers.   That doesn't mean it is right of course :)   One of the problems though is that we do not have a natural syntax to express the first part of a dict, compound, string, atom or integer as we have for lists ([a,b,c|...]).

Possibly a utility portray library such as `library(portray_text)` is the appropriate way to deal with this.  Portray/1 is designed to make huge or hard-to-read terms digestible for humans at the toplevel and during debugging.

**Comment by dtonhofer** [comment]
I think this can be closed for now.
