### ISSUE TITLE
Not coalescing LF CR could be good practice

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#677]
I am not 100% sure. But most line reading code I have seem
so far didn't coalesce LF CR. Only CR LF is coalesced.

Interestingly SWI-Prolog does coalesce 
LF CR, instead of giving LF LF:
```
?- open_string("abc\n\rdef\r\nghi", X), read_stream_to_codes(X, L, []), close(X).
X = <stream>(0000000006B14270),
L = [97, 98, 99, 10, 100, 101, 102, 10, 103|...].
```
To make a case, would need to show a tool, which doesn’t coalesce LF CR.

**Comment by jburse** [comment]
In Windows Notepad I see 4 lines:

![example](https://user-images.githubusercontent.com/5411487/94341824-dea69a00-000c-11eb-8a31-c1b9dc75cc8c.png)

If such a file comes as Prolog text and is consulted, error messages
line numbering might give wrong results, if LF CR is coalesced.

**Comment by JanWielemaker** [comment]
Please do not duplicate issues here and on the forum.   Closing.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/library-strings-dedent-string-indent-string-split-lines/2972/11

**Comment by jburse** [comment]
If you want to be compatible with Python, you probably
need to abandon LFCR coalesce in SWI-Prolog. I get this result:
```
Python 3.8.0 (default, Nov 14 2019, 22:29:45) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b'abc\n\rdef\r\nghi'.splitlines()
[b'abc', b'', b'def', b'ghi']
>>> 
```

[https://www.python.org/shell/](https://www.python.org/shell/)
