### ISSUE TITLE
"Out of global stack" although trail stack is primarily responsible

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#68]
When I do, with SWI 7.3.2 (64-bit):

<pre>
$ swipl <b>-T1m</b> -g "length(_,E),L is 2^E,write(L),write(' '),length(Ls,L), ignore((maplist(=(a),Ls),false)),false"
</pre>

then I get:

<pre>
1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144 
ERROR: Prolog initialisation failed:
ERROR: <b>Out of global stack</b>
</pre>

However, with the _same_ amount of global stack, and just increasing the _trail_ stack size, I get:

<pre>
$ swipl <b>-T2m</b> -g "length(_,E),L is 2^E,write(L),write(' '),length(Ls,L), ignore((maplist(=(a),Ls),false)),false"
1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144 <b>524288</b>
ERROR: Prolog initialisation failed:
ERROR: Out of global stack
</pre>

and increasing only the trail stack even further, I get:

<pre>
$ swipl <b>-T3m</b> -g "length(_,E),L is 2^E,write(L),write(' '),length(Ls,L), ignore((maplist(=(a),Ls),false)),false"
1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144 524288 <b>1048576 2097152</b>
</pre>

yet, still ending with:

<pre>
ERROR: Prolog initialisation failed:
ERROR: Out of <b>global</b> stack
</pre>

Thus, the trail stack is what should have been increased to get further solutions with this program.

If possible, please adapt the error message to reflect this. Thank you!

**Comment by JanWielemaker** [comment]
On 08/11/2015 06:33 PM, Markus Triska wrote:
> When I do, with SWI 7.3.2 (64-bit):
>
> $ swipl*-T1m*  -g "length(_,E),L is 2^E,write(L), write(' '),length(Ls,L), ignore((maplist(=(a),Ls),false)), false"
>
> then I get:
>
> 1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144
> ERROR: Prolog initialisation failed:
> ERROR:*Out of global stack*

Seems something odd in -g handling:

% swipl -T1m
?- catch((length(_,E),L is 2^E,write(L), write(' '),length(Ls,L), 
ignore((maplist(=(a),Ls),false)), false), Error, true).
1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072
Error = error(resource_error(stack), trail).

Low priority.

	--- Jan

**Comment by triska** [comment]
This is not limited to "-g". Consider for example:

    $ swipl -T1m

and the query:

    ?- catch((length(_,E), L is E^4, writeln(L), length(Ls,L), catch((maplist(=(a),Ls),throw(a)),a,true), false),Exc,true).

then I get:

<pre>
65536
<b>83521</b>
Exc = error(resource_error(stack), <b>global</b>).
</pre>

However, if I again extend *only* the *trail stack* with:

    $ swipl -T5m

then I get, for the same query:

<pre>
456976
<b>531441</b>
Exc = error(resource_error(stack), <b>global</b>).
</pre>

So, again it should have been the *trail* stack that must be increased, not the global stack.

**Comment by JanWielemaker** [comment]
The answer is in the code below.  For short, you get this type of mixup if the
trail stack limit is really low compared to the global limit.  Your case is an example of code that requires barely any trail space.  There is probably room for significant better heuristics on when
to GC, shift or signal out of stack.

```
/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(*) Some programs have a lot of global and hardly any trail requirement.
This means we gets lots of GCs for trail, which works fine, but they are
expensive due to the size of the global stack. As long as we do not have
generational GC, we make the trail free space proportional to the global
stack usage. This too isn't ideal; it is possible that simply nothing is
trailed and therefore it can be low.   Ideally, I think that the margins
should depend on the percentage of the   time spent in GC's triggered by
the stack. One of the problems we are   faced with is that not all OS'es
allow us to get per-thread CPU statistics.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

static size_t
tight(Stack s ARG_LD)
{ size_t min_room  = sizeStackP(s)/3;
  size_t spare_gap = s->def_spare - s->spare;

  if ( s == (Stack)&LD->stacks.trail )	/* See (*) */
  { min_room += sizeStack(global)/6;
    DEBUG(MSG_GC_SCHEDULE, Sdprintf("Trail min_room = %ld\n", min_room));
  }

  if ( min_room < s->min_free )
    min_room = s->min_free;

  if ( (size_t)roomStackP(s) < min_room + spare_gap )
    return 1;

  return 0;
}
```

**Comment by JanWielemaker** [comment]
Stack resizing and GC policy has been changed completely since.    Quite likely there are other issues, but this is outdated.  Closing.
