### ISSUE TITLE
Consider interpreting '\n' in SWISH

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#680]
SWISH doesn’t do transparent '\n' IO interpretation.
Seems to be rather that nl/0 is hooked.

<img width="481" alt="Bildschirmfoto 2020-09-27 um 11 20 55" src="https://user-images.githubusercontent.com/5411487/94361568-84154880-00b5-11eb-9000-545080cac714.png">

Doesn’t happen in the SWI-Prolog Mac console. I guess
the Mac console even interprets ‘\r’:

<img width="371" alt="Bildschirmfoto 2020-09-27 um 11 25 39" src="https://user-images.githubusercontent.com/5411487/94361571-88416600-00b5-11eb-9632-51fa5d9fa086.png">

Source code:
**Can SWISH interpret ‘\n’?**
[https://swish.swi-prolog.org/p/Newline.swinb](https://swish.swi-prolog.org/p/Newline.swinb)

**Comment by JanWielemaker** [comment]
Please do not open all these issues.  It has been explained and discussed several times how SWI-Prolog deals with newlines on Discourse.   SWISH has its own layer around I/O that is targeted at HTML rather than newline character codes.

**Comment by jburse** [comment]
HTML doesn't work on my side?

![Unbenannt](https://user-images.githubusercontent.com/5411487/94365729-7cfd3300-00d3-11eb-8e16-b01277045713.PNG)

What do you mean SWISH is for HTML output?

**Comment by JanWielemaker** [comment]
See library(pengines_io).

**Comment by jburse** [comment]
But SWISH is a client. Pengine is on the server. Thats not very 
helpful. Although queries are sent to the server.

I have the following usecase from Vidal:

**Comment by JanWielemaker** [comment]
write/1 translates a term into a complex HTML object that allows for folding, etc.   Use format/2 to write verbatim text.   It does use variable pitch font though, so better use HTML writing using https://swish.swi-prolog.org/example/html_output.swinb

**Comment by jburse** [comment]
format/2 does indeed something else.
Just out of curiosity I also checked CRLF:
```
format('~w',['  abc\n\r\r\n  def']).
  abc



  def
```
But TauProlog has no format/2. So its not portable.
And therefore I guess format/2 is a no-go.

**Comment by JanWielemaker** [comment]
Nasty.   write/1 map to a nested HTML ``<span>``, and you cannot have line breaks inside a span.  We could change the display to `inline-block`, but that still doesn't produce the right result if the atom with newlines is nested inside a compound.

The whole idea of write/1 is broken anyway.   It results in something that is neither intended to output text nor to output a term Prolog can read.   write/1 should have behaved as writeq/1 and format should have been part of the ISO standard.   Luckily quite a few systems have it.

SWISH is not a classical Prolog toplevel.  It is way more advanced.   As a result there are a few old scruffy things that no longer work.

**Comment by jburse** [comment]
You can configure `<PRE>` elements, so that they 
show space. No big deal. Here is an example CSS
entry to do that:

/* background */
```
.code2 {
    white-space: normal
}
```
I use this already for ages, to for example render this correctly:
```
fun(X, Y, Z, A) :-
   X =< Y, !,
   Z = A.
```
You could make cells, maybe a flag like the table render 
flag, that would  correctly show plain output. Again 
no big deal.

**Comment by jburse** [comment]
How can I overwrite write/1 ? This here works in SWISH:
```
show(X) :- html(span(style('white-space: pre'),X)).
```
And then:
```
?- show('  '), show('Hello').
  Hello
true
```
But when I do this:
```
write(X) :- html(span(style('white-space: pre'),X)).
```
I get error:
```
Redefined static procedure write/1
```

**Comment by JanWielemaker** [comment]
You can not, at least not in a sandboxed swish instance.   Probably goal_expansion/2 will work in SWISH.   Please stop using this as a question system.   It is on the wrong repo (moved several already) and this is not the purpose of an issue tracker.

**Comment by jburse** [comment]
But are my requirements now clear? I mean you closed the issue
without even knowing a blink of my requirements?

**Comment by JanWielemaker** [comment]
It won't work.   To print multiline stuff you cannot use write/1 and \n.  nl works, so does format and the HTML output support.   That is it.

**Comment by jburse** [comment]
Maybe use SWI-Prolog discourse to discuss this.
