### ISSUE TITLE
library(pengines_io) doesn't allow HTML

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#681]
See library(pengines_io).

_Originally posted by @JanWielemaker in https://github.com/SWI-Prolog/swipl-devel/issues/680#issuecomment-699634013_

**Comment by jburse** [comment]
You suggested the above library for HTML output.
Doesn' work on my side:

Tags are not interpreted. I made these test cases:

```
?- pengine_write('<b>hello</b> world!<br>').
<b>hello</b> world!<br>
true

?- pengine_format('~w', ['<br>  hello']).
<br>  hello
1true
```

Source code:
https://swish.swi-prolog.org/p/Pnegie.swinb

**Comment by JanWielemaker** [comment]
Prolog I/O escapes HTML syntax as it should.   To output HTML, see https://swish.swi-prolog.org/example/html_output.swinb.

**Comment by jburse** [comment]
Ok I see you mean library(http/html_write)) ? Right?

**Comment by JanWielemaker** [comment]
That is what it ultimately uses.

**Comment by jburse** [comment]
The library can do plain output, its relatively simple:
```
?- html(span(style('white-space: pre'),'  ')), html(span('Hello')).
  Hello
true
```
Works fine!
