### ISSUE TITLE
Output of frozen variable crashes depending on `write_attributes` flag

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#683]
SWIP version 8.3.7
MacOS 10.13.6 - command line or console

If `write_attributes` flag is set to something other than `ignore`, writing a frozen var can cause error ("ERROR: format/2: Not enough resources: portray_nesting") or crash (Segmentation fault: 11). Output looks like it's caught in a cyclic structure loop:

```
?- set_prolog_flag(write_attributes, portray).
true.

?- freeze(X,float(X)),write(X).
_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652{freeze(_10652
ERROR: format/2: Not enough resources: portray_nesting
?- set_prolog_flag(write_attributes, write).
true.

?- freeze(X,float(X)),write(X).
_17786{att(freeze,user:float(_17786{att(freeze,user:float(_17786{att(freeze,user:float(_17786{att(freeze,user:float(_17786{att(freeze,user:float(_17786{att(freeze,user:float(_17786{att(freeze,user:float(_17786{att(freeze

....

float(_17786{att(freeze,user:float(_17786{att(freeze,user:float(_17786{att(freeze,user:float(_17Segmentation fault: 11
```

```

**Comment by JanWielemaker** [comment]
I guess it depends on the definition of attr_portray_hook/1.   If this calls something that calls this hook again you may get into infinite recursion.   Note that freeze(X, float(X)) leads to a cyclic structure.  If for some reason the C stack is tight you get a SEGV.   The flag is old school.

**Comment by ridgeworks** [comment]
> I guess it depends on the definition of attr_portray_hook/1. If this calls something that calls this hook again you may get into infinite recursion.

So if `freeze` defines an `attr_portray_hook`, it has a bug. If it doesn't, there's a bug in `write` when the flag is set to `portray` and there is no `attr_portray_hook` for that attribute. But I think there's a bug somewhere.

Note that even when the flag is set to `write`, i.e., should be independent of any hook, writing frozen variables causes a crash.

> The flag is old school.

Is there anything to replace it? How should the output of attributes via `write` be supported?

**Comment by JanWielemaker** [comment]
> So if `freeze` defines an `attr_portray_hook`, it has a bug

Not sure I get that.  As far as I recall, attr_portray_hook/1 is called to print attributes.  If this hook calls write/1 or something similar with a term that contains attributes you have a recursive call.  Whether that terminates or not depends on the attributes and the hook, but as this freeze call leads to a cyclic structure it may well be non-terminating.

> Is there anything to replace it?

copy_term/3 and related hooks.

> How should the output of attributes via `write` be supported?

In itself, the portray hook is the only option to get attributes printed in a different way.   The whole thing may need a different angle from a higher level though.  I cannot judge that.

**Comment by ridgeworks** [comment]
> As far as I recall, attr_portray_hook/1 is called to print attributes. If this hook calls write/1 or something similar with a term that contains attributes you have a recursive call. Whether that terminates or not depends on the attributes and the hook, but as this freeze call leads to a cyclic structure it may well be non-terminating.

As I tried to say, if the `freeze` module defines an `attribute_portray_hook` and a cyclic (or other problematical) condition is possible, it needs to check for that and not cause non-termination or crashing. So if it doesn't, that's a bug in the `freeze` module.

If it doesn't define such a hook, then `write` has the same issue (IMHO). I don't think `write` crashes outputting cyclic structures so I'm not sure why outputting attributes does.

> copy_term/3 and related hooks.

And I do support these for top level output. But that doesn't help when a user uses `write` to output an attributed variable. 

> In itself, the portray hook is the only option to get attributes printed in a different way. The whole thing may need a different angle from a higher level though. I cannot judge that.

But in the meantime `attr_portray_hook` is the only option. So it seems premature to declare it "old school" just yet. If the solution is to modify `write` to use the same mechanism as the top level, I think that's probably OK.

**Comment by JanWielemaker** [comment]
> So if it doesn't, that's a bug in the `freeze` module.

Now I see.  It isn't really a module, but portraying the freeze attvars calls write/1, leading to recursion.   Pushed 7a91a24ede366b452fd027b4ce798c8445a85968 to fix this.

**Comment by ridgeworks** [comment]
OK, I see that freeze is implemented as a special case rather than through the hook. 

Is there any consensus on what should happen to `attr_portray_hook` in the longer term?
