### ISSUE TITLE
Minor: Confusing exception from `must_be/2`

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#685]
The deal is this:

`must_be(var,_)` throws. Good.
`must_be(nonvar,x)` throws. Good.

However, query words `bound` and `unbound` are unknown. 

```
?- must_be(bound,x).
ERROR: type `bound' does not exist
```

```
?- must_be(unbound,x).
ERROR: type `unbound' does not exist
```

Okay.

On the other hand:

```
?- must_be(unbound,X).
ERROR: Arguments are not sufficiently instantiated
```

```
?- must_be(bound,X).
ERROR: Arguments are not sufficiently instantiated
```

The above is confusing. The check for whether the 2nd argument is instantiated comes before the check for whether the query word actually exists. This should be reversed: first test the query word!

**Comment by JanWielemaker** [comment]
Makes sense.  Pushed 85712b112d560391f7a46f6bdac558bb64113426
