### ISSUE TITLE
Dict dereferencing with `.` happens too early inside a yall lambda expression

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#686]
This looks dicey:

I want to print `X.foo` "later" when I know about dict `X` (... just trying out how to get I/O monads in Prolog)

Consider:

```
test1(R) :- R = [Y]>>format("!!~q!!\n",[Y]).
test2(R) :- R = [Y]>>format("!!~q!!\n",[Y.foo]).
test3(R) :- R = [Y]>>(Q=Y.foo,format("!!~q!!\n",[Q])).
test4(R) :- R = [Y]>>(get_dict(foo,Y,V),format("!!~q!!\n",[V])).
```

In `test2/1` and `test3/1`, the dict dereferencing operator `.` is evaluated "too early", namely at expression call time when the dict to which `Y` is supposed to be bound is not known yet, rather than when it is really needed.

Good:

```
?- test1(R),call(R,12).
!!12!!
R = [_5530]>>format("!!~q!!\n", [_5530]).
```

Not good:

```
?- test2(R).
ERROR: Arguments are not sufficiently instantiated
ERROR: In:
ERROR:   [13] throw(error(instantiation_error,_8840))
```

Same problem with `test3/1`:

```
?- test3(R).
ERROR: Arguments are not sufficiently instantiated
ERROR: In:
ERROR:   [13] throw(error(instantiation_error,_10302))
```

But working around this with `test4/1` using explicit [`get_dict/3`](https://eu.swi-prolog.org/pldoc/doc_for?object=get_dict/3) works:

```
?- test4(R).
R = [_998]>>(get_dict(foo, _998, _1014), format("!!~q!!\n", [_1014])).

?- test4(R),call(R,_{foo:12}).
!!12!!
R = [_2974]>>(get_dict(foo, _2974, _2990), format("!!~q!!\n", [_2990])).
```

Sufficiently lazy!

Alternatively, without lambda expression and explicitly named predicate:

```
test5(R) :- R=execute_79790594.
execute_79790594(Y) :- format("!!~q!!\n",[Y.foo]).
```

Then

```
?- test5(R).
R = execute_79790594.

?- test5(R),call(R,_{foo:12}).
!!12!!
R = execute_79790594.
```

Yes, it works!

**Comment by JanWielemaker** [comment]
> test2(R) :- R = [Y]>>format("!!~q!!\n",[Y.foo]).

Prolog is not a typed language and this is the price.   `R = Term`  evaluates all functions in `Term` (and `R`).  To Prolog this is just a term, not a Lamda expression.   It only becomes one at the moment you pass it to call/2, but then the harm has already been done.

You can only _fix_ this in languages where lambda expressions are not ordinary data structures, so you know what is code that will eventually be executed and what is data.

**Comment by dtonhofer** [comment]
Thanks Jan.

It's not really a question of typing though - more than "evaluation eagerness". 

Anything that "looks like a dict dereferencing" inside a term is immediately reduced. The processor zeroes in on the dot expressions. Consider:

```
?- write_canonical(test2(R) :- R = [Y]>>format("!!~q!!\n",[Y.foo])).
ERROR: Arguments are not sufficiently instantiated
```

vs.

``` 
?- write_canonical(test2(R) :- R = [Y]>>format("!!~q!!\n",[Y])).
:-(test2(A),=(A,>>([B],format("!!~q!!\n",[B]))))
true.
```

There may even be nonsense (a typed language would not accept this, but in Prolog it's just some syntax tree):

```
?- write_canonical(x.y :- a).
ERROR: Type error: `dict' expected, found `x' (an atom)
```
or

```
?- write_canonical(X.Y.Z :- a).
ERROR: Arguments are not sufficiently instantiated
```

but

```
?- write_canonical(_{x:12,y:13}.x :- p).
:-(12,p)
true.
```

In fact, `.` behaves like an unquotable operation. Are there any other operators like that?

**Comment by JanWielemaker** [comment]
> It's not really a question of typing though - more than "evaluation eagerness".

That is another way to put it, I guess.   If you had typing and thus you know that a term is in fact something that will eventually get called you can avoid eager execution.   Without typing you need quoting.   That is not provided.  It could be, but there is no evident syntax that does not introduce ambiguity available.

You can return a dict function in a bit ugly way, using e.g.

      Func =.. [',', Dict, x].

That is ugly, but in the years dicts are around I think I only used this twice.   Note that this function only makes sense if it is processed by expand_goal/2 before being called.

I guess the simple conclusion is that the ./2 notation doesn't play with meta-arguments.   If you need that, use get_dict/3 or add an intermediate predicate.

This is more a discussion for the forum.
