### ISSUE TITLE
WASM:  -s BINARYEN_TRAP_MODE=clamp

### ISSUE THREAD

**Issue by jacobfriedman** [SWI-Prolog/swipl-devel#690]
BINARYEN_TRAP_MODE=clamp needs to be removed from both web & node builds of EmscriptenTargets.cmake in order for the dockerfile to build the WASM.

**Comment by JanWielemaker** [comment]
Ok.  Removed.  Not tested.   Please close when ok.

**Comment by jacobfriedman** [comment]
Will do with @rla (please pull the latest swipl-wasm and run the docker)
