### ISSUE TITLE
Ahnlab V3 detects swipl-ld.exe as a malware SWI-Prolog v8.2.1

### ISSUE THREAD

**Issue by Dongw1126** [SWI-Prolog/swipl-devel#694]
While using the program, some antivirus programs have detected swipl-ld.exe as a malware. Can I use it without worry? 

![image](https://user-images.githubusercontent.com/48395704/96359808-0099c500-1152-11eb-9950-8cb49ddc020c.png)

[VirusTotal Scan Result](https://www.virustotal.com/gui/file/666c6dccd13c882127e49fcb5b1e646145766ccfac7b2a2b31693d21fd072cc8/detection)

**Comment by JanWielemaker** [comment]
There have been long discussions about this.  See e.g., https://swi-prolog.discourse.group/t/parts-of-website-blocked-by-google-safe-browsing/1365/35.

The bottom line is that virus scanners seems to have a probability of approx 3% to detect an executable of the size of SWI-Prolog as a virus.   Promising should be that each binary has a different individual scanner that complains and typically a totally different piece of malware or virus.   Complaining helps, but with an approx 2 weeks release cycle that is rather cumbersome.

SWI-Prolog binaries for Windows are built from the git source inside a Docker container.   All the code to do so is publicly available.   The build process itself is IMO rather hard to compromise.   The sources have integrity checking by GIT and are being watched by quite a few people which should make it pretty hard to ingest a virus.

That said, software is a matter of trust.
