### ISSUE TITLE
Minor: format/2 going too far: A string of length 1 is interpreted as a float by obtaining the code point 

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#697]
It's minor but this is should throw IMHO. 

The string's character is transformed into a codepoint and printed as float.

I can't imagine anyone doing such a thing and expecting a valid outcome. If he/she does an exception would be appropriate punishment.

Recommending `type_error("float",Culprit)`.

```
?- format("|~e|",["1"]).
|4.900000e+01| 
true.
```

Multi-character string at least throws, but should throw type_error:

```
?- format("|~e|",["11"]).
ERROR: Type error: `[]' expected, found `"11"' (a string) ("x" must hold one character)
ERROR: In:
ERROR:   [10] format("|~e|",["11"])
ERROR:    [9] toplevel_call(user:user: ...) at /usr/local/logic/swipl/lib/swipl/boot/toplevel.pl:1113
```

OTOH character delivers vandermeer levels of Weird, should also throw type_error.

```
?- format("|~e|",['1']).
ERROR: Arithmetic: `'1'/0' is not a function
ERROR: In:
ERROR:   [10] format("|~e|",['1'])
ERROR:    [9] toplevel_call(user:user: ...) at /usr/local/logic/swipl/lib/swipl/boot/toplevel.pl:1113
```

**Comment by JanWielemaker** [comment]
> I can't imagine anyone doing such a thing and expecting a valid outcome.

It is.  Notably to deal with the old rational number handling, a format argument that must be a number uses arithmetic evaluation.  This is just 

    ?- A is "1".
    A = 49.

Which is the (somewhat old fashioned) way to use get character codes into arithmetic expressions.    Basically that evaluates a list holding a single integer to the integer.  As "1" is no longer [49], this conversion now also deals with one-character strings.
