### ISSUE TITLE
library(debug) should maybe export a debug/2, to mirror format/1

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#699]
Concerning [`library(debug)`](https://www.swi-prolog.org/pldoc/man?section=debug):

There is 

- `format/1` to print parameterless messages
- `format/2` to print parameterfull messages

However there is only

- `debug/3` to debug-print parameterfull messages

Suggestion the addition of `debug/2` to mirror `format/1` and allow the printing of parameterless debug messages.

**Comment by JanWielemaker** [comment]
I'm more inclined to call format/1,2,3 a mistake (inherited from Quintus Prolog).   Notably the /2 version is always confusing whether it is stream,format or format,arguments.    In my experience debug/2 is not often enough needed to be worth a separate predicate.   For anyone disagreeing it is easy enough to define yourself :)

**Comment by dtonhofer** [comment]
Thanks Jan. Makes sense. Closing.
