### ISSUE TITLE
writeq displays invalid atom

### ISSUE THREAD

**Issue by kintalken** [SWI-Prolog/swipl-devel#701]
writeq displays an invalid atom in the following two (for example) cases .

```
?- A='\u0000' , writeq(A) .
'\000\'
A = .

?- A='\u0001' , writeq(A).
'\001\'
A = .
```

**Comment by JanWielemaker** [comment]
``'\001\'`` is the canonical ISO compliant representation.  `'\uXXXX'` is a SWI-Prolog extension.

    ?- '\001\' == '\u0001'
    true.
