### ISSUE TITLE
call_with_inference_limit/1 leaves a stray choice open when inference limit exceeded

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#702]
At the manual page for [`call_with_inference_limit/3`](https://eu.swi-prolog.org/pldoc/doc_for?object=call_with_inference_limit/3) Stephan Krall has posted a comment in 2016:

> Concerning SWI-Prolog version 7.3.16: Is there a particular reason why call_with_inference_limit/3 
> leaves behind a superfluous choice point in the case Result == inference_limit_exceeded?
>
> Looking at the [source code](http://eu.swi-prolog.org/pldoc/doc/home/swipl/lib/swipl/boot/syspred.pl?show=src#call_with_inference_limit/3) of call_with_inference_limit/3 in boot/syspred.pl, I think that 
> changing (Result0 == ! -> ! ; true) to (Result0 \== inference_limit_exceeded -> ! ; true) in
>  line #665 could do the trick without causing much havoc... Have I been missing something?

This is still the case. 

```
?- call_with_inference_limit(bagof(X,between(1,inf,X),Bag),10,Result).
Result = inference_limit_exceeded ;
false.
```

Should this be fixed or should the manual mention this?

**Comment by JanWielemaker** [comment]
Thanks.  Should be fixed with 10b3738efcd88b76e5c23598b26d9e5102fc2f37
