### ISSUE TITLE
ninja: error: 'man/archive', needed by 'man/lib/prologpack.tex', missing and no known rule to make it

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [SWI-Prolog/swipl-devel#704]
AArch64, Fedora 33

Is something missing, but mandatory of these?: 

cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
-- Configuring SWI-Prolog-8.3.11
-- Could NOT find LibUUID (missing: LIBUUID_INCLUDE_DIR)
-- Could NOT find LibArchive (missing: LibArchive_LIBRARY LibArchive_INCLUDE_DIR)
-- Could NOT find ODBC (missing: ODBC_LIBRARY ODBC_INCLUDE_DIR)
-- Optional package Berkeley DB was not found
-- Could NOT find LibYAML (missing: LIBYAML_INCLUDE_DIR YAML_LIBRARY)
-- No junit.jar. Make sure junit.jar points to junit4.jar  Dropping JPL tests.
-- Could NOT find Qt5Widgets (missing: Qt5Widgets_DIR)
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Dropped xpce
  Could not find JPEG
-- Could NOT find Libedit (missing: LIBEDIT_LIBRARIES LIBEDIT_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: /data/jw/Prolog/Prolog/build

**Comment by JanWielemaker** [comment]
Not really mandatory, but you should disable building the documentation if you want to install a subset of the packages.   libarchive is needed by the archiving library, which is needed by the SWI-Prolog package manager.

In most cases, I'd advice to install all dependencies, possibly except for Java, Qt5, odbc and bdb if you know you do not need these.   If you need just a minimal version for some service, select the packages you need and disable building the documentation.

**Comment by pkoch** [comment]
I solved this with `sudo apt install libarchive-dev`. Maybe we should add that to [CMAKE.md](https://github.com/SWI-Prolog/swipl-devel/blob/b075866e11035a649ed707542979c6d5828d05df/CMAKE.md)?

**Comment by JanWielemaker** [comment]
Some additional nodes to CMAKE.md might be the way to go.   Alternatively we could sort out which packages are really needed to avoid failing on the docs and simply drop the docs if one is missing.   Eventually I'd like to reduce the dependencies.   Getting a clear picture on them is probably still useful ...

**Comment by pkoch** [comment]
All those alternatives seem reasonable. I'd maybe suggest adding a warning when we skip some step for lack of dependencies (so the user is more aware of what's going on and what would be the direction for enabling the missing features).

As a quick start to spare people a Google search, adding the missing dependency seems like the right next step here.

**Comment by JanWielemaker** [comment]
Ok.  Pushed a3492b62519ff41e8fbefb7ee9474273d3f757f0 to check and drop docs if a dependency is missing.  Not sure if all dependencies are listed, but the commonly reported culprits are listed.

**Comment by pkoch** [comment]
I don't know enough CMake to confirm it's right, but the spirit of the change looks great! Thank you! 🎉
