### ISSUE TITLE
Edge case optimization: Calling reset/ on a goal whose last instruction is the shift/1 call _could_ yield a continuation of 0

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#708]
We find:

```
?- reset(shift(X),X,Cont).
Cont = call_continuation([]).
```

or more extensively

```
top(Cont) :- reset(foo,_,Cont).   
foo :- shift(_).
```

when called:

```
?- top(Cont).
Cont = call_continuation([]).
```

Unless I am mistaken, a _slight_ optimization might be to have the continuation be 0 on return of `reset/3` because nothing will happen anymore if the non-zero continuation is called. 

This doesn't even affect backtracking, as we have the same behaviour in case of a final `shift/1`:

```
top(Cont) :- reset(foo,_,Cont).   
foo :- (format("a\n");format("b\n")),shift(_).
```

with

```
?- top(Cont).
a
Cont = call_continuation([]) ;
b
Cont = call_continuation([]).
```

versus

```
top(Cont) :- reset(foo,_,Cont).   
foo :- (format("a\n");format("b\n")).
```

with

```
?- top(Cont).
a
Cont = 0 ;
b
Cont = 0.
```

On the other hand, there is probably code which does not check for the instantiation of `Ball` when a 0 appears at the `Continuation` position. So it will miss the "last message out":

_last message out is `foo`_ 

```
?- reset(shift(foo),X,Cont).
X = foo,
Cont = call_continuation([]).
```

but will existing code be able to deal with this imaginary case??

```
?- reset(shift(foo),X,Cont).
X = foo,
Cont = 0.
```

**Comment by JanWielemaker** [comment]
True.   I'm rather reluctant do make such a change though.   First of all, a shift/1 was called and changing the continuation to `0` we cannot detect this anymore.   As nothing is executed after the shift, this is logically the same, but what if the the shift/1 is used to discover dependencies such as currently happening in _monotonic_ tabling?   That (I think) will break.    Considering that `call_continuation([])` is a fact I don't expect much will be gained.

**Comment by dtonhofer** [comment]
Thanks Jan. A fraught optimization then, as I thought. Better close this.
