### ISSUE TITLE
rdf/4 on one graph returns invalid results on backtracking if data inserted into another graph between solutions

### ISSUE THREAD

**Issue by EricZinda** [SWI-Prolog/swipl-devel#709]
Ok, I've spent many days narrowing this down from a big code base and believe there is a bug in the rdf store when reading from one graph and writing to another in the same query.  This one was really hard to get a small repro case for, I apologize for the size in advance...

Running test/2 (from the attached file) over and over in a fresh Prolog console will return different results even though it only queries the rdf graph called 'default' and the only changes are to the rdf graph called 'otherGraph'. These changes are made while the query is running.

I believe it is an rdf bug because:
- All calls to rdf/4 specify the graph 'default'. rdf/3 is never called.
- All calls to rdf_assert/4 *after loading* specify the graph 'otherGraph'.  rdf_assert/3 is never called

It seems to be sensitive to how much data is in the rdf store and how much gets added while the query is running.  It also seems to be sensitive to the kind of data that is added to the store while the query is running.  Just adding 600 rows of the same data didn't repro it for me.

Here is the test that runs to give a flavor of the repro.  The rest of the code is in the attached file.
~~~
% Backtrack over all places and all rocks in the graph called 'default'
% adding 600 items to a different graph called 'otherGraph' between each solution
test(Place, Rock) :-
    % Find all things named "place" in 'default' graph
    nameOf(Place, 'place', _), 
    % Find all things named "rock" in 'default' graph
    nameOf(Rock, 'rock', _), 
    % Add 600 items to a graph named 'otherGraph'
    addItems(600).
~~~

Sometimes it takes running this a few times to get a different result.  Also I've found that running from a fresh Prolog instance makes it repro better.

In a restarted console of SWI-Prolog (threaded, 64 bits, version 8.2.1), rename [Bug.txt](https://github.com/SWI-Prolog/swipl-devel/files/5540027/Bug.txt) to Bug.pl and:
~~~
?- consult(["/...path.../bug.pl"]).
true.

?- findall([Place, Rock], test(Place, Rock), Test).
% These are the expected results
Test = [[idRock1,idRock1],[idRock1,idRock2],[idRock1Bottom,idRock1],[idRock1Bottom,idRock2],[idRock2,idRock1],[idRock2,idRock2],[idRock2Bottom,idRock1],[idRock2Bottom,idRock2],[idRock2Bottom,idRock1],[idRock2Bottom,idRock2],[idPlage,idRock1],[idPlage,idRock2],[idPlageInside,idRock1],[idPlageInside,idRock2]].

% See that the results are different and include some duplicates even though the code doesn't modify the graph being queried
?- findall([Place, Rock], test(Place, Rock), Test).
Test = [[idRock1,idRock1],[idRock1,idRock2],[idRock1Bottom,idRock1],[idRock1Bottom,idRock2],[idRock2,idRock1],[idRock2,idRock2],[idRock2,idRock1],[idRock2,idRock2],[idRock2Bottom,idRock2],[idRock2Bottom,idRock1],[idPlage,idRock2],[idPlage,idRock1],[idPlageInside,idRock2],[idPlageInside,idRock1],[idRock1Bottom,idRock2],[idRock1Bottom,idRock1],[idRock2,idRock2],[idRock2,idRock1],[idRock1,idRock2],[idRock1,idRock1],[idRock2Bottom,idRock2],[idRock2Bottom,idRock1],[idPlage,idRock2],[idPlage,idRock1],[idPlageInside,idRock2],[idPlageInside,idRock1]].
~~~

**Comment by JanWielemaker** [comment]
After a little change to your test

```
t :-
    setof(Place-Rock, test(Place, Rock, 0), Ok),
    (   between(1, 100, I),
        setof(Place-Rock, test(Place, Rock, 600), Ret),
        (   Ok == Ret
        ->  format('~p: ok~n', [I])
        ;   ord_subtract(Ret, Ok, Extra),
            format('~p: Extra: ~p~n', [I, Extra]),
            ord_subtract(Ok, Ret, Missing),
            format('    Missing: ~p~n', [I, Missing])
        ),
        fail
    ;   true
    ).
```

And test/3 as

```
test(Place, Rock, N) :-
    % Find all things named "place" in 'default' graph
    nameOf(Place, 'place', _),
    % Find all things named "rock" in 'default' graph
    nameOf(Rock, 'rock', _),
    % Add 600 items to a graph named 'otherGraph'
    addItems(N).
```

It nicely says ok 100 times.  What you observe are side effects of the re-hashing.   This process can lead to tempory change of ordering as well as temporary duplicates.   As neither order nor duplicates are semantically relevant in RDF this has always been considered acceptable behavior.

**Comment by EricZinda** [comment]
Dang.  It thought that this phrase from the [doc](https://www.swi-prolog.org/pldoc/man?section=semweb-rdf-db):
> Modifications follow the Prolog logical update view semantics, which implies that modifications remain invisible to already running queries. 
meant this was a bug. 

My issue is that In my real app I have a ton more data and the duplicates are really killing performance as they force a lot more backtracking.  The only thing I really need from rdf at this point is nested transactions.  Any ideas for workarounds or alternative libraries?

**Comment by EricZinda** [comment]
I'll post this question in the discourse instead to make it more visible since we're beyond this particular issue now.  Thanks Jan!

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/behavior-of-a-backtracking-query-when-rdf-assert-1-or-assert-1-are-made-during-execution/3262/1
