### ISSUE TITLE
Singleton variable

### ISSUE THREAD

**Issue by PtrMan** [SWI-Prolog/swipl-devel#710]
```
t(constF(V), Dict, DictOut, OutIdx, [instr("LD_IMMF32", V, OutIdx)]) :-
    OutIdx = Dict.val, % retrieve outputIdx from dict
    NewVal is OutIdx+1,
    DictOut = Dict.put([val=NewVal]). % set new Idx
```
The web version of swiprolog (running 8.3.11) says that V is a singleton variable, but it appears more than once (and is unified correctly).

**Comment by JanWielemaker** [comment]
I don't see this.   Tried https://swish.swi-prolog.org/p/HyRKbwDS.pl

**Comment by PtrMan** [comment]
I should try the code :D . I guess I'll update this after I did isolate it :/

**Comment by JanWielemaker** [comment]
The online version occasionally does not update the highlighting.   If that happens, either reload the page or toggle __Semantic highlighting__ from the __Edit__ menu off and back on .
