### ISSUE TITLE
DOC: Wrong precedence given for bar in Sec. 4.25

### ISSUE THREAD

**Issue by fnogatz** [SWI-Prolog/swipl-devel#713]
Sorry, I could not find the sources of Section 4.25 from the reference manual ([html](https://www.swi-prolog.org/pldoc/man?section=operators) | [pdf](https://www.swi-prolog.org/download/stable/doc/SWI-Prolog-8.2.1.pdf#page=200)) to fix this on my own. Table 4.2 lists all of SWI's built-in operators, where the bar `|` is wrongly mentioned at precedence 1100, while it is at least for the last twelve years of precedence 1105 :owl:

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 41ac2b3504148bf9b661abc54070f17a0f81154b (which also indicates where the search).

**Comment by fnogatz** [comment]
Alright, next time I use grep again instead of GitHub's search :innocent:
