### ISSUE TITLE
Build failure with -DUSE_SIGNALS=OFF

### ISSUE THREAD

**Issue by plenarius** [SWI-Prolog/swipl-devel#736]
I was just experimenting with some of the build options and noticed this failure introduced due to this commit? https://github.com/SWI-Prolog/swipl-devel/commit/9cc35d9206e7aa87a2c5b6edc69225a991940b99

```
[329/337] Linking C executable src/swipl
FAILED: src/swipl 
: && /usr/lib/ccache/cc -O2 -gdwarf-2 -g3  -Wl,--export-dynamic -rdynamic src/CMakeFiles/swipl.dir/pl-main.c.o  -o src/swipl  -Wl,-rpath,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: src/libswipl.a -lcurses /usr/lib/x86_64-linux-gnu/libform.so /usr/lib/x86_64-linux-gnu/libz.so -ldl -lm -lrt && :
src/libswipl.a(pl-trace.c.o): In function `enable_debug_on_interrupt':
/home/jmg/Development/swipl-devel/build2/../src/pl-trace.c:1769: undefined reference to `terminate_on_signal'
/usr/bin/ld: src/swipl: hidden symbol `terminate_on_signal' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by JanWielemaker** [comment]
Just using it as a plain option leads to zillions of errors and warnings.   What other options did you pass and on which platform?   The option was added for platforms that do not have signals like WASM.   If you merely do not want signals use the `--no-signals` option (often used for embedding).

If there is some realistic setting that is broken by this patch I guess some `#ifdef` tweak can fix this.   Without the whole context it is a bit hard to see where and how.  Can you make a PR to fix your case?  Note that the CMake flag cause (notably) `HAVE_SIGNAL` to remain undefined.

**Comment by plenarius** [comment]
Thanks, I have no real world setting I just thought I'd report the issue but am content with your explanation. I was merely trying to pare down my static build as small as possible with CMake options and caught this build failure and figured I'd pass along the info. Feel free to close.

**Comment by JanWielemaker** [comment]
SWI-Prolog was never designed to be _as small as possible_.  I'm happy to handle PRs that allow making it smaller as long as these do not make the code and/or configuration too ugly.
