### ISSUE TITLE
SICStus emulation doesn't load library(dialect/sicstus/lists) in place of library(lists)

### ISSUE THREAD

**Issue by dgelessus** [SWI-Prolog/swipl-devel#742]
When `expects_dialect(sicstus)` is active, uses of `library(lists)` aren't redirected to `library(dialect/sicstus/lists)` as expected - it seems that the regular SWI `library(lists)` is used instead. This only affects `library(lists)` as far as I can tell - other overridden libraries like `library(terms)` are correctly loaded from the dialect subdirectory.

Tested using latest SWI-Prolog built from source (daafaa7beddd8e153b751d82b65aa9880a58d339). Minimal repro code:

```prolog
:- module(testthing, [test1/2, test2/2]).

:- expects_dialect(sicstus).
:- use_module(library(lists)).
:- use_module(library(terms)).

% SICStus-specific predicate from library(lists) - doesn't work.
test1(Sub, List) :- sublist(Sub, List).
% SICStus-specific predicate from library(terms) - works.
test2(Term, Bag) :- term_variables_bag(Term, Bag).
```

```prolog
[debug]  ?- test1(Sub, [1, 2]).
ERROR: Unknown procedure: testthing:sublist/2
ERROR: In:
ERROR:   [11] testthing:sublist(_57646,[1,2])
ERROR:   [10] testthing:test1(_57690,[1,2]) at <builddir>/testthing.pl:8
ERROR:    [9] toplevel_call(user:user: ...) at <builddir>/home/boot/toplevel.pl:1113
   Exception: (11) testthing:sublist(_48770, [1, 2]) ? leap
[debug]  ?- test2(a(B, c(D)), Vars).
Vars = [B, D].
[debug]  ?- current_module(sicstus_lists).
false.
[debug]  ?- current_module(sicstus_terms).
true.
```

If I manually replace `:- use_module(library(lists)).` with an explicit `:- use_module(library(dialect/sicstus/lists)).`, the code works as expected. So this seems to be just a problem with the loading process, not with `library(dialect/sicstus/lists)` itself.

```prolog
?- test1(Sub, [1, 2]).
Sub = [1, 2] ;
Sub = [1] ;
Sub = [2] ;
Sub = [].
?- current_module(sicstus_lists).
true.
```

**Comment by JanWielemaker** [comment]
Thanks.   Pushed three patches to address this issue and in general force loading SWI-Prolog's own libraries in `swi` dialect mode.  See git log messages.   Please give it a try ...

**Comment by dgelessus** [comment]
Yes, this seems to have fixed it, thank you!
