### ISSUE TITLE
Keypath for dictionaries does not work

### ISSUE THREAD

**Issue by abrandst** [SWI-Prolog/swipl-devel#744]
The manual https://www.swi-prolog.org/pldoc/man?section=bidicts states that for a dictionary .get may be used with a keypath, e.g a/b.
It gives the following example:

> ?- write(t{a:t{b:x}}.get(a/b)).
> x
> 

However, using SWI-Prolog 8.2.3(AMD64, Multi-threaded), I cannot reproduce the example.
Instead I get the following error:

> ?- write(t{a:t{b:x}}.get(a/b)).
> ERROR: Type error: `dict-key' expected, found `a/b' (a compound)
> ERROR: In:
> ERROR:   [13] get_dict(a/b,t{a:t{b:x}},_3632)
> ERROR:   [10] '<meta-call>'(user:user: ...) <foreign>
> ERROR:    [9] <user>
> ERROR:

**Comment by abrandst** [comment]
Tried again with the latest development release 8.3.15 - it works there. Is that a feature not available in the latest stable release?

**Comment by JanWielemaker** [comment]
It is new tro 8.3.15.
