### ISSUE TITLE
Windows 10 expand_file_name/2 with filenames including `€' has problems

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#747]
Maybe some Windows 10 filename encoding hell issue, I am somewhat confused about how latest Windows 10 handles filename encoding, yes I know, using special characters in Windows filenames is asking for trouble, Not sure, but I had a few months old SWI-Prolog that didn't have this problem. Also could be a some Windows 10 version update thing. 
Scandinavian characters äöå does not cause problesm. 

```
Welcome to SWI-Prolog (threaded, 64 bits, version 8.3.15)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word)

?- make_directory(tmp).
true.

?- cd(tmp).
true.

?- tell('test€.txt'),writeln('Merry Christmas'),told.
true.

?- expand_file_name('te*.*',A).
A = [].

?- directory_files('.',Li),member('test€.txt',Li).
Li = ['.', .., 'test€.txt'].

?- current_prolog_flag(encoding,Enc).
Enc = text
```

**Comment by JanWielemaker** [comment]
Pushed c2dbf22b871756a6e830398a3516c2f9f9ff04ad to address this.   There isn't that much wrong with Windows in this respect.   It is mostly hard to make Windows and Unix play the same game.

Should be in tomorrows daily.
