### ISSUE TITLE
Problem with 99 bottles of beer

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#749]
Are interrupts still working? Take the following code and query:
```
bottles(X) :-
    write(X), write(' bottles of beer on the wall,'), nl,
    write(X), write(' bottles of beer,'), nl,
    write('Take one down, and pass it around,'), nl,
    X1 is X - 1,
    write(X1), write(' bottles of beer on the wall.'), nl,
    bottles(X1).
bottles(1) :-
    write('1 bottle of beer on the wall, 1 bottle of beer,'), nl,
    write('Take one down, and pass it around,'), nl,
    write('Now they are alle gone.'), nl.

?- bottles(99).
```
With SWI-Prolog 8.3.15 on Windows Ctrl-C doesn’t halt the query.

Has the default behaviour changed?

**Comment by JanWielemaker** [comment]
See https://swi-prolog.discourse.group/t/debugger-interrupts/3339/5?u=jan

Please, do not raise problems in two places.

**Comment by jburse** [comment]
Actually I raised it on 3 places. Was first genuinely intersted in
the 99 bottles problem for some other reasons on stackoverflow, 
and then put the problem on GitHub and on SWI-Prolog discourse.

**Comment by jburse** [comment]
But this is like the 3rd time you harass me on GitHub.
Nexttime I will escalate to GitHub team, unless you 
remove your harassement.
