### ISSUE TITLE
Inconsistent arithmetic with unary minus and power

### ISSUE THREAD

**Issue by genivia-inc** [SWI-Prolog/swipl-devel#750]
~~~
?- X is - 2^2.
X = -4.

?- X is -2^2.
X = 4.

?- Y is 2, X is -Y^2.
Y = 2,
X = -4.
~~~
The unary minus should not be parsed as part of the number to prevent this flaw. Or alternatively, the operator precedences should be changed to give unary minus a higher precedence than power. But that could break things.

PS. this is with SWI-Prolog 8.2.1.

**Comment by JanWielemaker** [comment]
Hi Robert,   I fear it is mostly what it is.   The Prolog standard prescribes the operators and the fact that a negative number is a token.   The rest "happens".   In fact, the ISO standard also dictates "- 2" to be the token -2, which is where SWI-Prolog differs (as most older Prolog systems did).   So, in GNU-Prolog (pretty strict standard) you get 4,4,-4 as results.

I fear the only option is to write (-2)^2 or -(2^2).    Ideally we should probably flag these using ambiguous warnings as e.g. gcc does on legal constructs that are known to have a different meaning than many users expect.

**Comment by genivia-inc** [comment]
I agree it's not trivial as the parser accepts -2 as a number. Probably leave it as it is.

The same problem happens in B-Prolog. [Picat](http://picat-lang.org/) fixed this.
