### ISSUE TITLE
slightly confusing error message

### ISSUE THREAD

**Issue by koo5** [SWI-Prolog/swipl-devel#752]
```
?- number_string(N, compound()).
ERROR: Type error: `list' expected, found `compound()' (a compound)
```

**Comment by JanWielemaker** [comment]
I see.   Not easy to fix elegantly.  Either requires a lot of code duplication or changes to the C api to be explicit about which error to throw in addition to which types to accept.   I think I'll leave it as is for now.   Thanks for noting.
