### ISSUE TITLE
gtrace runs past its invocation point

### ISSUE THREAD

**Issue by koo5** [SWI-Prolog/swipl-devel#757]
Most of the issues i report are minor confusions, but this one bothers me a lot. If i call gtrace somewhere in my code, it often "overruns" the invocation point. It doesn't break where it's called (or in the next invoked clause), but somewhere 5 levels deep in the call stack. It's also not possible to get back to the correct clause. I click in the stack trace pane, but the code and variables are not displayed. Stepping will also not get me there. 

This happens on all versions tested so far, with and without --debug arg and 'debug' prolog flag.

The CLI 'trace' behaves as expected.

**Comment by JanWielemaker** [comment]
Doesn't really ring a bell.   Please try to create an example that can be reproduced.

**Comment by koo5** [comment]
figured it out: "cluster variables", second option in gtrace settings. Turn it off and gtrace goes haywire on pretty much any piece of code

**Comment by JanWielemaker** [comment]
Thanks.   The issue with disabling clustering is resolved.

**Comment by koo5** [comment]
nice, thanks!
