### ISSUE TITLE
In Windows, trailing forward slash at end of file path does not fail exists_file/1

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#764]
In Linux, exists_file/1 throws an exception. Well this issue affects only temporarily bad programmers that sometimes use malformed prolog file paths :) 

```
?- delete_file('tmp.txt').
true.

?- tell('tmp.txt'),writeln(true),told.
true.

?- exists_file('tmp.txt/').
true.

?- exists_directory('tmp.txt').
false
```

**Comment by JanWielemaker** [comment]
SWI-Prolog's path rewrite for Windows deletes the trailing `\`, but after removing that, it turns out Windows does the same.   With a lot of work we could of course work around this in the emulation layer.   I think it isn't worth the trouble though.
