### ISSUE TITLE
Create compound term with arity 0

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#766]
How does the creation of a compound term with arity 0 work?

Based on [documentation](https://www.swi-prolog.org/pldoc/doc_for?object=compound_name_arity/3) I was expecting the following to bind `X` to `test()`, but instead I receive a difficult to interpret error message:

```prolog
?- compound_name_arity(X, test, 0).
X = 
    [[ EXCEPTION while printing message '~W'
       with arguments [test(),[priority(699),partial(true),quoted(true),portray(true),max_depth(10),spacing(next_argument)]]:
       raised: domain_error(compound_non_zero_arity,test())
    ]]
.
```

I'm using the latest commit from master.

**Comment by JanWielemaker** [comment]
?  I get this, as one would expect.   Anything conflicting in your init file?

```
> swipl -f none
Welcome to SWI-Prolog (threaded, 64 bits, version 8.3.17-1-gb108d986b-DIRTY)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

    CMake built from "/home/janw/src/swipl-devel/linux"

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- compound_name_arity(X, test, 0).
X = test().

?- 
```

**Comment by wouterbeek** [comment]
Strange...

I do the following for commit `20e1b4e77e611be2f8e079c77bff96c916cf6028`:

```sh
cd Debug
rm -rf *
cmake .. -D CMAKE_BUILD_TYPE:STRING=Debug -G Ninja
cmake --build .
sudo cmake --install .
swipl -f none
```

And then in Prolog:

```prolog
?- compound_name_arity(X, test, 0).
X = 
    [[ EXCEPTION while printing message '~W'
       with arguments [test(),[priority(699),partial(true),quoted(true),portray(true),max_depth(10),spacing(next_argument)]]:
       raised: domain_error(compound_non_zero_arity,test())
    ]]
.
```

Is there anything else on my side that could explain this?

**Comment by JanWielemaker** [comment]
Turns out to be the debug build.   Looks like some print hook only used in debug mode.  Why do you compile for debugging?  That makes little sense unless you need to debug some deep down issue in Prolog itself.

**Comment by JanWielemaker** [comment]
Had a quick look.   The problem is a portray/1 rule for debugging tabling.   Pushed 69674e403fdf5b7744bda0b8f509e53591c8d762 to fix this.

**Comment by wouterbeek** [comment]
Thanks for fixing Jan!

I was using the debug build to have better feedback for the other bug that I reported (file names and line numbers), or is this not different between the Debug and Release builds?

**Comment by JanWielemaker** [comment]
The normal build includes GCC symbols, so if you run under gdb you get correct files and lines.  Only many automatic variables are marked as _optimized out_ and single stepping in optimized code is sometimes a bit weird.
