### ISSUE TITLE
Printing compound terms containing 0-arity subterms

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#767]
`print_term/2` from library `pprint` emits errors for some compound terms.  It's a bit difficult to come up with an MWE, but I've whittled down a lengthy AST to the following reproducible example:

```prolog
?- [library(pprint).
?- print_term(x('GroupGraphPattern'(['GroupOrUnionGraphPattern'(['BIND'('AS'('BNODE'(),var(list)))])])), []).
```

which results in the following error:

```
ERROR: Domain error: `compound_non_zero_arity' expected, found `'BNODE'()'
```

**Comment by JanWielemaker** [comment]
Thanks.  Pushed 62bb72b389545b7b2e0d6d407c0237f38f628549 to fix this.   You'll probably find more high level behavior that fails to deal with zero-argument compounds ...   Their use is first of all in dealing with DSLs where `name()` is a useful notation.
