### ISSUE TITLE
tmp_file and tmp_file_stream don't create random files and collide with concurrent use

### ISSUE THREAD

**Issue by rrooij** [SWI-Prolog/swipl-devel#772]
The tmp_file and tmp_file_stream predicates don't create random files. They are based on a counter (which in itself is not bad), but this counter is not shared among threads. That's why tmp_file and tmp_file_stream can't be reliably run across threads.

https://github.com/SWI-Prolog/swipl-devel/blob/d369dced9e907c26611a4c96f9f84912dc1c9f4d/src/os/pl-os.c#L716

This seems to be the problem.

We came up with the following solution in the meantime:

```prolog
/**
 * random_string(String) is det.
 */
random_string(String) :-
    Size is 2 ** (20 * 8),
    random(0, Size, Num),
    format(string(String), '~36r', [Num]).

random_file(Prefix, Filename) :-
    random_string(RandomString),
    atomic_list_concat([Prefix, RandomString], Tmp),
    tmp_file(Tmp, Filename).
```

**Comment by JanWielemaker** [comment]
Hmm.  `static` local variables are shared between threads, no?   Ok, the increment is not atomic which it should be, but then we use 

    (fd=open(temp, O_CREAT|O_EXCL|O_WRONLY|O_BINARY, 0600)) 

which is (AFAIK) an atomic operation that should recover from a possible conflict.   Am I missing something?   What exactly is going wrong?  Do two calls in different threads end up with the same tmp file?  An error?

**Comment by rrooij** [comment]
Thanks for your quick answer Jan! We saw this as we ran a lot of tests concurrently that were all using `tmp_file` or `tmp_file_stream`. I'll see if I can give you something to reproduce.

You are right about the static local variables! Should be shared indeed.

**Comment by JanWielemaker** [comment]
> saw this

What?   The code (which I think is a little clumsy but not incorrect)?  Some observed wrong behavior?   I appreciate a test, but a description of what goes wrong might be enough.

**Comment by rrooij** [comment]
>I appreciate a test
I made a simple test case that will demonstrate the problem.

```prolog
:- initialization(main).

create_tmp_stream(_, Out) :-
    tmp_file(testbase, Filename),
    ( exists_file(Filename)
    -> throw(error(file_exists))
    ;  true
    ),
    open(Filename, write, Stream),
    format(Stream, "Wew this is a test~n", []),
    close(Stream),
    Out = Filename.

main :-
    List = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    concurrent_maplist(create_tmp_stream, List, NewList),
    concurrent_maplist(create_tmp_stream, List, NewList2),
    % Search for overlap
    print(NewList), nl,
    print(NewList2), nl,
    halt.
```

When I run this a few times on Mac OS, it will eventually fail and throw the error, although at random times. (Sometimes you get 100 successes but in rare cases the tmp file already exists)

**Comment by JanWielemaker** [comment]
Thanks.   That is all correct.   tmp_file/2 is deprecated, for the same reason as the old POSIX tmpnam().   POSIX has tmpfile() and mkstemp() which, like SWI-Prolog's tmp_file_stream/3 not only determine a name, but also use open() as in my post above to atomically create the file in exclusive mode.   That avoids this problem as well as attackers guessing the tmp file names.

That said, if you do not care about the security issues (sometimes for a good reason), tmp_file/2 would be fine when we use atomic update of the counter.  Pushed 933daa95a2aa85b905d26511ba1cb4c57a2c5be4 to address this.
