### ISSUE TITLE
gtrace doesn't display code of a rule when there is a macro expansion in the rule.

### ISSUE THREAD

**Issue by koo5** [SWI-Prolog/swipl-devel#774]
symptoms overlap with #757 .

I understand that there is a rabbit hole in trying to preserve variable names or something, but why would the debugger just refuse to display a rule when there was some macro expansion in it? As i understand, it calls the expand_term or expand_goal or whatever predicates backwards, to see if the expanded form corresponds to original user code. Does gtrace refuse to display the rule when this backwards translation throws an error/fails? Seeing the expanded form would not only be just fine, but given the frequency of bugs in term expansion, it would be highly preferrable to the current state where the debugger just refuses to display any code at all

**Comment by koo5** [comment]
i'm not able to make a minimal example, it doesn't happen there. But it seems to be triggered by fnotation, like here: https://github.com/lodgeit-labs/accounts-assessor/blob/67aa1368563a8426f7b41ec664d561bdd3a95e8a/sources/lib/bank_statement.pl#L47

```
% [Thread pce] source for #23748201: 
% [Thread pce] Show source, PC = 86, Port = call
% [Thread pce] ClauseRef = <clause>(0x55aa21425ff0), PC = 86
% [Thread pce] Term-position: for ref=<clause>(0x55aa21425ff0) at PC=86: [2,2,2,2,2,2,2,1]
% [Thread pce] show_source(23748201,[gui(@17546502059784/prolog_debugger),pc(86),source,bindings,style(frame)]) failed
```

**Comment by JanWielemaker** [comment]
That is a known limitation.   Use goal/term expansion with arity 4 to rewrite the term position correctly and it should work.  That is a rather nasty job though.  Without, only some simple translations work.   You can also define the hook in prolog_clause to make the clause read and the decompiled clause match while rewritimg the term position information.

I have been working on a  more powerful heuristic mechanism to keep the term position in sync with the transformation.  That project stalled.   It looks promising, but being heuristic it probably leads to strange results in some cases.

**Comment by koo5** [comment]
not sure i follow. If you mean the hook here:
```
ubody(Read, Decompiled, Module, TermPosRead, TermPosDecompiled) :-
    unify_goal(Read, Decompiled, Module, TermPosRead, TermPosDecompiled),
    !.
```
this code never seems to be reached at all. Can i understand "clause read and the decompiled clause match while rewritimg the term position information" to mean that this is the way to make gtrace at least display the compiled code?
