### ISSUE TITLE
Unexpected behavior for making directory paths that start with `~`

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#78]
The following creates a subdirectory called `~/a` i.o. a subdirectory `a` inside the user's home directory.

```prolog
?- make_directory_path('~/a/').
```

**Comment by JanWielemaker** [comment]
Yes.  Only expand_file_name/2 expands ~ and $ and all the other wildchart stuff.  Once upon
a time that was different, but that gives all sorts of funny results if you have actual file names
holding ~, $, etc.  (Unix) file names can hold any character except for / and \0.
