### ISSUE TITLE
Stackoverflow check missing in recursion

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#785]
The ticket is not about the rule/[2,3] problem 
rather about an unreported stackoverflow.

I have tested this code on Mac and Windows. In both cases
I get a that SWI-Prolog 8.3.19 crashes and closes the window.
Also on the command line I get:
```
>.\bin\swipl.exe
Welcome to SWI-Prolog (threaded, 64 bits, version 8.3.19)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

1 ?- ['<path>\\vanilla3.pl'].
true.

2 ?- solve(sumlist(X,Y)).

>
```
In the above also the solve/1 call leaves the interpreter 
and exists without any error messages. Maybe the reason 
for this abort is that I have used a sumlist/2 without an 

accumulater, so its not tail recursive. Instead the last goal is an 
evaluable expression. The meta-interpreter, the solve/1 predicate 
will be partially tail recursive and normally recursive:
```
sumlist([X|L], S) => sumlist(L, H), S is X+H.
sumlist([], S) => S is 0.
```
Through meta interpretation the error happens since (=>)/2 is
seen as (:-)/2, and then the first rule is applied over and over again. 
But I guess the error can be also reproduced with (:-)/2 rules.

Open Source:

**Vanilla Interpreter, SWI-Prolog Problem**
[https://\gist.github.com/jburse/a3517410a28b759ef44f72584f89aaf8#file-vanilla3-pl
](https://gist.github.com/jburse/a3517410a28b759ef44f72584f89aaf8#file-vanilla3-pl
)

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with df7f72d160d5324f5c209e84921e80799d8d5d42

```
101 ?- solve(sumlist(X,Y)).
ERROR: Cannot represent due to `predicate references'
ERROR: In:
ERROR: [2,095,161] clause(sumlist(_46090674,_46090676),_46090670)
ERROR: [2,095,160] solve(sumlist(_46090704,_46090706)) at /home/janw/vanilla3.pl:36
ERROR: [2,095,159] solve((sumlist(_46090740,_46090742),_46090746 is ...)) at /home/janw/vanilla3.pl:35
ERROR: [2,095,158] solve(sumlist([_46090782|_46090784],_46090778)) at /home/janw/vanilla3.pl:36
ERROR: [2,095,157] solve((sumlist(...,_46090820),_46090824 is ...)) at /home/janw/vanilla3.pl:35
ERROR: [2,095,156] solve(sumlist([_46090860|...],_46090856)) at /home/janw/vanilla3.pl:36
ERROR: [2,095,155] solve((sumlist(...,_46090898),_46090902 is ...)) at /home/janw/vanilla3.pl:35
ERROR: [2,095,154] solve(sumlist([_46090938|...],_46090934)) at /home/janw/vanilla3.pl:36
```
