### ISSUE TITLE
dcg_basics integer//1 works for codes, but not for chars if there is a plus or minus sign. 

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#787]
We find that a signed sequence of digits can be accepted if it was exploded into codes:

```
atom_codes('-1233',Cs),phrase(integer(Out),Cs,Rest).
Cs = [45,49,50,51,51],
Out = -1233,
Rest = [].
```

But not into chars:

```
?- atom_chars('-1233',Cs),phrase(integer(Out),Cs,Rest).
false.
```

This is because in https://eu.swi-prolog.org/pldoc/doc/_SWI_/library/dcg/basics.pl?show=src#digit/3

```
sign(0'-) --> "-".
sign(0'+) --> "+".
```

Accepting chars or codes:

```
sign(0'-) --> (['-']|[45]),!.
sign(0'+) --> (['+']|[43]),!.
```

Then: 

```
?- atom_codes('+',Cs),phrase(sign(X),Cs,Rest).
Cs = [43],
X = 43,
Rest = [].

?- atom_chars('+',Cs),phrase(sign(X),Cs,Rest).
Cs = [+],
X = 43,
Rest = [].
```

**Comment by dtonhofer** [comment]
I guess we can close this. We stay on "codes"?

**Comment by JanWielemaker** [comment]
Yes.  If anything, we should have a directory with the DCG for codes and one for chars that host the same files that can probably be built from the same source.   That is in my view a workable alternative.

**Comment by dtonhofer** [comment]
Thanks Jan. Closing for now.
