### ISSUE TITLE
Error on Windows with set_stream(user_output, encoding(utf8))

### ISSUE THREAD

**Issue by josd** [SWI-Prolog/swipl-devel#790]
In EYE we do a
```
:- initialization(set_stream(user_output, encoding(utf8))).
```
since a very long time but we recently were informed that it gives an error on windows:
```
>swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.3.19)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

1 ?- set_stream(user_output, encoding(utf8)).
ERROR: No permission to encoding stream `user_output'
ERROR: In:
ERROR:   [10] set_stream(user_output,encoding(utf8))
ERROR:    [9] toplevel_call(user:user: ...) at c:/program files/swipl/boot/toplevel.pl:1113
2 ?-
```

**Comment by JanWielemaker** [comment]
> since a very long

Weird.  Not much has changed to this for a very long time either.   Surely you cannot change the encoding for `swipl-win.exe`.   It also doesn't make much sense for the normal Windows console as this uses the Windows Unicode API.   That might be the latest related change.   I'd have to look in the git history to find when.  Surely years ago.  It could make sense if you want to run `swipl.exe` with output redirected to a file.   Is that the scenario?

**Comment by josd** [comment]
I also can't remember and always use the Ubuntu swipl.
There was for sure a reason to have the
```
:- initialization(set_stream(user_output, encoding(utf8))).
```
in EYE and I think it was needed for Windows.

The reasoning output is on user_output and indeed
we typically redirect that to a file as well.

**Comment by josd** [comment]
Still with the error, the output on Windows seems to be fine e.g. passing https://github.com/josd/eye/blob/master/reasoning/utf8/utf8.n3
through eye gives
```
:s :p <http://example.org/test#béc>.
:s :p "€".
:s :p "\U0001D7CB"@en-us.
:s :p "Ø".
:s :p "the “test” is ok".
```
or in hex dump
```
00000000  50 52 45 46 49 58 20 3a  20 3c 68 74 74 70 3a 2f  |PREFIX : <http:/|
00000010  2f 65 78 61 6d 70 6c 65  2e 6f 72 67 2f 74 65 73  |/example.org/tes|
00000020  74 23 3e 0d 0a 0d 0a 3a  73 20 3a 70 20 3c 68 74  |t#>....:s :p <ht|
00000030  74 70 3a 2f 2f 65 78 61  6d 70 6c 65 2e 6f 72 67  |tp://example.org|
00000040  2f 74 65 73 74 23 62 c3  a9 63 3e 2e 0d 0a 3a 73  |/test#b..c>...:s|
00000050  20 3a 70 20 22 e2 82 ac  22 2e 0d 0a 3a 73 20 3a  | :p "..."...:s :|
00000060  70 20 22 5c 55 30 30 30  31 44 37 43 42 22 40 65  |p "\U0001D7CB"@e|
00000070  6e 2d 75 73 2e 0d 0a 3a  73 20 3a 70 20 22 c3 98  |n-us...:s :p "..|
00000080  22 2e 0d 0a 3a 73 20 3a  70 20 22 74 68 65 20 e2  |"...:s :p "the .|
00000090  80 9c 74 65 73 74 e2 80  9d 20 69 73 20 6f 6b 22  |..test... is ok"|
000000a0  2e 0d 0a 0d 0a                                    |.....|
```
It is all in utf8 except for code point `U+1D7CB 𝟋       f0 9d 9f 8b     MATHEMATICAL BOLD SMALL DIGAMMA`

**Comment by JanWielemaker** [comment]
Tried using your .nt file and a simple copy program below.     I can confirm that when I run

    swiplwin.exe t.pl utf8.n3

It prints the exception and mistreats the 𝟋.  The other chars are fine as the Unicode console API is used.   When running this with a redirect to a file no error is printed.  A bit unexpectedly the output seems even correct while SWI-Prolog on Windows cannot deal with Unicode characters > 0xFFFF.     Please contact me directly if you want full UTF-8 support for Windows ...

```
:- initialization(set_stream(user_output, encoding(utf8))).
:- initialization(main, main).

main([File]) :-
    setup_call_cleanup(
        open(File, read, In, [encoding(utf8)]),
        copy_stream_data(In, user_output),
        close(In)).
```

**Comment by josd** [comment]
OK, so nothing seems to be broken and for Windows we already worked around the Unicode limitation by using surrogate pairs e.g.
```
string_dq(-1, _, _, []) :-
    !,
    nb_getval(line_number, Ln),
    throw(unexpected_end_of_input(line(Ln))).
string_dq(0'\n, _, _, []) :-
    !,
    nb_getval(line_number, Ln),
    throw(unexpected_end_of_line(line(Ln))).
string_dq(0'", In, C, []) :-
    !,
    get_code(In, C).
string_dq(0'\\, In, C, D) :-
    get_code(In, C1),
    !,
    string_escape(C1, In, C2, H),
    (   current_prolog_flag(windows, true),
        H > 0xFFFF
    ->  E is (H-0x10000)>>10+0xD800,
        F is (H-0x10000) mod 0x400+0xDC00,
        D = [E, F|T]
    ;   D = [H|T]
    ),
    string_dq(C2, In, C, T).
string_dq(C0, In, C, D) :-
    (   current_prolog_flag(windows, true),
        C0 > 0xFFFF
    ->  E is (C0-0x10000)>>10+0xD800,
        F is (C0-0x10000) mod 0x400+0xDC00,
        D = [E, F|T]
    ;   D = [C0|T]
    ),
    get_code(In, C1),
    string_dq(C1, In, C, T).
```
