### ISSUE TITLE
Feature: Have a tracer toggle to switch on/off representing lists of integers as list of codes

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#795]
Debugging DCGs is a right PITA, and having lists-of-codes thrown on the screen does not improve things.

Suggestion: Have a tracer flag to switch on/off printing of lists of integers as lists of chars (of course, this demands some heuristics and will never be perfect)

**Comment by JanWielemaker** [comment]
For the commandline, use `?- portray_text(true).`.   In the GUI debugger, go to settings and enable _Portray codes_

**Comment by dtonhofer** [comment]
Got it. This inspired me to review the documentation for library(portray_text) - and enable the predicates to also give the current settings while keeping current functionality (if we have logic programming, why make predicates work only in "setter" mode?) Submitting a change request for this.
