### ISSUE TITLE
Error: unknown procedure

### ISSUE THREAD

**Issue by flexoron** [SWI-Prolog/swipl-devel#799]
Hello,

linux$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.2.3)
?- assertz(g(a)), g(M).
ERROR: Unknown procedure: g/1 (DWIM could not correct goal)

Isn't it allowed to call the goal g() at that point?

**Comment by JanWielemaker** [comment]
The pre-execution analysis of the interactive toplevel hits in that case.   You can wrap g(M) as call(g(M)) to bypass the analysis.
