### ISSUE TITLE
Edge case: Anonymous variables existentially quantified (or not) within setof/3

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#807]
Consider:

```
likes(john,mary).
likes(mary,adam).
likes(adam,mary).
likes(jack,destiny).
likes(destiny,adam).

person_set_1(PersonSet) :- setof(Person,(X^likes(Person,X)),PersonSet).
person_set_2(PersonSet) :- setof(Person,likes(Person,_),PersonSet).
person_set_3(PersonSet) :- setof(Person,(_^likes(Person,_)),PersonSet).
```

We expected `person_set_1(PersonSet)` to return the set of persons appearing as first argument to likes/2. And indeed:

```
?- person_set_1(PersonSet).
PersonSet = [adam, destiny, jack, john, mary].
```

Feeling-wise we would expect the same for `person_set_2(PersonSet)`, as `_` is supposed to be different in all cases. However, here `_` behaves as a standard "named variables", so there are three answers, one for each possible value of the second argument of likes/2:

```
?- person_set_2(PersonSet).
PersonSet = [destiny, mary] ;
PersonSet = [jack] ;
PersonSet = [adam, john].
```

But then, we would expect this to be fixed with an "existentially quantified anaonymous variable" (which is a bit contradictory), but this does not happen, existential quantification does not change behaviour: 

```
?- person_set_3(PersonSet).
PersonSet = [destiny, mary] ;
PersonSet = [jack] ;
PersonSet = [adam, john].
```

So I don't know whether there is anything to fix or clarify or rather to reject-by-compiler, in any case I this edge case is not so clean.

**Comment by JanWielemaker** [comment]
This is what the standard describes and has been how this worked as long as setof/3 exists.  This belongs in a textbook/tutorial/..., but not in the issue list for an implementation.   The compiler can't do much.   A "linter" like tool may detect that the existential variable does not appear in the goal, but that is allowed.
