### ISSUE TITLE
Min/max functions do not work for pos/neg infinity

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#809]
# Observed

I'm unable to calculate the minimum/maximum number if at least two of the operands are both are negative infinite or positive infinite:

```sh
?- X is inf, Y is min(X,X).
ERROR: Arithmetic: evaluation error: `float_overflow'
ERROR: In:
ERROR:   [11] _7594 is min(-1.0Inf,-1.0Inf)
ERROR:    [9] toplevel_call(user:user: ...) at /usr/local/lib/swipl/boot/toplevel.pl:1113

```

# Expected

The minimum/maximum operators to be applicable to all numbers, including positive/negative infinity.

# Steps to reproduce

In the top-level: `X is inf, Y is min(X,X).`

**Comment by JanWielemaker** [comment]
Hi Wouter!   This is a bit of a border case.   Normal Prolog arithmetic says that any evaluable  function that evaluates to a non-normal float (NaN, +/-Inf) shall raise an exception.    If you want to compute with non-normal floats there is a whole bunch of Prolog flags to control that.  In this case:

```
?- set_prolog_flag(float_overflow, infinity).
true.

102 ?- X is inf, Y is min(X,X).
X = Y, Y = 1.0Inf.
```
We could argue that min/2 and max/2 can be exceptions to this rule as they do not compute a new value.   Well, this too can get tricky as comparison may convert an integer to a float but big integers cannot always be represented as a float.

**Comment by wouterbeek** [comment]
Thanks Jan!  Not a bug a bug then...
