### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by javatlacati** [SWI-Prolog/swipl-devel#81]
Is anything going regard internationalize the documentation?

**Comment by JanWielemaker** [comment]
Nope.  Its already hard enough to keep the English docs in sync with the system.  I guess there is general tutorial material on Prolog in different languages.  Once you understand the basics I fear you need a basic understanding of English.

**Comment by javatlacati** [comment]
I do and I understand English. But many people don't. Please consider something like a parallel project that contains the documentation in html format so it won't affect the development of swi-prolog and the swi-prolog user base can benefit/contribute more actively.
Thanks for your effort and have a nice day.
