### ISSUE TITLE
GUI tracer broken

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#824]
The GUI tracer no longer works for me :-(  This may be related me upgrading to Ubuntu 2021.04 this week.  Could a change in the X Windows / Wayland support from the OS explain this error?

```
$ swipl
?- gtrace, true.
% The graphical front-end will be used for subsequent tracing
[PCE fatal: @helvetica_roman_12/font: Xopen failed on @display/display
	in: 	<No exception goal>
]
	[13] M @helvetica_roman_12/font ->_xopen(@display/display)
	[12] M @helvetica_roman_12/font ->_xopen(@display/display)
	[11] M @17454403549100/reporter <-height()
	[10] M @17454403549362/point ->initialise(0, (nil))
	[ 9] V @17454403549100/reporter ->reference((nil))
	[ 8] M @17454403549100/reporter ->initialise()
	[ 7] M @17454403512079/dialog ->append((nil), (nil))
	[ 6] M @emacs_mark_list/emacs_bookmark_editor ->fill_dialog()
	[ 5] M @emacs_mark_list/emacs_bookmark_editor ->initialise()
	[ 4] 
	[ 3] M @emacs/emacs ->initialise(@emacs_buffers/dict)
	[ 2] 
	[ 1] M @prolog/host ->call(trap_ref, emacs)
Host stack:
     [21] pce_principal:send(@17454403549100/reporter, reference(point(0, ?(@17454403549100/reporter, height))))
     [19] '$c_call_prolog'
     [18] pce_principal:send(@17454403512079/dialog, append(new(reporter), right))
     [17] Send-method on @emacs_mark_list/emacs_bookmark_editor: emacs_bookmark_editor->fill_dialog
     [16] '$c_call_prolog'
% The following threads wouldn't die: [main]
```

**Comment by JanWielemaker** [comment]
Wayland should not be a problem.   I used it at CWI for a while.  Several applications had glitches though, so I reverted to good old X11.   Looks like something is going wrong in the font selection.   Could be missing XFontConfig library?   In that case it falls back to really old code that I doubt still works.   You can try `?- debugpce(font).` and see whether it has something interesting to tell.

**Comment by wouterbeek** [comment]
I fix the above by reinstalling the dependencies for building SWI on Debian-based systems.  I never installed the Java stuff, but also `libunwind-dev` was missing.  Could that have caused the above error?

default-jdk default-jdk-headless default-jre junit4 libgoogle-perftools-dev libgoogle-perftools4 libhamcrest-java libunwind-dev openjdk-11-jdk openjdk-11-jdk-headless
  openjdk-11-jre

**Comment by wouterbeek** [comment]
I'm not able to get the error again by removing `libunwind-dev` :-(  At least this solved the issue.

**Comment by JanWielemaker** [comment]
Do I understand you didn't recompile immediately and thus the root of the problem is that the old binary is not compatible with the new version?  `libunwind` is surely unrelated.   It is used to produce a C stack trace in case of a crash.   Actually it is no longer the first choice for producing stack traces.  If possible the glibc routines are used.

**Comment by wouterbeek** [comment]
> Do I understand you didn't recompile immediately and thus the root of the problem is that the old binary is not compatible with the new version?

The strange thing is that the issue was fixed immediately after installing the above mentioned dependencies, i.e., without recompilation.  Is that even possible?  (I had removed `libunwind-dev` previously to work around [another issue](https://github.com/bincrafters/community/issues/1373).)

**Comment by JanWielemaker** [comment]
> The strange thing is that the issue was fixed immediately after installing the above mentioned dependencies, i.e., without recompilation. Is that even possible?

Hard to imagine.   The problem might have been the result of a broken or incomplete installation of the FontConfig infrastructure, but surely not libunwind.   The only thing I can imagine is that `apt` fixed the problem as a side effect.
