### ISSUE TITLE
Error when expanding goal inside `\+` and `;`

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#825]
Expanded code generating odd error messages of the the form:
```
ERROR: /Users/ ... /test_intersect.pl:8: 
ERROR:    put_attr/3: Uninstantiated argument expected, found _13872{$var_info = ...},_13894{$var_info = ...} (1-st argument)  
```
when loading module:
```
:- module(test_intersect,[]).

goal_expansion(intersect((Xl,Xh), (Yl,Yh), (Zl,Zh)),
			   (Zl is max(Xl, Yl), Zh is min(Xh, Yh), Zl =< Zh)
			  ).

test_(X,Y,Z) :- intersect(X,Y,Z).          % OK
test_(X,Y,Z) :- \+intersect(X,Y,Z).        % Error
test_(X,Y,Z) :- not(intersect(X,Y,Z)).     % OK
test_(X,Y,Z) :- X=0 ; intersect(X,Y,Z).    % Error
```

**Comment by JanWielemaker** [comment]
This happens if you bind variables in the goal expansion.  It could be considered a bug,  I'm no sure you want this in the first place though.   Your code has become like this:

```
test_intersect:test_((A, B),  (C, D),  (E, F)) :-
    E is max(A, C),
    F is min(B, D),
    E=<F.
```
You see it going wrong in the last clause with would have expanded to 

```
test_intersect:test_((A, B),  (C, D),  (E, F)) :-
    (   (A,B) = 0
    ;   E is max(A, C),
        F is min(B, D),
        E=<F
    ).
```

**Comment by ridgeworks** [comment]
> This happens if you bind variables in the goal expansion. It could be considered a bug, .... 

This was the original intent of the experiment. And that was the code I was hoping for in the "OK" cases, i.e., not a bug.

> You see it going wrong in the last clause 

Not really wrong for the purposes of a test case, but yes, not useful code. Perhaps I should have used something like `X=(0,0)`.

In any case I think the main points are:
- it should work consistently, i.e., why do `\+` and `;` generate errors and the others do not.
- the error message isn't very helpful
- the error message should, at worst, be a warning for all cases. Variables should be unified as requested.

**Comment by JanWielemaker** [comment]
The behavior is caused by the "freshness" analysis that restores the freshness of variables after ``\+`` as this doesn't change anything and when starting the analysis of the second branch of a disjunction.  What you do is really dubious as you bind a variable globally in the clause.  If you do that inside a negation you get wrong semantics.    So yes, a better error would be desirable and possibly goal expansion should guarantee no goal variables are bound.   On the other hand, if there is no negation and there are no cuts the semantics is probably preserved.

**Comment by ridgeworks** [comment]
> What you do is really dubious as you bind a variable globally in the clause. If you do that inside a negation you get wrong semantics.

Any binding done in a negation is undone so I'm not sure how I get wrong semantics. Consider if I had used `not` instead of `\+`; has the semantics changed?

What I'm trying to do is inline a predicate call. But that call has different argument syntax, e.g., sometimes it's `intersect(X,Y,Z)` and sometimes `intersect((L1,H1),(L2,H2),(L3,H3))`, or some mixture of the above. It kind of defeats the purpose of goal expansion if I have to "normalize" all the calls.

I can see some downsides to my experiment, but I don't see anything "dubious".

**Comment by JanWielemaker** [comment]
Well, the translation of the disjunction is obviously wrong as `test_(0, _, _)` should succeed.   Similar is the translation for the clause with not/1 wrong as test_/3 for any term that is not a pair should succeed but fails because the head does not unify.   Binding variables without disjunctions and negation is fine without cuts, but that is the only safe exception.   You get no error for not/1 as not/1 is a backward compatibility predicate that is unknown to the compiler and thus the compiler doesn't know that not/1 never binds any variables.

You need to do the unification explicitly in the rewritten goal such that it happens runtime rather then compile time.  Note that if it is safe to do so the compiler will move the unification anyway in the most recent versions.

**Comment by ridgeworks** [comment]
I think the penny just dropped. The issue is that this "unification" is happening at compile time.

> Well, the translation of the disjunction is obviously wrong as test_(0, _, _) should succeed. 

Consider this as a programming error, rather the disjunctive test should be:
```
test_(X,Y,Z) :- X=(0,0) ; intersect(X,Y,Z).    % Error
```

> You need to do the unification explicitly in the rewritten goal  ...

So I think this is saying the goal expansion should look like:
```
goal_expansion(intersect(X,Y,Z),
               (X=(Xl,Xh), Y=(Yl,Yh), Z=(Zl,Zh),
                Zl is max(Xl, Yl), Zh is min(Xh, Yh), Zl =< Zh
               )
              ).
```
I suppose this does the job, but it somewhat seems to defeat the purpose of inlining the predicate since the unifications may be unnecessary.  Consider:
```
test_((L1,H1),(L2,H2),(L3,H3)) :- intersect((L1,H1),(L2,H2),(L3,H3)).
```
which now expands to:
```
test_intersect:test_((L1, H1),
                     (L2, H2),
                     (L3, H3)) :-
    (L1, H1)=(A, B),
    (L2, H2)=(C, D),
    (L3, H3)=(E, F),
    E is max(A, C),
    F is min(B, D),
    E=<F.
```
rather than the previous:
```
test_intersect:test_((L1, H1),
                     (L2, H2),
                     (L3, H3)) :-
    L3 is max(L1, L2),
    H3 is min(H1, H2),
    L3=<H3.
```
For my particular use case, I think I can guarantee that there are no semantic issues, i.e., all arguments to the goal expansion will be ground terms of the form `(L,H)` (interval bounds) at run time. So it would be helpful if the compiler generated, at worst, a warning instead of an error. (I'm still not certain whether this kind of optimization is worthwhile but at least it would be possible.)

**Comment by JanWielemaker** [comment]
Simply make goal expansion check the argument is a pair (pick the elements of the pair), a plain variable (do runtime unification) or anything else (either translate to `fail` or generate an error).   That gives efficient and correct code.  

I don't think a warning is appropriate, only a more sensible error.  The future is to inlining code.  Macros are too hard for too many people (as we also know from other languages with macro expansion: useful but easy to get wrong).

**Comment by ridgeworks** [comment]
Yes, pushing the job into goal expansion seems to work pretty well, and gets around some other issues I was thinking about. I'm happy to have this issue closed subject to a decision on a more instructive error message.

Thanks for the help.

**Comment by JanWielemaker** [comment]
Pushed 1f97e8d6cb73d6dda77410f9f0c417c81b903843 to improve the error message and address the issue in the documentation.
