### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by edechter** [SWI-Prolog/swipl-devel#83]
On [this page](http://www.swi-prolog.org/pldoc/man?section=dicts), the link in the sentence below is broken.

See also :</2, which can be used to test for existence and unify multiple key values from a dict.

**Comment by wouterbeek** [comment]
From my experience the comparators are often broken in the documentation system, so this may be a more generic issue.

**Comment by wouterbeek** [comment]
This seems to work now...  Time heals everything as they say.
