### ISSUE TITLE
/usr/local/lib/swipl/library/thread.pl:356: Singleton variable in branch: Test

### ISSUE THREAD

**Issue by koo5** [SWI-Prolog/swipl-devel#835]
```
Warning: /usr/local/lib/swipl/library/thread.pl:356:
Warning:    Singleton variable in branch: Test
```
Sometimes it prints, sometimes it doesn't. 
Not sure at what version started noticing this, but it still happens in 8.3.24-3-g32f8079a1-DIRTY

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 24cbf084b5259d2fa76f4fdd872a226b0471d4d4.   Should happen when compiling with optimization and `library(debug)` loaded which causes debug/3 calls to be translated to `true`
