### ISSUE TITLE
swipl-win: second use_module succeeds even if pack is broken

### ISSUE THREAD

**Issue by mgondan** [SWI-Prolog/swipl-devel#848]
See this (Windows):

Welcome to SWI-Prolog (threaded, 64 bits, version 8.3.25)
(etc.)
?- pack_install(environ).
% Contacting server at https://www.swi-prolog.org/pack/query ... ok
Install environ@1.0 from http://www.swi-prolog.org/download/pack/environ-1.0.tgz Y/n? 
% Contacting server at https://www.swi-prolog.org/pack/query ... ok
(etc.)
Install "environ-1.0.tgz" (1,084 bytes) Y/n? 
% gcc  -I"c:/program files/swipl/include"   -c -o c/environ.o c/environ.c
(etc.)
true.

[Now I simulate a broken pack by deleting the dll from environ]
?- delete_file('c:/users/matth/appdata/local/swi-prolog/pack/environ/lib/x64-win64/environ.dll').
true.

?- use_module(library(environ)).
ERROR: c:/users/matth/appdata/local/swi-prolog/pack/environ/prolog/environ.pl:5:
(etc., as expected)
ERROR: Exported procedure environ:environ/1 is not defined
true.

[This one should not succeed.]
?- use_module(library(environ)).
true.

**Comment by JanWielemaker** [comment]
A second use_module call just imports the interface of the first load.    If you try to call it you'll get an error.   You got an error while loading.  In that case you can expect errors when you try to run the code.   I see little reason to change that.
