### ISSUE TITLE
Error compiling without GMP or MT

### ISSUE THREAD

**Issue by m4c0** [SWI-Prolog/swipl-devel#85]
I'm trying to make the tiniest version possible of SWI-Prolog to embed it, but I'm having problems configuring with "--disable-gmp" or "--disable-mt".

If I disable GMP, I get errors in "pl-gmp.c", regarding "V_MPZ", "V_MPQ" and lots of undeclared identifiers.

If I disable MT, I get errors in "pl-atom.c", with nasty stuff requiring an item named "thread" in "struct PL_local_data".

**Comment by JanWielemaker** [comment]
I've pushed a patch for `--disable-gmp`.  Roberto Bagnara is mosly behind the `--disable-mt`, but he has a hard job as a lot of the threading code is being rewritten by Keri Harris.   Disabling GMP mostly saves dependency on `libgmp`.  I don't think the system itself gets much smaller.  I don't know the size impact of disabling threading.  My estimate is that it won't be impressive either.

**Comment by JanWielemaker** [comment]
Keri pushes changes for his lockless tables and I added another patch.  It now compiles and, at least basically, runs.  This also gives the size comparison (Ubuntu 14.04 64-bits, gcc 4.8.4).  First entry
is the single threaded version.  So, the single-threaded version is 12% smaller.

```
hppc823 (no-mt; master) 13_> size ../lib/x86_64-linux/libswipl.so
   text	   data	    bss	    dec	    hex	filename
1041972	  80256	  17904	1140132	 1165a4	../lib/x86_64-linux/libswipl.so
hppc823 (linux; master) 5_> size ../lib/x86_64-linux/libswipl.so
   text	   data	    bss	    dec	    hex	filename
1171241	  84656	  18720	1274617	 1372f9	../lib/x86_64-linux/libswipl.so
```
