### ISSUE TITLE
Version 8.3.24: Spurious crash on thread_join/2

### ISSUE THREAD

**Issue by EricZinda** [SWI-Prolog/swipl-devel#852]
I have spuriously, though relatively often (once every 10 runs or so) gotten the below crash in the SWI Prolog process on  mac OS Catalina.  I apologize that the only way I've been able to repro is using Python to interact with the server.  Here's how to repro:

Extract the files in: [Bug.zip](https://github.com/SWI-Prolog/swipl/files/6718760/Bug.zip)

In SWI Prolog 8.3.24 start the server. The following will launch a server on a background thread:
~~~
?- consult('/<path>/language_server.pl').
true.

?- language_server:language_server([port(4242), password(debugnow)]).
true.
~~~

In Python 3.7 or later run a Python test that will repeat 100 times to try to reproduce the error, it should eventually crash and make the Prolog process disappear. Usually after 10 iterations on my machine but it seems to be a timing issue so YMMV:
~~~
python test_prologserver.py
~~~

Here's the crash
~~~
Prolog: SWI-Prolog [thread 3 (language_server1_conn1_goal) at Fri Jun 25 12:07:19 2021]: received fatal signal 11 (segv)
Prolog: C-stack trace labeled "crash":
Prolog:   [0] /Applications/SWI-Prolog.app/Contents/Frameworks/libswipl.8.3.24.dylib(save_backtrace+0x8e) [0x1078804ee]
Prolog: Prolog stack:
Prolog:   [34] system:thread_join/2 [PC=1 in supervisor]
Prolog:   [33] $syspreds:thread_join/1 [PC=6 in clause 1]
Prolog:   [32] time:run_alarm_goal/2 [PC=6 in clause 1]
Prolog:   [31] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [28] system:catch/3 [PC=2 in clause 1]
Prolog:   [27] language_server:abortSilentExit/2 [PC=98 in clause 1]
Prolog:   [26] system:<meta-call>/1 [PC=20 in clause -1]
Prolog:   [25] forall/2 [PC=11 in clause 1]
Prolog:   [24] language_server:stop_language_server/1 [PC=86 in clause 1]
Prolog:   [22] $bags:findall_loop/4 [PC=5 in clause 1]
Prolog:   [21] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [17] $bags:findall_loop/4 [PC=5 in clause 1]
Prolog:   [16] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [12] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [9] system:catch/3 [PC=2 in clause 1]
Prolog:   [8] language_server:goal_thread/1 [PC=157 in clause 1]
Prolog:   [0] system:$c_call_prolog/0 [PC=0 in top query clause]
Prolog: Running on_halt hooks with status 139
Prolog: Killing 5197 with default signal handlers
~~~

**Comment by JanWielemaker** [comment]
Fixed with babf6491e1b7b47329786ef5b3ae387cc29b7b5e.   This patch disallows detaching a thread that is being joined, joining a thread that is preparing to be detached as well as joining a thread that is already being joined by some other thread.   All these attempts result in a permission_error exception.
