### ISSUE TITLE
Last automatic daily build is from June 29 03:11:02 now is July 1

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#855]
I was expecting to find a July 1 03:00 to install it
[swipl-w64-2021-06-29.exe  Tue Jun 29 03:11:02 2021 12,324,323](https://www.swi-prolog.org/download/daily/bin/)

**Comment by JanWielemaker** [comment]
Daylies doesn't always build ...    Triggerred a CI build.  If I do not mess up before, tonight's should build again.   You can also pick prolog_codewalk.pl from GIT and dump it into your installation.
