### ISSUE TITLE
Building on macOS fails with error about `struct mallinfo`

### ISSUE THREAD

**Issue by dgelessus** [SWI-Prolog/swipl-devel#857]
Trying to build commit 583ccb42297bcd0cd49cf10b4e090bab3468e2e1 on macOS 10.14 gives me these compilation errors:

```
.../swipl-devel/src/pl-alloc.c:1877:28: error: calling function with incomplete return type 'struct mallinfo'
  { struct mallinfo info = fmallinfo();
                           ^~~~~~~~~~~
.../swipl-devel/src/pl-alloc.c:1864:15: note: forward declaration of 'struct mallinfo'
static struct mallinfo (*fmallinfo)(void) = NULL;
              ^
.../swipl-devel/src/pl-alloc.c:1877:21: error: variable has incomplete type 'struct mallinfo'
  { struct mallinfo info = fmallinfo();
                    ^
.../swipl-devel/src/pl-alloc.c:1864:15: note: forward declaration of 'struct mallinfo'
static struct mallinfo (*fmallinfo)(void) = NULL;
              ^
2 errors generated.
```

This seems to be related to the newly introduced use of `<malloc.h>`, which seems to be a Linux- or glibc-specific header. The inclusion of the header is correctly wrapped in `#ifdef HAVE_MALLOC_H`/`#endif`, but the code that uses `struct mallinfo` from the header is not wrapped in the same condition.

**Comment by JanWielemaker** [comment]
Oops.  Pushed a fix.   B.t.w. (concerning other post) If you are about performance compile SWI-Prolog using gcc 10 or later and enable PGO.   See scripts/make-distribution for how the binary distro is compiled.  About twice as fast as the clang compiled one :smile:
