### ISSUE TITLE
During clean build: "Unknown procedure" errors related to PCE while generating docs

### ISSUE THREAD

**Issue by dgelessus** [SWI-Prolog/swipl-devel#859]
While doing a clean build (newly created build directory) of 05a40addb0c58302d60ed4fd27ccc332731f45ea on macOS 10.14, I received these errors:

```
[ 93%] Generating lib/main.tex
ERROR: <builddir>/home/xpce/prolog/boot/pce_pl.pl:37:
ERROR:    Unknown procedure: send/2
ERROR: <builddir>/home/xpce/prolog/boot/pce_pl.pl:37:
ERROR:    Unknown procedure: get/3
ERROR:      However, there are definitions for:
ERROR:            det/1
ERROR:            get/1
ERROR:            get0/1
ERROR:            get/2
ERROR:            get0/2
[ 93%] Generating jswrite.tex
ERROR: <builddir>/home/xpce/prolog/boot/pce_expansion.pl:43:
ERROR:    Unknown procedure: pce_error/1
ERROR: <builddir>/home/xpce/prolog/boot/pce_expansion.pl:43:
ERROR:    Unknown procedure: pce_info/1
ERROR: <builddir>/home/xpce/prolog/boot/pce_expansion.pl:43:
ERROR:    Unknown procedure: pce_warn/1
ERROR: <builddir>/home/xpce/prolog/boot/pce_realise.pl:46:
ERROR:    Unknown procedure: pce_error/1
ERROR: <builddir>/home/xpce/prolog/boot/pce_goal_expansion.pl:39:
ERROR:    Unknown procedure: pce_error/1
[ 93%] Generating httpfiles.tex
ERROR: <builddir>/home/xpce/prolog/lib/english/pce_messages.pl:40:
ERROR:    Unknown procedure: get/3
ERROR:      However, there are definitions for:
ERROR:            det/1
ERROR:            get/1
ERROR:            get0/1
ERROR:            get/2
ERROR:            get0/2
Warning: Halting with status 1 due to 8 errors and 0 warnings
```

The build failed at this point. However, when running the build a second time (in the same directory, without cleaning/deleting) everything built successfully without errors.

[Here's the full build log](https://github.com/SWI-Prolog/swipl-devel/files/6777779/build_log.txt), so you can see the execution order of all build steps (this is a parallel build).

**Comment by kamahen** [comment]
Happened for me also on Ubuntu 20.0.4. 
I haven't isolated which commit triggered it.

**Comment by JanWielemaker** [comment]
Thanks.   I think it should be fixed with 5a398616889e10cc14a2e61c0b47fce58bb88e7b.   Please reopen if not.

**Comment by kamahen** [comment]
I just experienced this again - with a clean PGO build

**Comment by kamahen** [comment]
Git/github and I do not understand each other ... anyway, the problem went away after I restarted with a fresh clone.
