### ISSUE TITLE
PL_unify_blob can create new atoms despite PL_BLOB_NOCOPY | PL_BLOB_UNIQUE flags

### ISSUE THREAD

**Issue by jshprentz** [SWI-Prolog/swipl-devel#861]
### Summary

When defining a blob type with the Foreign Language Interface (https://www.swi-prolog.org/pldoc/man?section=blobtype) and specifying both `PL_BLOB_NOCOPY` and `PL_BLOB_UNIQUE`, "uniqueness is determined by comparing the pointer rather than the data pointed at." This uniqueness guarantee can fail when the blob contains dynamic data. The problem seems to be caused by a call to `MurmurHashAligned2` in the `lookupBlob` function, which is defined in `swipl-devel/src/pl-atom.c`.

### Context

I am developing a foreign library and a Prolog module that controls some devices attached to Raspberry Pi general purpose input/output (GPIO) pins. The data structures representing these devices typically contain fixed data, such as a pin number, and dynamic data, such as a brightness level of a LED.

During unit testing, when many tests establish connections to the same devices, I observed that Prolog created different atoms for the same blob addresses. These debug logs show Prolog using two different atoms for the same blob:
```
seesaw_neopixels.c:327:acquire_seesaw_board_blob(): <atom>(173061) <seesaw_board>(0x2575a0)
seesaw_neopixels.c:327:acquire_seesaw_board_blob(): <atom>(407557) <seesaw_board>(0x2575a0)
```
The blob type for an Adafruit Seesaw board was defined as follows:
```
static PL_blob_t pl_seesaw_board_blob_type = {
  PL_BLOB_MAGIC,
  PL_BLOB_NOCOPY | PL_BLOB_UNIQUE,
  "seesaw_board",
  release_seesaw_board_blob,
  compare_seesaw_board_blob,
  write_seesaw_board_blob,
  acquire_seesaw_board_blob
};
```

This code accepts an I2C bus number and address, tries to find an existing Seesaw board structure, creates a new board structure and connects if necessary, and unifies the board's blob structure with a Prolog term.
```
c_neopixels_connect_seesaw_board (
    term_t pl_i2c_bus,
    term_t pl_i2c_addr,
    term_t pl_seesaw_board)
{
  seesaw_board_t *board;
  ... // Validate i2c_bus and i2c_addr
  if (!(board = find_board (i2c_bus, i2c_addr)))
    {
      gpio_handle = connect_seesaw (i2c_bus, i2c_addr);
      board = PL_malloc (sizeof (seesaw_board_t));
      initialize_board (board, gpio_handle, i2c_bus, i2c_addr);
    }
  return PL_unify_blob (
      pl_seesaw_board,
      board,
      sizeof (seesaw_board_t),
      &pl_seesaw_board_blob_type);
}
```
### Analysis

`PL_unify_blob` relies on `lookupBlob` to find an existing atom for a blob or create a new atom. The essence of `lookupBlob` is:

1. If the `PL_BLOB_UNIQUE` flag is set, look for the blob in a hash table. Return the corresponding atom if found.
2. Create a new atom for the blob.
3. If the `PL_BLOB_UNIQUE` flag is set, add the new atom to the hash table.
4. Return the new atom.

The hash table search is careful (in `same_name`) to compare blob pointers when `PL_BLOB_NOCOPY` is set. Otherwise the search compares the blob contents.

### An Anomaly

The hash table search begins at a position determined by this line in `lookupBlob`:
```
v0 = MurmurHashAligned2(s, length, MURMUR_SEED);
```
This hash value is based on the entire contents of the blob (pointed to by `s`).

**If the blob contents have changed since a previous lookup, the hash value could vary, the wrong hash bucket could be scanned, and a previous atom for the blob could be overlooked.**

### A Possible Fix

The line above could be replaced by something like this to hash on the blob pointer instead of the blob contents when appropriate:
```
if ( true(type, PL_BLOB_UNIQUE) && true(type, PL_BLOB_NOCOPY) )
{ v0 = MurmurHashAligned2(&s, sizeof(s), MURMUR_SEED);
} else
{ v0 = MurmurHashAligned2(s, length, MURMUR_SEED);
}
```

### Workaround

The static "key" data can be gathered at the beginning of the blob structure. For example:
```
typedef struct seesaw_board
{
  struct key
  {
    int i2c_bus;
    int i2c_addr;
  } key;
  int gpio_handle;
  int data_speed;
  ...
} seesaw_board_t;
```
The size of this key data can be passed to `PL_unify_blob` so the hash value is based only on the key data.
```
PL_unify_blob (pl_seesaw_board, board, sizeof (board->key), &pl_seesaw_board_blob);
```

### Versions

`SWI-Prolog version 8.0.2 for armv8l-linux`

running on

`Linux raspberrypi 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l`

**Comment by JanWielemaker** [comment]
Thanks for the detailed analysis!    Fixed (almost) as proposed with 613baf44dcda75cb8cf8b9c806294134fb1420ee.  Note there are two other ways around.    One is to only use `PL_BLOB_UNIQUE` and pass a pointer to the pointer (and sizeof the pointer to the pointer).    Another one I often use is to have the acquire function store the created blob handle in the structure.   Now, if you have to unify with an already existing structure you simply use `PL_unify_atom(t, ptr->symbol)`.

I'm afraid 8.0.2 won't be patched.   In not too long time we should see 8.4.0.
