### ISSUE TITLE
yall and clpfd

### ISSUE THREAD

**Issue by eddiec** [SWI-Prolog/swipl-devel#876]
Hi,
I've seen a couple of mentions of this but not enough to help me.
I have a program that fails on what I was sure was correct code. I eventually tracked it down to a maplist seemingly expanded a bit wonkily.  Here is a minimal example:

```
:- use_module(library(clpfd)).            %this happens in a consulted file in the actual application

compare_rulesets(Acl,Devs, Diffs):-
    maplist([D,D-Rules]>>
	    findall(Disp,
		    (acl_rule(D,Acl,Action,Protocol,Src-SP,Dst-DP,_,_,_),
		     member(D,Devs),
		     once(displayf(Acl,Action,Protocol,Src-SP,Dst-DP, Disp))),
		    Rules),
	    Devs,
	    Rulesets),
    cmp_lists(Rulesets, Diffs).

show_group_diff_table(Devs,Type, Groups):-
    maplist(
	([G,[G,Type|Devs]]>>true), %obviously this does a lot more than 'true' in the original
	Groups,Table),
    forall(member(row,Table), writeln(row)).

?-listing(show_group_diff_table).
```
The `show_group_diff_table` looks like:
```
show_group_diff_table(Devs, Type, Groups) :-
    '__aux_maplist/3___aux_yall_437b082c17dcc54b5b599890bef5e8c92d538f79+0'(Groups,
                                                                            Table),
    \+ ( member(row, Table),
         \+ writeln(row)
       ).
```
It does the same thing in the repl or when run as `swipl test.pl`. If I comment out `compare_rulesets` I get:
```
show_group_diff_table(Devs, Type, Groups) :-
    maplist([G, [G, Type|Devs]]>>true,
            Groups,
            Table),
    \+ ( member(row, Table),
         \+ writeln(row)
       ).
```
As expected. Whatever the aux_maplist predicate is doing it has no references to `Devs` or `Type`!

I'm running `SWI-Prolog (threaded, 64 bits, version 8.2.4)`, not tried to install later version because I've rarely managed to compile/install swipl for Linux, but if it's known to be fixed in a later version I'll give it another try.

I'd be happy enough with a workaround (that doesn't involve modules - nowhere near ready for that).  My pathetic attempt to import yall without (>>)/2 was met with scorn :)

Cheers,
Eddie

**Comment by eddiec** [comment]
Sigh.  So focussed on the problem that the obvious workaround of using an auxiliary predicate didn't occur to me.

**Comment by eddiec** [comment]
Deeper sigh!  OK, I plumb forgot about using {...}.  Only ever used it once before.

**Comment by JanWielemaker** [comment]
I typically prefer a helper predicate.  Easier to understand and debug 😄

**Comment by eddiec** [comment]
I like to see everything in one place but I get your point.
Cheers.

**Comment by kamahen** [comment]
+1 to helper predicates, although I often have trouble coming up with a suitable name. ;)
Sometimes my helper predicate is nothing more than a reordering of the arguments, especially if it's a "partial" predicate, e.g. maplist(my_pred_(abc), L1, L2) where: my_pred_(X,Y,Z):-my_pred(Y,X,Z).

I also tend to use helper predicates inside setof/bagof rather than the "^" notation.

Also, yall can have slightly different semantics, depending on whether it's compiled or interpreted. (Usually this isn't a problem, though)
