### ISSUE TITLE
segv in system:trie_gen/3  

### ISSUE THREAD

**Issue by EricZinda** [SWI-Prolog/swipl-devel#885]
In SWI-Prolog (threaded, 64 bits, version 8.3.29), MacOS (Intel) I got the following crash, don't know if this is helpful enough to do anything with. Is there anywhere that more information gets dumped automatically?  This was while using the MQI so it wasn't a top level process that would give a nice Mac stack dialog.

If I can get a good repro case, I'll add it.  Never seen it before.

Prolog: SWI-Prolog [thread 4 (mqi1_conn1_goal) at Thu Sep 16 20:39:30 2021]: received fatal signal 11 (segv)
Prolog: C-stack trace labeled "crash":
Prolog:   [0] /Applications/SWI-Prolog.app/Contents/Frameworks/libswipl.8.3.29.dylib(save_backtrace+0x67) [0x10b8062d6]
Prolog: Prolog stack:
Prolog:   [21344] system:trie_gen/3 [PC=1 in supervisor]
Prolog:   [21342] $apply:forall/2 [PC=6 in clause 1]
Prolog:   [21339] system:$c_call_prolog/0 [PC=0 in top query clause]
Prolog:   [21338] assert/1 <foreign>
Prolog:   [21337] persistency:db_assert_sync/1 [PC=17 in clause 1]
Prolog:   [21336] system:$c_call_prolog/0 [PC=0 in top query clause]
Prolog:   [21335] system:with_mutex/2 <foreign>
Prolog:   [21332] store_assert/4 [PC=12 in clause 1]
Prolog:   [21330] createInitialData/0 [PC=29 in clause 3]
Prolog:   [21329] $bags:findall_loop/4 [PC=5 in clause 1]
Prolog:   [21328] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [21322] $bags:findall_loop/4 [PC=5 in clause 1]
Prolog:   [21321] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [21317] $bags:findall_loop/4 [PC=5 in clause 1]
Prolog:   [21316] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [21312] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [21309] system:catch/3 [PC=2 in clause 1]
Prolog:   [21308] mqi:goal_thread/1 [PC=158 in clause 1]
Prolog:   [0] system:$c_call_prolog/0 [PC=0 in top query clause]

**Comment by JanWielemaker** [comment]
Without more context it gets hard ....

**Comment by EricZinda** [comment]
I figured.  I think I might have a repro.  I'll keep digging.

**Comment by EricZinda** [comment]
OK, I have a repro and it repros on Ubuntu 20.04.2 as well.  It takes running a whole suite of tests from Python to hit the bug, and the environment is a little complicated to set up. So I created a docker container that repros it for me (I'm on MacOS Big Sur).  The repository is on DockerHub, I can you add me as a collaborator so you can download it if you send me your DockerHub ID.  Or you can tell me somewhere else to push it.

It takes quite a while to hit it, the tests take something like 20 minutes to run, but I've hit it consistently.

Here's the run command for the container:
~~~
docker run --name testrun --env DONTUSEGOOGLE_APPLICATION_CREDENTIALS="" -i p8yservice /usr/src/Python-3.7.8/python /Adventure.py "/logtests true" "/runall SystemTests" "exit"
~~~

Here's the crash dump I get on the Ubuntu container:
~~~
Prolog: SWI-Prolog [thread 4 (mqi1_conn1_goal) at Fri Sep 17 17:49:01 2021]: received fatal signal 11 (segv)
Prolog: C-stack trace labeled "crash":
Prolog:   [0] PL_advance_hash_table_enum() at ??:? [0x7f8913ae28e5]
Prolog:   [1] PL_advance_hash_table_enum() at ??:? [0x7f8913ae29ad]
Prolog:   [2] PL_advance_hash_table_enum() at ??:? [0x7f8913ae2abe]
Prolog:   [3] PL_sigaction() at ??:? [0x7f8913b3ec28]
Prolog:   [4] killpg() at ??:? [0x7f8913865210]
Prolog:   [5] PL_realloc() at ??:? [0x7f8913b4b8e2]
Prolog:   [6] PL_get_dict_key() at ??:? [0x7f8913aa97c6]
Prolog:   [7] PL_thread_self() at ??:? [0x7f8913b193bc]
Prolog:   [8] PL_get_dict_key() at ??:? [0x7f8913aab78e]
Prolog:   [9] PL_unregister_atom() at ??:? [0x7f8913aecb0b]
Prolog:   [10] PL_call_predicate() at ??:? [0x7f8913b27db4]
Prolog:   [11] PL_get_dict_key() at ??:? [0x7f8913abacab]
Prolog:   [12] PL_get_dict_key() at ??:? [0x7f8913abbb1c]
Prolog:   [13] PL_check_data() at ??:? [0x7f8913a71db1]
Prolog:   [14] PL_get_pointer_ex() at ??:? [0x7f8913b00abd]
Prolog:   [15] PL_unregister_atom() at ??:? [0x7f8913aed69c]
Prolog:   [16] PL_get_pointer_ex() at ??:? [0x7f8913b097ca]
Prolog:   [17] PL_is_dict() at ??:? [0x7f8913b4a3fc]
Prolog:   [18] PL_unregister_atom() at ??:? [0x7f8913af1d0a]
Prolog:   [19] PL_get_pointer_ex() at ??:? [0x7f8913b097ca]
Prolog:   [20] PL_write_term() at ??:? [0x7f8913a93135]
Prolog:   [21] start_thread() at ??:? [0x7f8913735609]
Prolog:   [22] clone() at ??:? [0x7f8913941293]
Prolog: Prolog stack:
Prolog:   [21334] system:trie_gen/3 [PC=1 in supervisor]
Prolog:   [21332] $apply:forall/2 [PC=6 in clause 1]
Prolog:   [21329] system:$c_call_prolog/0 [PC=0 in top query clause]
Prolog:   [21328] assert/1 <foreign>
Prolog:   [21327] persistency:db_assert_sync/1 [PC=17 in clause 1]
Prolog:   [21326] system:$c_call_prolog/0 [PC=0 in top query clause]
Prolog:   [21325] system:with_mutex/2 <foreign>
Prolog:   [21322] store_assert/4 [PC=12 in clause 1]
Prolog:   [21320] createInitialData/0 [PC=29 in clause 3]
Prolog:   [21319] $bags:findall_loop/4 [PC=5 in clause 1]
Prolog:   [21318] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [21312] $bags:findall_loop/4 [PC=5 in clause 1]
Prolog:   [21311] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [21307] $bags:findall_loop/4 [PC=5 in clause 1]
Prolog:   [21306] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [21302] system:setup_call_catcher_cleanup/4 [PC=5 in clause 1]
Prolog:   [21299] system:catch/3 [PC=2 in clause 1]
Prolog:   [21298] mqi:goal_thread/1 [PC=158 in clause 1]
Prolog:   [0] system:$c_call_prolog/0 [PC=0 in top query clause]
Prolog: Running on_halt hooks with status 139
Prolog: Killing 12 with default signal handlers
~~~

**Comment by JanWielemaker** [comment]
Was fixed, closing.
