### ISSUE TITLE
?- listing(load_foreign_library).   "Evolves" perhaps due to autoloading

### ISSUE THREAD

**Issue by logicmoo** [SWI-Prolog/swipl-devel#89]
?- listing(load_foreign_library).   "Evolves" perhaps due to autoloading

```prolog

Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.10)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- listing(load_foreign_library).
:- meta_predicate prolog_listing:load_foreign_library(:).

prolog_listing:load_foreign_library(A) :-
        load_foreign_library(A, default(install)).

:- meta_predicate prolog_listing:load_foreign_library(:,+).

prolog_listing:load_foreign_library(B:A, C) :-
        with_mutex('$foreign', load_foreign_library(A, B, C)).

true.

?- listing(load_foreign_library).
:- meta_predicate shlib:load_foreign_library(:).

shlib:load_foreign_library(A) :-
        load_foreign_library(A, default(install)).

:- meta_predicate shlib:load_foreign_library(:,+).

shlib:load_foreign_library(B:A, C) :-
        with_mutex('$foreign', load_foreign_library(A, B, C)).

shlib:load_foreign_library(A, _, _) :-
        current_library(A, _, _, _, _), !.
shlib:load_foreign_library(A, B, F) :-
        retractall(error(_, _)),
        find_library(A, C, E),
        asserta(loading(A)),
        retractall(foreign_predicate(A, _)),
        catch(B:open_shared_object(C, G), D, true),
        (   nonvar(D)
        ->  delete_foreign_lib(E, C),
            assert(error(C, D)),
            fail
        ;   delete_foreign_lib(E, C)
        ), !,
        (   entry(A, F, H),
            call(B:call_shared_object_function(G, H))
        ->  retractall(loading(A)),
            assert_shlib(A, H, C, B, G)
        ;   foreign_predicate(A, _)
        ->  retractall(loading(A))
        ;   retractall(loading(A)),
            retractall(foreign_predicate(A, _)),
            close_shared_object(G),
            findall(H, entry(A, F, H), I),
            throw(error(existence_error(foreign_install_function,
                                        install(C, I)),
                        _))
        ).
shlib:load_foreign_library(A, _, _) :-
        retractall(loading(A)),
        (   error(_, B)
        ->  retractall(error(_, _)),
            throw(B)
        ;   throw(error(existence_error(foreign_library, A), _))
        ).

true.

?-
```

I confirmed this happens before and after my other pull request ..  And I think this is a linux-only issue.   I am creating this issue so if someone wants to fix this before me they are aware of it

**Comment by JanWielemaker** [comment]
Hi Douglas,

Some of this has to do with the interaction between DWIM (Do What I Mean) and autoloading.
The system basically tries to find predicates from an incomplete specification, listing all matches.
If nothing matches, it also looks at the autoload index.  It then autoloads.  It did that into the module `prolog_listing`.  That was a bug.  Into the context module might make some sense, but I now hacked it to load the module without importing anything anywhere, so the program should remain unchanged.  I also now always find the module of the real definition.

So, listing(m:name) now lists predicates name `name` with any arity that are defined or can be autoloaded into m, using the actual definition module as prefix or no prefix if they are actually defined in m.

It is not clear to me this is the best thing to do.   It is at least more consistent now.

**Comment by logicmoo** [comment]
On Sat, Nov 7, 2015 at 8:38 AM, Jan Wielemaker <notifications@github.com>
wrote:

> Hi Douglas,
>
> . Into the context module might make some sense, but I now hacked it to
> load the module without importing anything anywhere, so the program should
> remain unchanged. I also now always find the module of the real definition.
>

Ah yes, I do like that we no longer automatically import/1 at the same
time!  That was being pesky on several fronts in one of my pack's code.
But wasn't sure how to clearly argue for the new behavior.

if an  autoload defines  other_guy:name/5 ..  (and lets say DWIM fails)
If I ask for

  myself: (....
    clause(name/5,true),
    .... )

  I could have some errant other_guy:name/5 taking over my module before I
got to my own   :- myself:dynamic(name/5).    In the file.  (My mistake
surely, and I think even a warning happens) but still it "sometimes it I
get away with it", because  my  :-dynamic(name/5) came early enough and I
did not know.. Now the rest of the modules in my pack are using one of the
 name/5s but I have no idea which.


> It is not clear to me this is the best thing to do. It is at least more
> consistent now.
>

This seems a better place to continue from

**Comment by logicmoo** [comment]
Oh actually i assumed too much.. this is just for calls to listing/1

And clause(name/5,true), also wont inspire  autoload either.
