### ISSUE TITLE
Unexpected results with concatenation of variable and dict

### ISSUE THREAD

**Issue by spl** [SWI-Prolog/swipl-devel#891]
What does it mean to juxtapose a variable `X`, bound to a dict, with another dict? Here's a simple example:

```prolog
?- X = d{a: 1, b: 2}, Y = X{a: 2}.
X = d{a:1, b:2},
Y = d{a:1, b:2}{a:2}.

?- Z0 = $Y.a.
Z0 = 2,
Y = d{a:1, b:2}{a:2}.

?- Z1 = $Y.b.
ERROR: key `b' does not exist in d{a:1,b:2}{a:2}
```

Is this an intentional design? If so, how should we interpret `d{a:1, b:2}{a:2}` since we can't actually use that syntax directly?

```prolog
?- Z3 = d{a:1, b:2}{a:2}.
ERROR: Syntax error: Operator expected
ERROR: Z3 = d{a:1, b:2
ERROR: ** here **
ERROR: }{a:2} . 
```

For context, this came up with a typo. We had `JSON{...}` instead of `json{...}`, and `JSON` was bound to a `json{...}` dictionary.

This was first observed in `swipl` 8.2.4 and remains the same in 8.4.0.

**Comment by JanWielemaker** [comment]
> Is this an intentional design? If so, how should we interpret `d{a:1, b:2}{a:2}` since we can't actually use that syntax directly?

Seems ok.  `Y` doesn't have a `b` key.   It has a tag that happens to be a dict, but key lookup does not consider the tag.   In normal life dict tags should be unbound or an atom.   That is what the syntax allows for.   There is no real way we can enforce later unification to something else though (well, using a constraint but that seems overkill to me).   The result is a term that does what it is supposed to do, but has no syntax that can be read.   Note that this isn't the only term without syntax.   Cyclic terms have no syntax either.

**Comment by spl** [comment]
Got it. Thanks!
