### ISSUE TITLE
problem : swish login with a google acount 

### ISSUE THREAD

**Issue by GerdaJanssens** [SWI-Prolog/swipl-devel#899]
![swishlogin](https://user-images.githubusercontent.com/19166581/140314069-ed78e495-977d-47c0-bb70-197c9dbef5ad.JPG)

Jan,
Yesterday and today I am not able to login with my Google account (before it was working ok).
See screen shot.

Gerda

**Comment by JanWielemaker** [comment]
Possibly fixed.  It complained the reply URI still used http://.  Changed to https://.  Doesn't seem to take effect immediately.

**Comment by GerdaJanssens** [comment]
Unfortunately not (completely) fixed yet. Thanks for looking at it.  Gerda
![swishlogin2](https://user-images.githubusercontent.com/19166581/140401579-70644fbc-219c-4c4f-bc4d-4d09120d302e.JPG)

**Comment by JanWielemaker** [comment]
But it is fixed now 😄   At least for me.  I needed to change the redirect URL both at Google and in swish.  Forgot the latter.
