### ISSUE TITLE
[pceEmacs] Coloring of predicate called only from within at_halt/1

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/swipl-devel#9]
In pceEmacs,  coloring of predicate definitions suggests that the predicate is never called when only called from within `at_halt/1`.

![at_halt_coloring](https://cloud.githubusercontent.com/assets/1685012/3101341/3ce66f74-e632-11e3-883c-b1bf804cbf46.png)
.

**Comment by JanWielemaker** [comment]
Seems fixed in recent versions.
