### ISSUE TITLE
TL;DR page for swipl

### ISSUE THREAD

**Issue by EmilySeville7cfg** [SWI-Prolog/swipl-devel#902]
Hello! It would be nice to have [TL;DR page](https://github.com/tldr-pages/tldr) for `swipl` command. ;) I know that in some universities Prolog is used so an ability to quickly begin using it from command line would be nice for students loving command line (as me).

**Comment by kamahen** [comment]
Do you mean this: https://www.swi-prolog.org/pldoc/man?section=quickstart ?

If so, are you suggesting copying that to https://github.com/tldr-pages/tldr/tree/main/pages/common/ ?

**Comment by EmilySeville7cfg** [comment]
> If so, are you suggesting copying that to https://github.com/tldr-pages/tldr/tree/main/pages/common/ ?

Yes, I suggest it.

**Comment by kamahen** [comment]
The contents of https://www.swi-prolog.org/pldoc/man?section=quickstart are built into <build>/man/Manual/quickstart.html , but that's not in .md format.

So, somebody (who?) would need to convert the contents to MarkDown, and would also need to keep it up-to-date (again, who?).

**Comment by EmilySeville7cfg** [comment]
I can convert it into .md format.

**Comment by EmilySeville7cfg** [comment]
Please view this [PR](https://github.com/tldr-pages/tldr/pull/7433) for details.

**Comment by EmilySeville7cfg** [comment]
Issue is closed because the mentioned PR was merged.
