### ISSUE TITLE
swipl can't read prolog-file from STDIN

### ISSUE THREAD

**Issue by JRaspass** [SWI-Prolog/swipl-devel#909]
```
$ echo ':- writeln("Hello, World!").' | swipl -g halt /dev/stdin
ERROR: Prolog initialisation failed:
ERROR: file `'/dev/stdin'' does not exist
```
Ideally we'd support `-` as a magic filename like most interpreters but I would expect reading from a pipe to at least work.

Running with `strace` shows that the `stat` succeeds but we still return an error:
```
newfstatat(AT_FDCWD, "/dev/stdin", {st_mode=S_IFIFO|0600, st_size=0, ...}, 0) = 0
write(2, "ERROR: Prolog initialisation fai"..., 79ERROR: Prolog initialisation failed:
```

Running `SWI-Prolog version 8.4.1 for x86_64-linux` from the Arch repo

**Comment by JanWielemaker** [comment]
Interesting thought.    I'm not aware of any Prolog system that can read the program from stdin.  It most you can simply pipe through the interpreter which will drive the normally interactive toplevel.   That allows for

```
swipl -q << EOF
[user].
:- writeln("Hello, World!").
end_of_file.
EOF
```

Many systems also have a two pass compiler or generate object/VM instruction files.   For SWI-Prolog it could work to load the program from stdin.   I'm not entirely sure I see a good use case though.

**Comment by JRaspass** [comment]
Ah true, I should probably explain my motivation. I maintain https://code.golf which recently gained support for [SWI-Prolog](https://github.com/code-golf/code-golf/pull/533). So the code comes from a user's browser POST and I try where possible to avoid writing it to disk to prevent trivial Quine solutions and to generally keep the design simpler.

No worries if this is too tricky to add I just thought it would be a nice quality of life improvement to match other interpreters like Perl/Python/Ruby/etc.

**Comment by JanWielemaker** [comment]
I see.    On second though, not very elegant, but this works:

```
echo ':- writeln("Hello world").' | swipl -g "load_files(stdin, [stream(user_input)])" -t halt
```

I think it is good enough for your use case :smile:

**Comment by JRaspass** [comment]
Even works with arguments! Many thanks, closing this issue then.
```
$ echo ':- prolog_flag(argv, Args), maplist(writeln, Args).' | swipl -g "load_files(stdin, [stream(user_input)])" -t halt -- foo bar baz
foo
bar
baz
```
