### ISSUE TITLE
Behavior of brace_terms is inverted compared to documentation

### ISSUE THREAD

**Issue by dgelessus** [SWI-Prolog/swipl-devel#914]
According to the documentation for the [write_term/2](https://www.swi-prolog.org/pldoc/doc_for?object=write_term/2) option `brace_terms`:

> **brace_terms**(*Bool*)
> If `true` (default), write `{}(X)` as `{X}`. See also `dotlists` and `ignore_ops`.

But in the current version of SWI, the meaning of the option is inverted - `brace_terms(true)` actually *disables* brace syntax, and `brace_terms(false)` enables it:

```prolog
Welcome to SWI-Prolog (threaded, 64 bits, version 8.5.3-19-g17d9ad004)
?- write_term({x}, [brace_terms(true)]).
{}(x)
true.
?- write_term({x}, [brace_terms(false)]).
{x}
true.
```

So either the implementation or the documentation needs to be fixed.

Unfortunately, it seems that SWI has had this backwards behavior of `brace_terms` ever since the option was added in 2013 (f551a52697d347c1d012db7fd128c36728fe086e, ca5d068b2b059a72c903d6a4db0ef52ce8e49446). Apparently not many people care about this option, considering that nobody reported this bug in the last 8 years, but I'm sure that some code out there now expects SWI's inverted implementation rather than the documented behavior. In fact, SWI's own library(edinburgh) seems to be one example - its `display` predicate uses `write_term` with the option `brace_terms(true)` to *disable* brace syntax.

The easy way out would be to declare the implemented behavior as correct and adjust the documentation accordingly. However, this would be incompatible with YAP, which also supports `brace_terms` and [implements the logic correctly](https://github.com/vscosta/yap/blob/a0928de253648b35b5ebe5c5be1956e3f87b4ca3/os/writeterm.c#L247-L250) (i. e. `brace_terms(false)` disables brace syntax).

([Somewhat related discussion on Discourse](https://swi-prolog.discourse.group/t/best-way-to-write-terms-for-interoperability/4709))

**Comment by JanWielemaker** [comment]
I see.   I think that for the sake of compatibility and consistency we should declare the docs to be right.   The reason is probably the use of or'ed flags internally, were we want no flag to have the default behavior.

Pushed 6de4420d22ae650970bd46d79629342498e00be3
