### ISSUE TITLE
pack_install/2 from  a Github  zip file url is propably having a problem

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#935]
I am not a fluent Github or Git user but now that I researched things it seems that there could be problems with  prolog_pack:github_release_url/3

```
?- prolog_pack:github_release_url('https://github.com/SWI-Prolog/swipl-devel/archive/V8.5.7.zip', Pack, Version) .
Pack = 'swipl-devel',
Version = version([8, 5, 7]).
```
I think all Github urls for downloading zip have  [for example here](https://github.com/SWI-Prolog/swipl-devel/tags) the  `refs/tags` in the url. 

Maybe the `archive` should be replaced with `archive/refs/tags` in the prolog_pack:github_release_url/3 if nothing is depending on the current url with just `archive`

**Comment by JanWielemaker** [comment]
Thanks.  Pushed 6c1c5c71a05ef67033acea6a9b2668db10c37733 to accept both locations.

**Comment by xpxaxsxi** [comment]
The 6c1c5c7 does not work. It is still not parsing the File correctly when URL has archive/refs/tags.

This  is an interesting bug, I dug into it few hours -- chance to learn-- and found out that the atomic_list_concat/3 cannot unify when list has atom-members that include the separator. 

Could it be that atomic_list_concat/3 just cannot do this type of unification when the mode is  "-++" ????

```
?- atomic_list_concat(['a/b',c], /, 'a/b/c').
true.

?- atomic_list_concat(['a/b',X], /, 'a/b/c').
false
```
