### ISSUE TITLE
query for determining init.pl path does not work on Windows 11

### ISSUE THREAD

**Issue by medovina** [SWI-Prolog/swipl-devel#949]
I'm running SWI-Prolog 8.4.2.

Section 2.2 "The user's initialisation file" of the documentation says that the following query will reveal the directory where init.pl is located:

```
?- absolute_file_name(app_config(.), Dir, [file_type(directory)]).
Dir = ’/home/jan/.config/swi-prolog’.
```

Unfortunately, the query fails on Windows (at least on my Windows 11 installation):

```
ERROR: source_sink `app_config('.')' does not exist
```

And so it's unclear where init.pl should be located.

**Comment by JanWielemaker** [comment]
I see.  That doesn't seem to work if the directory does not yet exist.   You should be able to enumerate the candidate folders using

     ?- absolute_file_name(app_config(.), Dir, [solutions(all)]).

The location on Windows is normally the _AppData_ folder followed by `swi-prolog`., where the AppData is by default `Application data` innyour home.    I've pushed a fix for editing or creating this file from the __Settings__ menu entry.  This was broken as well 😢

**Comment by medovina** [comment]
Thanks very much for the quick reply and this helpful information!
