### ISSUE TITLE
Latest daily build for Windows is from 2022-2-23 y-m-d

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#950]
As seen here [https://www.swi-prolog.org/download/daily/bin/](https://www.swi-prolog.org/download/daily/bin/)

**Comment by JanWielemaker** [comment]
Seems the new signal API stuff breaks the windows port.   I'm traveling and will look at it later.

**Comment by JanWielemaker** [comment]
Looks like it is fixed.   at least the build proceeds.
