### ISSUE TITLE
[swi/prolog 8.2.3 -> 8.4.2] : absolute_file_name/3

### ISSUE THREAD

**Issue by didier31** [SWI-Prolog/swipl-devel#957]
On Unix-like platforms, macos for Paulo Moura and  freeBSD for me, we've noticed the following issue :

? - absolute_file_name('/bin/[', Path, [expand(true)]).

ERROR: Syntax error: Unmatched '['
ERROR: In:
ERROR:   [11] expand_file_name('/bin/[',_12088)
ERROR:   [10] absolute_file_name('/bin/[',_12114,[expand(true)]) at /Users/pmoura/lib/swipl/boot/init.pl:1261
ERROR:    [9] toplevel_call(user:user: ...) at /Users/pmoura/lib/swipl/boot/toplevel.pl:1162

**Comment by kamahen** [comment]
This also happens on Ubuntu.

The left bracket has special meaning for file name expansion by bash - for example, try `echo /usr/bin/[a-b]*`. Similarly, left brace, e.g. `echo /usr/bin/*{perl,put}*`.

Also:
```
?- forall(absolute_file_name('/bin/aa*', Path, [expand(true), solutions(all)]), writeln(Path)).
/bin/aa-enabled
/bin/aa-exec
/bin/aapt
/bin/aapt2
true.

?- forall(absolute_file_name('/bin/*{perl,put}*', Path, [expand(true), solutions(all)]), writeln(Path)).
/bin/dh_perl
/bin/dh_perl_openssl
/bin/inputattach
/bin/intel-virtual-output
/bin/isdv4-serial-inputattach
/bin/perl
/bin/perl5.30.0
/bin/perl5.30-x86_64-linux-gnu
/bin/perlbug
/bin/perldoc
/bin/perli11ndoc
/bin/perlivp
/bin/perltex
/bin/perlthanks
/bin/tput
/bin/traceroute6.iputils
/bin/update-perl-sax-parsers
/bin/xinput
true.
```

**Comment by JanWielemaker** [comment]
> The left bracket has special meaning for file name expansion by bash

Indeed.  Though, it is not bash doing this but Prolog itself.   Expand implies both glob patterns and variables.    In some cases you may want to have just one of these.   To expand only variables you must escape the glob patterns, e.g.   You can avoid variable expansion by replacing `$` with `[$]`.

    ?- absolute_file_name('/bin/[[]', Path, [expand(true)]).
    Path = '/bin/['.
