### ISSUE TITLE
transpose/2 is absent from PDF documentation

### ISSUE THREAD

**Issue by medovina** [SWI-Prolog/swipl-devel#960]
SWI-Prolog includes a predicate transpose/2 in the clpfd library:

   https://www.swi-prolog.org/pldoc/doc_for?object=clpfd:transpose/2

However this predicate does not appear in the PDF documentation in the latest release 8.5.8.

**Comment by kamahen** [comment]
There's some discussion here:
https://swi-prolog.discourse.group/t/why-is-transpose-2-not-in-library-lists/4707
https://swi-prolog.discourse.group/t/proposal-for-an-alternative-transpose-2-definition/883

**Comment by JanWielemaker** [comment]
With SWI-Prolog/swipl-devel@4b6bf6eede2a000405f5b2ca1125b80d50b7b4d7 I've added transpose/2 to the clp(fd) docs.   It is not ideal, but reflects the current situation and after a predicate with the same name from library(ugraphs) was renamed there is no big confusion any longer.

**Comment by medovina** [comment]
Great - thanks!
