### ISSUE TITLE
Printing a dict with an unbound variable gives wrong result

### ISSUE THREAD

**Issue by torbjornlager** [SWI-Prolog/swipl-devel#97]
Trying to print a dict with an unbound variable inside should probably throw an error, but:

?- use_module(library(http/json)).
true.

?- current_output(S), json_write_dict(S, foo{a:X}).
{"a": {}}
S = <stream>(0x10cfffe48),
X = json([]).

**Comment by JanWielemaker** [comment]
Yip.  Fixed in SWI-Prolog/packages-http@e7f0d77fcadea840e0c2c8dc40e60c22b85ab93c
