### ISSUE TITLE
Uninformative warning

### ISSUE THREAD

**Issue by borisvassilev** [SWI-Prolog/swipl-devel#99]
I don't even know how to name this issue.... This is a minimal reproducible example. This is the file `foo.pl`:

```
foo :- maplist([_], []).
```

When you just consult it, everything seems fine (even though I am not sure what it is supposed to mean). Then, upon `make`:

```
$ swipl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.14-2-g2f7cf13)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- [foo].
true.

?- make.
Warning: Unknown message: extended_pos(list_position(19,22,[20-21],none),1)
Warning: Unknown message: extended_pos(list_position(19,22,[20-21],none),1)
true.
```

**Comment by JanWielemaker** [comment]
It can't do the position logic.  Would be feasible to add, but given that the program doesn't make much sense in the first place I won't put that high on the agenda.

**Comment by borisvassilev** [comment]
Yes, definitely low priority. The reason why I got this is that I forgot the `>>true` for a library(yall) lambda. The warning itself is cryptic, but by the time I tried to run the code I got a clear error and more importantly, a line number.

**Comment by JanWielemaker** [comment]
Won't fix, also because it is planned to revise the entire position handling.
