### ISSUE TITLE
Non-sensical error from  prolog_colour library with discontiguous clauses

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/swipl-devel#990]
When I load a file (as below) I get a discontiguous clauses warnings, that's fine, I expect this.  (Windows 10 and  version 8.5.7-31-g6600d5469)
```
:- module(tmp6,[]).
alpha( 1).
beta.
alpha( 2).
```

When I edit the file by adding an '%' and make it in Pce-Emacs ...
```
:- module(tmp6,[]).
alpha( 1). %
beta.
alpha( 2).
```
... I get this weird error about url???  and format???, I have been just ignoring this nonsensical error. Today I had inspiration and time to dig in to this weird error message. 
```
?- 
ERROR: c:/users/pasik/documents/prolog/peltp/data6/tmp6.pl:7:
ERROR:    format/3: Type error: `text' expected, found `url('c:/users/pasik/documents/prolog/peltp/data6/tmp6.pl':3)' (a compound)
% c:/users/pasik/documents/prolog/peltp/data6/tmp6 compiled into tmp6 0.03 sec, -2 clauses

```
I believe the prolog_colour library is getting mixed up from the discontiguous predicates and  the 'discontiguous clauses' warning is never shown.

But when I add the '%' and save it in Pce-Emacs and at the prompt run 'make' I get the same discontiquous warning as when starting up.

**Comment by JanWielemaker** [comment]
Doesn't reproduce.  If, as your other issue this is using 8.5.7, please upgrade first.

**Comment by xpxaxsxi** [comment]
Yes the  8.5.11 does not have this.
